### PR TITLE
Issue #1163 - Convert PercentError to use templates

### PR DESCRIPTION
**Pull request by Mailkov**
IA Page: https://duck.co/ia/view/percent_error

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
deploying to beta...

**Comment by mintsoft** [comment]
@moollaza This LGTM, tested a few queries etc looks fine

**Comment by jagtalon** [comment]
Looks good! :+1:

**Pull request merged**
