### PR TITLE
Swift cheat sheet: Fixes #2095

### PR DESCRIPTION
**Pull request by gabhi**
Added new topics in the  cheatsheet for Swift arrays, methods, instances, and enums.

---
IA Page: https://duck.co/ia/view/swift_cheat_sheet

### CODE REVIEW

**Comment by GuiltyDolphin** [comment]
@gabhi Did you mean #2095? That was a pull request.

Please include a description of what you've actually done to 'fix' the cheat sheet.

**Comment by gautamkrishnar** [comment]
I think this is just some improvement to the existing cheatsheet. :+1:
Thanks @gabhi

**Comment by gabhi** [comment]
Yes this PR includes improvements to the existing cheatsheet.

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Just let me know when you're happy with this and I'll merge.

**Comment by gautamkrishnar** [comment]
@guiltydolphin i think its good to merge :+1:

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Okay :)

**Comment by moollaza** [comment]
@gabhi thanks again for fixing the Swift Cheat Sheet! You did a great job. We at DuckDuckGo, the DuckDuckHack community, and all the people who will encounter this Instant Answer really appreciate it.

We could really use your help on something else now. There was a nice suggestion about improving the Currency IA’s triggers for precious metals in https://github.com/duckduckgo/zeroclickinfo-spice/issues/1421 and I think you'd similarly do a great job with it. Please comment on this issue if you'd be willing to take it up!

I think it is a good fit for you, but I'm of course not entirely sure, so I'd love to chat if you're around this week or next. Please message me on slack (@moollaza) or send me an email (moollaza@duckduckgo.com) if you'd be interested in talking. 

Thanks again!

**Pull request merged**
