### PR TITLE
Google Drive Cheat Sheet

### PR DESCRIPTION
**Pull request by DPAUTH**
new cheatsheet
#3471 

ia: https://duck.co/ia/view/google_drive_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@DPAUTH Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
hey @DPAUTH - do you want to double-check your code and see why this is failing?

**Comment by tagawa** [comment]
Hi @DPAUTH. I've just sent a pull request to your `gdrive` branch. If you can merge that, then it should fix the file problem in this pull request automatically: https://github.com/DPAUTH/zeroclickinfo-goodies/pull/1

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=google drive cheatsheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/google_drive_cheat_sheet_mobile.png?WfEa5y7K7D)

**Comment by tagawa** [comment]
Cool - thanks @DPAUTH! It's now working on the beta server so the community can test it and give feedback if necessary: https://beta.duckduckgo.com/?q=google+drive+cheat+sheet&ia=cheatsheet

**Comment by DPAUTH** [comment]
@tagawa Thank you, for repairingmy cheat sheet's issue!

**Comment by tagawa** [comment]
We haven't had any further feedback so let's merge. Thank you very much for creating this @DPAUTH and for not giving up with the Git issues! It should go live in a few days 😃

**Pull request merged**
