### PR TITLE
RandomDate: Add support for ranges

### LINKED ISSUE #3407: Random Date: Allow some customization
For example, it'd be good to be able to restrict the date to certain years or time periods, e.g.:
`random date (in) 2016`
`random date (in the) past`
`random date (in the) future`   

------
IA Page:  http://duck.co/ia/view/random_date 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
###### Description of changes

Adds support for queries of the form `random date in the (past|future)` and ranges (`random date between 1st Jan and 2nd September`)

###### Which issues (if any) does this fix?

Fixes #3407 

###### People to notify (@mention interested parties)

@tagawa 

---

Instant Answer Page: https://duck.co/ia/view/random_date

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Thanks for starting on this already @GuiltyDolphin. Can I be awkward and add "random future date" as an example query?

**Comment by GuiltyDolphin** [comment]
@tagawa Sure thing.

I'm reluctant to add support for any more formats until #2810 is merged - the current parser doesn't cut it for what most of the formats require.

This will handle the case for `date` and `datetime` - that alright?

Remind me once #2810 is merged and I'll add support for the rest of the formats.

**Comment by tagawa** [comment]
Nice! Yes, this looks good for now, and I see what you mean about extra formats.
I also like the clarifying subtitle which should prevent confusion. Let's keep it open for community testing/feedback for a few days before merging.

**Comment by GuiltyDolphin** [comment]
@tagawa There is a slight bug, try (for example) `random date between Jan 1st 2000 and Jan 1st 5000` - it doesn't respond.

If you try this on `duckpan query` you'll see that an answer arives *eventually*, but it takes a while. This is nothing to do with this IA and instead appears to be a bug with the `DateTime` package - and how the Dates Role is using the package.

My instinct (after a bit of profiling) is that when setting the time zone Datetime has to do a bunch of calculations updating its seconds to ensure that it doesn't become out-of-sync as years progress - meaning that very large years can lead to a *lot* of calculations.

Anyway, I'll see if this is still an issue in #2810 and hopefully fix it if it is - might require a bit of magic though.

**Comment by tagawa** [comment]
@GuiltyDolphin That query seems OK to me. Trying up to 9999 takes a while longer but it still gets there without timing out.

**Comment by tagawa** [comment]
@GuiltyDolphin Are you happy for me to merge this?

**Comment by GuiltyDolphin** [comment]
@tagawa Sure - just remind me to add the rest of the functionality after #2810 is sorted ^.^

**Comment by tagawa** [comment]
...aaaaaand it's live!

**Pull request merged**
