### PR TITLE
Fix case for structured_answer "operation"

### LINKED ISSUE #904: Fix case for structured_answer "operation"
The structured_answer "operation" should be title case. 

Examples below:
+ calculator => Calculator
+ international calling code => International Calling Code 
+ random password => Random Password
+ convert => Convert

selection_056
selection_057
selection_058

### PR DESCRIPTION
**Pull request by MrChrisW**
Fixes #904

### CODE REVIEW

**Comment by jagtalon** [comment]
@MrChrisW nice, except why was the attribution changed in one of them?

**Comment by mintsoft** [comment]
WeekdaysBetween.pm to be precise!

**Comment by MrChrisW** [comment]
@mintsoft That's actually @jagtalon's fault see [981538c7c1aed2d547357a5510141cd0c9820a81](https://github.com/duckduckgo/zeroclickinfo-goodies/commit/981538c7c1aed2d547357a5510141cd0c9820a81#diff-2c08f52b889f71d15911d938cd1cdb9d) not sure why GitHub is showing the file as changed...

**Comment by MrChrisW** [comment]
@mintsoft @jagtalon Fixed.

**Comment by jagtalon** [comment]
:+1:

**Pull request merged**
