### PR TITLE
JSONValidator: Change default indentation to 4 spaces

### PR DESCRIPTION
**Pull request by sahildua2305**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`JSONValidator: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes
Changing indentation to 4 spaces because that's more common instead
of 2 spaces

###### People to notify
@moollaza @MariagraziaAlastra 

---

Instant Answer Page: https://duck.co/ia/view/json_validator

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by sahildua2305** [comment]
Need your feedback on this - @duckduckgo/community-leaders

**Comment by sahildua2305** [comment]
@moollaza can you have a look over this quick fix?

**Comment by moollaza** [comment]
@sahildua2305 Thanks! This LGTM :+1:

**Pull request merged**
