### PR TITLE
New cheat sheet: HipChat

### PR DESCRIPTION
**Pull request by tagawa**
IA: https://duck.co/ia/view/hipchat_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=hipchat cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/hipchat_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=hipchat cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/hipchat_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=hipchat cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/hipchat_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=hipchat cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/hipchat_cheat_sheet_mobile.png)

**Comment by jophab** [comment]
@tagawa  :+1:  :smile:

**Comment by tagawa** [comment]
Thanks @jophab!

**Comment by moollaza** [comment]
@tagawa Thanks! This LGTM :+1:

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=hipchat cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/hipchat_cheat_sheet_mobile.png)

**Comment by tagawa** [comment]
Gracias! I'd like to add keyboard shortcuts as well, but there isn't a way to combine two template types in one cheat sheet so I'll think about the best way to do that.

**Pull request merged**
