### PR TITLE
New Multiplication Table Cheat Sheet

### PR DESCRIPTION
**Pull request by KAUTH**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [x] New Instant Answer
  - [x] Cheat Sheets: **`New Multiplication Table Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Provide an overview of the changes this pull request introduces.
###### Which issues (if any) does this fix?

Fixes #NNNN - how specifically does it fix the issue?
###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/multiplication_table_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=multiplication table cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/multiplication_table_cheat_sheet_mobile.png?IhimGYwuF9)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=multiplication table cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/multiplication_table_cheat_sheet_mobile.png?06Nynhxr8P)

**Comment by KAUTH** [comment]
When is the IA going to be assigned to some one?;-)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=multiplication table cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/multiplication_table_cheat_sheet_mobile.png?1iqZSkXkmu)

**Comment by KAUTH** [comment]
@GuiltyDolphin is everything ok with this IA because it's been stuck in the development pipeline for quite some time now. Thanks in advance for the feedback!

**Pull request closed without merging**
