### PR TITLE
Chord Goodie PR

### PR DESCRIPTION
**Pull request by gerhuyy**
**What does your Instant Answer do?**

It determines the way to play a given chord on a given instrument. 
It then displays it as a standard chord diagram, using html divs

**What problem does your Instant Answer solve (Why is it better than organic links)?**

When looking for how to play a certain chord using the internet, you will have trouble 
finding one source that covers all your needs. Although one website might sometimes 
have a few chords, they generally won't have information on more complex ones, or not
for different instruments. Further, the system behind formulating a given pattern is
relatively simple, and based in mathematics.

**What is the data source for your Instant Answer? (Provide a link if possible)**
n/a

**Why did you choose this data source?**
n/a

**Are there any other alternative (better) data sources?**
n/a

**What are some example queries that trigger this Instant Answer?**

"C ukulele chord", "F# minor guitar tab", "Esus4 uke tab", "Dmaj7 guitar chord"

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

Musicians, especially those playing guitar or ukulele.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

https://duck.co/ideas/idea/537/piano-guitar-chords

This one embodies the idea behind this goodie, although it wasn't the inspiration
for it.

**Which existing Instant Answers will this one supercede/overlap with?**

None, as far as I can tell.

**Are you having any problems? Do you need our help with anything?**

I'm unsure if the way I did the test file is adequate/proper. (ie. I copied the function
that creates the html). I felt that writing it all out would be more prone to errors 
than writing code was. I thought that seeing things render properly in pratice stood
for itself.

**Where did you hear about DuckDuckHack? (For first time contributors)**

I used duckduckgo because of reddit comments and implicit firefox support for it.
After using it for some time, I decided to try making this.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

It looks like this

## Checklist
Please place an 'X' where appropriate.

```
- [x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [x] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [x] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [x] Google Chrome
        - [x] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [x] Google Chrome
        - [x] Firefox
        - [] Opera
        - [x] Safari

    - iOS (iPhone)
        - [x] Safari Mobile
        - [x] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

```

### CODE REVIEW

**Comment by moollaza** [comment]
@gerhuyy Thanks a lot for contributing, we really appreciate it :smiley: -- I wish you would have emailed us first though, because we're actually just about to merge in a nearly identical Instant Answer: #858 

The big difference in the two is that yours uses CSS to create the diagram which is pretty neat.

I'm going to put this one on hold for now, because I'd like to merge and deploy the other PR as we've been working on that one for a while and I don't want to discard the time and effort put in over there.

Would you mind taking a look at that PR and checking if your Instant Answer offers any benefits (aside from the use of images vs css) -- does yours perhaps handle more variations of chords?

We're *just* about to launch template support for Goodies (so you won't have to build as much HTML manually and I would love for this kind of IA to display a few tiles showing the various shapes for different chords.

How does that sound?

**Comment by mintsoft** [comment]
@moollaza Other option could be to remove the overlapping triggers and just use this for ukulele chords?

**Comment by moollaza** [comment]
@mintsoft that could definitely work, but if we can represent more/all instruments in a single IA I'd prefer we do it that way and have a unified way of displaying them (i.e. Images or CSS). I think it would seem odd if we presented Guitar and Ukulele chords in different ways.

It looks like the `GD::Tab::Guitar` lib that was used in the other PR was actually inspired by http://search.cpan.org/~tateno/GD-Tab-Ukulele-0.01/lib/GD/Tab/Ukulele.pm, so the other PR could certainly handle ukulele chords.

Likewise there's a similar lib for Piano: https://metacpan.org/pod/GD::Chord::Piano. 

I guess we could split them up into 3 separate IAs: `MusicChords::Guitar`, `MusicChords::Ukulele`, and `MusicChords::Piano` perhaps?

**Comment by mintsoft** [comment]
@moollaza yeah that'd certainly work

**Comment by gerhuyy** [comment]
@moollaza Because it's based more on code than a database, new instruments and chords can be added with ease. The visual style would also be easy to change because it generates it on the fly. 

Whichever way this goes, thanks guys.

**Comment by moollaza** [comment]
> Because it's based more on code than a database, new instruments and chords can be added with ease. The visual style would also be easy to change because it generates it on the fly.

@gerhuyy that's a great point. We're going to merge the other one for now and get it live. I really like the idea of CSS/HTML over images though, and the fact that we can extend this for other instruments.

We'll be launching Goodie templates soon and I think this IA would be a great candidate for a revamp with a templated implementation.

For now I'll mark this as on hold, and will get back to you with updates.

>Whichever way this goes, thanks guys. 

You're the one to be thanked! Thanks for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers in the mean time.

**Comment by moollaza** [comment]
@gerhuyy Goodie templates are now live (and documentation is currently being written!) If you're still interested in this, we'd love to move ahead to a templated, HTML version of this IA.

An example of an IA using custom templates can be seen here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/BPMToMs.pm

The 2048 Game PR also demonstrates custom templates + a JavaScript file: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1036

**Comment by moollaza** [comment]
Ping! @gerhuyy are you still interested in finishing this up? We'd love to see this go live!

**Comment by javathunderman** [comment]
@moollaza Are you continuing this?

**Comment by moollaza** [comment]
@javathunderman I'd love for @gerhuyy to pick it up if he's still available and interested, or someone else from the community is welcome to do so!

**Comment by charles-l** [comment]
@moollaza, were you thinking that all the HTML/CSS would be put in a template (i.e. including the string/fret HTML generation)?

**Comment by mintsoft** [comment]
@charles-l That'd be the ideal

**Comment by moollaza** [comment]
>were you thinking that all the HTML/CSS could be put in a template (i.e. including the string/fret HTML generation)?

I think that will work. We now have JS available to Goodies, so we could port the Perl logic that generates the HTML to JS and execute it in the `build` fn. But the more we can put into a template, the better :+1:

**Comment by charles-l** [comment]
@moollaza Do templates grab CSS from somewhere other than the share directory? The CSS file isn't being picked up by the .handlebars file.

**Comment by charles-l** [comment]
Oops. Nevermind. The CSS class name was just changed (zci__body instead of zci--answer). The CSS loads fine.

**Comment by moollaza** [comment]
👍

**Comment by charles-l** [comment]
@moollaza @mintsoft I've got a few more things to tweak, but it's pretty much finished. Should I open a new pull request? Or is it possible to continue working on this one (if so, I don't know how)?

**Comment by mintsoft** [comment]
@charles-l I'd open a new one; AFAIK Github doesn't let user B take over user A's PRs

**Comment by javathunderman** [comment]
@mintsoft This can be closed then, seeing as @charles-l is taking this up.

**Comment by moollaza** [comment]
:+1:

**Comment by moollaza** [comment]
@charles-l in general we suggest you clone the branch used for the PR so you can pull in the existing commits.

**Pull request closed without merging**
