### PR TITLE
Conversions: Workaround math.js erg bug

### PR DESCRIPTION
**Pull request by pjhampton**
## Description of new Instant Answer, or changes

erg is wrongly defined in math.js

```
> math.eval('1 erg to joule')
{ [String: '1e-5 joule']
  units: [ { unit: [Object], prefix: [Object], power: 1 } ],
  dimensions: [ 1, 2, -2, 0, 0, 0, 0, 0, 0 ],
  value: 0.00001,
  fixPrefix: true,
  isUnitListSimplified: true }
```

This PR adds a work around. It's not possible to monkey patch, so that's why I went with the name `ergfixed`

## People to notify

@moollaza 
cc/ @bsstoner 

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/conversions

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@pjhampton Have you opened an issue against math.js so we take this workaround out at some point?

**Comment by mintsoft** [comment]
Also is it possible to add a test around the actual conversion result so we can see at a glance if we regress by taking this out at some point?

**Comment by pjhampton** [comment]
Opps sorry @mintsoft. Must have missed this.
Yeah, I reported and patched. I'm discussing with them the possibility of adding all our custom units so we don't have to build them at runtime.
And no, we can't do that presently but I'm up for hearing ideas 👍

**Comment by mintsoft** [comment]
@pjhampton  So this PR can be closed? Was I right to close the issue?

**Comment by pjhampton** [comment]
You can close the issue, that's fine. But this still needs to be merged 😄  We can't just swap out math.js versions because there hasn't been a release on their end + multiple IAs rely on it.

**Comment by moollaza** [comment]
@pjhampton Thanks! This LGTM :+1:

**Comment by bsstoner** [comment]
This was released to production 🚀

**Pull request merged**
