### PR TITLE
Paper: Fix letter size to be correct

### LINKED ISSUE #4319: Paper: US letter paper size is wrong
**Query:**
https://duckduckgo.com/?q=letter+paper+size&ia=answer

**Currently displayed size:**
210mm x 279mm (8.27in x 11in)

**Correct size:**
8.5 by 11.0 inches (215.9 by 279.4 mm)

**To fix:**
Size can be corrected in https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/paper/sizes.yml

------
IA Page:  http://duck.co/ia/view/paper 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattlehning

### PR DESCRIPTION
**Pull request by jonk1993**
## Description of new Instant Answer, or changes

Change the letter size to the correct size, 8.5 by 11.0 inches (215.9 by 279.4 mm)

## Related Issues and Discussions

Fixes #4319

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/paper

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
@duckduckgo/duckduckhack-contributors anybody with expertise here? This could do with being reviewed. 😄

**Comment by tagawa** [comment]
Hi @jonk1993. Thank you very much for contributing this fix. Please could you tweak it so the format is the same as the other entries? I.e.
`8.5in x 11.0in (215.9mm x 279.4mm)`

**Comment by jonk1993** [comment]
@tagawa ahh yes, you got it 👍

**Comment by jonk1993** [comment]
Hmm not sure why the Travis CI is failing, `duckpan test` completes successfully on my branch locally

**Comment by tagawa** [comment]
Hmm, not sure what was happening there but I ran Travis again and it's fine now. Thanks again for this update 😃

**Pull request merged**
