### PR TITLE
Goodies: Harmonising trimming to use Text::Trim

### PR DESCRIPTION
**Pull request by mintsoft**
As suggested by @moollaza I've switched everything to use `Text::Trim` instead of each Goodie implementing it

### CODE REVIEW

**Comment by mintsoft** [comment]
@moollaza @jagtalon any idea what on earth is going on with Travis here?
`multiple values given for property Text::Trim in section Prereqs at /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/x86_64-linux/Class/MOP/Method/Wrapped.pm line 158.`
https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/jobs/56332886

**Comment by moollaza** [comment]
@mintsoft hmm I'm not sure. It looks like another PR that adds `Text::Trim` to the dist.ini was already merged. https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1059

Looks like you may need to rebase? The Dist has changed a bit since this PR was opened.

**Comment by mintsoft** [comment]
@moollaza Good call; that fixed it!

**Comment by jagtalon** [comment]
@mintsoft aa, sorry, looks like there's another conflict with dist.ini!

**Comment by moollaza** [comment]
@mintsoft if you remove the dist.ini from your PR it should be good

**Comment by mintsoft** [comment]
@moollaza @jagtalon should be resolved!

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
