### PR TITLE
CheatSheets: htmlencode < >

### LINKED ISSUE #1414: Cheat Sheets: Need to encode angle brackets "<", ">" inside code blocks
Looks like the Emacs Cheat Sheet is slightly broken now. The "Search and Replace" section contains a key with `[<replace-string>]` in it. The angle brackets aren't being encoded and so a `<replace-string></replace-string>` element is being created on the page.

https://duckduckgo.com/?q=emacs+cheat+sheet&t=ffab&ia=cheatsheet&iax=1

-----
IA Page: https://duck.co/ia/view/cheat_sheets

### PR DESCRIPTION
**Pull request by mattr555**
This seems to work... fixes #1414

/cc @moollaza @mintsoft

### CODE REVIEW

**Comment by mintsoft** [comment]
LGTM

**Comment by moollaza** [comment]
Seems OK. I think a more general `encode_entities` function will be needed so that we can encode others.

Something similar to underscore.js's `_.escape()` could work and could be added to our new open-source utils repo: https://github.com/duckduckgo/duckduckgo-utils/blob/master/util.js

We have a `DDG.strip_all_html()` actually which might work?

**Comment by mintsoft** [comment]
@moollaza I looked at the `strip_all_html` doesn't that just remove it rather than encode it?

**Comment by moollaza** [comment]
> I looked at the strip_all_html doesn't that just remove it rather than encode it?

@mintsoft looks like you're right. We should probably have an `encode_entities` method then :+1:

**Pull request merged**
