### PR TITLE
New Guitar Chords Cheat Sheet

### PR DESCRIPTION
**Pull request by JasonCFisher**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [X] New Instant Answer
  - [X] Cheat Sheets: **`New {Guitar Chords} Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

What changes does this PR introduce? 
###### Related Issues or Discussions

What issues or discussions (if any) does this PR address? Please provide the issue # or link.
###### People to notify

@mention any relevant people/organizations

---

Instant Answer Page: https://duck.co/ia/view/guitar_chords_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention
Created guitar chord cheat sheet with links to chord diagrams.  Appears through searches for guitar chords cheat sheet, guitar cheat sheet, guitar chord cheat sheet, and guitar chord diagrams cheat sheet.

### CODE REVIEW

**Comment by daxtheduck** [comment]
@JasonCFisher Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=guitar chords cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/guitar_chords_cheat_sheet_mobile.png?YPFeDsaWEK)

**Comment by JasonCFisher** [comment]
If the above dax comment that you are only accepting instant answers related to programming is correct, then it would be useful to explicitly state that you are only looking for programming instant answers in  the how-to documents (Welcome, walkthrough pages, etc).  The fact that you offer cheat sheets on a variety of topics gives the impression that you will accept submissions outside of programming topics.

Thank you for the opportunity to practice my coding.  Hopefully, you can use this at some point.

**Comment by akanshgulati** [comment]
Hi @JasonCFisher for the contribution. The dax comment is autonomous and it's right also as Duckduckgo is currently working mainly for improving the experience for programmers under the [programming mission](https://forum.duckduckhack.com/t/duckduckhack-getting-started/53/3). But since you have contributed in your interest area, we will test your cheatsheet and in case it works fine, we can merge it too.

**Comment by mintsoft** [comment]
@JasonCFisher What about linking to our own guitar chord IA instead? https://duckduckgo.com/?q=guitar+a+chord&t=ffab&ia=answer

**Comment by pjhampton** [comment]
Closing as this PR looks to have gone stale.

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄

**Pull request closed without merging**
