### PR TITLE
Fixed missing sections and descriptions for cheatsheet

### PR DESCRIPTION
**Pull request by gautamkrishnar**
Fixed:
- Missing sections
- Descriptions

#2015

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
More commits to come :+1:

**Comment by gautamkrishnar** [comment]
@moollaza :smile: 
```
t/CheatSheets/CheatSheetsJSON.t .. ok                                                                                                                                                         
All tests successful.                                                                                                                                                                         
Files=1, Tests=177,  0 wallclock secs ( 0.08 usr  0.02 sys +  0.25 cusr  0.02 csys =  0.37 CPU)                                                                                               
Result: PASS
```

**Comment by gautamkrishnar** [comment]
@moollaza why the checks are failing?

**Comment by gautamkrishnar** [comment]
Closing this PR as most uptodate version is available at #2072

**Pull request closed without merging**
