### PR TITLE
Add alias section in MySQL cheat sheet

### PR DESCRIPTION
**Pull request by vikashvverma**
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2389

IA Page: [ https://duck.co/ia/view/mysql_cheat_sheet](https://duck.co/ia/view/mysql_cheat_sheet)

### CODE REVIEW

**Comment by daxtheduck** [comment]
## [MySQL Cheat Sheet](https://duck.co/ia/view/mysql_cheat_sheet)

**Description**: Provides an overview of essential MySQL Data Types, Functions and Methods

**Example Query**: [MySQL Cheat Sheet](https://beta.duckduckgo.com/?q=MySQL Cheat Sheet), [](https://beta.duckduckgo.com/?q=)

**Tab Name**: Answer

**Source**: http://www.cheatography.com/davechild/cheat-sheets/mysql/

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/mysql_cheat_sheet)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/mysql_cheat_sheet)*

**Comment by GuiltyDolphin** [comment]
@vikashvverma I'm not sure that is a terribly useful alias, but I'll see what others have to say: @duckduckgo/instant-answer-maintainers thoughts?

**Comment by vikashvverma** [comment]
@GuiltyDolphin Even I thought so. But sometimes people do search like this as well.

**Comment by moollaza** [comment]
I think this is acceptable :+1:

**Pull request merged**
