### PR TITLE
New FTP Cheat Sheet

### PR DESCRIPTION
**Pull request by jnshrz**
https://duck.co/ia/view/ftp_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@jnshrz Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=FTP cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/ftp_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=FTP cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/ftp_cheat_sheet_mobile.png)

**Comment by GuiltyDolphin** [comment]
@preemeijer You were interested in making one of these - would you like to have a look over?

**Comment by preemeijer** [comment]
@GuiltyDolphin thanks for your trust. I will do.
@jnshrz I will look at it all this weekend and come back to you.

**Comment by preemeijer** [comment]
@jnshrz You have made a good cheat sheet about FTP. It is very nice categorized!
My only question (and this is not a showstopper): Why haven't you added the commandline options?

Cheers, Paul

**Comment by jnshrz** [comment]
@preemeijer Thanks for your feedback! I wasn't sure wether they would fit into this 'basic' FTP cheat sheet, but you're right, they could become very handy.
I will add them today.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=FTP cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/ftp_cheat_sheet_mobile.png)

**Comment by GuiltyDolphin** [comment]
@preemeijer Thanks for reviewing this! I've had a quick look over and it looks fine to me; let me know when you're satisfied and I'll be happy to merge.

**Comment by preemeijer** [comment]
@GuiltyDolphin it is ready to be merged.
@jnshrz Thank you!

**Comment by GuiltyDolphin** [comment]
@preemeijer @jnshrz Thanks guys!

**Comment by daxtheduck** [comment]
@jnshrz this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
