### PR TITLE
New xmonad Cheat Sheet

### PR DESCRIPTION
**Pull request by jarroddunne**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Adds a cheatsheet for the xmonad window manager default keybindings.
###### Which issues (if any) does this fix?

Fixes #NNNN - how specifically does it fix the issue?

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/xmonad_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
hey @jarroddunne I'm not seeing your example query trigger this cheat sheet on beta

**Comment by tagawa** [comment]
Hi @jarroddunne. Thank you for creating this cheat sheet. It looks like your pull request includes many files from another project which means we can't merge them. Please could you either:
a) Remove all files except `xmonad.json` from this pull request, or
b) Create a new branch, commit only the `xmonad.json` file, and send a new pull request. This might be easiest.

Git can be confusing so if you need any help with this please let me know.

**Comment by GuiltyDolphin** [comment]
@jarroddunne In general (basically always) it is best to work on a branch other than `master` when doing pull requests - this allows you to update your master branch without having to do something weird with Git, and gives you another layer of protection (you can just scrap your extra branch) should anything go wrong.

**Comment by tagawa** [comment]
Just a note that this has been replaced by a new pull request: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3462
Thanks @jarroddunne!

**Pull request closed without merging**
