### PR TITLE
New TypeScript Cheat Sheet

### PR DESCRIPTION
**Pull request by vikashvverma**
**What does your Instant Answer do?**

Displays an overview of TypeScript Types, Arrays, Functions, Generics etc.

Screenshot:

screen shot 2016-02-17 at 10 37 38 pm

IA Page: [ https://duck.co/ia/view/typescript_cheat_sheet](https://duck.co/ia/view/typescript_cheat_sheet)

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=typescript cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/typescript_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=typescript cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/typescript_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=typescript cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/typescript_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=typescript cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/typescript_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@vikashvverma Thanks! This LGTM :+1:

**Pull request merged**
