### PR TITLE
Updated DuckDuckGo Goodie

### PR DESCRIPTION
**Pull request by zekiel**
adding to the ddg_goodie
should've done --amend instead of continuous commiting.

### CODE REVIEW

**Comment by zekiel** [comment]
//cc @nilnilnil

**Comment by MrChrisW** [comment]
@zekiel This is failing as using `\` is not a valid way to escape single quotes in YAML (I know it's crazy) 

So you'll need to update [line 69 of responses.yml](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/zac/privatesearchtrigger/share/goodie/duck_duck_go/responses.yml#L69) 

From: ` base_format: '[DuckDuckGo. The search engine that doesn\'t track you]'`

To: ` base_format: '[DuckDuckGo. The search engine that doesn''t track you]'`

**Comment by zekiel** [comment]
Thanks @MrChrisW  --very much. 

updated!

**Comment by jagtalon** [comment]
:+1:

**Pull request merged**
