### PR TITLE
Update redis.json: Fixes #2017

### LINKED ISSUE #2017: Redis Cheat Sheet: Add in essential HLL and Geo commands
In light of https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1614#commitcomment-15116972 we should add in the essential HLL and Geo commands for Redis to round out the content here.

/cc @seisfeld 

------
IA Page:  http://duck.co/ia/view/redis_cheat_sheet

### PR DESCRIPTION
**Pull request by gautamkrishnar**
Update redis.json: Fixes #2017
- added HLL
- added Geo

IA Page: https://duck.co/ia/view/redis_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
@seisfeld thanks for finding the error. It happened when i copied the code from JSONeditoronline :smile:

**Comment by seisfeld** [comment]
Travis still fails, but not related to this work here. Thanks for the fix...

**Comment by moollaza** [comment]
@gautamkrishnar Thanks! This LGTM :+1: 

Failing tests are unrelated. We're looking into them

**Pull request merged**
