### PR TITLE
Update xamarin cheatsheet:fixes #3266

### LINKED ISSUE #3266: Xamarin Cheat Sheet: Added "xamarin studio" alias
This requires adding the following line to the JSON file, just before the `template_type`:

`"aliases": ["xamarin studio"],

It should be a nice first contribution for a new developer.

------
IA Page:  http://duck.co/ia/view/xamarin_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gitcodes

### PR DESCRIPTION
**Pull request by gautamkrishnar**
Fixes #3266

---

Instant Answer Page: http://duck.co/ia/view/xamarin_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gitcodes

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by zekiel** [comment]
@gitcodes can you please review and OK this change before the [maintainer timeout period](http://docs.duckduckhack.com/maintaining/guidelines.html#overseeing-changes)? We'll merge if no response within 14 days.

**Comment by gitcodes** [comment]
you can merge this everything seems ok.

**Comment by edgesince84** [comment]
thanks for your input @gitcodes

**Comment by moollaza** [comment]
@gautamkrishnar Thanks! This LGTM :+1:

**Pull request merged**
