### PR TITLE
goodie for FSF founder

### PR DESCRIPTION
**Pull request by marwendoukh**
# Goodie Pull Request Template

Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**
answer for the question 'fsf founder'  .the free software foundation

**What problem does your Instant Answer solve (Why is it better than organic links)?**
quick answer to the query

**What is the data source for your Instant Answer? (Provide a link if possible)**
https://www.fsf.org/about/staff-and-board

**Why did you choose this data source?**
the official website

**Are there any other alternative (better) data sources?**
No

**What are some example queries that trigger this Instant Answer?**
fsf founder
free software foundation founder
who is the founder of fsf ?
who is the founder of the free software foundation ?

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
developers,linux users ...

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No

**Which existing Instant Answers will this one supercede/overlap with?**

**Are you having any problems? Do you need our help with anything?**

**Where did you hear about DuckDuckHack? (For first time contributors)**

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

## Checklist
Please place an 'X' where appropriate.

```
- [X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera
   -Linux
![screenshot from 2015-08-07 15 12 27](https://cloud.githubusercontent.com/assets/10298519/9137655/033f59a6-3d17-11e5-9a30-861bcce96b57.png)

        - [X] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera
```

### CODE REVIEW

**Comment by mintsoft** [comment]
Hi @marwendoukh thanks for the contribution, however this is a little too specific for a whole instant answer and would probably be answered by the wikipedia IA that's already inplace

**Comment by marwendoukh** [comment]
Why you don't accept this kind of IA ? this could make DDG better :'(

**Comment by mintsoft** [comment]
@moollaza do you agree or have I been too strict here

**Comment by marwendoukh** [comment]
I will try another one

**Comment by mintsoft** [comment]
@marwendoukh I'm sorry about that, however there are some great new IA ideas here : https://duck.co/ideas/status/3

**Pull request closed without merging**
