### PR TITLE
calculator and PrimeFactors: removed alarm

### LINKED ISSUE #3867: Calculator: Remove `alarm`
### Description
The calculator wraps its evaluation of the input in an `alarm` to keep it from running too long. We've since limited the execution time of Goodies internally the alarm in the IA is no longer needed.

**Note**: The PrimeFactors Goodie also has an alarm that should be removed.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/calculator

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
## Description of new Instant Answer, or changes
Removed alarm() from Calculator and PrimeFactors which was making sure script doesn't execute for more than one second. Removed since execution time is now limited by itself. Also removed redundant variable tracking time spent in PrimeFactors script.

## Related Issues and Discussions

Fixes #3867

## People to notify

@moollaza @GuiltyDolphin 

---

Instant Answer Page: https://duck.co/ia/view/calculator and https://duck.co/ia/view/prime_factors

### CODE REVIEW

**Comment by daxtheduck** [comment]
@nalinbhardwaj Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@nalinbhardwaj Thank you!

**Comment by nalinbhardwaj** [comment]
@GuiltyDolphin Has this update been pushed to production for Prime Factors IA?
I think it was pushed for the Calculator IA but not the Prime Factors IA because https://duck.co/ia/view/prime_factors doesn't list me as contributor. Is there some issue with the change?

**Comment by GuiltyDolphin** [comment]
@nalinbhardwaj Uhh, I think Dax only recognizes one IA per PR. @jdorweiler do contributors need to be manually updated for more than 1 IA?

**Comment by nalinbhardwaj** [comment]
@GuiltyDolphin cool then. Just wanted to make sure it worked fine. :)

**Comment by jdorweiler** [comment]
Yes, Dax needs a single IA per pull request.

**Pull request merged**
