### PR TITLE
Java File Handling Cheat Sheet: Modify contents

### PR DESCRIPTION
**Pull request by rasikapohankar**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [x] Improvement    
    - [x] Enhancement: **`{Java File Handling Cheat Sheet}`**

###### Description of changes

Added description and meta to the cheat sheet and refactored two sections, made Buffered Streams and Line Oriented I/O sections look somewhat pretty.

###### People to notify (@mention interested parties)
@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/java_file_handling_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
thanks @rasikapohankar - will review shortly!

**Comment by tagawa** [comment]
Thank you @rasikapohankar - I've just installed it to beta for testing: https://beta.duckduckgo.com/?q=java+file+handling+cheat+sheet&ia=cheatsheet&iax=1

If there are no further comments from the community in a day or two this looks good to merge.

**Comment by tagawa** [comment]
@rasikapohankar Looks like no further feedback so let's merge. Thank you for improving this - Java developers will be happy!

**Pull request merged**
