### PR TITLE
add Redis commands cheatsheet

### PR DESCRIPTION
**Pull request by wykhuh**

### CODE REVIEW

**Comment by zekiel** [comment]
thanks @wykhuh! Looking forward to this

**Comment by MrChrisW** [comment]
Hi @wykhuh, thanks for your contribution. Do you mind filling out the [Goodie Pull Request Template]() and adding it to your initial comment. This will provide the community a quick way to review your CheatSheet Goodie. Thanks :+1:

**Comment by zachthompson** [comment]
[IA idea](https://duck.co/ideas/idea/5987/redis-command-cheat-sheet)  Thanks for taking this up.  Two things I think we'll want to tweak:

1. Mirror the sections given by [Filter by group](http://redis.io/commands#).
2. Remove the '+' between command words.

Also, if you have any expertise on what the most popular command groups are, we could order them appropriately in 'section_order'.

**Comment by moollaza** [comment]
Closing as abandoned.

**Pull request closed without merging**
