### PR TITLE
CPP Unordered Multimap

### PR DESCRIPTION
**Pull request by ManrajGrover**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New {CPP Unordered Multimap} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

This PR adds CPP Unordered Multimap IA.

###### Which issues (if any) does this fix?

None

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/cpp_unordered_multimap_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention
None

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=CPP Unordered Multimap Cheat Sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/cpp_unordered_multimap_cheat_sheet_mobile.png?Lroo5Yav1t)

**Comment by tagawa** [comment]
Thank you for another cheat sheet @ManrajGrover. It looks good but a little bit short - I wonder if it could be combined with some other reference. I don't know much about C++ but are there methods for unordered maps, or is there such a thing as ordered multimap, that could perhaps be included with this?

**Comment by ManrajGrover** [comment]
Hey @tagawa! :smile: C++ multimaps are by default [ordered](http://www.cplusplus.com/reference/map/multimap/insert/) based on key. This has been covered in previous [Cheat Sheet](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/cpp-multimap.json). I'll check out some other references but current reference doesn't have any other functions to be included. Also, I had this small doubt. How can one add multiple references in cheat sheet?

**Comment by tagawa** [comment]
@ManrajGrover Thanks for the explanation. At the moment it's not possible to add multiple references (i.e. multiple values) in cheat sheets, but don't worry about it in this case. Actually, I was probably being too strict (sorry!) - I think it will be fine as it is. Let's give it a few days to see if there are any review comments from testing on the beta server: https://beta.duckduckgo.com/?q=CPP%20Unordered%20Multimap%20Cheat%20Sheet

**Comment by tagawa** [comment]
@ManrajGrover Thank you for one more C++ cheat sheet! Looks good so I'll merge this. Much appreciated :-)

**Comment by daxtheduck** [comment]
@ManrajGrover this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
