### PR TITLE
Added Japanese prefectures cheat sheet

### PR DESCRIPTION
**Pull request by tagawa**
**What does your Instant Answer do?**
Lists Japan's prefectures (like states) and their capitals.

**What is the data source for your Instant Answer? (Provide a link if possible)**
https://en.wikipedia.org/wiki/Japanese_prefectures

**Why did you choose this data source?**
It's an accurate, comprehensive list.

**Are there any other alternative (better) data sources?**
No.

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
People learning more about Japan.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No.

**Are you having any problems? Do you need our help with anything?**
No.

**Where did you hear about DuckDuckHack? (For first time contributors)**
N/A

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
japanese-prefectures-cheatsheets
---
https://duck.co/ia/view/japanese_prefectures_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Japanese Prefectures Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/japanese_prefectures_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@tagawa this LGTM :+1:

**Comment by tagawa** [comment]
Right first time, woohoo! :tada:

**Comment by MrChrisW** [comment]
@tagawa Obligatory
img

**Comment by tagawa** [comment]
Thank you, thank you - autographs later...

**Comment by moollaza** [comment]
@tagawa congrats! It's live: https://duckduckgo.com/?q=Japanese%20Prefectures%20Cheat%20Sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers! :wink:

**Comment by tagawa** [comment]
Wow, that's super fast! Just one thing - there's no "i" icon to open the infobox.

**Comment by moollaza** [comment]
@tagawa looks like it's there now! https://duckduckgo.com/?q=Japanese+Prefectures+Cheat+Sheet&ia=cheatsheet

**Comment by tagawa** [comment]
Yep, WFM. Thanks.

**Pull request merged**
