### PR TITLE
Converting CSS nth-child to jQuery

### PR DESCRIPTION
**Pull request by spentacular**
Resolving Issue #1157

Let me know if there's anything I need to change and I'll get it fixed @moollaza

### CODE REVIEW

**Comment by mintsoft** [comment]
LGTM @moollaza

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
~~LGTM :+1: ~~

Wait a sec...I'm seeing a big empty space below the preview values on Firefox:

vim_cheatsheet_at_duckduckgo

**Comment by moollaza** [comment]
I think you need to hide the divs before running masonry. Or hide them initially in CSS (because that will affect the DOM before `onShow()` runs) and then un-hide the first 3 with JS.

**Comment by spentacular** [comment]
Doh! My bad. Is there any easy way for me to use my JS instead of the other one, or inject it to double check?

**Comment by spentacular** [comment]
Sorry about that, I should have gone through the docs and figured about codio.

screen shot 2015-07-15 at 4 31 53 pm

screen shot 2015-07-15 at 4 32 10 pm

Here are the Firefox and Chrome screenshots of the update. I moved the if to fire before masonry ran, which solves the problem.

**Comment by moollaza** [comment]
>Sorry about that, I should have gone through the docs and figured about codio.

Don't sweat it :smiley: 

>Here are the Firefox and Chrome screenshots of the update. I moved the if to fire before masonry ran, which solves the problem.

Awesome!

**Comment by moollaza** [comment]
Works perfectly: 
dashboard
bs_win7_ie_8 0

**Comment by moollaza** [comment]
@spentacular thanks again!

**Comment by spentacular** [comment]
No problem at all @moollaza ! I'm going to look around and see what else I can get into, but let me know if you see anything and I'd be happy to help.

**Pull request merged**
