### PR TITLE
Dice: Increased dice size

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
## Description of new Instant Answer, or changes

Increased size of die. Original seemed way too small to me.

## People to notify

@loganom 

---

Instant Answer Page: https://duck.co/ia/view/dice

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by loganom** [comment]
@nalinbhardwaj It may be useful to accompany a PR like this with a side-by-side comparison. I'll be able to take a look at the difference tomorrow, but it would be nice for someone else to weigh in on this, as I have never considered enlarging the dice.. but don't want to dismiss it based on my opinion. 

@moollaza

**Comment by nalinbhardwaj** [comment]
@loganom makes sense. Here's a comparison:

New

screen shot 2017-01-30 at 1 21 49 am
Old

screen shot 2017-01-30 at 1 18 19 am

**Comment by mintsoft** [comment]
@loganom I like the larger die personally; I've always though the other ones were a little difficult to see

**Comment by loganom** [comment]
Thanks for the feedback @mintsoft. Glad to have someone else comment because of my bias :)

**Comment by loganom** [comment]
@mintsoft I was going to merge but can't recall the desired merge/squash/ commit as is action, could you please remind me? Thanks

**Comment by loganom** [comment]
Thanks for making this change @nalinbhardwaj :)

**Comment by loganom** [comment]
Looks like quite a few in the master commit history are squashes, so that's what I'll do.

**Comment by moollaza** [comment]
FWIW I think a better fix would be to replace the font-size class we're currently using on the element (`tx--21`) with our biggest font size class, `t-xxxxl`. It's not quite as big as the 350% though.

Just seems odd that we're specifying the font size with a css class, and also setting it even larger with the `font-size`

**Comment by nalinbhardwaj** [comment]
@moollaza I did try that, it seemed small to me. The dots on the dice aren't prominent at smaller sizes, but if you think it's _really_ not okay to deviate from the standards I'll change it back.

**Comment by moollaza** [comment]
> I did try that, it seemed small to me.

Ah glad to know you first tried that!

It looks like the font-size renders to 48px with `t-xxxxl` and with `tx--21` + `350%` its 55px.

The 48px looks OK to me, but if you feel its still too small then I think we're OK.

This is `t-xxxxl` on my screen:
roll_dice_at_duckduckgo

**Comment by nalinbhardwaj** [comment]
@moollaza Maybe someone else should look into this too. If more people think both are fine then we could switch it to `t-xxxxl` because deviating from standard may create some confusion in future.

Here's a comparison of the two:

`t-xxxxl`:
screen shot 2017-02-09 at 1 37 05 am
current:
screen shot 2017-02-09 at 1 37 45 am

**Comment by loganom** [comment]
`t-xxxxl` improves the readability of the IA while maintaining consistency with other font-size declarations, and receives my vote of approval.. wish I had thought of this earlier!

@nalinbhardwaj

**Comment by nalinbhardwaj** [comment]
Should I make another PR? @loganom

**Comment by loganom** [comment]
Yes, please. That would be great, @nalinbhardwaj

**Comment by loganom** [comment]
@nalinbhardwaj @moollaza I neglected to consider a dice roll such as `roll 2d6`. It appears as if the display will be less than satisfying. The _only_ rolls that appear to display as expected are the `roll 3 dice` format. I think the right thing to do is to pull this change until we have a suitable fix.

**Comment by moollaza** [comment]
@nalinbhardwaj @loganom I've reverted the changed and merged it.

We need to use our `t-x...` classes in the templates to size the dice appropriately. 

@nalinbhardwaj please be sure to test the display on mobile screens as well 👍

**Comment by loganom** [comment]
Thank you @moollaza - sorry for the inconvenience!

**Pull request merged**
