### PR TITLE
Passphrase: Add dash to regex accepted characters

### PR DESCRIPTION
**Pull request by moollaza**
## Description of new Instant Answer, or changes
Add's support for `-` in passphrase words. There are 4 in words.txt (e.g. "yo-yo", "drop-down").

Without this, the tests are susceptible to failure.

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [x] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [x] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [x] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [x] There is no unnecessary files in place (such as editor config files)
- [x] There is no API keys / secrets present
- [x] Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/passphrase

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@moollaza looks like this run may have exposed a problem is the tests: https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/builds/218583520#L1196 looks like `Path::Tiny` may have removed `subdir`

**Comment by moollaza** [comment]
> looks like Path::Tiny may have removed subdir

Doesn't look like there have been any recent changes to `Path::Tiny` that affect `subdir`: https://github.com/dagolden/Path-Tiny/blob/master/Changes

Running the build again...

**Comment by moollaza** [comment]
@mintsoft ok I managed to break it locally by upgrading `Module::Data`. That lib switched that from using `Path:::Class` which has `subdir` to `Path::Tiny` which uses `child`.

I am making a PR for DDG 👍

**Comment by moollaza** [comment]
Merging as I'm pretty confident this works. We will be fixing the tests this week 👍

**Pull request merged**
