### PR TITLE
PercentOf: Include terminating equal sign in trigger

### LINKED ISSUE #4052: Calculator: support equals sign when triggering percentage queries
## Problem

Based on user feedback, the calculator is not triggering on the query `7970 - 20% =`, but triggers on `7970 - 20%`. 

**Triggers** 👍 

screen shot 2017-03-28 at 10 06 24 am

**Doesn't Trigger** 👎 

screen shot 2017-03-28 at 10 06 54 am

## Solution

1. Add a test, or two!
2. The user should update the [query handling regex](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/PercentOf.pm#L16) to also make this trigger appropriately. 

## People to notify
@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/calculator

### PR DESCRIPTION
**Pull request by edcallaghan**
PercentOf: Include terminating equal sign in trigger

## Description of new Instant Answer, or changes

Includes optional terminating equal sign in trigger.

## Related Issues and Discussions

Fixes #4052 

## People to notify

@pjhampton 

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/percent_of

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Hi @edcallaghan, 👋  welcome!

First, thanks so much for submitting a PR 💙  💛  ❤️ . However, it doesn't meet out current community's standards / expectations. Can you please update the title to our typical format? Also, please reference the original issue in the section heading **Related Issues and Discussions**. In addition, please reach out to the relevant people in **People to notify**. I have put this issue on hold until this has been completed.

**Comment by pjhampton** [comment]
Thanks @edcallaghan! 
Next reviewer merge 👍

**Comment by moollaza** [comment]
@edcallaghan Thanks! This LGTM :+1:

**Pull request merged**
