### PR TITLE
domjacko's First Goodie

### PR DESCRIPTION
**Pull request by domjacko**
# Goodie Pull Request Template

Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**
It displays my name and tells me I'm awesome.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
The problem of people not knowing I'm awesome.

**What is the data source for your Instant Answer? (Provide a link if possible)**
None.

**Why did you choose this data source?**
None.

**Are there any other alternative (better) data sources?**
No.

**What are some example queries that trigger this Instant Answer?**
"duckduckhack domjacko"

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Everyone.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

**Which existing Instant Answers will this one supercede/overlap with?**
None.

**Are you having any problems? Do you need our help with anything?**
Nope.

**Where did you hear about DuckDuckHack? (For first time contributors)**
Twitter

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screen shot 2015-05-23 at 17 03 58

## Checklist
Please place an 'X' where appropriate.

```
- [X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [X] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

```

### CODE REVIEW

**Comment by domjacko** [comment]
# Goodie Pull Request Template

Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**
Displays shortcuts for the Firefox Awesome Bar.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Allows users to quickly get the list of shortcuts up without having to find the web page

**What is the data source for your Instant Answer? (Provide a link if possible)**
All data is found on this site.
https://support.mozilla.org/en-US/kb/awesome-bar-keyboard-shortcuts

**Why did you choose this data source?**
It's the official Mozilla source

**Are there any other alternative (better) data sources?**
Nope.

**What are some example queries that trigger this Instant Answer?**
"Firefox Awesome Bar cheat sheet"

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Firefox users

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No.

**Which existing Instant Answers will this one supercede/overlap with?**
None.

**Are you having any problems? Do you need our help with anything?**
No.

**Where did you hear about DuckDuckHack? (For first time contributors)**
Twitter

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screen shot 2015-05-23 at 23 17 17



## Checklist
Please place an 'X' where appropriate.

```
- [X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [X] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

```

**Comment by MrChrisW** [comment]
@domjacko Thanks for your contribution. You'll need to split these two up into separate PR's in order to get them reviewed and merged. :+1:

**Comment by domjacko** [comment]
@MrChrisW sorry, but any idea how to do that?

**Comment by MrChrisW** [comment]
@domjacko Sure! I'd recommend creating a new branch from your `master` branch using:
+ `git checkout -b firefox-awesome`
- This branch will now contain your first Goodie and the Firefox cheatsheet. 
+ Delete the first Goodie files from this branch using `git rm <goodie files>`
+ Make a new commit and push `git push -u origin firefox-awesome`

Then switch back to your master branch `git checkout master` and revert the commit that added the Firefox cheatsheet files using `git revert ab3cbd6` and push.

After that you'll have the first Goodie on your `master` branch (**in this PR**) and the Firefox cheatsheet on the `firefox-awesome` branch which you can switch to using `git checkout firefox-awesome` .

Then when ready you can create a new PR for merging the `firefox-awesome` branch with the `duckduckgo/zeroclickinfo-goodies` branch :+1: 

One more thing to note: CheatSheets are currently being updated to use a single Perl controller and simple JSON files for keywords and shortcuts (see #1131 & this [comment](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1091#issuecomment-94551609) for more info) *so you may need to wait for this to be completed before contributing your awesome cheatsheet!*

Hope that makes sense, please let me know if you have any questions, we're always here to help :smile:

**Comment by domjacko** [comment]
Okay. The commit should be reverted now so this PR should only by my 'First Goodie'. Thanks a lot for your help. I have also contacted someone about the new Cheatsheet format so should be sorting that too :)

**Comment by MrChrisW** [comment]
@domjacko Congratulations on making your first Goodie :cake: 

Now that you've made your first Goodie, we really hope you'll continue to contribute and make more Instant Answers! (Like your new CheatSheet!) Please checkout our [Ideas forum](https://duck.co/ideas) if you're unsure about what to build. 

There's always lots of discussion in our [GitHub repositories](https://github.com/duckduckgo) feel free to tackle issues or submit pull requests.

P.S Your Goodie should go live within a few weeks, we'll let you know here when it does!

**Comment by moollaza** [comment]
@domjacko congrats! It's live: https://duckduckgo.com/?q=duckduckhack+domjacko&ia=answer

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
