### PR TITLE
Remove duplicate word

### PR DESCRIPTION
**Pull request by horacekmi**

### CODE REVIEW

**Comment by daxtheduck** [comment]
@horacekmi Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub username:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by horacekmi** [comment]
This should fix https://duckduckgo.com/?q=vitamin+cheat+sheet&t=ffab&ia=answer&iax=1 - source for Vitamin D (fish mentioned twice)

**Comment by moollaza** [comment]
@horacekmi Thanks for contributing and welcome to DuckDuckHack!

This LGTM :+1: Great catch!

We invite you to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

**Comment by GuiltyDolphin** [comment]
Sorry, but @moollaza the pun!! Argh...

**Comment by moollaza** [comment]
@GuiltyDolphin hahaha I didn't even plan that one ;)

@horacekmi thanks again for fixing this Cheat Sheet! I wanted to get in touch with you to see if there’s anything I can help you with, or if you’d like me to suggest some more ways in which you can help out (bugs, new IA’s etc)?

I’m reaching out to our recent, successful contributors to see what brought them to DuckDuckHack, and what else you’d like to work on? Perhaps something more difficult like a full Goodie or API-Powered Spice Instant Answer?

Also if you have any feedback or thoughts on your experience contributing to DuckDuckHack I’d really appreciate it!

Cheers!

**Comment by edgesince84** [comment]
@horacekmi,  thanks again for fixing the cheat sheet! You’ve done a really good job here and we'd like you to help our community tackle the next big challenge - our mission to become the best search engine for programmers: https://duck.co/blog/post/297/help-for-programmers.

When you're ready to move on, please: 

- Create a new Instant Answer to increase our Programming IA coverage

OR

- Test live programming Instant Answers (or those in development) for bugs and suggest improvements 

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage).

Thanks again!

**Pull request merged**
