### PR TITLE
Bengali cheat sheet added

### PR DESCRIPTION
**Pull request by birajkarmakar**
**What problem does your Instant Answer solve (Why is it better than organic links)?**
It will help to find Basic bengali words and phrases instantly for new people who don't know bengali. As bengali is the official language of the state of West Bengal in India and it is also the national language of Bangladesh.

**What is the data source for your Instant Answer? (Provide a link if possible)**
http://www.omniglot.com/language/phrases/bengali.php

**Why did you choose this data source?**
It's a nice bengali cheat sheet and I've added some basics into the cheat sheet.

**Are there any other alternative (better) data sources?**
not that I know of.

**What are some example queries that trigger this Instant Answer?**
Bengali phrases, english to bengali, basic bengali phrases, basic bengali words.

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Every person who want to know a little bit about Bengali language.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes, https://duck.co/ideas/idea/6718/bengali-cheat-sheet .

**Which existing Instant Answers will this one supercede/overlap with?**
Not sure. I hope this is new IA.

**Are you having any problems? Do you need our help with anything?**
No.

**Where did you hear about DuckDuckHack? (For first time contributors)**
From internet. 

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
bengali-cheatsheet

-----
IA Page: https://duck.co/ia/view/bengali_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@birajkarmakar Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by iambibhas** [comment]
Hi @birajkarmakar, thanks for working on this. I actually had the bengali cheatsheet ready, but had to remove it from the previous PR where I introduced a new cheatsheet template called `language`. That template has a separate key for transliteration. Because you've already worked on this, here it my cheatsheet JSON as a gist - https://gist.github.com/iambibhas/d1b8275c17fdc47791a0

Just follow the syntax, change the template type and move the text you have inside brackets to the `trn` key. See how it looks.

**Comment by gautamkrishnar** [comment]
:+1:

**Comment by moollaza** [comment]
Looks like this still needs to be converted to use the new template. Instead of just `key` and `val` it should have `key`, `val` and `trn` like it does here: https://gist.github.com/iambibhas/d1b8275c17fdc47791a0

**Comment by iambibhas** [comment]
@birajkarmakar do you intend to finish this? Otherwise I'll send my version as another PR.

**Comment by gautamkrishnar** [comment]
@iambibhas I think he is busy with mozfest and mozlando.... He will finish it soon....

**Comment by moollaza** [comment]
@gautamkrishnar though there's no rush, do you know how soon?

Seems like in the interest of time @iambibhas might as well go ahead an make a PR

**Comment by gautamkrishnar** [comment]
@moollaza i m not sure about that. I will let him know about the issue...

**Comment by birajkarmakar** [comment]
I just come back. I will do it within next few days. 
Thanks.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Bengali Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/bengali_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
>I just come back. I will do it within next few days. 

Great! :+1:

**Comment by gautamkrishnar** [comment]
@moollaza  have u noted the screenshot?
Some unicode issue... :smile:

**Comment by birajkarmakar** [comment]
@gautamkrishnar 
I have checked in browser no Unicode issue.
https://beta.duckduckgo.com/?q=bengali+cheatsheet&ia=cheatsheet&iax=1

**Comment by birajkarmakar** [comment]
Today I am working on this.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Bengali Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/bengali_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Bengali Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/bengali_cheat_sheet_mobile.png)

**Comment by gautamkrishnar** [comment]
@birajkarmakar i mean the automatic screenshot system has an issue. Your code is perfectly fine...
:+1:

**Comment by moollaza** [comment]
@birajkarmakar this LGTM :+1:

Thanks a lot for contributing (we really appreciate it :smiley:). We invite you to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

**Comment by tagawa** [comment]
Nice job @birajkarmakar!

**Comment by gautamkrishnar** [comment]
@birajkarmakar congrats :smile: :+1:

**Comment by moollaza** [comment]
@birajkarmakar congrats! It's live: https://duckduckgo.com/?q=Bengali%20Cheat%20Sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Comment by tagawa** [comment]
Nice @birajkarmakar! One day I'll have to make it to India to test these phrases :-)

**Comment by birajkarmakar** [comment]
Thanks !

**Comment by gautamkrishnar** [comment]
@tagawa waiting for that day to mee you here! :wink: :smile:

**Pull request merged**
