### PR TITLE
created Goodie that displays shortcuts for Eclipse IDE

### PR DESCRIPTION
**Pull request by dmcdowell**
What does your Instant Answer do?
Displays shortcuts for Eclipse IDE.

What problem does your Instant Answer solve (Why is it better than organic links)?
It provides a no-click answer for users looking for shortcuts for Eclipse IDE.

What is the data source for your Instant Answer? (Provide a link if possible)
http://www.shortcutworld.com/shortcuts.php?l=en&p=win&application=Eclipse

Why did you choose this data source?
This data source was the most comprehensive of the data sources available.

Are there any other alternative (better) data sources?
http://www.vogella.com/tutorials/EclipseShortcuts/article.html
http://www.rossenstoyanchev.org/write/prog/eclipse/eclipse3.html

Unlike the chosen data source, these sources have fewer listed shortcuts and have not seen a more recent update than the date of the chosen source's most recent update (3/17/15).

What are some example queries that trigger this Instant Answer?
"eclipse cheatsheet", "eclipse cheat sheet", "eclipse commands", "eclipse help", "eclipse shortcuts", "eclipse shortcut", "eclipse reference", "eclipse guide", "eclipse quick reference"

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)
Programmers.

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?
No.

Which existing Instant Answers will this one supercede/overlap with?
None.

Are you having any problems? Do you need our help with anything?
No.

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
eclipse_shortcuts

Checklist

Please place an 'X' where appropriate.

- [X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [X] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [X] Google Chrome
        - [X] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10
        - [X] IE 11

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

### CODE REVIEW

**Comment by moollaza** [comment]
@dmcdowell thanks a lot for contributing, we really appreciate it! We'll be sure to review this shortly and give you some feedback!

**Comment by moollaza** [comment]
@dmcdowell sorry for the delay here! We were hard at work re-implementing the CheatSheets and it's now all done and documented.

The new way to make CheatSheets is much simpler, you only need to create a single JSON file and add it to the CheatSheet Goodie's share dir, `/share/Goodie/CheatSheet/`

Would you be able to convert this to the new JSON format? You can read the docs to learn about the new format: https://duck.co/duckduckhack/goodie_cheat_sheets

Once it's converted, we should be able to quickl review and merge this in!

Thanks again for contributing and sorry for the delay!

**Comment by mintsoft** [comment]
@dmcdowell Just checking in, are you interested into converting this into a cheatsheet?

**Comment by moollaza** [comment]
@dmcdowell It looks like someone else has come along and created an Eclipse IDE Cheat Sheet. You can see it here: https://duckduckgo.com/?q=eclipse+cheat+sheet&t=ffab&ia=cheatsheet

If you think it's missing anything important please feel free to submit a PR to update it. I'm closing this PR now as it's no longer needed because a cheat sheet, using the new JSON format now exists.

Sorry we couldn't use this, but thanks a lot for contributing. We really appreciate it and hope you'll stick around and continue to contribute!

**Pull request closed without merging**
