### PR TITLE
improving nodejs cheatsheet

### PR DESCRIPTION
**Pull request by Sayanc93**
IA: https://duck.co/ia/view/nodejs_cheat_sheet

Maintainer: @stanly-johnson

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@Sayanc93 thanks for this.

@stanly-johnson you are the maintainer of this IA. Please review the changes and let us know if you approve of them.

Seeing as @Sayanc93 has changed the indentation use this link to view the changes that have been made, ignore whitespace changes: https://github.com/stanly-johnson

**Comment by stanly-johnson** [comment]
@moollaza Looks good to me :+1:

**Comment by moollaza** [comment]
@stanly-johnson thanks!

**Pull request merged**
