### PR TITLE
removed html_enc() from HTMLEntitiesEncode.pm fixes:#3563

### PR DESCRIPTION
**Pull request by gautamkrishnar**
fixes:#3563

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Thanks!

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Whoops, look like you missed a few, mind making another PR?

**Comment by gautamkrishnar** [comment]
@guiltydolphin can you please elaborate?

**Comment by gautamkrishnar** [comment]
What's missed ?

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar There's a couple of `html_enc` calls still hanging around (do a quick `grep`).

**Comment by gautamkrishnar** [comment]
@GuiltyDolphin  i left them untouched because this IA require html_enc to work. It is even comparing a value with the html_enc() function. Please check the code. If you are sure that it must be removed, i wi open up annother pr.

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Ah, you are correct - this should be using an external library then (e.g., `HTML::Entities`) rather than `html_enc` which is designed for 'internal' use.

Would you like to update the library usage?

**Comment by gautamkrishnar** [comment]
@guiltydolphin sure, i am having my eams this week. I will give it a try after that... :+1: 

Thanks :laugh:

**Pull request merged**
