### PR TITLE
Italic transliteration text for language template

### PR DESCRIPTION
**Pull request by wongalvis**
image

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
:+1: LGTM

**Comment by moollaza** [comment]
@wongalvis we tend to use font-styling pretty lightly (usually opting for colour differentiation), but I can see the need to separate these visually.

@abeyang what are your thoughts on this? We have a new cheat sheet template that add's a 3rd line of text, providing a transliteration. How should we differentiate this from the actual translation? This format is only used when the translation is provided in a non-latin character set.

**Comment by abeyang** [comment]
Hey @wongalvis , like @moollaza mentioned, we generally don't use italics -- but given the use case, I think this is fine. Thanks.

**Comment by moollaza** [comment]
@abeyang thanks!

@wongalvis I think instead of CSS, we should use markup to indicate the text should be styled differently. Let's wrap the text inside the `<div>` with an `<em>` -- our site CSS will italicize the text as a result.

**Comment by wongalvis** [comment]
@moollaza It's now updated.

**Comment by moollaza** [comment]
@wongalvis Thanks! This LGTM :+1:

**Pull request merged**
