### PR TITLE
PR to fix issue #1143

### PR DESCRIPTION
**Pull request by charles-l**
Removed case-dependent file names for the GuitarChord goodie share directory. See issue #1143 for more information.

### CODE REVIEW

**Comment by moollaza** [comment]
@charles-l it looks like you need to run generate.pl again? I see all the files that were deleted but none were added to replace them?

**Comment by charles-l** [comment]
@moollaza oops, my git history got all goofed up and I was trying to fix it. It must not have added the images.

I've added them back now.

**Comment by moollaza** [comment]
@charles-l LGTM :+1:  Thanks a lot :smiley:

**Comment by charles-l** [comment]
@moollaza Great! I'll submit the PR for the CSS Chord cheatsheet soon.

**Pull request merged**
