### PR TITLE
Formula One Calendar

### PR DESCRIPTION
**Pull request by CVasquezG**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [x ] New Instant Answer
  - [ x] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Added an Instant answer that displays the Formula One Calendar.
###### Which issues (if any) does this fix?

Fixes #NNNN - how specifically does it fix the issue?
###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/formula_one_calendar

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

btw I used this tutorial http://docs.duckduckhack.com/walkthroughs/word-count-screencast.html

### CODE REVIEW

**Comment by daxtheduck** [comment]
@CVasquezG Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Hi @CVasquezG. Thank you very much for submitting this. It looks like it's still in progress so please let us know when you're ready for review or if you'd like any help with anything. By the way, do you know where'll get the calendar data from? Have you found a public API?

**Comment by CVasquezG** [comment]
Hello,
Yeah i apologize for making a pull request so early. For the API I was
thinking of using http://ergast.com/mrd/ but i need to contact them first
to ask permission.
I will keep working on it and try and ask more questions on slack since i
know i still have to do quite a bit.
Are there any more sources where i can see more documentation other than
http://docs.duckduckhack.com/resources (especially for how to do the
testing, a video would be really helpful).

Thank You

Camilo

**Comment by tagawa** [comment]
No problem @CVasquezG! As an F1 fan, it's great to see something like this being developed.
Regarding resources, we have a selection of videos which cover basics and IA tutorials: https://vimeo.com/channels/duckduckhack
Unfortunately they don't include testing but that's a good idea.
One more thing - if we are allowed to use that API, then this will have to be moved from the `zeroclickinfo-goodies` repository to the `zeroclickinfo-spice` one. Only "Spice" IAs have the ability to make calls to external APIs.

**Comment by GuiltyDolphin** [comment]
Hey @CVasquezG - as @tagawa mentioned, I think this'd be better of as a Spice if we're using an API; otherwise we'll get stuck with outdated data.

We try not to make any Instant Answers that have data that can become invalid as time passes - it might confuse people!

Don't worry too much about moving from Goodies->Spice; there's only a couple of extra 'keywords' and a little JS, but that's all!

**Comment by pjhampton** [comment]
This PR has gone stale. Closing as a result. 

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄

**Pull request closed without merging**
