### PR TITLE
New Clojure cheatsheet

### PR DESCRIPTION
**Pull request by Sayanc93**
IA: https://duck.co/ia/view/clojure_cheat_sheet

I searched and found the IA already exists for this cheat sheet although didn't find any file under it. Used the previous IA link for this PR instead. I hope thats okay.

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=clojure cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/clojure_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=clojure cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/clojure_cheat_sheet_mobile.png)

**Comment by Sayanc93** [comment]
Can this be reviewed and merged?

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=clojure cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/clojure_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=clojure cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/clojure_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=clojure cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/clojure_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@Sayanc93 thanks again for creating the Clojure Cheat Sheet! You’ve been doing a really good job here and we'd like you to help make DuckDuckGo even better for yourself and others interested in Clojure.

When you're ready to move on, please: 

- Create a new Instant Answer for searches you do related to Clojure

OR

- Test live Clojure Instant Answers (or those in development) for bugs and suggest improvements

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Creating-or-Improving-Instant-Answers).

Thanks again!

**Comment by moollaza** [comment]
Also, Thanks! This LGTM :+1:

**Pull request merged**
