### PR TITLE
New Goodie: What Does Dax Say

### PR DESCRIPTION
**Pull request by tagawa**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [X] New Instant Answer
  - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
  - [X] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Dax is the DuckDuckGo mascot and this is what he says.
###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/what_does_dax_say

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Current status: Trying to get the audio to work on the beta server. MP3 content type needs fixing I think.

**Comment by mintsoft** [comment]
@tagawa Ping! Are you planning to finish this one off or would you prefer it closed for now?

**Comment by tagawa** [comment]
Thanks for the ping @mintsoft. I think @moollaza told me this needs some work on our servers to get the audio to work, which is not a priority right now, so I'll close this. Maybe one day...

**Pull request closed without merging**
