### PR TITLE
Goodie LOLCAT Translator

### PR DESCRIPTION
**Pull request by JohnCarlosReed**
screenshot from 2014-11-10 21 47 07

**What does your Instant Answer do?**
Converts text into the LOLCAT language

**What problem does your Instant Answer solve (Why is it better than organic links)?**
It is a dynamic translator

**What is the data source for your Instant Answer? (Provide a link if possible)**
The Goodie PM file source code
https://github.com/JohnCarlosReed/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/LOLCAT.pm

**What are some example queries that trigger this Instant Answer?**
lolcat followed by any text

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
meme lovers, cat people, geeks

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes:  https://duck.co/ideas/idea/4595/lolcat-translator-goodie

**Which existing Instant Answers will this one supercede/overlap with?**
None

**Are you having any problems? Do you need our help with anything?**
No

**Where did you hear about DuckDuckHack? (For first time contributors)**
Searched for Perl open source projects

## Checklist
Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Ubuntu 14
        [X] Firefox

```

### CODE REVIEW

**Comment by zekiel** [comment]
@JohnCarlosReed  updates? here to help if you need anything.

**Comment by jagtalon** [comment]
@JohnCarlosReed Any updates? Would love to see this out! Really cool IA. :)

**Comment by jagtalon** [comment]
Closing this for now. Can always open it again!

**Comment by moollaza** [comment]
Labelling as abandoned, perhaps someone from the community can finish this one up

**Comment by puskin94** [comment]
@moollaza @jagtalon Which changes can I make, helping finishing this ??

**Comment by moollaza** [comment]
@puskin94 please take a look at the feedback given here: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/740/files and make sure everything has been addressed. 

I'm not sure what the current state of this IA is but once those are addressed and the above comments, we can give this one another look.

**Comment by mintsoft** [comment]
@moollaza @puskin94 IIRC it's just a case of making it so that it's not triggering too broadly etc

**Comment by francisbrito** [comment]
A "quick and dirty" way to narrow down the trigger could be changing the trigger word to be `lolcat say` as in: `lolcat say i'd like to have a cheeseburger`. Maybe have the trigger word be a post-fix like this: `i'd like to have a cheeseburger in lolcat`. Any thoughts?

**Comment by mintsoft** [comment]
@francisbrito that would work to reduce the query space somewhat; however if I searched for `memes related to lolcat` it'd still trigger.

I think unless the query contains words that can be "lolcatted" i.e. (`keys %repl `) then the goodie should return.

@francisbrito Are you looking at finishing this off? Much appreciated if you are!

**Comment by moollaza** [comment]
@francisbrito @mintsoft a similar IA would be the "DuckSay" Spice where we've only allowed the trigger to come at the start of the IA: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/DuckSay.pm#L15

I think that would work in this case as well. We could also then check to make sure the words exist in the "lolcat dictionary" so that they can be translated.

**Comment by francisbrito** [comment]
@mintsoft  I didn't make clear the trigger in the post-fix example was  **`in lolcat`**, meaning `memes related to lolcat` wouldn't return, sorry about that. Nevertheless, I understand your point, the query should **only** be triggered if it contains "lolcattable" (lol?) words. As for coding it, yes, I'm interested in helping finish this and other unfinished IAs to get used developing them. That being said, I have no previous expertise in Perl so any guide, tutorial or pointer is much appreciated. :)

@moollaza I agree. I'm thinking about using "lolcatsay" but it seems a little wordy. Maybe "lolsay" or "catsay" (all cats speak lolspeak after all ;))?

**Comment by mintsoft** [comment]
@francisbrito Both approaches sound viable to me; we can have a review about which will work most effectively on the PR :+1:  

With regards to getting started etc, have you run through the quickstart (https://duck.co/duckduckhack/goodie_quickstart)? It's a pretty speedy introduction to the DDH architecture that should give you a good grounding. If you are having any problems you can always post to duckduckhack@listbox.com or open a PR and we'll help you out.

**Comment by puskin94** [comment]
@francisbrito @mintsoft If thereis any kind of problem I can help finishing it :)

**Comment by zekiel** [comment]
should we close this out now?

**Pull request closed without merging**
