### PR TITLE
use record template in UnixPermissions goodie

### PR DESCRIPTION
**Pull request by jarmokivekas**
Moved the UnixPermissions goodie to use a template as part of #1163. If there is a more suitable template let me know. 

Tests still need amending to match the changes.

### CODE REVIEW

**Comment by jarmokivekas** [comment]
This is how it looks before and after:

before:
before

after:
after


That last 'Attributes'  key is in the "Show more". Not all answers have that key, though (since it's not always relevant), in which case there is no "Show more" and the answer is displayed in its entirety.

**Comment by mintsoft** [comment]
@jarmokivekas This is excellent, looks much better!

**Comment by mintsoft** [comment]
Although, I think it probably makes more sense to never have the show more in this situation?

**Comment by jarmokivekas** [comment]
I wasn't able to find how to disable the cut. Is there a key that can be set somewhere like in `structured_answer => templates => options`?

**Comment by jarmokivekas** [comment]
I just noticed that in this case the "Show more" automatically disappears (the last item is shown) when the browser window is wider than 850 pixels.

**Comment by mintsoft** [comment]
@jarmokivekas I think you might be right; I can't see an obvious way to 'disable' that behaviour so I feel it might be part of the responsive nature of the templates. @moollaza any clarification?

**Comment by moollaza** [comment]
@jarmokivekas @mintsoft right now there's no way to disable or set the cut-off. It's actually based on height, not # of elements. 

This is great for now. If we find we need to configure the cutoff in other places I'll talk to the team about making it flexible.

@jarmokivekas thanks a ton!

**Pull request merged**
