### PR TITLE
Updated repo to use pull request templates

### PR DESCRIPTION
**Pull request by gautamkrishnar**
Updated the repo to use PR templates:
https://github.com/blog/2111-issue-and-pull-request-templates.

@moollaza  what's your opinion on this?
I will update all other repos if needed! and will submit PR's

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
@duckduckgo/community-leaders what do u think about this?

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar I don't think we need *that* PR template back :wink:

I'm thinking something *much* more simple, we only really need a quick summary, maybe a screenshot (if applicable) and a link to the IA page.

**Comment by gautamkrishnar** [comment]
Yes i was also thinking like that. Lets know what the community has to say on it.

**Comment by gautamkrishnar** [comment]
Closing this

**Pull request closed without merging**
