### PR TITLE
TShark Cheat Sheet

### PR DESCRIPTION
**Pull request by adityatandon007**
## Description:
A network protocol analyzer

## People to notify
@moollaza @vduddu 

---

Instant Answer Page: https://duck.co/ia/view/tshark_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by adityatandon007** [comment]
@vduddu  I have made the changes as suggested by you. Thanks for the suggestions and thanks for reviewing my request

**Comment by adityatandon007** [comment]
Thanks @vduddu for approving the changes.

**Comment by vduddu** [comment]
@adityatandon007 I think terminal would be fine as you might be writing the filter and corresponding function... :)

**Pull request merged**
