### PR TITLE
Add group tabs to Firefox cheatsheet

### PR DESCRIPTION
**Pull request by danielfilho**
This PR adds 3 more shortcuts to Firefox cheat sheet, to what I believe is the best feature on it: tab management and grouping.

This is useful for all Firefox users.

Also, this is my first PR for DDG, so I'm planning to contribute more often :smile: 

ddg-firefox-tab-manager

### CODE REVIEW

**Comment by namandistro** [comment]
Hey thanks for the submit but I had already pulled a request for the complete cheatsheet which will be merged soon and this are even added to that... you can check it... https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1336

**Comment by danielfilho** [comment]
good one @namandistro. just add the `[Ctrl] [Shift] [E]` to yours, and I'll close this PR :)

**Comment by namandistro** [comment]
@Danielfilho I will surely make that change it just that. I find no official mentioning of that command.

**Comment by danielfilho** [comment]
hmm, this looks very official from here:

i8nmbmpfgo-3000x3000

:D

**Comment by namandistro** [comment]
@Danielfilho I will surely make that change and thanks once again.

**Comment by moollaza** [comment]
@Danielfilho thanks a lot for contributing, we really appreciate it. I'm glad you guys are able to collaborate and make the Cheat Sheet even better!

**Comment by namandistro** [comment]
@danielfilho I guess i already included that...! Still thanks.

**Pull request closed without merging**
