### PR TITLE
Opera Cheat Sheet

### PR DESCRIPTION
**Pull request by rhea-ahuja**
What does your Instant Answer do?

Show all The Opera shortcut keys as cheat sheet.

What is the data source for your Instant Answer? (Provide a link if possible)

http://www.makeuseof.com/tag/opera-shortcuts/

Why did you choose this data source?

One of the Best and even recommended.

Are there any other alternative (better) data sources?

Their are chances.

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)

Opera users.

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?

Yes, https://duck.co/ideas/idea/6291/opera-browser-cheat-sheet

Are you having any problems? Do you need our help with anything?

No

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
screenshot from 2015-08-27 23 41 58

-----
IA Page: https://duck.co/ia/view/opera_cheat_sheet

### CODE REVIEW

**Comment by mintsoft** [comment]
@rhea-ahuja Thanks for contributing; as a former Opera user this'd be of use to me! However these shortcuts look like they're for Opera <= 12.17? Do you know if they're still valid for Chrome/Blink based Opera versions? (15+)

**Comment by rhea-ahuja** [comment]
@mintsoft yes, those changes have been made.

**Comment by MariagraziaAlastra** [comment]
Hey @rhea-ahuja, thanks a lot for your contribution!
We'd like to give you edit permissions for your [IA Page](https://duck.co/ia/view/opera_cheat_sheet); in order to do that, though, we need to know your username on duck.co (if you're not registered you can sign up [here](https://duck.co/my/register)). Thank you!

**Comment by rhea-ahuja** [comment]
Its rhea_ahuja @MariagraziaAlastra

**Comment by MariagraziaAlastra** [comment]
@rhea-ahuja Thanks, now you can edit your IA Page! Let me know if you have any issues :)

**Comment by mintsoft** [comment]
This LGTM, however most of the shortcuts will only apply if advanced keyboard shortcuts are enabled (http://help.opera.com/opera/Windows/1857/en/fasterBrowsing.html#advanced) can we attempt to make that explicit somewhere?

**Comment by moollaza** [comment]
>This LGTM, however most of the shortcuts will only apply if advanced keyboard shortcuts are enabled (http://help.opera.com/opera/Windows/1857/en/fasterBrowsing.html#advanced) can we attempt to make that explicit somewhere?

@rhea-ahuja @mintsoft sounds like adding a `description` would be a great way to explain that shortcuts need to be enabled to work!

**Comment by moollaza** [comment]
Once the description is added, this LGTM :+1:

**Comment by rhea-ahuja** [comment]
@moollaza Have a look.

**Comment by moollaza** [comment]
@rhea-ahuja Thanks for taking the time to contribute! We really appreciate it.

I've merged this in, with some minor adjustments, in #1571 

We invite you to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

**Comment by moollaza** [comment]
@rhea-ahuja congrats! It's live: https://duckduckgo.com/?q=opera+cheat+sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
