### PR TITLE
Multiple CheatSheet: Updated aliases as per #2967

### LINKED ISSUE #2967: Various Cheat Sheets: Update aliases
@duckduckgo/duckduckhack-contributors Some very low-hanging-fruit here; we need some aliases updated for a pending PR (#2777):

- [x] https://duck.co/ia/view/dothraki_cheat_sheet (@varundey) - remove `dothraki language`
- [ ] https://duck.co/ia/view/finnish_cheat_sheet (@riqpe) - remove `english to finnish` and `basic finnish`
- [x] https://duck.co/ia/view/greek_cheat_sheet (@synbit) - remove `english to greek` and `basic greek`
- [ ] https://duck.co/ia/view/high_valyrian_cheat_sheet (@siddhanjay) - remove `game of thrones language` and `valyrian language`
- [ ] https://duck.co/ia/view/kannada_cheat_sheet (@pnpninja) - remove `basic kannada`
- [x] https://duck.co/ia/view/minionese_cheat_sheet (@swapagarwal) - remove `minion language`
- [ ] https://duck.co/ia/view/spanish_cheat_sheet (@rasikapohankar)  - remove `basic spanish`
- [x] https://duck.co/ia/view/telugu_cheat_sheet (@roxxup) - remove `english to telugu` and `basic telugu`

### PR DESCRIPTION
**Pull request by d1ndra**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [x] Bug fix: **`Various Cheat Sheets: Fix #2967`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Provide an overview of the changes this pull request introduces.

###### Which issues (if any) does this fix?

Fixes #2967 - Updated aliases

###### People to notify (@mention interested parties)
@GuiltyDolphin 

---

Instant Answer Page: https://duck.co/ia/view/finnish_cheat_sheet 
Instant Answer Page: https://duck.co/ia/view/high_valyrian_cheat_sheet 
Instant Answer Page: https://duck.co/ia/view/kannada_cheat_sheet 
Instant Answer Page: https://duck.co/ia/view/spanish_cheat_sheet 
Instant Answer Page: https://duck.co/ia/view/telugu_cheat_sheet 

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @siddhanjay 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pnpninja 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @roxxup

### CODE REVIEW

**Comment by daxtheduck** [comment]
@d1ndra Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
## [Finnish Cheat Sheet](https://duck.co/ia/view/finnish_cheat_sheet)

**Description**: Basic Finnish words and phrases.

**Example Query**: [finnish cheat sheet](https://beta.duckduckgo.com/?q=finnish cheat sheet)

**Tab Name**: Cheat Sheet

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/finnish_cheat_sheet)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/finnish_cheat_sheet)*

**Comment by NaveenKarippai** [comment]
I suspect this PR should be split into different PR each with change set for the respective IA (not four IA change sets on a single PR). What would you say @GuiltyDolphin ?

**Comment by GuiltyDolphin** [comment]
@d1ndra Thanks.

**Pull request merged**
