### PR TITLE
Cpp Multimap Cheat Sheet added

### PR DESCRIPTION
**Pull request by ManrajGrover**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New {CPP Multimap} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

This pull request adds CPP Multimap Cheat Sheet 

###### Which issues (if any) does this fix?

None

###### People to notify (@mention interested parties)

@zekiel @moollaza 

---

Instant Answer Page: https://duck.co/ia/view/cpp_multimap_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention
None

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Cpp Multimap Cheat Sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/cpp_multimap_cheat_sheet_mobile.png?pPhEntzdgi)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Cpp Multimap Cheat Sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/cpp_multimap_cheat_sheet_mobile.png?TP5XuKZdPp)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Cpp Multimap Cheat Sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/cpp_multimap_cheat_sheet_mobile.png?aEz9hPYOuz)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Cpp Multimap Cheat Sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/cpp_multimap_cheat_sheet_mobile.png?MZGDbqPdwL)

**Comment by tagawa** [comment]
Hi @ManrajGrover. Thank you for creating another Instant Answer - you're a C++ cheat sheet machine! 

I'm not sure why this one was failing but restarting Travis seems to have fixed it. It's now on the beta server for testing:
https://beta.duckduckgo.com/?q=Cpp+Multimap+Cheat+Sheet&ia=cheatsheet&iax=1

**Comment by ManrajGrover** [comment]
@tagawa Hey! :smile: Thank you for restarting the build. This generally happens because Build is not able to find the IA page created on duck.co because page is not public. I remember there was an issue raised for fixing this.

**Comment by tagawa** [comment]
@ManrajGrover I see you what you mean. Anyway, thank you for this cheat sheet. Looks good to me - let's get merging...

**Comment by daxtheduck** [comment]
@ManrajGrover this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
