### PR TITLE
RestructuredText Cheat Sheet: Fix typo

### LINKED ISSUE #4454: RestructuredText Cheat Sheet: Missing "*" in Emphasis line
Hey there,

On the line that states `*emphasis`, it's missing an * at the end. Should instead be `*emphasis*`.

Thanks.

------
IA Page:  http://duck.co/ia/view/restructuredtext_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nickschafran

### PR DESCRIPTION
**Pull request by anoadragon453**
Fixes small typo: `*emphasis` -> `*emphasis*`

## Related Issues and Discussions

Fixes #4454 

## People to notify

@nickschafran 

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

---
Instant Answer Page: https://duck.co/ia/view/restructuredtext_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
Travis has thrown a fit on this so I'm restarting the build

**Comment by anoadragon453** [comment]
Strange, but thank you.

**Comment by mintsoft** [comment]
Cool, tested on my duckpan and LGTM

**Comment by mintsoft** [comment]
Many Thanks @anoadragon453

**Comment by anoadragon453** [comment]
@mintsoft Thank you for your wonderfully open infrastructure!

**Pull request merged**
