### PR TITLE
Touch up CheatSheets

### PR DESCRIPTION
**Pull request by zachthompson**
A few outstanding items on CheatSheets:

* "Vim" was still hardcoded
* Convert tabs to spaces
* @moollaza forgot to give himself credit.

### CODE REVIEW

**Comment by moollaza** [comment]
>AutoPrereqs for dzil. Seems to do a better job than we do manually.

What?! Why haven't we been using this?!

**Comment by zachthompson** [comment]
Might be too good to be true, @moollaza.  Let me see if I can make travis happy.

**Comment by jagtalon** [comment]
@zachthompson autoprereqs just blew my mind.

**Comment by zachthompson** [comment]
@jagtalon We're pulling it from here and will add to the BuildShareAssets PRs.

**Comment by moollaza** [comment]
LGTM ;

**Pull request merged**
