### PR TITLE
Attempt to fix #1451

### LINKED ISSUE #1451: TimezoneConverter: Some results are "too" friendly
I tried to convert "5 AM EDT" to my time zone and I got "Noon EEST". It took me a while to notice the word because I was looking for a HH:MM time stamp. Please always give the exact time as the main text and use smaller text for the more friendly "noon".

image

---

IA Page:  http://duck.co/ia/view/timezone_converter

### PR DESCRIPTION
**Pull request by alexandernext**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer
  - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [ X ] Enhancement: **`{Timezone Converter}: {Fixed issue described in #1451}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Discards the "noon" and "midnight" labels.
###### Which issues (if any) does this fix?

Fixes #1451- it discards the "noon" and "midnight" labels.
###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/timezone_converter

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@alexandernext it looks there are a few tests that need to be updated still. It looks like there are instances of `0:00 AM` that should be `12:00 AM` and some reversed `AM` and `PM` in the tests. 

Checkout the Travis output, or run the tests locally to see what's failing 👍

**Comment by edgesince84** [comment]
hey @alexandernext I wanted to see if you still planned on finishing this up - we really appreciate your contribution and want to see this go live. We're closing up old PRs in the next week, so let me know if I should leave this open for you!

If you'd rather work on something new, we'd like to invite you to our [new forum](https://forum.duckduckhack.com/) to preview how we're improving programming-related searches. There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Comment by pjhampton** [comment]
Closing as this PR looks to have gone stale.

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄

**Pull request closed without merging**
