### PR TITLE
CSS cheat sheet: Add import syntax

### PR DESCRIPTION
**Pull request by vikashvverma**
This PR adds import syntax to cheat sheet.

IA Page : https://duck.co/ia/view/css_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@vikashvverma Doesn't work for me: (I think it is the `@`):

screenshot from 2016-02-16 08 46 15

Also, it feels quite out of place (you used a slightly more Backus style compared to the others - perhaps try and get it to match the surrounding style).

**Comment by vikashvverma** [comment]
Sure

**Comment by vikashvverma** [comment]
@GuiltyDolphin I think it has not been deployed to [beta](https://beta.duckduckgo.com/?q=css+cheat+sheet&ia=answer&iax=1).

It looks fine locally.

screen shot 2016-02-16 at 2 42 36 pm

**Comment by vikashvverma** [comment]
@GuiltyDolphin It's on [beta](https://beta.duckduckgo.com/?q=css+cheat+sheet&ia=answer&iax=1) now and looks fine.

**Comment by GuiltyDolphin** [comment]
@vikashvverma Bracket eh?

I still think it could be updated to follow the style of the rest of the cheat sheet a bit more though. The alternative would be to update the rest of that section to match the new syntax (only 3 keys?).

**Comment by moollaza** [comment]
@vikashvverma Thanks! This LGTM :+1:

**Pull request merged**
