### PR TITLE
Is website up or down Goodie 

### PR DESCRIPTION
**Pull request by codenirvana**
**What does your Instant Answer do?**
Check if given URL is onine or not

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Provides the status of URL user looking for.

**What are some example queries that trigger this Instant Answer?**
"isup duckduckgo.com", "is up https://duckduckgo.com",  "online duckduckgo.com", "github.com is down"

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Geeks, computing_info, Web Dev

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes, [Check if a site is online](https://duck.co/ideas/idea/6602/check-if-a-site-is-online)

**Which existing Instant Answers will this one supercede/overlap with?**
This will overlap !isup bang

**Are you having any problems? Do you need our help with anything?**
Yes I want to add multiple trigger like this- :start-trigger: query :end-trigger:

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screenshot

### CODE REVIEW

**Comment by mintsoft** [comment]
@codenirvana Hello! Thanks for the PR, unfortunately Goodies cannot perfom HTTP requests. If there's an API available then a spice could be used instead. That said, there is https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/IsItUp.pm already?

**Comment by moollaza** [comment]
@codenirvana please make sure you share your idea with us before diving into it so we can ensure you don't spend your time working on something we can't accept!

**Comment by codenirvana** [comment]
@moollaza I made this because its listed in Instant Answer Ideas and its not flagged duplicate and under development.

**Comment by codenirvana** [comment]
@mintsoft seems like that spice is not working...
I searched a lot but its not giving any instant answer.

**Comment by moollaza** [comment]
@codenirvana @mintsoft looks like the API switched to HTTPS so the IA isn't working right now. I pushed an update an it will be fixed with the next release.

> I made this because its listed in Instant Answer Ideas 

to clarify (and it's not your fault, because we haven't made it very clear) ideas marked as `new` haven't been approved by us yet. Once the idea's status is changed to "Needs a developer" it means we've approved it and it is now claimable. You'll see the "claim this idea" button beside the IA and clicking it will claim it, let everyone know you've claimed it, and also generate an IA Page for the idea.

> and its not flagged duplicate and under development.

Sorry about that. We need to do a better job of curating the ideas so this doesn't happen in the future.

**Pull request closed without merging**
