### PR TITLE
New Prime Instant Answer

### PR DESCRIPTION
**Pull request by JoshNavi**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [X] New Instant Answer
  - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
  - [X] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

This is an Instant Answer that will determine whether a number is prime and if not display the numbers it is divisible by.
###### Which issues (if any) does this fix?

Fixes #NNNN - how specifically does it fix the issue?
###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/prime

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
@JoshNavi Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by JoshNavi** [comment]
https://duck.co/ia/view/prime

**Comment by edgesince84** [comment]
hey @JoshNavi - can you fill out the IA page some more?  things such as the data source could be added - and we'll get this reviewed!

**Comment by GuiltyDolphin** [comment]
@JoshNavi we already have an Instant Answer for prime factors: https://duck.co/ia/view/prime_factors - this also will tell you whether or not a number is prime (though you must ask for the factors first).

And an Instant Answer that generates primes: https://duck.co/ia/view/prime_number

What exactly is it this Instant Answer aims to do that *isn't* handled by those Instant Answers? You could improve the triggering of [PrimeFactors](https://duck.co/ia/view/prime_factors) to better handle queries of the form 'is X prime?' if you are attempting to handle those queries.

**Comment by pjhampton** [comment]
Closing as this PR looks to have gone stale.

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄

**Pull request closed without merging**
