### PR TITLE
Change Tab name to match IA Page

### PR DESCRIPTION
**Pull request by moollaza**
Updating tab name to canonical "Answer"

---
IA Page: https://duck.co/ia/view/alt_calendars

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@moollaza Might want to update those tests!

**Comment by moollaza** [comment]
> @moollaza Might want to update those tests!

Whoops, Fixed!

**Comment by GuiltyDolphin** [comment]
@moollaza Thanks! No maintainer yet so :+1:

**Pull request merged**
