### PR TITLE
Questions containing fractions should return fraction result

### PR DESCRIPTION
**Pull request by munizas**
# Goodie Pull Request Template

Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**
Returns a fraction math result if the query contains fractions

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Currently the calculator only returns decimal answers, this feature adds the answer in fraction form

**What is the data source for your Instant Answer? (Provide a link if possible)**
N/A

**Why did you choose this data source?**
N/A

**Are there any other alternative (better) data sources?**
N/A

**What are some example queries that trigger this Instant Answer?**
"3/7 + 5/6", "1/4 + 2/4";

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Anyone who has the need for a calculator

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes

**Which existing Instant Answers will this one supercede/overlap with?**

**Are you having any problems? Do you need our help with anything?**
Not at the moment

**Where did you hear about DuckDuckHack? (For first time contributors)**
I saw the duck icon pop up when I was typing into the top search bar in Firefox

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
https://drive.google.com/file/d/0B7KPWDfeqtoHeXBjZkg4NjBoc00/view?usp=sharing

## Checklist
Please place an 'X' where appropriate.

```
[] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
    Appended tests to the existing Calculator.t
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[X] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [X] Google Chrome
        [X] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [X] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [X] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by jagtalon** [comment]
@munizas 

- Would something like http://search.cpan.org/~kevina/Fraction-v.53b/Fraction.pm be better instead of writing our own?

- Not sure if I like the display--looks a bit crowded. I don't have any alternatives, though CC @abeyang @moollaza 

screen shot 2015-01-15 at 9 58 40 am

- @mintsoft @moollaza is it worth trying to convert the result into a fraction? Maybe decimal is good enough?

**Comment by munizas** [comment]
@jagtalon 
Kevin Atkinson's Fraction module is definitely a more complete implementation as far as supporting additional operators such as subtraction, division etc.  For the problem I was trying to solve, this alternative Fraction module might introduce overhead since I'm only using addition in my implementation.  That being said, if you plan to do more complex arithmetic with actual fraction objects, not just decimal representations, in the future then I would recommend using Kevin's module.

**Comment by moollaza** [comment]
Hey guys,

Sorry for the late response. I agree that the mixed fraction/decimal answer is a little crowded and hard to quickly understand.Taking a step back, I'm not sure this approach is really the best way to handle how the calculator's answers should be represented though.

Eventually the calculator will move towards a more interactive Instant Answer (Goodie templates are currently being worked on internally...) which would mean we'd have more control over the frontend via JS. Once we're at that stage, I think it would make more sense to have some sort of toggle on the UI that could allow you to switch to a fractional view. I feel that a decimal answer should always be the default, though.

What do you guys think of that? I hate to throw away your work @munizas, perhaps some of it could be ported to JS later if necessary?

**Comment by munizas** [comment]
@moollaza that's fine with me.  Don't worry about the work, it was a fun first experience with Perl, the duckduckgo environment and working with you guys.

**Comment by moollaza** [comment]
@munizas alternatively, if you'd like to at least have your work go to some use, maybe we should allow for fractional answers based on a trigger word like "fraction", "to fraction", "fraction math" etc? That way this is still useful and then perhaps we could add a link to calculator results that says something like "View as fraction"

Any thoughts on that guys?

**Comment by jagtalon** [comment]
@moollaza that sounds good

**Comment by moollaza** [comment]
Closing for now. Can open back up if you'd like to move ahead with my suggestion @munizas

**Comment by munizas** [comment]
Ok sounds good.  I'll probably continue working on it after the semester
ends, thanks.

**Pull request closed without merging**
