### PR TITLE
New VB.NET Cheat Sheet

### PR DESCRIPTION
**Pull request by EpicWolverine**
###### What does your Pull Request do (check all that apply)?

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

This pull request adds a cheat sheet for VB.NET. 

This is my first cheat sheet (and first IA), so I'm not sure if I was too detailed in some areas or too vague in others. 

###### Which issues (if any) does this fix?

None.

###### People to notify (@mention interested parties)

@tagawa, thanks for helping me out.

---

Instant Answer Page: https://duck.co/ia/view/vb_net_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @EpicWolverine

### CODE REVIEW

**Comment by daxtheduck** [comment]
@EpicWolverine Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Hi @EpicWolverine, thanks for submitting this. It's looking good but the automatic checks have failed. This seems to be because the IA page has the name "vb_net_cheat_sheet" so please could you rename your JSON file to `vb_net.json`, and change its ID to `vb_net_cheat_sheet`? We should probably then add `vbnet` as another alias as well.

**Comment by EpicWolverine** [comment]
It didn't like that either. Do you have another recommendation?

**Comment by gaulrobe** [comment]
@EpicWolverine try vb-net.json as the file name.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=vb.net cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/vb_net_cheat_sheet_mobile.png?hoTIx5eU70)

**Comment by tagawa** [comment]
@EpicWolverine Sorry, my mistake. Thanks for renaming again - it looks like it worked. This is now on the beta server for testing (https://beta.duckduckgo.com/?q=vb.net%20cheat%20sheet) and if all goes well we should be able to merge soon.

**Comment by daxtheduck** [comment]
@EpicWolverine this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Comment by mintsoft** [comment]
LGTM Thanks @gaulrobe @tagawa  @EpicWolverine

**Comment by EpicWolverine** [comment]
Sweet. Thanks to all of you for your help. The DDG community is indeed as awesome as you claim it to be.

**Pull request merged**
