### PR TITLE
Harry Potter spell cheatsheet

### PR DESCRIPTION
**Pull request by gokul1794**
**What does your Instant Answer do?**
It lists out all the Harry Potter spells.

**What is the data source for your Instant Answer? (Provide a link if possible)**
http://harrypotterspells.net/

**Why did you choose this data source?**
Because it had all of the spells mentioned in the book

**Are there any other alternative (better) data sources?**
Wikipedia and harrypotterspells have pretty much the same thing covered.

**What are some example queries that trigger this Instant Answer?**
harry potter spells guide, harry potter spells cheatsheet

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Wizards and witches who need a quick reference while dueling. ;D

**Where did you hear about DuckDuckHack? (For first time contributors)**
Heard it from @kbhat95 and attended the DDG meetup in Bangalore

I've tested it on Firefox and Coogle Chrome on Ubuntu 14.04 and Android.

### CODE REVIEW

**Comment by moollaza** [comment]
@gokul1794 Thanks a lot for contributing, we really appreciate it :smiley:

Can you please fill out the [pull request template](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/pull_request_template_spice.md) and edit your initial comment.

Thanks!

For anyone interested here's how this looks right now:

screen shot 2015-06-03 at 18 38 54

------

@abeyang I think this is mergable, but it's definitely a use-case we hadn't really considered (i.e. alpha sort etc)

Ultimately I think this may need to be a Goodie when we're able to use the category view but for now this is good.

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
@gokul1794 Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Comment by moollaza** [comment]
@gokul1794 congrats! It's live: https://duckduckgo.com/?q=harry+potter+spells+cheat+sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Comment by gokul1794** [comment]
Yay! :D

**Pull request merged**
