### PR TITLE
Don't each references in CheatSheets

### PR DESCRIPTION
**Pull request by zachthompson**
Generates warnings, e.g. https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2835.

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@zachthompson There's some in the tests too, I believe.

**Comment by mintsoft** [comment]
@zachthompson looks better, but as @GuiltyDolphin says, there's still some in the test suite:
```
t/CheatSheets/CheatSheetsJSON.t .. values on reference is experimental at t/CheatSheets/CheatSheetsJSON.t line 28.
each on reference is experimental at t/CheatSheets/CheatSheetsJSON.t line 195.
```

**Comment by GuiltyDolphin** [comment]
@mintsoft I think the real problem is that we're so cutting edge :wink:

Perhaps I'd better update to 5.20 ^.^

**Comment by mintsoft** [comment]
@GuiltyDolphin Speak for yourself! I'm a Debian guy, it aint stable until it's at least 4 years old!

**Comment by GuiltyDolphin** [comment]
@mintsoft So that's why I can't get any of the *new* releases ;) Gimme them nightly GitHub repos!

**Comment by zachthompson** [comment]
Ok @mintsoft and @GuiltyDolphin, what say you?

**Comment by mintsoft** [comment]
@zachthompson I'm still getting:
```t/CheatSheets/CheatSheetsJSON.t .. values on reference is experimental at t/CheatSheets/CheatSheetsJSON.t line 28.
```
But that doesn't show up on Travis for some reason

**Comment by zachthompson** [comment]
Nice, try now.

**Comment by mintsoft** [comment]
@zachthompson LGTM!

**Pull request merged**
