### PR TITLE
Fix #1934 - Rubiks Cube Patterns: Show all patterns for "rubics cube patterns", add images to results

### LINKED ISSUE #1934: Rubiks Cube Patterns: Show all patterns for "rubics cube patterns", add images to results
I just came across this website: http://ruwix.com/the-rubiks-cube/rubiks-cube-patterns-algorithms/

which showcases visuals for many patterns. We should try and borrow these images (with permission from the website ideally) or find others that are freely available, or make our own (/cc @thm @abeyang thoughts?)

Then, we can show those images along with the results to improve them.

For the query "rubics cube patterns", we could do a tile-view highlighting pictures of each pattern with the name. Clicking the tile could potentially show more info, or send you to a the above website.

------
IA Page:  http://duck.co/ia/view/rubiks_cube_patterns

### PR DESCRIPTION
**Pull request by Mailkov**
IA Page: http://duck.co/ia/view/rubiks_cube_patterns

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata post coming soon

**Comment by moollaza** [comment]
@Mailkov sorry for the delay! Thanks a lot for this. It's now live on Beta. I demoed this for the team and everyone is really excited.

The design team has some feedback though. //cc @abeyang

**Comment by russellholt** [comment]
Hey, this is cool!

**Comment by mintsoft** [comment]
@abeyang this LGTM; is it good design wise?

**Comment by moollaza** [comment]
@Mailkov @mintsoft This LGTM :+1:

I believe the design team has some ideas for the SVG but we can go ahead and merge this for now.

**Pull request merged**
