### PR TITLE
Add more public DNS providers

### PR DESCRIPTION
**Pull request by Snapy**
What has been changed :
- updated links to newer ones and/or make use of https
- Added a lot of providers according to http://pcsupport.about.com/od/tipstricks/a/free-public-dns-servers.htm among others

I have a few questions before possibly merging :
- Is there a limit to the number of IPv4/6 per provider
  - OpenDNS has two additional basic DNS, Level3 has 4.2.2.1 to 6  

Adding up to four DNS servers would be enough in most case or displaying them with a "show more" button like in other IAs.
- What are the criteria for the providers
  - free & public (naturally)
  - basic filtering allowed (spam, botnets, viruses, malwares and the likes ; even pornography/adult content)
  - any other criteria such as free registration to have more control over what is filtered
- For the ones that offer different filtering policies (Yandex.DNS, OpenDNS, Norton, Comodo) is there a way to show more prominently these choices in the IA  

Adding another attribute to be able to sort by criteria (location, filtering, IPv4/6) would be great.
- Is there any restriction regarding the location of the DNS servers
  - It would be nice to display the DNS from the ISP of a given country (or is it out of the scope of this IA)

Depending of the answers to the above questions, I will modify my PR.

Feel free to tell me if there is anything else I should modify.

-----
IA Page: https://duck.co/ia/view/public_dns

### CODE REVIEW

**Comment by daxtheduck** [comment]
@Snapy Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by moollaza** [comment]
@Snapy thanks a lot for this! These updates are great :+1: 

> Is there a limit to the number of IPv4/6 per provider 

I think right now we went with 2 each because it worked will. The code can be updated to handle more (I have more on this...)

>Adding up to four DNS servers would be enough in most case or displaying them with a "show more" button like in other IAs.

This too can be achieved if the code get's updated.

> What are the criteria for the providers 

I don't believe we have any set-rules or requirements. The list has just been slowly growing as new devs have added to it. We could agree on some guidelines and add a README to the IA's share dir explaining them, or add it as a comment to the YAML I suppose.

> For the ones that offer different filtering policies (Yandex.DNS, OpenDNS, Norton, Comodo) is there a way to show more prominently these choices in the IA

Again, this is possible with updates to the code...

>Adding another attribute to be able to sort by criteria (location, filtering, IPv4/6) would be great.

We have plans to bring this functionality to IA's soon. But it would require updating the code to use a built-in template.

>Is there any restriction regarding the location of the DNS servers

Again no real rules have been set. The community is free to decide upon what you'd like to see here. 

> - It would be nice to display the DNS from the ISP of a given country (or is it out of the scope of this IA)

I'm not quite sure what you mean by this, but it does sound like it would be outside the scope.

> Feel free to tell me if there is anything else I should modify.

In it's current state this PR is OK. But this IA is long overdue for a visual update and a code cleanup. We should be using a built-in template for this IA.

We could use the List template to show rows + columns of data, like the [NameDays IA](https://duckduckgo.com/?q=name+days+maria&t=ffab&ia=answer) (though the design is right, this was implemented before templates were available so the code isn't a good example) or [AQI](https://duck.co/ia/view/aqi).

Would you be interested in updating the code to use a template? You may need to use some CSS.

**Comment by moollaza** [comment]
I'd be happy to merge this as-is, either way :+1:

**Comment by Snapy** [comment]
Thanks for your replies @moollaza . I am willing to update the code to use the new template (and adapt to my suggetions) although I am quite inexperienced regarding CSS but if you point me in the right direction I will be pleased to update the IA.

**Comment by Snapy** [comment]
I created a branch with a draft of a [readme] (/Snapy/zeroclickinfo-goodies/blob/patch-1-readme.md/share/goodie/public_dns/README.MD) file. Feedback is welcomed.
Regarding location-based DNS providers (such as ISP) I took a look at [PR#2110] (/duckduckgo/zeroclickinfo-spice/pull/2110) (great work @cylgom) and it is what is needed except that in this case there is no API.
Also is there anyway to see it live on <https://beta.duckduckgo.com> ?
I wonder if it would be enough (for now) to put on the same line DNS servers from a same filtering policy and adding a fourth column with the name of the policy. It would look like

Provider       | IPv4 | IPv6 | Filtering Policy
-----------   |   ----- | ----- | -------------------
Yandex.DNS | 77.88.8.8/77.88.8.1 | |  <abbr title="Basic Quick and reliable DNS">Basic</abbr>
                    | 77.88.8.88/77.88.8.2 | | Safe

I am still thinking of more ways to improve this goodie.

**Comment by moollaza** [comment]
>I created a branch with a draft of a readme file. Feedback is welcomed.

Excellent thanks! The README looks great. With regards to the link for creating an Issue, we typically suggest users visit the IA Page for the Instant Answer, and click the "Create Issue" button. The ensures that the Issue is linked back to the IA Page, because the button adds a link back to the IA Page, which our community platform will detect.

> Also is there anyway to see it live on https://beta.duckduckgo.com ?

@Snapy The OpenNIC Spice is now available on Beta: https://beta.duckduckgo.com/?q=opennic+42.42.42.42&ia=dns

>I wonder if it would be enough (for now) to put on the same line DNS servers from a same filtering policy and adding a fourth column with the name of the policy.

@Snapy it should be. Right now the template creates an `<li>` and your sub-template, will create `<div>` that create the look of columns. You could put `<div>`s inside the columns, making it look like there are multiple rows. This is similar to how the NameDays IA works.

I wouldn't suggest using another `<li>` to create a second "row" like you have in your table above though.

>I am still thinking of more ways to improve this goodie.

I'll have our designer, @abeyang weigh in on this..

**Comment by Snapy** [comment]
I meant if my modifications of the public DNS could be live on the beta version of DDG.
Also on mobile there is a display issue (no scrollbar and truncated). Will it be fixed when switching to the new template ?

**Comment by moollaza** [comment]
>I meant if my modifications of the public DNS could be live on the beta version of DDG.

Sorry, they're deploying now...

>Also on mobile there is a display issue (no scrollbar and truncated). Will it be fixed when switching to the new template ?

It should, but there's a chance we'll need to write some mobile-specific CSS to handle narrow screens

**Comment by moollaza** [comment]
@Snapy apologies for the delay, this is now live on Beta: https://beta.duckduckgo.com/?q=public+dns&ia=answer

**Comment by moollaza** [comment]
@Snapy I can merge this one in if you'd like to tackle the re-design in a separate PR?

**Comment by Snapy** [comment]
Thanks ! Just need to check if I add some I have found since then.

**Comment by Snapy** [comment]
Added the readme.md (was in another branch) and added two DNS providers. Also as you said it's better to make the redesign in a new PR. So it should be ready to be merged except if you want a last minute change.

**Comment by Snapy** [comment]
@moollaza Can you merge ?

**Comment by moollaza** [comment]
@Snapy Thanks! This LGTM :+1:

**Pull request merged**
