### PR TITLE
Correct naming of commonescapesequences

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
That name!

-----
IA Page: https://duck.co/ia/view/common_escape_sequences_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
## [Common Escape Sequences](https://duck.co/ia/view/common_escape_sequences)

**Description**: Common Escape Sequences lists the common escape sequences in the most programming languages (i.e Python, C, C++, C#, JavaScript, Java, etc ...)

**Example Query**: [Common Escape Sequences guide](https://beta.duckduckgo.com/?q=Common Escape Sequences guide), [common escape sequences cheat sheet, common escape sequences cheatsheet, ](https://beta.duckduckgo.com/?q=common escape sequences cheat sheet, common escape sequences cheatsheet, )

**Tab Name**: Answer

**Source**: https://en.wikipedia.org/wiki/Escape_sequences_in_C

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/common_escape_sequences)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/common_escape_sequences)*

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=common escape sequences cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/common_escape_sequences_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=common escape sequences cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/common_escape_sequences_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@GuiltyDolphin Thanks! This LGTM :+1:

**Pull request merged**
