### PR TITLE
SHA3: Adding break-all

### PR DESCRIPTION
**Pull request by mintsoft**
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3147 - 

###### People to notify (@mention interested parties)

@moollaza @MariagraziaAlastra 

---

Instant Answer Page: https://duck.co/ia/view/sha3

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rafacas

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MariagraziaAlastra** [comment]
Thanks @mintsoft, this LGTM! @moollaza what do you think?

**Comment by mintsoft** [comment]
ping! @moollaza

**Comment by moollaza** [comment]
@mintsoft whooops! This LGTM :+1:

**Pull request merged**
