### PR TITLE
New Cheatsheet: Photoshop

### PR DESCRIPTION
**Pull request by kbhat95**
**What does your Instant Answer do?**
Provides a cheatsheet for Adobe Photoshop.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
It serves as a quick reference for Photoshop shortcuts. Zero-clicks!

**What is the data source for your Instant Answer? (Provide a link if possible)**
I've primarily used [this](https://helpx.adobe.com/content/dam/help/attachments/PhotoshopCC-KBSC.pdf), the official documentation. [This](http://morris-photographics.com/photoshop/shortcuts/downloads/PSCC%20Keyboard%20Shortcuts%20Win.pdf) provided a few more shortcuts.

**Why did you choose this data source?**
It's the official reference; seemed alright to me.

**Are there any other alternative (better) data sources?**
The two I've listed seem pretty comprehensive, so I'm going to venture a 'no'.

**What are some example queries that trigger this Instant Answer?**
* 'photoshop cheatsheet'
* 'photoshop cheat sheet'

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Graphic designers in a hurry, I suppose. It's always convenient to not have to click more than necessary.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes; you can find it [here](duck.co/ideas/idea/5973/cheatsheet-for-photoshop).

**Which existing Instant Answers will this one supersede/overlap with?**
None.

**Are you having any problems? Do you need our help with anything?**
I've finished off the Windows shortcuts, barring custom combinations (which probably don't belong here anyway). I'd like to know if I need to add the Mac versions, or if this is fine.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

I've tested on the following platforms:
    - Ubuntu 14.04
        [X] Google Chrome

------

https://duck.co/ia/view/photoshop_cheat_sheet

### CODE REVIEW

**Comment by moollaza** [comment]
@kbhat95 thanks a lot for contributing, we really appreciate it! We'll be sure to review this shortly and give you some feedback!

**Comment by moollaza** [comment]
@kbhat95 I'll get back to you on this soon. We're reviewing the design and contemplating some other things that this PR has brought to light!

**Comment by kbhat95** [comment]
@moollaza sure. Is one of those things the fact that a very long section (```Tools``` here) isn't being dealt with properly?

**Comment by moollaza** [comment]
@kbhat95 we're deciding if we really want all the `+` between keys or not, and how to handle bigger cheat sheets.

Separately, if you could break up the Tools section into small ones, that would help.

**Comment by kbhat95** [comment]
@moollaza my concern is that the tools (their shortcuts, anyway) don't lend themselves to grouping very well. Putting the brush-related shortcuts in another group helps to a certain extent, but what would I call the remaining tools?

**Comment by moollaza** [comment]
>Putting the brush-related shortcuts in another group helps to a certain extent, but what would I call the remaining tools?

Misc? Other?

Or make Brushes one section and Tools another? I don’t care too much as long as we can break it up and users are able to understand what they're seeing :)

**Comment by kbhat95** [comment]
@moollaza I think this looks a lot better now. :)

screenshot from 2015-06-30 10 21 55
screenshot from 2015-06-30 10 22 13
screenshot from 2015-06-30 10 22 28

**Comment by abeyang** [comment]
Hey, looking good @kbhat95 ! Can we get rid of all the `+`? So this is BAD:

`[Ctrl] + [Alt] + [Delete]`

And this is GOOD:

`[Ctrl][Alt][Delete]`

**Comment by kbhat95** [comment]
@abeyang @moollaza does this look good?

screenshot from 2015-07-03 09 20 38
screenshot from 2015-07-03 09 20 52
screenshot from 2015-07-03 09 21 09

**Comment by abeyang** [comment]
Looks good! One thing I'd change is zoom in -- just make it: `[Ctrl] [+]` (it's understandable without the `[=]` key)

Finally -- and this is just a personal request, because it's something I have to keep looking up -- is it possible to include blend mode shortcuts? :smile:

image

**Comment by kbhat95** [comment]
@abeyang blend mode? Say no more! :)
@moollaza check this out!

I've merged ```Brushes``` back into ```Tools``` so that it looks balanced.

screenshot from 2015-07-07 22 16 51
screenshot from 2015-07-07 22 17 07
screenshot from 2015-07-07 22 17 22

**Comment by abeyang** [comment]
:boom: Looks good! :+1:

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
@kbhat95 congrats! It's live: https://duckduckgo.com/?q=photoshop+cheat+sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
