### PR TITLE
CPP Maps IA Added

### PR DESCRIPTION
**Pull request by ManrajGrover**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New {CPP Maps} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

This pull request adds new cheat sheet CPP Maps.

###### Which issues (if any) does this fix?
None

###### People to notify (@mention interested parties)

@zekiel @moollaza 

---

Instant Answer Page: https://duck.co/ia/view/cpp_maps_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention
None

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gaulrobe** [comment]
@ManrajGrover this is very handy! 

Might you be interested in making it a Fathead though? Some perks of it being a Fathead is better querying and we could provide code snippets for people!

For example, a query for `c++ map count` could immediately have an IA result with `Searches the container for elements with a key equivalent to k and returns the number of matches.` and the code snippet that is on http://www.cplusplus.com/reference/map/map/count/.

Just a thought! See http://docs.duckduckhack.com/resources/fathead-overview.html if you are interested, otherwise having a cheatsheet is good too!

**Comment by ManrajGrover** [comment]
@gaulrobe That sure will be more helpful. But for now this looks good. I'm currently learning Perl and will sure work on Fathead and Spice in couple of days. Then, we can convert full documentation into Fathead. :smile:

**Comment by gaulrobe** [comment]
@ManrajGrover that sounds like a good plan to me! Don't hesitate to let any of us know if you need any assistance as you go! :)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=cpp map cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/cpp_maps_cheat_sheet_mobile.png?HrerBwrhxc)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=cpp map cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/cpp_maps_cheat_sheet_mobile.png?zZz1uTw7F9)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=cpp map cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/cpp_maps_cheat_sheet_mobile.png?5E7ZEd0VJj)

**Comment by daxtheduck** [comment]
@ManrajGrover this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
