### PR TITLE
Fusion360 Cheat Sheet

### PR DESCRIPTION
**Pull request by salmanfarisvp**
Description: Fusion360 Keyboard shortcuts

Example Query: Fusion360 cheat sheet

Tab Name: Cheat Sheet

Source: https://www.cadlinecommunity.co.uk/hc/en-us/articles/210361725-Fusion-360-Keyboard-Shortcuts

IA: https://duck.co/ia/view/fusion360_keyboard_shortcuts

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by salmanfarisvp** [comment]
IA: https://duck.co/ia/view/fusion360_keyboard_shortcuts

**Comment by kirkins** [comment]
@salmanfarisvp you're using your master branch for this PR, which seems to have code relating to other IAs.

I recommend syncing your master branch with that of the official DuckDuckGo Goodies repo. Then make a branch for fusion360, add only the changes relating to the fusion360 PR. Then close this PR and open a new one.

**Comment by salmanfarisvp** [comment]
Ok, thanks

**Pull request closed without merging**
