### PR TITLE
Libre office cheatsheet: Fixed wrong information

### PR DESCRIPTION
**Pull request by gautamkrishnar**
Fixes: #3727 

---

IA Page: http://duck.co/ia/view/libre_office_writer_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
@sahildua2305  please review this

**Comment by sahildua2305** [comment]
@gautamkrishnar can you please update the commit message?
```
git commit --amend
```
and then push with `-f` flag.

**Comment by gautamkrishnar** [comment]
Yes @sahildua2305 thanks.. I was busy with my exam... Sorry for being late 😄

**Comment by gautamkrishnar** [comment]
@sahildua2305 you must review this one to get it merged...

**Comment by gautamkrishnar** [comment]
Since @sahildua2305 is unreachable. @moollaza  or @tagawa Can you please approve these changes...

**Comment by gautamkrishnar** [comment]
Thanks @sahildua2305

**Pull request merged**
