### PR TITLE
GitCheatSheet: Added new git commands

### PR DESCRIPTION
**Pull request by GPhantom**
## Description of new Instant Answer, or changes

Adding git remotes commands

## People to notify

@adityatandon007 @gautamkrishnar 

---

Instant Answer Page: https://duck.co/ia/view/git_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GPhantom** [comment]
What is the problem? The test is failing with: "The command "dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm --quiet --notest --mirror http://www.cpan.org/ --mirror http://duckpan.org" failed and exited with 123 during ."

**Comment by adityatandon007** [comment]
@GPhantom regarding that problem just try rebuilding the test again.

**Comment by gautamkrishnar** [comment]
👍 Merged... Thanks for your contribution...

**Comment by GPhantom** [comment]
My pleasure :) Thanks for merging :+1:

**Pull request merged**
