### PR TITLE
AltCalendars converted to a structured answer (#402)

### PR DESCRIPTION
**Pull request by rafacas**
Converted the AltCalendars Goodie and its tests to structured answer.

### CODE REVIEW

**Comment by moollaza** [comment]
@rafacas thanks a lot for this!

If you're really interested in making this one awesome, you could take a stab at converting it to use the new Goodie templates? We don't have any docs yet (still in the works but you will want to mimic the [Minecraft Goodie](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Minecraft.pm#L54)

The difference is that you can now pass data along to one of our built-in templates (the ones we currently use for Spice IAs). In this case, I'd suggest the `text` template. And you can automatically generate the More at Wikipedia link now by setting the `sourceUrl` and `sourceName` in the `Meta` section of the `structured_answer` object.

**Comment by moollaza** [comment]
@rafacas haha I just remembered why this one wasn't a structured answer -- it returns HTML which right now get's escaped. Even though you've encoded it, we don't treat the text as raw HTML so if you run it in DuckPAN you'll see the result is broken:

2015-03-25_18h34_06

Looks like this one *needs* to be moved to a new Goodie template as I've described above!

**Comment by moollaza** [comment]
I suppose the alternative is to simply get rid of the wiki URL -- I'm fine with that as well.

**Comment by rafacas** [comment]
@moollaza haha, I usually test it with ```duckpan query``` and ```prove```. I'll start using ```duckpan server``` too.
I think I'm going to try the new ```Text``` template :)

**Comment by moollaza** [comment]
@rafacas awesome! Thanks a lot :)

**Comment by rafacas** [comment]
Hi @moollaza I just updated the branch with the ```Text``` template.

Here is a screenshot:

screen shot 2015-03-26 at 16 50 03

BTW, the templates are pretty cool ;)

**Comment by moollaza** [comment]
@rafacas this is great -- let's switch our title and subtitle around though. The actual answer should be the most prominently displayed item as it's the answer. The context (Meiji Calendar Conversion) is less important so it should be the subtitle.

**Comment by rafacas** [comment]
Sorry @moollaza, I've just seen your comment. I'll change it and wait for @abeyang to comment on it.

**Comment by rafacas** [comment]
I've just changed the name from ```Calendar``` to ```Calendar Conversion```.

screen shot 2015-03-27 at 12 19 18

**Comment by abeyang** [comment]
Hi @rafacas , it's almost there. Usually, for the subtitle, it would be ideal to see what the converted date is (in this case, "Meiji 42"). Thus, can we do something like this (notice I removed "calendar"):

> **1909**
> Meiji 42 - Equivalent Gregorian Year

What do you think?

**Comment by rafacas** [comment]
@abeyang That makes perfect sense :)

I've just updated it. Here is a screenshot:
screen shot 2015-03-27 at 16 46 34

**Comment by abeyang** [comment]
Looks good! :+1:

**Pull request merged**
