### PR TITLE
Template: Use of single quotes

### PR DESCRIPTION
**Pull request by sahildua2305**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [x] Non–Instant Answer
    - [x] Other (Role, Template, Test, Documentation, etc.): **`Templates: Use of single quotes everywhere`**

###### Description of changes
Made changes to use single quotes everywhere in the template

Fixes: #3347 

###### People to notify (@mention interested parties)
@moollaza @GuiltyDolphin

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@sahildua2305 Thanks!

Same comment as your Spice PR if you're up for it :)

**Comment by sahildua2305** [comment]
Here it is! @GuiltyDolphin ;)

**Comment by GuiltyDolphin** [comment]
@sahildua2305 Thanks! :dolphin:

**Pull request merged**
