### PR TITLE
Roman numerals (improvements)

### PR DESCRIPTION
**Pull request by gargaml**
Some new features added to the roman numerals IA,

## Description of new Instant Answer, or changes

A new converter has been added to the client side.  When the IA is triggered by the query, a converter appears with the possibility to change values dynamically.
For instance, if the query is roman XV, the server side pre-computes the arabic number and send the answer to the client.  But then, the user can actually modify the value to do more.  If the query requests a conversion from arabic to roman, the interface swaps input fields automatically. 

## Related Issues and Discussions
https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4344

The interface can be meliorated but it is already functional. Maybe we could add a button in the middle to replace the '=' sign and allows the user to swap fields dynamically.

## People to notify
@pjhampton 

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/roman)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test roman`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/roman

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by hchienjo** [comment]
@gargaml seems like the original query like 
screenshot from 2017-08-05 11-58-58
 `X to arabic numerals` are broken in this PR 
screenshot from 2017-08-05 12-00-18. Shouldn't we still support the original queries as well as add the interactive UI?

**Comment by gargaml** [comment]
I did not include queries with the keyword 'numeral'. I was trying to minimize the number of regular expressions involved in the worst case. But I can add the regular expressions to match against this keyword and be compatible with the previous version.

**Comment by gargaml** [comment]
I modified some regular expressions to consider original queries and added some tests to check them.

**Comment by hchienjo** [comment]
Thank you very much @gargaml! I will leave this unmerged for a while in case @pjhampton has anything more to add.

**Comment by moollaza** [comment]
@gargaml @hchienjo this should not have been merged. It needs to be verified by @pjhampton .

At first glance the code needs improvements.

I am going to revert the merge.

**Comment by hchienjo** [comment]
Oh, alright. Sorry about that.

**Comment by moollaza** [comment]
>Oh, alright. Sorry about that.

It's okay 👍

**Comment by moollaza** [comment]
@gargaml can you please open another PR?

**Pull request merged**
