### PR TITLE
Other: Optimize Images

### PR DESCRIPTION
**Pull request by holtjohnson**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [x] Non–Instant Answer
    - [x] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Felt like optimizing your images for you because I felt like it.

I used a bunch of different [lossless](https://en.wikipedia.org/wiki/Lossless_compression) compress algorithms to find the smallest file size without touching the quality at all (that would be [Lossy](https://en.wikipedia.org/wiki/Lossy_compression) compression algos).

### CODE REVIEW

**Comment by daxtheduck** [comment]
@holtjohnson Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
hi @holtjohnson!  thanks for your contribution - I'm going to hand it off to the right people to review this.  

We're currently focused on our [mission to improve programming-related Instant Answers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), so that's where the majority of our attention is going to be, so it may take some time to get this reviewed, but we do appreciate your contribution!

**Comment by bsstoner** [comment]
👍

**Pull request merged**
