### PR TITLE
Added English Braille Cheat Sheet

### PR DESCRIPTION
**Pull request by chappers**
**What does your Instant Answer do?**

Add content to the cheatsheet instant answers.

**What is the data source for your Instant Answer? (Provide a link if possible)**

The cheat sheet for english braille is based on the article on wikipedia. <https://en.wikipedia.org/wiki/English_braille>

**Why did you choose this data source?**

It is easily accessible compared with digging through the standards which is in a pdf.

**Are there any other alternative (better) data sources?**

Alternative data sources could be from the International Council on English Braille (ICEB) <http://www.iceb.org/ueb> which has the same alphabet encoding on the "Rules of Unified English Braille 2013.pdf" on the same webpage. The encoding is on pg 41

**What are some example queries that trigger this Instant Answer?**

English Braille Cheat Sheet

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

Reference, Special Interest

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

No

**Are you having any problems? Do you need our help with anything?**

Not right now

**Where did you hear about DuckDuckHack? (For first time contributors)**

From the stopwatch/timer portion of duck duck go

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

image

-----
IA Page: https://duck.co/ia/view/english_braille_cheat_sheet

### CODE REVIEW

**Comment by moollaza** [comment]
@chappers thanks a lot for contributing, we really appreciate it! We'll be sure to review this shortly and give you some feedback!

**Comment by mintsoft** [comment]
@chappers this looks pretty good to me, the only thing is there doesn't appear to be a difference between the numbers and the first letters of the alphabet. Is it context sensitive or are there markers to indicate when it's digits etc?

**Comment by chappers** [comment]
@mintsoft There are formatting marks for letter, capitalization, and numbers, but they don't really have an English equivalent, so I'm not sure whats the best way to place it on the cheat sheet.

**Comment by moollaza** [comment]
>There are formatting marks for letter, capitalization, and numbers, but they don't really have an English equivalent, so I'm not sure whats the best way to place it on the cheat sheet.

@chappers can you give an example? Maybe we should have examples as another section?

**Comment by chappers** [comment]
I probably should have checked with you before actually changing it. I have some examples as shown here:

image


I switched `key` and `val`, which is similar to what [nato alphabet cheat sheet](https://duckduckgo.com/?q=nato+alphabet+cheatsheet&ia=cheatsheet) did, and added some examples on how it would work.

**Comment by moollaza** [comment]
>I switched key and val, which is similar to what nato alphabet cheat sheet did, and added some examples on how it would work.

:+1: That seems fine

@chappers let's put these examples into a new section though so it's separated from the other two parts

**Comment by moollaza** [comment]
@abeyang any thoughts on design?

**Comment by abeyang** [comment]
@chappers If that screenshot that you've provided is the latest (with the formatting marks section), then it looks good! :+1:

**Comment by chappers** [comment]
@abeyang Yes, that screenshot is the latest.

**Comment by abeyang** [comment]
Then it's :+1: from me. Unless we're ready to try out the reference sheet -- @moollaza ?

**Comment by moollaza** [comment]
LGTM :+1: Will add the reference template myself..

**Comment by moollaza** [comment]
@chappers congrats! It's live: https://duckduckgo.com/?q=english+braille+cheat+sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
