### PR TITLE
CrontabCheatSheet: Remove Goodie

### PR DESCRIPTION
**Pull request by rasikapohankar**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] Improvement
    - [x] Enhancement: **`{CrontabCheatSheet}: {Update to template}`**

###### Description of changes

Updated the Goodie to use structured_answer, moved the custom table to handlebars template and updated the css to use .zci--<id>. For #1163. Not sure if this is entirely right since it does not get rid of the HTML completely. 
Also, instead this could be made a cheat sheet with the contents in a JSON file directly with the type `terminal`?

###### People to notify (@mention interested parties)
@tagawa @moollaza @GuiltyDolphin 

---

Instant Answer Page: https://duck.co/ia/view/crontab_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nkorth

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@rasikapohankar As you mentioned - we've been wanting to get this Goodie ported to a cheat sheet for a while, would you like to do so? It should be fairly straight-forward.

**Comment by rasikapohankar** [comment]
@GuiltyDolphin Sure, yes I'd like to do it. Should I change it in this pull request?

**Comment by GuiltyDolphin** [comment]
@rasikapohankar I think the best method of going about this would be to have 1 PR removing the old Goodie, and 1 PR adding the cheat sheet (so it can be deployed to Beta).

Sound about right @moollaza ?

**Comment by rasikapohankar** [comment]
@GuiltyDolphin Oh yes, I forgot about that part :+1: I'll delete the files of the Goodie in this PR and make another to add the JSON file then. I guess the pull request with the deletion of files will get merged first and the IA will be made offline? and then online again after the PR with the cheat sheet is merged?

**Comment by GuiltyDolphin** [comment]
@rasikapohankar I'm not entirely sure - but we'll have to take the old Goodie off Beta before we can deploy the cheat sheet, it shouldn't *really* matter in what order we merge them as long as they are done at roughly the same time.

**Comment by tagawa** [comment]
Just managed to remove this from the beta server. It's still on the production server but that should be resolved when #3376 goes live, so closing this.

**Comment by rasikapohankar** [comment]
Thanks @tagawa! :) When #3376 is merged and goes live, won't we be removing the current code for the Goodie from the repository? I had updated this PR to remove those files. I think I updated this pull request a little too early :smile: But I guess we can keep this open as it will be needed later?

**Comment by GuiltyDolphin** [comment]
@tagawa Yeah, this is needed to *remove* the code for the old Goodie; the Beta issue was separate.

**Comment by tagawa** [comment]
Aha, I see now. I was being too enthusiastic :-)
Thanks @rasikapohankar @GuiltyDolphin

**Comment by tagawa** [comment]
New cheat sheet is live: https://duckduckgo.com/?q=crontab%20cheat%20sheet&ia=cheatsheet
so merging this PR to remove the old files. Thank you @rasikapohankar!

**Pull request merged**
