### PR TITLE
Improvements from #2620 + fixes from the comments

### PR DESCRIPTION
**Pull request by aleksandar-todorovic**
Implements the improvements from now inactive #2620 and fixes the things stated in the comments of that PR.

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@aleksandar-todorovic Would you mind finding out the names of the maintainers and ccing them in?

**Comment by aleksandar-todorovic** [comment]
cc @zachthompson @codenirvana @vishwakulkarni @zekiel @mbionchi @elebow @gautamkrishnar @dnmfarrell @sagarhani @jclement @pratts @stanly-johnson @gokul1794 @goromlagche @zpalffy @AshishAAB 

I hope I didn't miss someone.

**Comment by GuiltyDolphin** [comment]
@aleksandar-todorovic Thanks! If you fix any merge conflicts then we can finish this up as soon as we've had responses (or 7 days).

**Comment by GuiltyDolphin** [comment]
@aleksandar-todorovic Oh boy, merge conflicts.

**Comment by gautamkrishnar** [comment]
Is this abandoned @aleksandar-todorovic

**Comment by gautamkrishnar** [comment]
I think thus PR is abandoned....

**Comment by gautamkrishnar** [comment]
@duckduckgo/duckduckhack-contributors anyone like to do take this up again?

**Comment by adityatandon007** [comment]
@gautamkrishnar Is it okay to make separate PR for each of the changes or should I make a single PR with all the changes in it.

**Comment by gautamkrishnar** [comment]
@adityatandon007 
You could use a tool like git-pr to checkout the pull so that it will maintain the correct attribution. Also you can do it manually. Yes, It is okay to make a single pr for all the changes.

**Comment by adityatandon007** [comment]
@gautamkrishnar thanks for precious advice. Though I haven't used any tool like git-pr but I know how to do manually. I would make the change and the inform you :+1:

**Comment by adityatandon007** [comment]
@gautamkrishnar I wanted ask something. It is not related to this issues. Are you on slack :grey_question:

**Comment by gautamkrishnar** [comment]
@adityatandon007 sure... I will come online soon. I am on my phone..  Please Wait ..

**Pull request closed without merging**
