### PR TITLE
Fixes #1457 - updated code styles for terminal cheat sheet templates

### LINKED ISSUE #1457: Cheat Sheets Terminal Template: Long text causes columns to overlap
Looks like we'll need to adjust our CSS a bit to prevent this.

/cc @alohaas 

duckduckhack

### PR DESCRIPTION
**Pull request by alohaas**
Displaying the `<code>` elements as `inline-block` seemed to create a bubble of excess space in the right side of the column. Couldn't find a definitive answer as to why that was happening, but by moving a class assignment around in the `terminal.handlebars`, we can display `<code>` elements as `inline`, which solved the problem. CSS is weird :)

### CODE REVIEW

**Comment by mintsoft** [comment]
@alohaas I'm not sure this is fixed in FF. I just hacked the perldoc cheatsheet to have content similiar to the mysql one in the screenie and it still appears to be problematic:

image

**Comment by alohaas** [comment]
hm, let me see if I can replicate your content in the perldoc cheat sheet. I am working in FF, so I probably overlooked something.

**Comment by mintsoft** [comment]
Looking at it, I think it might be a linewrap issue. I think the large `column1=value1` is forcing the box to overflow

**Comment by alohaas** [comment]
Yeah I am seeing that too.

**Comment by alohaas** [comment]
got it. `word-break` and `word-wrap`assignments need to happen to the parent `td.cheatsheet__key` not on the `code` element. Making this change.

**Comment by alohaas** [comment]
@mintsoft seems to be better...will be submitting a new PR
screen shot 2015-08-29 at 11 30 33 am

**Comment by mintsoft** [comment]
Cool, does that mean the original changes to the handlebars template were unnecessary or were they tweaking something that I've not noticed?

**Comment by alohaas** [comment]
@mintsoft possibly! Let me take a look.

**Comment by alohaas** [comment]
@mintsoft seemed to work without the template change :+1:

**Comment by mintsoft** [comment]
Cool @moollaza I'll turn this over to you :)

**Comment by moollaza** [comment]
@alohaas this LGTM :+1:

Thanks a lot for the awesome and quick fix!

**Comment by alohaas** [comment]
You're welcome :grin:

**Comment by moollaza** [comment]
@alohaas in working with more PR's I think I've discovered some visual regression from these changes. It looks like we're breaking words in the keyboard template and code template which causes some keys to look broken:

eclipse_cheat_sheet_at_duckduckgo
regex_cheat_sheet_at_duckduckgo

Looks like we should update the `word-break` CSS so that it only applies to the reference template.

Potentially we may need to get creative and only apply it to keys that have particularly long "words", but I think that should be a last resort.

**Comment by alohaas** [comment]
Hi @moollaza, apologies for the slow response. I have just returned from a week-long trip with no access to my developer tools :sob: 

I will be looking into this issue tomorrow and will have a more thorough fix!

**Pull request merged**
