### PR TITLE
t/LeapYear.t: Test was failing on Perl 5.16

### PR DESCRIPTION
**Pull request by jagtalon**
@mintsoft I tested it internally, and I'm not sure why it's failing but this fixes it.

### CODE REVIEW

**Comment by mintsoft** [comment]
@jagtalon that's odd; it's not failing in Travis or on my 5.16 installs. I wonder if there's a timezone thing going on or something

**Comment by jagtalon** [comment]
@mintsoft yeah that's probably true. Maybe anything other than Jan 1 would work?

**Comment by mintsoft** [comment]
@jagtalon Can you try changing it to : 
```perl
set_fixed_time("2015-01-01T00:00:00Z");
```
and see if it still fails for you?

**Comment by jagtalon** [comment]
@mintsoft Still doesn't work, unfortunately 

```
t/LeapYear.t .. 1/?
    #   Failed test 'Deep: full ZCI object'
    #   at /usr/local/ddg.cpan/perl5/lib/perl5/DDG/Test/Goodie.pm line 76.
    #     Structures begin differing at:
    #          $got->{answer} = '2014 CE is not a leap year'
    #     $expected->{answer} = '2015 CE is not a leap year'
    # Looks like you failed 1 test of 1.

#   Failed test 'Query: is it a leap year?'
#   at /usr/local/ddg.cpan/perl5/lib/perl5/DDG/Test/Goodie.pm line 80.
# Looks like you failed 1 test of 10.
```

**Comment by jagtalon** [comment]
Merging because we need to release it! :)

**Comment by mintsoft** [comment]
awesome @jagtalon !

**Comment by jagtalon** [comment]
@mintsoft so sorry, didn't mean to cut you off and just do my own thing. Will try to prevent this in the future.

**Comment by mintsoft** [comment]
@jagtalon No worries, needs must! It's also a pretty academic issue

**Pull request merged**
