### PR TITLE
Conversions: Fixes #2125

### LINKED ISSUE #2125: Conversions: Add support for ping, Taiwanese unit of area commonly used in real estate listings.
@mintsoft 

See https://en.wikipedia.org/wiki/Taiwanese_units_of_measurement

------
IA Page:  http://duck.co/ia/view/conversions

### PR DESCRIPTION
**Pull request by mintsoft**
Includes the entire of: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2126 plus the fix for the pluralisation (and tests of course)

---------
IA Page: http://duck.co/ia/view/conversions

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@mintsoft This is now on Beta!

**Comment by heycam** [comment]
Thanks for finishing that off, @mintsoft!

**Comment by mintsoft** [comment]
No problem @heycam  :+1:

**Comment by GuiltyDolphin** [comment]
@mintsoft @heycam Thanks, checked it out on Beta and it is looking good! :dolphin:

**Comment by mintsoft** [comment]
Thanks for the merge @GuiltyDolphin

**Pull request merged**
