### PR TITLE
Braille Cheat Sheet: Add braille code for 'Hi' and 'Hello'

### PR DESCRIPTION
**Pull request by vikashvverma**
IA Page: https://duck.co/ia/view/english_braille_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@vikashvverma @mayank7 thanks a lot for all the updates guys -- I would love to chat with you two about how making more meaningful contributions though have you considered joining our Slack community?

Adding to all of our cheat sheets does help, but there are real problems that need fixing, and more meaningful ways of contributing. I'd like to clarify if you are submitting all these pull requests because of HackerEarth, or because you're truly interested in making these Cheat Sheets more useful for yourself and DuckDuckGo users?

Also, seeing as you're just updating multiple cheat sheets, the number of PR's is getting a little out of hand so I'm going to ask that you **submit any future updates in a single PR**. We're behind on merging your PR's and it's making the repo artificially noisey. It's perfectly fine for a single PR to update multiple cheat sheets. Just be sure to add links to each IA Page that has been updated in the PR description.

Thanks again for the contributions, we appreciate you taking the time to contribute.

/cc @duckduckgo/community-leaders

**Comment by moollaza** [comment]
@vikashvverma @mayank7 could you go through your currently open PR's that update existing cheat sheets and **group them all into a single new PR** as well? That will make things much easier for us to review. 

You should be able to cherry-pick your commits into a new branch and submit a new PR, then close your existing PRs.

Thanks again, we appreciate your help.

**Comment by moollaza** [comment]
@vikashvverma with regards to this specific PR, I'm not sure it adds any value to this Cheat Sheet. The additions seem out of place.

@chappers you're the creator of this cheat sheet -- any thoughts?

**Comment by mayank7** [comment]
@moollaza Okay, I will merge all my Open PR's into one PR, just give me some time.

**Comment by moollaza** [comment]
> Okay, I will merge all my Open PR's into one PR, just give me some time.

@mayank7 thank you very much!

**Comment by chappers** [comment]
@moollaza I agree, I do not think the additions provide any additional value.

**Comment by vikashvverma** [comment]
@moollaza There are many new cheat sheets that I have opened. I think that can remain in a separate PR.

**Comment by GuiltyDolphin** [comment]
@vikashvverma Move into #2746 if still applicable.

**Pull request closed without merging**
