### PR TITLE
preemeijer scratch cheatsheet

### PR DESCRIPTION
**Pull request by preemeijer**
**What does your Instant Answer do?**
Scratch cheatsheet for the buildingblocks

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Don't know the answer to this

**What is the data source for your Instant Answer? (Provide a link if possible)**
http://www.dummies.com/how-to/content/scratch-for-kids-for-dummies-cheat-sheet.html

**Why did you choose this data source?**
It was the best that I could find for this purpose

**Are there any other alternative (better) data sources?**
Yes for example http://wiki.scratch.mit.edu/wiki/Scratch_Wiki:Table_of_Contents/Program

**What are some example queries that trigger this Instant Answer?**
scratch cheatsheet

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
For students who get some lessons with this program; starting programmers.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
https://duck.co/ideas/idea/6332/scratch-cheatsheet

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
scratch-cheatsheet

-----
IA Page: https://duck.co/ia/view/scratch_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@preemeijer Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by moollaza** [comment]
@preemeijer thanks for contributing! I see that you don't have any text descriptions for these. Each of these should have some text explaining what the command is for.

This Cheat Sheet may benefit from copying the "Example" style approach that some of the other programming language Cheat Sheets (like Lua) have used. Where the `val` would be "Loop until X" and the `key` would be the code snippet.

**Comment by preemeijer** [comment]
@moollaza Okay will get that on then. I had started that but I just thought that it would be to much info for a cheatsheet but I will go and change this cheatsheet with the help of the wikipage that I addressed as an alternative page. Thanks for the feedback.

**Comment by moollaza** [comment]
@preemeijer whoops, it looks like somehow your commits overlapped and so this PR was technically "merged" because the SVN changes here also existed in the other PR that I merged last week. Can you submit a new PR for your Scratch Cheat Sheet please?

**Comment by moollaza** [comment]
Sorry about the mess@

**Comment by preemeijer** [comment]
@moollaza no problem at all. It's not ready yet for production and I will make a new PR.
I'm working with branches so that the mess will also be less on my side.

**Comment by moollaza** [comment]
:+1: Thanks!

**Pull request merged**
