### PR TITLE
Add alias meta-data to nodejs cheatsheet

### PR DESCRIPTION
**Pull request by NaveenKarippai**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [x] Bug fix: **`nodejs_cheat_sheet: Fix {3116} add alias meta-data`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

The nodejs cheatsheet does not trigger for query
`node.js`. This could be fixed by adding alias
meta-data on json file.

Provide an overview of the changes this pull request introduces.

* added alias meta-data for cheatsheet

* triggers for `node.js` query

###### Which issues (if any) does this fix?

See also: #3116

Fixes #NNNN - how specifically does it fix the issue?

###### People to notify (@edgesince84)

---

Instant Answer Page: https://duck.co/ia/view/nodejs_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @stanly-johnson

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by zekiel** [comment]
Generally seems ok to me, tho, we'd still want to wait the normal [time](http://docs.duckduckhack.com/maintaining/guidelines.html) for the maintainer to acknowledge the change.  (stanly-johnson)

**Comment by zekiel** [comment]
@stanly-johnson are you ok w/ this change? We'll hit the [merge button in ~1 week](http://docs.duckduckhack.com/maintaining/guidelines.html#for-maintainers) (or sooner w/ your OK)

**Comment by zekiel** [comment]
no response from the maintainer per the [cutoff period](http://docs.duckduckhack.com/maintaining/guidelines.html#for-maintainers) -- merging!

**Pull request merged**
