### PR TITLE
factorial_calculator: Add new goodie

### PR DESCRIPTION
**Pull request by NaveenKarippai**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [x] Other: **`New {factorial_calculator} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

The factorial_calculator returns the factorial of a given
number input. It makes it easier for the user to find factorial
of a number.

Provide an overview of the changes this pull request introduces.

* added new goodie

###### People to notify (@GuiltyDolphin , @moollaza )

---

Instant Answer Page: https://duck.co/ia/view/factorial_calculator

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by NaveenKarippai** [comment]
**ToDo:**

* [ ] Write test suite
* [ ] Refactor code

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin @moollaza The Goodie gets triggered (successfully) when we run `duckpan query` but **does NOT get triggered** on running `duckpan server`. Could you please have a quick look on this issue. Thanks!

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai Thanks for this - unfortunately this is already handled by the Calculator (we used to have a Goodie like this but it was made redundant by the addition of the functionality to the Calculator - https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1802).

If you want additional triggers or whatnot please suggest them in an issue for the Calculator :)

**Pull request closed without merging**
