### PR TITLE
new added top footballer.json

### PR DESCRIPTION
**Pull request by vishwakulkarni**
created a cheat sheet for top footballer.

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Hi @vishwakulkarni, thanks for the contribution! Do you mind adding the [the Goodies PR template](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/pull_request_template_goodie.md) filled in, in your first comment?

**Comment by zachthompson** [comment]
@vishwakulkarni Don't these rankings vary over time?  I believe this would become outdated pretty quickly if I understand the source correctly.

**Comment by altern8tif** [comment]
I think this may be more useful as a Spice – using footballer's names as queries to show their rankings.

Cheatsheets should be more for information that rarely changes, exhaustive, more of a source for reference etc.  May be worthwhile to consider certain guidelines for what are good candidates for cheat sheets.

**Comment by zachthompson** [comment]
Thanks, but needs to update dynamically to reflect changes.

**Comment by moollaza** [comment]
@vishwakulkarni thanks a lot for contributing, sorry we can't use this PR though. We'd love for you to stick around though and continue to contribute. There's many issues in the repo's that need to be addressed and there are also many Ideas on or Forum that are awaiting a developer.

If you're going to work on a new Instant Answer please reach out to use first to make sure the idea has been approved so that we won't run into anything like this again.

Thanks again!

**Pull request closed without merging**
