### PR TITLE
Better Contributing MD - slightly redundant to docs on purpose

### PR DESCRIPTION
**Pull request by talsraviv**
Thanks to @gautamkrishnar for the idea!

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
:smile: :+1: Looks cool...

**Comment by moollaza** [comment]
@talsraviv I think for bug fixes, they should describe the fix high-level in the name, link the actually addressed issues in the description, and also give some explanation about what they've done and why, when it’s a non-trivial fix.

Good example:

> **PeopleInSpace: Use smaller local image, fallback to API when needed**
> This PR fixes #2090.
> The images used by the API are very large and don't change often. I've but a smaller version of each image (and a 2x version for retina screens) in the share directory. The callback will try and load a local image based on the astronauts name and fallback to using the API's image if one does not exist.

**Comment by talsraviv** [comment]
@moollaza good points. Added.

**Comment by talsraviv** [comment]
@moollaza updated in spice and main docs as well

**Comment by talsraviv** [comment]
@moollaza bump

**Comment by GuiltyDolphin** [comment]
@talsraviv Improved Docs :smile:

Bit O' a delay here.

**Pull request merged**
