### PR TITLE
Play Conway's Game of Life

### PR DESCRIPTION
**Pull request by russellholt**
This IA lets you play conway's game of life in your browser.

Initial PR **WIP**

- Needs UX work
- Needs better animation handling
... but it works.

## What this does

This lets you play [Conway's Game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life) in your browser, as an IA.

It supports controls for stop, start, step, clear, randomize, and has several built-in shapes you can place: a point, a basic glider, a spaceship, and the Gosper Glider Gun. See the wikipedia page above for definitions of these terms.

I made the artistic decision to wrap the field around. Although this isn't the standard game of life, it allows you to watch it forever. Could be toggle-able.

Also, I made a decision to show the previous state as gray, which makes an interesting visual presentation (and educational). This could be toggle-able.

## todo

- fix interactive buttons
- support more shapes
- render in the full IA area
- add an infobox for links to wikipedia and other relevant Game of Life sites
- add a data source for the shapes
- allow shadow state to be toggleable
- allow wrap-around to be toggleable
- decide about animation handling
- tests

screen shot 2016-01-30 at 2 08 50 pm

pictured above: gosper glider gun in action (gray is previous state, below)

---
https://duck.co/ia/view/life

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@russellholt  I'm going to close this PR for now; feel free to reopen it whenever you like :+1:

**Comment by russellholt** [comment]
thank you @mintsoft . I may get on it again soon but can't say exactly when :)

**Comment by mintsoft** [comment]
@russellholt I figured!

**Pull request closed without merging**
