### PR TITLE
New  World Population  Cheat Sheet

### PR DESCRIPTION
**Pull request by vikashvverma**
This cheat sheet displays population of continents and top countries.

Screenshot:

screen shot 2016-02-22 at 11 20 00 pm

IA Page: [https://duck.co/ia/view/world_population_cheat_sheet](https://duck.co/ia/view/world_population_cheat_sheet)

### CODE REVIEW

**Comment by daxtheduck** [comment]
## [World Population Cheat Sheet](https://duck.co/ia/view/world_population_cheat_sheet)

**Description**: Displays population of continents and top countries

**Example Query**: [world population cheat sheet](https://beta.duckduckgo.com/?q=world population cheat sheet), [world census cheat sheet](https://beta.duckduckgo.com/?q=world census cheat sheet)

**Tab Name**: Answer

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/world_population_cheat_sheet)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/world_population_cheat_sheet)*

**Comment by moollaza** [comment]
I'm not sure this is an appropriate cheat sheet given that this data will constantly need to be updated. I'd rather we use an API to list the populations of continents and countries.

**Comment by GuiltyDolphin** [comment]
@moollaza We already have one, don't we? The WorldBank Spice, I mean.

**Comment by moollaza** [comment]
>@moollaza We already have one, don't we? The WorldBank Spice, I mean.

Yup that covers individual countries. I was thinking of other possibilities, like tiles representing the population for each continent or maybe even a graph of the world population?

There's probably lots more info we can show :+1:

**Comment by GuiltyDolphin** [comment]
@moollaza I agree - there's a lot we could do with the front-end for this kind of thing!

**Pull request closed without merging**
