### PR TITLE
POTUS: Triggering is way too keen

### PR DESCRIPTION
**Pull request by mintsoft**
## Description of new Instant Answer, or changes
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3760

## Related Issues and Discussions
Unfortunately, the regex isn't actually matching the query, it's replacing bits that we don't need so we can pass the remainder on to `words2nums` to convert. This was defaulting to the current president if it couldn't parse, which basically means it would show the current president for anything that isn't "first" "second" etc i.e. "elect" or "vice".

Whether this is worth fixing or not I'll leave up to the community/staff. If this doesn't work/isn't resliant enough, I'd suggest starting from scratch from a guard regex instead.

## People to notify
@moollaza @bsstoner 

---

Instant Answer Page: https://duck.co/ia/view/potus

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@mintsoft seems like it doesn't trigger on `who is the president of the united states` ?

I think a guard regex is the best plan. Also "Who was" should probably show the previous president?

**Comment by mintsoft** [comment]
@moollaza I've implemented a guard regex here, and I think I've exposed a bug in duckpan/zci . 

I've got a failing test at the moment for `who is the president-elect of the us`, which shouldn't even trigger based on the triggers: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3938/files#diff-66449435cf1d3b4e87ded23d450483eaR12  

https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/builds/205568133#L1010

I'm guessing that it's not matching that as an array of strings verbatim, but an array of words or something. I've not had a chance to dig into duckpan yet.

**Comment by mintsoft** [comment]
Also just confirmed it's just tests, it happens in `duckpan server` and `duckpan query`

**Comment by moollaza** [comment]
@mintsoft thanks for confirming, I'm investigating. I think you're correct that it's a bug in `DDG::Block::Words`

You can see how it breaks `president-elect` into `president` and `elect` and then checks the following words which match the trigger phrase.

I think we should probably not break dash separated words into sub-words. That change could have a potentially very big effect on triggering though...

**Comment by moollaza** [comment]
@mintsoft can you add another guard to ensure we're dealing with `president\s` and not `president-.+`? That's the easiest fix for now.

**Comment by mintsoft** [comment]
@moollaza I'll add that guard in

**Comment by mintsoft** [comment]
Also I think the bug is more subtle than that; if it was just as you described then "who is the president elect of the united states" should trigger, which it doesn't. Unless I've misinterpreted?

**Comment by mintsoft** [comment]
@moollaza I've flipped out to `query_lc` and then re-implemented the replacements of the triggers with empty sting before the guard; that way, if we fix up duckpan/`DDG::Block::Words` then we can easily flip back to 'remainder' and delete https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3938/files#diff-66449435cf1d3b4e87ded23d450483eaR25

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

**Pull request merged**
