### PR TITLE
Add git cheat sheet

### PR DESCRIPTION
**Pull request by moosilauke**
Added *git.json* - first attempt at creating a git cheat sheet for DDG (also my first attempt at cloning, forking, pulling, etc. :grimacing:) Hopefully I did this vaguely right...

### CODE REVIEW

**Comment by MrChrisW** [comment]
Hey @moosilauke, unfortunately it looks like @zekiel beat you to making a git cheatsheet see #1165

I'll close this, however please feel free to contribute another cheatsheet! Thanks again for your interest in DDH.

**Comment by moosilauke** [comment]
Damn, beat by two minutes *and* with a vastly superior cheat sheet! Still a good learning exercise for me though. Thanks @MrChrisW and @zekiel!

**Comment by MrChrisW** [comment]
@moosilauke :smile: Please feel free to stick around and tackle any issues or contribute a new IA, hopefully you can continue to learn more about DDG and GitHub!

Checkout our [Ideas forum](https://duck.co/ideas) if you're unsure about what to build.

**Comment by zekiel** [comment]
wow @moosilauke  I don't think this has ever happened before but sorry for the duplicate! Where did you hear about DuckDuckHack?

**Comment by moosilauke** [comment]
@zekiel Came over via Hacker News! I'm looking to apply for the People Ops role and wanted to get my hands dirty first. Besides, I'm trying to learn Rails and a little git practice never hurt.

**Comment by zekiel** [comment]
Thanks @moosilauke  Best of luck with your projects!

**Pull request closed without merging**
