### PR TITLE
Improving contributing file to reflect contributor guide

### PR DESCRIPTION
**Pull request by talsraviv**
Changing to reflect the messaging in the contributing guide https://duck.co/help/contributing/create-instant-answer

[Same as PR on spice](https://github.com/duckduckgo/zeroclickinfo-spice/pull/2003)

cc @zekiel

### CODE REVIEW

**Comment by zekiel** [comment]
@talsraviv  I like it but wouldn't want this to exist as documentation --just a list of steps. Where to look, what to do, etc. "A launchpad" 

Would recommend the following:

1. Section order should be: 
 --Quick Start
 --Create New
 --Improve Current

2. Would replace Cheat Sheets w/ QuickStart goodie 

3. Take out language that makes it seem like each section is necessary before moving to the next. 

3. Each section should have a 1,2,3 list to get started. For example, the Create New section should be something like: 

1. Get an idea
   -grab one from the top voted or think of your own
2. Let us know what you're working on by emailing open@duckduckgo.com
3. Start coding here: duck.co/duckduckhack/.../

**Comment by talsraviv** [comment]
Makes sense. Can you clarify number 2?

**Comment by talsraviv** [comment]
@zekiel whatchoo think

**Comment by zekiel** [comment]
@talsraviv  on #2 --> I meant suggesting a Cheat Sheet over the QuickStart bc it's actually valuable. It seems like we're advocating people to make QuickStart IAs since it's in contributing.md. To me, this should show people where to make an impact so would give them something real like CheatSheets

**Comment by talsraviv** [comment]
@zekiel I thought about this for a bit and realized they're both valuable for different user goals. Check out what I did.

My thinking if it's valuable:
- If *learning the goodie framework* is the goal, the quick start is the best (because cheat sheets don't touch on the PM file or tests or the full loop - and they require doing some content research)
- If *contributing quickly* is the goal, then cheat sheets are better, for those same reasons.

**Comment by talsraviv** [comment]
Reminder to self... if this is cool to merge I'll do the same for Spice repo

**Comment by zekiel** [comment]
@talsraviv  nailed it! LGTM

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
