### PR TITLE
silverli's new sublime text cheat sheet for OSX Goodie

### PR DESCRIPTION
**Pull request by silverli**
**What does your Instant Answer do?**
Helps users with shortcuts for OSX in Sublime 2.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Easier Format, readability of shortcuts for people using DuckDuckGo.

**What is the data source for your Instant Answer? (Provide a link if possible)**
http://www.cheatography.com/gelicia/cheat-sheets/sublime-text-2-shortcuts-verbose-mac/

**Why did you choose this data source?**
Seemed like the best option for Sublime 2 (especially since Sublime 3 is still in beta).

**Are there any other alternative (better) data sources?**
Maybe, but this is the best I found for now.

**What are some example queries that trigger this Instant Answer?**
"sublime text mac cheat sheet"

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Developers, Computer Science Majors, people who use pretty text editors, Mac users.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Not sure. I didn't look.

**Which existing Instant Answers will this one supercede/overlap with?**
This one goes well with the sublime text shortcuts for PC (the file is called: "sublime-text.json").
If possible, I'd say there should be a way to have the two instant answers appear together in the instant answer area, with the tab option to see PC or OSX shortcuts.

**Are you having any problems? Do you need our help with anything?**
No. All seems to work!

**Where did you hear about DuckDuckHack? (For first time contributors)**
GDI Philly

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
image
image

## Checklist
Please place an 'X' where appropriate.

```
- [X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [X] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

### CODE REVIEW

**Comment by jagtalon** [comment]
Hey, @silverli! Please change `Cmd` to the snazzier `⌘`. :)

**Comment by silverli** [comment]
Do I just copy and paste ⌘ in the json or is there an ASCII character?

**Comment by jagtalon** [comment]
@silverli copy pasting that squiggle is good!

**Comment by silverli** [comment]
See above for instant answer template pull request template I added in first request.

image

**Comment by jagtalon** [comment]
Looks like the test is failing! Check out https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/IsAwesome/19kestier.t as a reference.

**Comment by silverli** [comment]
Hey @jagtalon, I deleted the test IsAwesome "silverli.t" file.  Dont really understand why it was causing an issue though.

**Comment by mintsoft** [comment]
@silverli It looks like there's both a cheatsheet and an `is_awesome` in this PR, can you bomb out the `is_awesome`; I think the cheatsheets are awesome enough!

**Comment by silverli** [comment]
hey @mintsoft-- i thought i deleted the is_awesome silverli.t file? is there another way i should remove it?  thanks!

**Comment by mintsoft** [comment]
@silverli you did indeed, however there's still the actual IA (`IsAwesome/silverli.pm`) in the PR

**Pull request closed without merging**
