### PR TITLE
Remove IsAwesome Goodies

### PR DESCRIPTION
**Pull request by moollaza**
**The time has come to say "Goodbye" to the IsAwesome Goodies! :cry:**

In an effort to greatly lower the barrier to contributing a real Instant Answer, we created the "IsAwesome" Goodie tutorial. We showed developers how to make a working Instant Answer with a unique trigger related to their GitHub username, which provide an Instant Answer declaring the developer was awesome for successfully completing the tutorial and creating a real Instant Answer.

These Instant Answers were a success in terms of getting more developers to contribute, however, ultimately they were a failure in that they didn't really improve DuckDuckGo for anyone. The trigger was purposely made to be very niche and so these "Instant Answers" didn't truly add any value as they only provided a single result to a single query. 

We never included these Goodies in Instant Answer index and none of them have an Instant Answer Page. We also made the decisions to stop accepting Pull Requests for these Instant Answers several months ago. Seeing as these IAs are never used, and are not represented in our Instant Answer Index we've made the decision to remove them from the repo as well.

Thanks to everyone who helped create, review, and merge these contributions!

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@moollaza You mean my tests are going to be fast again? :wink:

**Comment by zekiel** [comment]
ooo rah!

**Comment by zachthompson** [comment]
click the button!

**Comment by moollaza** [comment]
Fare thee well!

**Comment by GuiltyDolphin** [comment]
@moollaza Whoo! That cut 30 seconds of my test time!

**Comment by mintsoft** [comment]
Awesome!

**Pull request merged**
