### PR TITLE
Fix FedEx tracking URL

### LINKED ISSUE #1111: FedEx: Tracking link needs to be updated -- currently leads to "page has moved"
https://duckduckgo.com/?q=fedex+9241990100130206401644&ia=answer

Clicking the link we provide sends the user to a page which states:

```
Moved Permanently

The document has moved here.
```

We need to be sending them to:
https://www.fedex.com/apps/fedextrack/?action=track&tracknumbers=9241990100130206401644&action=track

### PR DESCRIPTION
**Pull request by stevenmg**
Fixes the issue with FedEx tracking links leading to an old URL.

I also removed a link in the comments that was outdated. Unfortunately I was not able to find the current URL.

Fixes #1111

### CODE REVIEW

**Comment by stevenmg** [comment]
I almost forgot this references bug #1111

**Comment by mintsoft** [comment]
@stevenmg http://images.fedex.com/us/solutions/ppe/FedEx_Ground_Label_Layout_Specification.pdf

**Comment by stevenmg** [comment]
This is what I see at that page.
screenshot 2015-04-22 13 24 15

**Comment by moollaza** [comment]
The PDF link works for me as well. Click it in that above comment prompts me to save the file.

**Comment by stevenmg** [comment]
Ok, I just tested in Internet Explorer and it works there, but not in Firefox for some reason. I will add the link again.

**Comment by stevenmg** [comment]
I am finished with this, and it should be ready to merge unless someone has something to add.

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Pull request merged**
