### PR TITLE
small change on bash json file

### PR DESCRIPTION
**Pull request by igithub14**
## Description of new Instant Answer, or changes

 

 

---

Instant Answer Page: https://duck.co/ia/view/bash_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by igithub14** [comment]
If this is a bug fix:
{IA **bash.json**}: 
I just added the **Modulo Operator**. I wrote it in the **Section** _Arithmetic Operators_, at line 279.


The reason why I'd like to pull this modest change is because it's a way to me to understand if I'm able to use git, and so if I can help you on DuckDuckGo.  Thank you anyway.



---


Instant Answer Page: [https://duck.co/ia/view/bash_cheat_sheet](url)

**Comment by pjhampton** [comment]
Hi @igithub14,

It's not clear what this change is because you changed the filename. Can you please rename the file back to bash.json. This will make the tests pass as well

**Comment by pjhampton** [comment]
Many thanks, @igithub14 😄

**Comment by igithub14** [comment]
You're welcome! I know the change I proposed is extremely simple: I just
wanted to try. I hope I can do a little better soon.

Bye

**Pull request merged**
