### PR TITLE
improved queries and ok_queries

### PR DESCRIPTION
**Pull request by brianlechthaler**
added 'self harm', 'how to kill self', 'my life is over', 'suicide prevention hotline', 'suicide howto', and 'suicide instructions to @queries

added 'suicide squad' to @ok_queries

### CODE REVIEW

**Comment by GuiltyDolphin** [comment]
@brianlechthaler Hey - thanks for contributing.

It seems you've only updated the tests - you might want to have a look at `share/goodie/help_line/triggers.yml` which is where the triggers are kept.

**Comment by GuiltyDolphin** [comment]
@brianlechthaler Heyo, you still interested in finishing this? No worries if you don't have time or anything - just checking in.

**Comment by brianlechthaler** [comment]
Apologies; I currently do not have the time.

**Comment by moollaza** [comment]
@brianlechthaler that's no problem. We'll let another community member finish this up.

**Pull request closed without merging**
