### PR TITLE
Make the handle a template parameter

### PR DESCRIPTION
**Pull request by zachthompson**
Allow dev to choose their handle during IA creation.

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by russellholt** [comment]
LGTM

**Comment by GuiltyDolphin** [comment]
@zachthompson Nice :+1:

**Comment by moollaza** [comment]
this one isn't ready for merge -- we need to merge + release the DuckPAN PR first

**Comment by zachthompson** [comment]
The DP PR is merged. I'll release.

**Comment by moollaza** [comment]
:+1:

**Pull request merged**
