### PR TITLE
Goodie: Minecraft crafting recipes.

### PR DESCRIPTION
**Pull request by engvik**
**What does your Instant Answer do?**
Return the crafting recipe for something that can be crafted in Minecraft.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
A faster and cleaner answer.

**What is the data source for your Instant Answer? (Provide a link if possible)**
A static file.

**Why did you choose this data source?**
It contains most of the recipes.

**Are there any other alternative (better) data sources?**
No, not that I know of.

**What are some example queries that trigger this Instant Answer?**
ladder in minecraft
minecraft craft tnt

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Minecraft players.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes, [this](https://duck.co/ideas/idea/4535/minecraft-crafting-guide).

**Which existing Instant Answers will this one supercede/overlap with?**
None.

**Are you having any problems? Do you need our help with anything?**
- We might need to change the triggers, but I tried to avoid using regex. Open for suggestions.
- I'm not sure if you allow header tags in the HTML. I use h3 for the headline.

**Where did you hear about DuckDuckHack? (For first time contributors)**
Not my first contribution.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
minecraft-ddg
## Checklist

Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[\] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [X] Firefox
        [] Native Browser
        [X] Google Chrome
        [] Opera

    - Ubuntu
        [X] Firefox
        [X] Chromium
        [X] Opera
```

---

> IA Page: https://duck.co/ia/view/minecraft

### CODE REVIEW

**Comment by MrChrisW** [comment]
Happy New Year @larseng Any update on this? :smile:

**Comment by larseng** [comment]
Hi and happy new year! Sorry, been busy during the holidays, but I'll get to it this weekend. Actually got an reply from MinecraftXL as well, but still no updates.

**Comment by MrChrisW** [comment]
@larseng No problem! Great to hear you received a reply from MinecraftXL. I'm really looking forward to seeing this Goodie live :smile:

**Comment by larseng** [comment]
Still no updates on their website, so I updated the broken descriptions with descriptions from somewhere else.

How does it look @abeyang @mintsoft @MrChrisW ?

**Comment by jagtalon** [comment]
@larseng Thanks! Putting it up on a server for final review!

**Comment by jagtalon** [comment]
@larseng It looks really good. Just one more thing--the image is too close to the text. Is it possible to add a little spacing?

screen shot 2015-01-08 at 5 10 25 pm
screen shot 2015-01-08 at 5 11 37 pm

Thank you!

**Comment by larseng** [comment]
@jagtalon Done :smile: I also aligned the image with the recipe text as in @abeyang's image.

**Comment by jagtalon** [comment]
:+1:

**Comment by larseng** [comment]
Nice :smile:

**Comment by abeyang** [comment]
@larseng it's looking better! However, can we make the following changes so it'll more look like this:

minecraft-1

Changes:
- align image to the right rail, so that it matches with the SERP content
- align image to the top, so it matches to the title text
- move Ingredients into the subtitle (right below title)
- mockup's gutter is too wide -- we'll need to tighten that

Finally, we should be using the standard template classes, like the title should be zci__header and the description should be zci__content. Maybe @jagtalon can help you with that?

Thanks! Almost there!

**Comment by jagtalon** [comment]
@larseng I can make a PR for these changes and get it out as soon as I can!

**Comment by larseng** [comment]
@jagtalon Thanks, that would be great as I can't get to this until sunday at earliest.

**Comment by moollaza** [comment]
Hey guys, I'm moving the design updates to an issue. Hopefully someone from the community can tackle this!

**Comment by moollaza** [comment]
@larseng congrats! It's live: https://duckduckgo.com/?q=how+do+i+craft+a+cake+in+minecraft&ia=minecraft

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Comment by moollaza** [comment]
Apologies for the long delay, we used this IA as a candidate for the new Goodie templates. It was the first live Goodie to use the new templates!

**Pull request merged**
