### PR TITLE
Elixir Cheat Sheet

### PR DESCRIPTION
**Pull request by pjhampton**
## Elixir Cheat Sheet

https://duck.co/ia/view/elixir_cheat_sheet

### Description
Elixir is a dynamic functional programming language built on top of the Erlang Virtual Machine. This cheat sheet aims to give a non-exhaustive overview of typical language constructs and syntax.

### Data Source
http://elixir-lang.org/

### Example Queries
Elixir Cheat Sheet, Elixir overview, Elixir syntax, elixir programming language

### CODE REVIEW

**Comment by daxtheduck** [comment]
@pjhampton Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
## [Elixir Cheat Sheet](https://duck.co/ia/view/elixir_cheat_sheet)

**Description**: Elixir is a dynamic functional programming language built on top of the Erlang Virtual Machine. This cheat sheet aims to give a non-exhaustive overview of typical language constructs and syntax.

**Example Query**: [Elixir Cheat Sheet](https://beta.duckduckgo.com/?q=Elixir Cheat Sheet), [Elixir overview, Elixir syntax, elixir programming language](https://beta.duckduckgo.com/?q=Elixir overview, Elixir syntax, elixir programming language)

**Tab Name**: Answer

**Source**: http://elixir-lang.org/

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/elixir_cheat_sheet)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/elixir_cheat_sheet)*

**Comment by moollaza** [comment]
@pjhampton why the close?

**Comment by moollaza** [comment]
Never mind I see it was continued :+1:

**Pull request closed without merging**
