### PR TITLE
Add tests to distro

### PR DESCRIPTION
**Pull request by zachthompson**
Different route.  Let's add t/ back.

### CODE REVIEW

**Comment by moollaza** [comment]
Hmm looks like some of these test are legitimately failing locally but not all of them...

**Comment by zachthompson** [comment]
@mintsoft there was a single test updated to make sure it failed appropriately.  Is that what you saw?

**Comment by mintsoft** [comment]
@zachthompson actually, it looks like I missed it totally: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1218/files Sorry about that!

**Comment by moollaza** [comment]
Merging for now because it *should* be working. I can't figure out why EmailValidator is failing but will try and fix.

**Comment by mintsoft** [comment]
@moollaza Just had a look into EmailValidator, if one disables the `2 > /dev/null` then everything is complaining (https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/builds/70502605#L4032) however, EmailValidator stood out with this:
```
[10:17:56] t/EmailValidator.t ............... Use of uninitialized value in subroutine entry at /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/File/ShareDir.pm line 329.
Use of uninitialized value in subroutine entry at /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/File/ShareDir.pm line 329.
Use of uninitialized value in subroutine entry at /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/File/ShareDir.pm line 329.
Net::Domain::TLD not available at /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/Email/Valid.pm line 217.
[10:17:56] t/EmailValidator.t ............... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Pull request merged**
