### PR TITLE
CONTRIBUTING.md must contain pull request naming conventions

### PR DESCRIPTION
**Pull request by gautamkrishnar**
I think CONTRIBUTING.md must contain pull request naming conventions.It will help new contributors to chose the correct title for their PR. as you can see in the screenshot below, the link to readme.md is displayed on GitHub while opening a new PR. 
screenshot 143

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
@moollaza what did you say? :smile:

**Comment by moollaza** [comment]
@talsraviv thoughts? Perhaps we should just link to the relevant section in the docs?

Duplication kinda sucks, but sending them away isn't amazing either.

---

@gautamkrishnar also, we've updated the docs to tell devs to put "Fixes X in the description now, because that actually ensures the issue will be closed

**Comment by tagawa** [comment]
Looks good to me. Although it's duplication it's not likely to change and need maintenance.

**Comment by talsraviv** [comment]
I support this - makes sense. It makes me think of putting the most important highlights of the submitting section in this. I didn't realize it was linked so prominently.

**Comment by talsraviv** [comment]
I will merge and build on this - thanks @gautamkrishnar!

**Comment by talsraviv** [comment]
Oh wait I don't have write access. @moollaza when you merge let me know and I'll build on top of what @gautamkrishnar started.

**Comment by gautamkrishnar** [comment]
:smile: :+1:

**Comment by moollaza** [comment]
@talsraviv merged!

**Pull request merged**
