### PR TITLE
Swap key-value pair on `Three states` section of git cheatsheet

### PR DESCRIPTION
**Pull request by NaveenKarippai**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`Git cheatsheet: swap key-value for Three states section`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes
The key-value pair was not following the standard order and it should be swapped to make it look consistent with other key-value data included on git cheatsheet JSON data.

Provide an overview of the changes this pull request introduces.
git.JSON file modified

###### Which issues (if any) does this fix?

Fixes #NNNN - how specifically does it fix the issue?

###### People to notify @chrissherlock

---

Instant Answer Page: https://duck.co/ia/view/git_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zekiel

### CODE REVIEW

**Comment by daxtheduck** [comment]
@NaveenKarippai Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by NaveenKarippai** [comment]
This PR was opened by adding a changeset (PATCH) on top of PR #2969. 

Could someone please leave a comment if a different workflow should be chosen. Thanks in advance!

**Comment by chrissherlock** [comment]
Whoops! Sorry about that, nice catch :-)

**Comment by NaveenKarippai** [comment]
@chrissherlock no worries! I'm glad to help. 

I wonder if this is the right workflow, maybe I should have forked your goodies repo and submitted a PR to your forked repo/branch.

**Comment by zekiel** [comment]
we can ignore this bc #2969 fixed the same

thank you both @chrissherlock @NaveenKarippai

**Comment by NaveenKarippai** [comment]
@zekiel This PR #2987 was modifications on top of PR #2969. Could you please have a look the changes on commit object 113d68f

**Comment by zekiel** [comment]
@NaveenKarippai  ahh i see. Totally missed that between my tabs :) Thanks for the follow up -- will merge now.

**Comment by NaveenKarippai** [comment]
@zekiel Thanks. Btw, do you know why the changeset on 113d68f doesn't show up on beta-server? Or, Am I too early to look that up?

**Pull request merged**
