### PR TITLE
New Age of Empires Cheat Sheet

### PR DESCRIPTION
**Pull request by Vonter**
## Description of new Instant Answer, or changes

Adds an Instant Answer for a cheat sheet for the 1997 RTS video game, Age of Empires.

## Related Issues and Discussions

https://duck.co/ia/view/age_of_empires_cheat_sheet

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/age_of_empires_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
Hmm, this is a *literal* cheat sheet, I'm not sure if it's what we were originally intending here. @moollaza @tagawa any opinions?

**Comment by sahildua2305** [comment]
@mintsoft I think it's okay to have *literal* cheat sheets as people searching for Age of Empires cheat sheet would actually want this content.

**Comment by mintsoft** [comment]
@Vonter This is almost ready to merge, although the test are failing with:
```
[23:34:33] t/CheatSheets/CheatSheets.t ...... age-of-empires.json and aoeii.json both using alias 'aoe' at t/CheatSheets/CheatSheets.t line 42, <$fh> line 1.
```

If you remove the `aoe` alias then the test will pass

**Comment by tagawa** [comment]
Yes, I agree with @sahildua2305 - it's not showing anything illegal and is probably what gamers want when searching for cheats.

**Comment by Vonter** [comment]
@mintsoft I have modified the alias to aoe1. Thanks for pointing out the mistake.

Also, I had created this cheat sheet after seeing age-of-mythology.json and I thought that this is a valid way of using a cheat sheet.

**Comment by mintsoft** [comment]
@Vonter It's absolutely fine, it's just the first time I'd seen a game cheats cheatsheet appear. I think overall this LGTM 👍

**Comment by daxtheduck** [comment]
@Vonter this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
