### PR TITLE
URLEncode: enable triggering on 'uri' as well

### LINKED ISSUE #3201: URLEncode: Trigger on "uri" as well
Should probably trigger on `uri` in addition to `url`.

------
IA Page:  http://duck.co/ia/view/urlencode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nishanths

### PR DESCRIPTION
**Pull request by neosilky**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

`uri` is now matched in the same way as `url` was. A few tests have been added. Let me know if you'd like the full test suite replicating.

###### Which issues (if any) does this fix?

Fixes #3201 by duplicating all existing triggers to match `uri`.

###### People to notify (@mention interested parties)

@nishanths, @tagawa 

---

Instant Answer Page: https://duck.co/ia/view/urlencode

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nishanths

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Thanks for the quick work @neosilky. It's now working on the beta server: https://beta.duckduckgo.com/?q=uri+encode+https%3A%2F%2Fduckduckhack.com%2F&ia=answer

We'll get a few more eyes on it for testing, and then merge if no problems.

**Comment by mintsoft** [comment]
LGTM

**Comment by neosilky** [comment]
@mintsoft @tagawa Are we good to merge now? :)

**Comment by tagawa** [comment]
@nishanths As maintainer, are you happy with this update?

**Comment by tagawa** [comment]
Hi @neosilky. I think the maintainer is busy at the moment, but everything looks good to me so let's merge merge merge!
Thank you very much for making this improvement, and thanks for the feedback @mintsoft.

**Pull request merged**
