### PR TITLE
Images added to Chinese zodiac

### LINKED ISSUE #1431: Chinese Zodiac: Switch to Icon template, use new Animal icons
We now have custom animal icons that we can use with the Icon template to really improve this Instant Answer!

The image assets can be found here: http://cl.ly/2Y403l2i253X

------
IA Page:  http://duck.co/ia/view/chinese_zodiac

### PR DESCRIPTION
**Pull request by Sloff**
Fixes #1431:

Note that this is working for the darker themes, but I'm not sure how to change the colour for the lighter themes.

-----
IA Page: https://duck.co/ia/view/chinese_zodiac

### CODE REVIEW

**Comment by mintsoft** [comment]
@abeyang any thoughts about the light theme?

**Comment by thm** [comment]
@Sloff @mintsoft @abeyang The icons are meant to be displayed within a `#222` circle, without borders or shadows. Attached below is the original design:
screenshot

**Comment by moollaza** [comment]
@thm thanks for posting that *crucial information*! I just realized I missed that part! :frowning:

**Comment by jagtalon** [comment]
Oh that looks amazing

**Comment by Sloff** [comment]
Looks awesome! Anything I can do from my side for now?

**Comment by abeyang** [comment]
Ditto what @thm said. :smile:

**Comment by abeyang** [comment]
Actually, @thm, we do want to include the elements as well, no? In other words, they're not a `#222` background, but the colors would correspond to the element?

**Comment by thm** [comment]
@abeyang I would like to finalize the colors for the elements in tandem with the colors for the astrological zodiac icons (those have slightly different elements). I don't want to stall this contribution though, so I'd rather revise it later when we implement the astrological zodiac icons! :smile:

**Comment by abeyang** [comment]
@thm that sounds like a good plan.

**Comment by Sloff** [comment]
Hi all, I changed the background color by using elClass, not sure if this is what you wanted, but let me know if I should do it differently.

**Comment by Sloff** [comment]
Hi @moollaza, colors changed

**Comment by abeyang** [comment]
@Sloff Looks good. However, dark version is a bit awkward:

image

@thm Can you provide "dark" version of the assets?

**Comment by thm** [comment]
@abeyang @Sloff Sure, here you go http://cl.ly/031x1w413L1M

**Comment by moollaza** [comment]
@Sloff @abeyang Hmm the color is being changed by our own CSS here. We may need to just use a CSS rule to force the dark background. Using Dark assets is actually much more work because we'd need to detect the dark theme and choose the images on the frontend using JavaScript because the Perl doesn't know what theme is chosen.

@Sloff sorry about the back and forth, but let's add a CSS file for this that forces `bg-clr--slate` to `#333`. We can use `!important` if needed, but let's make sure we namespace the CSS as usual, using `.zci-chinese_zodiac`

After that, this is good for merge!

**Comment by abeyang** [comment]
@Sloff Ok, after talking with @moollaza about this, I agree with him -- let's try to force the circle background color to use `#333`, even in dark mode.

**Comment by thm** [comment]
@Sloff @moollaza Since this issue is still open I'm posting the final colors here for the elements. Would love to see this live!:

color codes

**Comment by Sloff** [comment]
Hi all, sorry for the long delay, I altered the icon colors, but I'm not sure what to use for the wood color.

**Comment by moollaza** [comment]
>Hi all, sorry for the long delay, 

@Sloff it's no problem at all :+1: 

>I altered the icon colors, but I'm not sure what to use for the wood color.

Hmm, I guess temporarily, we'll need to define our own CSS class/rule for `$brown`. I'll have the team add a new internal class so we can remove the stylesheet once we get an internal `$brown` setup and released

@Sloff how does that sound?

**Comment by abeyang** [comment]
@Sloff Hi, for these images, can we also lose that outer dark ring?

**Comment by moollaza** [comment]
@Sloff Ping! I'm just checking in to see if you're still interested in finishing this one up? We'd love to see this go live!

There's absolutely no rush, just wanted to make sure you're not stuck on anything.

**Comment by moollaza** [comment]
@Sloff I'm going to close this for now. Happy to re-open if you're still interested in finishing this up!

**Pull request closed without merging**
