### PR TITLE
Sloff's Awesome Tutorial Goodie

### PR DESCRIPTION
**Pull request by Sloff**
**What does your Instant Answer do?**
It displays the text "Ettienne Pitts is awesome and has successfully completed the DuckDuckHack Goodie tutorial!" when searching "duckduckhack sloff"

**What are some example queries that trigger this Instant Answer?**
Only "duckduckhack sloff"

**Where did you hear about DuckDuckHack? (For first time contributors)**
On the DuckDuckGo website

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
example

## Checklist
Please place an 'X' where appropriate.

```
- [X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [] Google Chrome
        - [X] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

```

### CODE REVIEW

**Comment by MrChrisW** [comment]
@Sloff Congratulations on making your first Goodie :tada:

Now that you've made your first Goodie, we really hope you'll continue to contribute and make more Instant Answers! Please checkout our [Ideas forum](https://duck.co/ideas) if you're unsure about what to build. 

There's always lots of discussion in our [GitHub repositories](https://github.com/duckduckgo) feel free to tackle issues or submit pull requests.

**Comment by Sloff** [comment]
Thanks @MrChrisW !

**Comment by zekiel** [comment]
Hey @Sloff!  Thanks for getting involved--we're leaving comments for you over at your other Instant Answer pull request (#415). 

On, "where did you hear about DuckDuckHack" -- you mentioned that you saw it on duckduckgo.com Was it, by chance, the new i-link that you see in some Instant Answer boxes? For example, to the left of "more at people in space" here https://duckduckgo.com/?q=who%27s+in+space&t=ffab&ia=answer  ? or some other location on duckduckgo.com?

**Comment by Sloff** [comment]
Hi @zekiel, I was just exploring the DDG website and found it under the "Getting Involved" part of the menu

**Comment by moollaza** [comment]
@Sloff congrats! It's live: https://duckduckgo.com/?q=duckduckhack+sloff&t=ffcm&ia=answer

Sorry for the late notice!

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
