### PR TITLE
REPO: New PR template

### PR DESCRIPTION
**Pull request by pjhampton**
## Description of new Instant Answer, or changes

This PR template update aims to:

- Reflect the redirected focus on improving existing IAs based on user feedback
- Reflect the success of the Fathead PR template
- Encourage better IA Pages and IA testing practices
- Encourage the reviewer merging to merge appropriately

## People to notify

@moollaza 
@duckduckgo/community-leaders 

## Other notes

- This will be used as the Spice PR template as well
- An easy way to view is to copy and paste into a [Gist](https://gist.github.com/)

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
Do we need to squash the commits before merging?

**Comment by pjhampton** [comment]
@gautamkrishnar yep. @moollaza mentioned this yesterday on slack 😄

**Comment by mintsoft** [comment]
@pjhampton I think @moollaza has changed the settings on the repo; merging a PR now squashes the commits automatically (hence the `squash and merge` button)

**Comment by pjhampton** [comment]
Yeah, your right @mintsoft - I'll remove this. Any more critique is welcome!

**Comment by moollaza** [comment]
@pjhampton Thanks! This LGTM :+1:

**Pull request merged**
