### PR TITLE
Bash Primary Expressions: Title/Subtitle Layout 

### LINKED ISSUE #2299: Bash Primary Expressions: Convert to text template, use title/subtile layout
This IA was recently converted to template, but could be further improved by using a more canonical Title/Subtitle design.

Seeing as this one has `pre` blocks, it mean the title/subtitle will need to use `title_content` and `subtitle_content` sub-templates (title.handlebars and subtitle.handlebars)

For a query like `bash if [[ "abc" -lt "cba" ]]` the result should look like:

> **true if `"abc"` is numerically less than `"cba"`**
> Bash expression: `[[ "abc" -lt "cba" ]]`

---

IA Page:  http://duck.co/ia/view/bash_primary_expressions

### PR DESCRIPTION
**Pull request by mr-karan**
**Fixes #2299.** Modified the handlebars template file to replicate the template design mentioned in the issue #2299 

---

https://duck.co/ia/view/bash_primary_expressions
Maintainer: @mintsoft

### CODE REVIEW

**Comment by daxtheduck** [comment]
@mr-karan Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
Hiya @mr-karan unfortunately someone has already opened a PR for this: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2648

**Comment by GuiltyDolphin** [comment]
@mintsoft I think this PR should be re-opened, I've had a quick look and it looks like @mr-karan had #2473 open before #2648 - this appears to be a continuation of that.

Considering the current solutions are the same though, I would suggest having a look at @mintsoft's comment over on #2648 about the template @mr-karan.

**Comment by mintsoft** [comment]
@GuiltyDolphin fine with me

**Comment by moollaza** [comment]
@mr-karan Ping! I'm just checking in to see if you're still interested in finishing this one up? We'd love to see this go live!

There's absolutely no rush, just wanted to make sure you're not stuck on anything.

**Comment by mintsoft** [comment]
@mr-karan Ping! Just checking in if you're still interested in finishing this up. If not we can re-open it up to the community to finish

**Comment by mintsoft** [comment]
@mr-karan I'm closing this for now, just ping us if you want it reopening

**Pull request closed without merging**
