### PR TITLE
Golang Cheat Sheet : Add JSON escape sequences

### PR DESCRIPTION
**Pull request by vikashvverma**
I have removed HTML tags and added Proper JSON escape sequences.
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2257
@moollaza Can you review this.

### CODE REVIEW

**Comment by moollaza** [comment]
@vikashvverma this seems OK. We'll need to merge the updates to the parser before testing this though :+1:

**Comment by vikashvverma** [comment]
@moollaza Yeah sure.

**Comment by vikashvverma** [comment]
@moollaza I think this can be merged now!

**Comment by GuiltyDolphin** [comment]
@vikashvverma Move into #2746 if still applicable.

**Pull request closed without merging**
