### PR TITLE
Support `-ve` and `+ve`

### PR DESCRIPTION
**Pull request by hemanth**
`-ve` and `+ve` are also in usage. //cc @moollaza @mintsoft

### CODE REVIEW

**Comment by hemanth** [comment]
//cc @moollaza @mintsoft

**Comment by mintsoft** [comment]
@hemanth thanks, although this line will need editing too: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1855/files#diff-58bc8e0568cd4135bd5ae8e76dd3be5bR48 or the input needs to be normalised

**Comment by hemanth** [comment]
@mintsoft Done. I was also planning to edit `BloodDonor.t`

**Comment by mintsoft** [comment]
Thanks for the improvement @hemanth !

**Comment by hemanth** [comment]
Green now, but should we ucase the entire string..hmm

**Comment by mintsoft** [comment]
@hemanth I think it's fine to leave the +-/ve bit lower case, the letter is `uc` so that it displays better

**Comment by hemanth** [comment]
Cool, thanks!

**Pull request merged**
