### PR TITLE
Added speedrate cheatsheet for duck

### PR DESCRIPTION
**Pull request by mvsn**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Provide an overview of the changes this pull request introduces.

###### Which issues (if any) does this fix?

Fixes #NNNN - how specifically does it fix the issue?

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/speedrate

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
@mvsn Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@mvsn It looks like you've just imported the IA metadata JSON - have a look over the [cheat sheet walk-through](http://docs.duckduckhack.com/walkthroughs/programming-syntax.html) for some guidance on creating a cheat sheet.

**Comment by mvsn** [comment]
@GuiltyDolphin I'm trying to create an instant answer using static content (I don't have a wikipedia page yet). Is it possible to do it? Thanks for your help!

**Comment by GuiltyDolphin** [comment]
@mvsn Hmm? The fields for the cheat sheets have to be entered manually - if you have a set of 'static' articles from which you can scrape data it would be worth looking at a FatHead.

**Comment by mvsn** [comment]
Thanks @GuiltyDolphin - will check out FatHead

**Comment by mintsoft** [comment]
@GuiltyDolphin @mvsn should this be closed?

**Comment by mvsn** [comment]
yes please. thanks @GuiltyDolphin <https://github.com/GuiltyDolphin>

**Pull request closed without merging**
