### PR TITLE
C cheat sheet: Re-arranged operators according to precedence (fixes #2938)

### LINKED ISSUE #2938: C Cheat Sheet: Operators should be ordered by precedence
This reference page may help: http://en.cppreference.com/w/c/language/operator_precedence

(Originally reported in the [C subreddit](https://www.reddit.com/r/C_Programming/comments/4gp2xt/help_improve_duckduckgos_crelated_searches/))

------
IA Page:  http://duck.co/ia/view/c_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @harisphnx

### PR DESCRIPTION
**Pull request by harisphnx**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`C cheat sheet: Fixes #2938`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Re arranged the operators in their separate sections to match the order of precedence.

###### Which issues (if any) does this fix?

No issues

###### People to notify (@mention interested parties)

@tagawa 

---

Instant Answer Page: https://duck.co/ia/view/c_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by harisphnx** [comment]
@tagawa @mintsoft, Can we remove the label "Maintainer Input Requested"?

**Comment by tagawa** [comment]
Thanks @harisphnx. This looks good to me so let's merge!

**Comment by edgesince84** [comment]
@harisphnx thank you for your contribution to DuckDuckHack, we really appreciate it! I'm reaching out to let you know that we recently launched a new forum with the initiative of improving programming-related searches, and I hope you'll [join us](https://forum.duckduckhack.com/)!

There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Pull request merged**
