### PR TITLE
DistancePerHour fixes issue #955

### LINKED ISSUE #955: Conversions: Support "100 km/h to mph"
We support https://duckduckgo.com/?q=100+km+to+miles&t=ffab&ia=answer, and it would be great if we could support this as well.

https://duck.co/ia/view/conversions

### PR DESCRIPTION
**Pull request by BigxMac**
I just started the work on this, but figured I would submit a PR so I can get some help with questions I have. Atm the current code will not be triggered no matter what. For some reason when I type in a trigger keyword and just make it return "triggered" the code isn't run. Could someone help me resolve this. Thanks! 

Fixes #955 

-----
IA Page: https://duck.co/ia/view/distance_per_hour

### CODE REVIEW

**Comment by mintsoft** [comment]
@BigxMac I believe the original intent of https://github.com/duckduckgo/zeroclickinfo-goodies/issues/955 is to extend the Conversions.pm module with handling for this: 
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Conversions.pm

That said, I'll have a look into why it's not triggering and get back to you shortly

**Comment by mintsoft** [comment]
Hmm, It looks like the basic triggering is working fine, I've changed it to:
```perl
package DDG::Goodie::DistancePerHour;

use DDG::Goodie;

zci answer_type => "Conversion";
zci is_cached   => 1;

# Metadata.  See https://duck.co/duckduckhack/metadata for help in filling out this section.
name "DistancePerHour";
description "Converts kph to mph and vise versa.";
primary_example_queries "5 mph to kph", "5 m/h to k/h";
secondary_example_queries "optional -- demonstrate any additional triggers";
category "calculations";
topics "math";
code_url "https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/DistancePerHour.pm";
attribution github => ["BigxMac", "Jared Stefanowicz"];

# Triggers
triggers any => "mph", "mih" , "m/h" , "mi/h", "kph", "kih", "k/h", "ki/h";

# Handle statement
handle remainder => sub {

    return "hello";
};
1;
```

And I get "hello" as the output from `duckpan query`:
```
Query: mph
  You entered: mph
---
DDG::ZeroClickInfo  {
    Parents       WWW::DuckDuckGo::ZeroClickInfo
    public methods (4) : DOES, has_structured_answer, new, structured_answer
    private methods (0)
    internals: {
        answer        "hello",
        answer_type   "Conversion",
        caller        "DDG::Goodie::DistancePerHour",
        is_cached     1,
        is_unsafe     0
    }
}
---
```

**Comment by BigxMac** [comment]
As for extending conversions.pm I spoke with moollaza on the issue and he said that due to the impared modularity of the conversions.pm I was welcome to create a new one. Seems to be triggering now... Odd

**Comment by mintsoft** [comment]
@BigxMac Ah! Sorry I wasn't aware of that :) Gimme a shout if you need a hand with anything else

**Comment by BigxMac** [comment]
I added my code for it which should work fine but it seems that the second group isn't being selected in <code>my $unit = $2;</code> as it always returns undef.

**Comment by BigxMac** [comment]
Thanks I'll look into it and make use of that.

**Comment by BigxMac** [comment]
Before I can make use of that for some odd reason the number is not being picked up. in <code> my $number = $1;</code>

**Comment by mintsoft** [comment]
@BigxMac I'd try outputting `$_`; it's probably that the first part of the regex isn't being matched as it's `*` if there's a space at the start of `$_`

**Comment by BigxMac** [comment]
How can I find what keyword was triggered?
If I can find that I could be done.

**Comment by mintsoft** [comment]
@BigxMac If you switch it from `handle remainder` to `handle query` then `$_` the will be the entire query. It's not too well documented, but the info is here: https://duck.co/duckduckhack/goodie_triggers#query-formats

**Comment by moollaza** [comment]
Ping! @BigxMac I'm just checking in to see if you're still interested in finishing this one up? We'd love to see this go live!

There's absolutely no rush, just wanted to make sure you're not stuck on anything.

**Comment by BigxMac** [comment]
I am very interested, especially in contributing to DDG. I just really dislike Perl. I am doing more iOS development and JS so maybe I'll try contributing there next time. Finals are this week so how about I try to finish it up Friday and into this weekend. :)

**Comment by BigxMac** [comment]
so my regex is <code>/(\d)(.)/</code>. I need to get the number (which works) and then the unit the number is in so I can convert it to the opposite. I can't seem to access the format in my regex groups. I have two groups. How can I access both of them.

**Comment by mintsoft** [comment]
@BigxMac `$2` and `$3` will contain the second and third groups respectively.However I don't think the regex as written will do what you want. I think you want something like:
```perl
/^(\d+)\s?(.+)\s(?:to\s)?(.+)$/
```
When given "44 m/h to km/h" that should return;
* `$1` as "44"
* `$2` as "m/h"
* `$3` as "km/h"
Which I think is what you're trying to achieve?

**Comment by BigxMac** [comment]
That was exactly what I was looking for! It works now, but I am just trying to format the output to only a few digits of precision so "5 mph to kph" returns 3.10 instead of 3.10685596. I saw the DDG number helper and I'm going to try to use that.

**Comment by mintsoft** [comment]
Excellent, you could use the number styler
```perl
with 'DDG::GoodieRole::NumberStyler';
my $styler = number_style_for("0.123456789");
return unless $styler;
return "answer: ".$styler->for_display($perl_number);
```
Or there's the classic `sprintf`:
```perl
return "answer: ".sprintf("%.3f", "0.123456789");
```

**Comment by BigxMac** [comment]
I committed the final working version. I apologist for the delay in this. I plan on contributing some more, but not until I read up on Perl and JS some more. Thanks for all the help @mintsoft! :smile:

**Comment by mintsoft** [comment]
@BigxMac No problem; it's what we're here for. If you do have any problems, (with perl or DDG specific), we're always happy to help out!

**Comment by mintsoft** [comment]
@moollaza I can't help but feel there's a bit of a wasted resource here; how are things looking on the new super-cool, super-funky conversions/calculator (tm) ?

**Comment by moollaza** [comment]
@BigxMac @mintsoft terribly sorry for the delay!

No updates on a conversions IA yet so let's get this one moving along.

I think we should convert this one to use a template (now that they’re available to Goodies!) and have it look like the existing conversion Goodie: https://duckduckgo.com/?q=2lb+to+oz&ia=answer

**Comment by moollaza** [comment]
The `Text` template group should work here.

**Comment by BigxMac** [comment]
Im at yearbook camp and I won't be home until Thursday so it will have to wait a few days. Rocking my DuckDuckGo shirt though. https://vimeo.com/133540870

**Comment by moollaza** [comment]
>Im at yearbook camp and I won't be home until Thursday so it will have to wait a few days. Rocking my DuckDuckGo shirt though.

No problem! Have fun dude :+1:

**Comment by mintsoft** [comment]
@BigxMac Just checking in, are you still interested in finishing this off?

**Comment by BigxMac** [comment]
Absolutely! I'm out now, but will look into it when I go home.

**Comment by BigxMac** [comment]
I would just close this. :( I just don't have the time and can't stand perl. Thanks for all the help and the patience. If I were in your shoes this would have been closed months ago

**Comment by mintsoft** [comment]
@BigxMac No problem at all!

**Pull request closed without merging**
