### PR TITLE
Add visual to Frequency Spectrum goodie

### PR DESCRIPTION
**Pull request by wilkox**
Re #300, adds visual (inline SVG) for electromagnetic and/or audible frequency ranges.
image

### CODE REVIEW

**Comment by wilkox** [comment]
With 4a83ca4: marker label goes away and frequency range names are abbreviated on smaller screens.
img_1869

**Comment by wilkox** [comment]
6493841 adds a workaround for the Firefox problem (simply hides the marker tag and label).

**Comment by jagtalon** [comment]
@wilkox nice nice! Will check it out!

**Comment by jagtalon** [comment]
:+1:

**Comment by wilkox** [comment]
:D Thanks everyone

**Pull request merged**
