### PR TITLE
Updated Root Calculator to structure answer and fixed other bugs

### PR DESCRIPTION
**Pull request by kfloey**
This commit fixes the bug described in issue #1019

The IA now uses the structured answer format and removes the simplified answer in the parentheses for whole number answers
screenshot from 0000-00-00 00 00 00

but not for answers that are not whole numbers
screenshot from 0000-00-00 00 00 00

- [x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [x] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [x] Tested cross-browser compatibility

### CODE REVIEW

**Comment by kfloey** [comment]
@mintsoft @moollaza I still need to fix the negative square root bug, but this is my progress so far

**Comment by mintsoft** [comment]
@kfloey I like that, looks like the best of both worlds to me

**Comment by kfloey** [comment]
@moollaza Everything is working as it should; I fixed the bug for negative root.

screenshot from 2015-02-28 10 47 04

**Comment by moollaza** [comment]
@kfloey looks great!

I noticed a couple other problems which are separate from this. You're welcome to fix them in this PR, otherwise I'll make a new issue for it:

2015-02-28_11h34_04
2015-02-28_11h33_18

**Comment by kfloey** [comment]
@moollaza for each of the above issues is the desired output the `sqrt(-100+12)` and `sqrt(100-34)`?  Or are you looking for `sqrt(-100)+12` and `sqrt(100)-34`.  

For bugs, I also noticed that the regex used to control the trigger some work. For example:

screenshot from 2015-02-28 12 11 16

Also, try adding any word in front of square root of "number" (Try: `foo square root of 9`) and duckpan returns an error. I don't think that will show an error to the users, but I doubt DDG want buggy code...

**Comment by mintsoft** [comment]
@kfloey I think @moollaza expects `sqrt(100-34)` for the second one. 
Personally for `negative 100 +12` its exactly what i'd expect, `negative (100+12)`. Maybe @moollaza expected `sqrt(12-100)` i.e. `sqrt(-88)`?

**Comment by kfloey** [comment]
@moollaza I was wrong about the regex needing work.  The reason that those bugs are occurring is because the `str2nbr` function does not support those inputs...

**Comment by kfloey** [comment]
@moollaza @mintsoft Is there a reason this goodie has not been merged with the Calculator goodie.  I would think that some of the things we would want done in the CalcRoots.pm would overlap with the Calculator.pm a little bit.

**Comment by mintsoft** [comment]
@kfloey Good point, Calculator hasn't got any support for handling of radicals or rationals etc currently, it's only doing simplistic decimal calculations. I don't think there'd be any objection to the idea of extending it to support such things if you wanted to etc, it's just never been done!

**Comment by moollaza** [comment]
> I don't think there'd be any objection to the idea of extending it to support such things if you wanted to etc, it's just never been done!

100% agreed! I think there's lots of room to improve the calculator.pm module.

------

Something I pointed out to the team that we briefly discussed though was moving the calculator to the frontend using a lib like [Math.js](http://mathjs.org/) which comes with more functionality than we currently offer, plus it's extensible so we could easily add additional modules to it. 

Any thoughts on that? One big benefit is that we could then easily allow for an interactive calculator

**Comment by moollaza** [comment]
@kfloey @mintsoft sorry I missed the above comments. I was assuming `sqrt(-88)` and `sqrt(100-43)` but it's totally fair that the specified order is ambiguous. I think in either case we parsed this wrong?

On the topic of the calculator IA (and this one) I recently discovered Mathjs.org, which provides a relatively comprehensive (and extensible) library for handling Math equations.

I'll be speaking with the team about moving the calculator (and conversions, which Mathjs supports) to the frontend, so we should probably pause on this until we figure out where we're headed.

Any thoughts or opinions on that?

**Comment by kfloey** [comment]
>Any thoughts on that? One big benefit is that we could then easily allow for an interactive calculator

@moollaza I think that using Math.js would be a great idea.  It seems to have a really well documented site and lots of features.  I've remember seeing at least a few requests for an interactive calculator on the community platform, and I personally believe a better front end Calculator UI would be a lot more efficient and easier to use for DDG users compared to the current calculator IA.


>I'll be speaking with the team about moving the calculator (and conversions, which Mathjs supports) to the frontend, so we should probably pause on this until we figure out where we're headed.

Unless you wanted to merge this so the structured answer for CalcRoots would be live until more progress is made, I see no reason to continue working on this for now, especially if you'll be using Math.js in the future.

**Comment by moollaza** [comment]
This LGTM :+1: 

Not sure how soon Math.js will be coming along.

**Pull request merged**
