### PR TITLE
Add spaces to improve legibility

### PR DESCRIPTION
**Pull request by vikashvverma**
IA Page: [ https://duck.co/ia/view/solar_system_cheat_sheet](https://duck.co/ia/view/solar_system_cheat_sheet)

Resolves https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2230

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=solar system cheatsheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/solar_system_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=solar system cheatsheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/solar_system_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@vikashvverma Thanks! This LGTM :+1:

**Pull request merged**
