### PR TITLE
Github Atom cheat sheet

### PR DESCRIPTION
**Pull request by stanly-johnson**
**What does your Instant Answer do?**
Displays Github atom shortcut keys

**What is the data source for your Instant Answer? (Provide a link if possible)**
ShortcutWorld - http://www.shortcutworld.com/en/linux/Atom-%28text-editor%29_1.0.html

**Why did you choose this data source?**
Most extensive one found online

**Are there any other alternative (better) data sources?**
Nope

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Programmers

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No

**Where did you hear about DuckDuckHack? (For first time contributors)**
Github

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screenshot from 2015-08-26 02 37 01
screenshot from 2015-08-26 02 37 09

### CODE REVIEW

**Comment by seisfeld** [comment]
This one looks like a duplicate of #1419. Maybe these can be merged/coordinated?!

**Comment by rhea-ahuja** [comment]
@MrChrisW This is an already Submitted PR which is totally completed have a look at #1419

**Comment by stanly-johnson** [comment]
#1419 and this commit contain different information. I suggest merging the two files.

**Comment by namandistro** [comment]
@stanly-johnson hey, I saw your changes you added some extra commands so I can even do is add your commands to mien so we can closw this request?

**Comment by namandistro** [comment]
@stanly-johnson I just went through all your PR just wanna recommend make separate branches for diffr IA coz you just pulled 4 files with this one req. I hope you understand what I mean.

**Comment by stanly-johnson** [comment]
@namandistro I'm ok with you adding the extra info to your cheatsheet. And thanks, I did create seperate pull requests, the above ones were created by error.

**Comment by namandistro** [comment]
@stanly-johnson Added your code you can close this pull!

**Comment by moollaza** [comment]
@stanly-johnson @namandistro @seisfeld sorry for getting to this late, thanks a lot for working together and combining efforts. Really appreciate it!

I'll close this PR.

**Pull request closed without merging**
