### PR TITLE
Bash Primary Expressions: Use title/subtitle layout

### LINKED ISSUE #2299: Bash Primary Expressions: Convert to text template, use title/subtile layout
This IA was recently converted to template, but could be further improved by using a more canonical Title/Subtitle design.

Seeing as this one has `pre` blocks, it mean the title/subtitle will need to use `title_content` and `subtitle_content` sub-templates (title.handlebars and subtitle.handlebars)

For a query like `bash if [[ "abc" -lt "cba" ]]` the result should look like:

> **true if `"abc"` is numerically less than `"cba"`**
> Bash expression: `[[ "abc" -lt "cba" ]]`

---

IA Page:  http://duck.co/ia/view/bash_primary_expressions

### PR DESCRIPTION
**Pull request by analyticalmonk**
**Fixes #2299.**
Used a title/subtitle layout as outlined by @moollaza in the issue description.

https://duck.co/ia/view/bash_primary_expressions

### CODE REVIEW

**Comment by daxtheduck** [comment]
@analyticalmonk Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
Hiya @analyticalmonk thanks for the PR. 

Whilst you've almost achieved the look @moollaza was referring to, I believe he was hoping the implementation would use the `title` and `subtitle` subtemplates: http://docs.duckduckhack.com/frontend-reference/subtemplates.html

**Comment by moollaza** [comment]
> Whilst you've almost achieved the look @moollaza was referring to, I believe he was hoping the implementation would use the title and subtitle subtemplates:

Correct!

**Comment by GuiltyDolphin** [comment]
See my comment on #2657 on why I'm closing this - I think we should work on the solution over there.

**Comment by moollaza** [comment]
@analyticalmonk thanks again for trying to improve the Bash Primary Expressions Goodie! You did a really good job here and we'd like you to help our community tackle the next big challenge - our mission to become the best search engine for programmers: https://duck.co/blog/post/297/help-for-programmers.

When you're ready to move on, please: 

- Create a new Instant Answer to increase our Programming IA coverage

OR

- Test live programming Instant Answers (or those in development) for bugs and suggest improvements 

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage).

Thanks again!

**Pull request closed without merging**
