### PR TITLE
New BMI calculator Instant Answer

### PR DESCRIPTION
**Pull request by alexg11100**
https://duck.co/ia/view/bmi_calculator

### CODE REVIEW

**Comment by daxtheduck** [comment]
@alexg11100Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@alexg11100 We already have a [bmi calculator](https://duck.co/ia/view/interactive_bmi_calculator) in progress - but we currently need a front-end: would you be interested in implementing it? https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2118

**Comment by alexg11100** [comment]
@GuiltyDolphin Sorry about that I didn't notice there was already one in progress. I'm afraid my front-end skills aren't quite up to scratch but thanks for the offer.

**Pull request closed without merging**
