### PR TITLE
New JavaDoc cheat sheet

### PR DESCRIPTION
**Pull request by AdiChat**
## New JavaDoc Cheat Sheet

This PR creates a cheat sheet listing the various JavaDoc tags.

 _Javadoc_ is a documentation generator created by Sun Microsystems for the Java language (now owned by Oracle Corporation) for generating API documentation in HTML format from Java source code. The tags are used for this purpose.

Check out the cheat sheet : [here](https://beta.duckduckgo.com/?q=javadoc+cheat+sheet&ia=cheatsheet&iax=1)

Cheat Sheet page : [here](https://duck.co/ia/view/javadoc_cheat_sheet)

Developer and Maintainer: [**AdiChat**](https://github.com/AdiChat)

---
https://duck.co/ia/view/javadoc_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@AdiChat Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/javadoc_cheat_sheet_mobile.png?qstSHAu1AV)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=javadoc cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/javadoc_cheat_sheet_mobile.png?GCmDzurHdE)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=javadoc cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/javadoc_cheat_sheet_mobile.png?dj3ZbPVxOR)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=javadoc cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/javadoc_cheat_sheet_mobile.png?6Mare59Uyf)

**Comment by marti1125** [comment]
Hi @AdiChat  If you have more ideas or some IA you would like contribute. I suggest you visit ;)
https://forum.duckduckhack.com/c/programming/java

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=javadoc cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/javadoc_cheat_sheet_mobile.png?HdCKaTkD1n)

**Comment by AdiChat** [comment]
@marti1125 Looks good. :+1:

**Comment by daxtheduck** [comment]
@AdiChat this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
