### PR TITLE
DuckDuckGo: fix link to Tor onion service

### PR DESCRIPTION
**Pull request by rahiel**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer
  - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [x] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

The Tor link was not an onion link, but a link to an onion proxy. It's replaced with the actual hidden service.
###### Which issues (if any) does this fix?

Fixes #NNNN - how specifically does it fix the issue?
###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/duck_duck_go

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
@rahiel Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by rahiel** [comment]
Hey @moollaza (pinging you because you had the last commit on the repo), could you review this? The link currently served by this IA has been wrong for a long time now.

The correct link is `http://3g2upl4pq6kufc4m.onion` as is also shown on [Wikipedia](https://en.wikipedia.org/wiki/DuckDuckGo) and on the [founder's blog](https://web.archive.org/web/20101231132520/http://www.gabrielweinberg.com/blog/2010/08/duckduckgo-now-operates-a-tor-exit-enclave.html).

Currently the IA is linking to `http://3g2upl4pq6kufc4m.onion.link`, notice that this is a subdomain of `onion.link`, a domain that has no association with DDG. It certainly is not DDG's hidden service.

**Comment by pastly** [comment]
DuckDuckGo should not be encouraging the use of tor2web proxies as they are dangerous for user anonymity. They are a huge single point of trust and possibly failure

If the user is using Tor Browser: using a tor2web link is not only redundant (traffic goes over Tor twice), it is dangerous. The tor2web proxy is able to tell what the user's query was and what the results were.

If the user is _not_ using Tor Browser: it's even worse. In addition to the above, the tor2web proxy will know __who__ is making these search queries. There is zero benefit for a user not using Tor Browser to use a tor2web proxied ddg onion service over regular ddg.

I'm pinging @bsstoner because they are the maintainer according to ddg.

This seems like a simple fix with great benefit for user anonymity.

**Comment by bsstoner** [comment]
It's irrelevant though I guess, this is the right link. 👍

**Comment by bsstoner** [comment]
Thanks @rahiel and @pastly for pinging us on this.

**Pull request merged**
