### PR TITLE
Port Emacs Cheat Sheet to json format.

### PR DESCRIPTION
**Pull request by punchagan**
Finishes the remaining part of #1155

### CODE REVIEW

**Comment by zekiel** [comment]
thanks @punchagan  :) We'll get to this asap!

**Comment by javathunderman** [comment]
ping @moollaza

**Comment by moollaza** [comment]
@punchagan This LGTM :+1: 

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Comment by punchagan** [comment]
@moollaza Thanks for merging it! 

I've been a regular user of duckduckgo for the last couple of years or so, though I never contributed before. I saw a tweet for help with Emacs related stuff, and jumped onto it! :) I'm going to look around and see if I find anything else I can help out with!

**Comment by moollaza** [comment]
@punchagan sorry for the late notice but these changes are live!

https://duckduckgo.com/?q=emacs+cheat+sheet&ia=cheatsheet

**Comment by punchagan** [comment]
@moollaza Thanks for the notice! Cool to see them live!

**Pull request merged**
