### PR TITLE
New JavaScript Goodie

### PR DESCRIPTION
**Pull request by jrswab**
## Description of new Instant Answer, or changes
This give a direct answer to the question/search "how to make comments in javascript".
https://duck.co/ia/view/display_javascript_comment_syntax

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/{ID}

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by kirkins** [comment]
I think allowing such a small Goodie would be a slippery slope. If this why not have a Goodie for every common question about language X.

It's also packaged as a cheat sheet, which traditionally should be a set of commands or rules surrounding something.

I recommend adding this to the existing [Javascript cheat sheet ](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/javascript.json)and making a pull request to add it there.

**Comment by jrswab** [comment]
@kirkins That makes sense and undstand the need for that. I just noticed that when searching for that on DDG it gave some instant answer from stackoverflow that did not really answer said question. I'll think of another goodie to add that is not already a part of a cheat sheet.

**Comment by kirkins** [comment]
I absolutely agree with you on that. The answer returned from stackoverflow is way off.

**Comment by jrswab** [comment]
@kirkins is there a better way for me to go about something like this?
Maybe have a cheat sheet of a bunch of common characters and what they do?

**Comment by kirkins** [comment]
I think that would be ok, a lot of the language sheets seem to just reference functions but the [R cheat sheet ](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/r.json#L33)seems to be alone the lines of what you're suggesting.

You can call it javascript syntax as opposed to the one I linked which seems to be focused on methods.

**Comment by jrswab** [comment]
@kirkins Awesome, thank you good sir! Is there anything I need to do on my end for to cancel or remove this pull?

**Comment by kirkins** [comment]
There should be a close pull request button beside the comment button. 

Will keep an eye out for your next PR. 👍

**Comment by jrswab** [comment]
😄 Thanks @kirkins I've been using DDG since before DDH was even a thing and feel it's time I give back ❤️ See you around Git!

**Comment by kirkins** [comment]
@benabrahamson also could run the json file through [this beautifier](https://duckduckgo.com/?q=json+beautifier&atb=v56-6_a&ia=answer) with indent set to 4.

**Pull request closed without merging**
