### PR TITLE
Optimize Chinese Dynasties Cheat Sheet

### PR DESCRIPTION
**Pull request by eflyjason**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`{Chinese Dynasties Cheat Sheet}: {Optimize Chinese Dynasties Cheat Sheet}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

- Add space between Chinese character and English name.

- Add name in Traditional Chinese for some dynasty/period

---

Instant Answer Page: https://duck.co/ia/view/chinese_dynasties_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by javathunderman** [comment]
Any thoughts @moollaza?

**Comment by zekiel** [comment]
@javathunderman  do you need any particular type of help or review? If you agree w/ the changes or need some extra eyes, we can try promoting it in the community.

**Comment by javathunderman** [comment]
@zekiel Looks all good to me. We can open this up to the community for input though.

**Comment by mintsoft** [comment]
@javathunderman @zekiel It's largely just whitespace changes so :+1:

**Pull request merged**
