### PR TITLE
Indian Spices Cheat Sheet

### PR DESCRIPTION
**Pull request by shahbaz17**
https://duck.co/ia/view/indian_spices_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=hindi spice name cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/indian_spices_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@shahbaz17 Thanks! This LGTM :+1:

**Comment by shahbaz17** [comment]
Thanks @moollaza

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=hindi spice name cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/indian_spices_cheat_sheet_mobile.png)

**Comment by edgesince84** [comment]
@shahbaz17,  thanks again for fixing the Indian Spices Cheat Sheet! You’ve been doing a really good job here and we'd like you to help make DuckDuckGo even better for yourself and others interested in Indian spices.

When you're ready to move on, please: 

- Create a new Instant Answer for searches you do related to Indian foods / cooking 

OR

- Test live spices / cooking Instant Answers (or those in development) for bugs and suggest improvements

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Creating-or-Improving-Instant-Answers).

Thanks again!

**Comment by shahbaz17** [comment]
Hello DDG,
How about creating a cheat sheet where there will be steps to make a dish.
A Dish such as Biryani,Paneer Butter Masala etc .
Because people here search about " How to make any dish regularly " on
youtube and Google.
I thought this would be also good for DDG.
Eg. If you search for " How to make Kahwa ? " (a special kind of tea made
in Jammu & Kashmir)

Then the output should show in Steps with the ingredients involved .

**Comment by shahbaz17** [comment]
The Output of the earlier search. How to make Kahwa ?

Kahwa Recipe
Kahwa is a popular refreshing beverage. It provides instant relief from
headache. Learn how to make/prepare Kehwa by following this easy recipe.

*Ingredients:*

   - 4 Cups water
   - A pinch of Cinnamon (dalchini)
   - 1/2 tsp Fresh kashmiri green tea, crushed
   - 2 Green cardamoms, crushed
   - 3-4 Almonds, shredded
   - 4 strands Saffron, crushed
   - Sugar to taste


*How to make Kahwa:*

   - Pour water in a vessel.
   - Add crushed green tea leaves and cinnamon.
   - Bring to boil.
   - As soon as it boils, add saffron & sugar to taste.
   - Add cardamoms and shredded almonds.
   - Cover and boil for a few minutes.
   - Remove from the flame.
   - Kehwa is ready to drink.

**Comment by moollaza** [comment]
> How about creating a cheat sheet where there will be steps to make a dish.

Hi @shahbaz17, I think a single cheat sheet dedicated to a single recipe is too niche. A better approach would be a Spice that handles recipes for Indian foods so that we can cover more queries with a single Instant Answer.

Another approach could be to build a cheat sheet for several popular Indian drinks/teas like the new Classic Cocktails cheat sheet: https://beta.duckduckgo.com/?q=classic+cocktails+cheat+sheet&ia=cheatsheet&iax=1

**Pull request merged**
