### PR TITLE
Conversions: Fix #2041

### LINKED ISSUE #2041: Conversions: After 14 decimals places, scientific notation no longer used?
This behaviour seems like a bug?

Lower limit (6 0's): https://duckduckgo.com/?q=3000+km+to+m&t=ffab&ia=answer

https://duckduckgo.com/?q=30000+km+to+m&t=ffab&ia=answer

Upper limit? (14 0's): https://duckduckgo.com/?q=300000000000+km+to+m&t=ffab&ia=answer

https://duckduckgo.com/?q=3000000000000+km+to+m&t=ffab&ia=answer

/cc @mintsoft 

-----
IA Page: https://duck.co/ia/view/conversions

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
Fixes an issue with scientific notation.

-----
IA Page: https://duck.co/ia/view/conversions

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@mintsoft I've modified the `NumberStyle` a tiny bit to use `Math::BigFloat` for converting to decimal notation.

Before it was using `sprintf("%f", ...)` which was only allowing a few decimal places before the cut-off. Using `Math::BigFloat` should allow arbitrary (40 default?) precision.

**Comment by mintsoft** [comment]
@GuiltyDolphin Sounds like a good move to me

**Comment by moollaza** [comment]
Deploying to beta...

**Comment by moollaza** [comment]
Whoops, no IA page link! Adding on in..

**Comment by moollaza** [comment]
Deploying again...

**Comment by mintsoft** [comment]
@moollaza I've given this a quick run around and it looks good to me; the problem seems solved

**Comment by GuiltyDolphin** [comment]
@moollaza I think this one's done.

**Comment by GuiltyDolphin** [comment]
@moollaza @mintsoft Bump.

**Comment by mintsoft** [comment]
@GuiltyDolphin @moollaza I think this still isn't deploying to beta properly: https://beta.duckduckgo.com/?q=300000000000000000+km+to+mm&ia=answer

**Comment by GuiltyDolphin** [comment]
@mintsoft Oh! We had to take it down recently because it conflicts with some changes to the Calculator.

**Comment by GuiltyDolphin** [comment]
@mintsoft If you're happy with this then I'd say it's good to merge - you managed to get a look at it one Beta before, right?

> I've given this a quick run around and it looks good to me; the problem seems solved and I can't find any regressions

I don't think the Calculator will be off Beta for a while, so I don't think we'll be able to re-deploy.

**Comment by mintsoft** [comment]
@GuiltyDolphin It looks fine to me, I've given it a runaround on my local duckpan it seems OK

**Pull request merged**
