### PR TITLE
New US State Capitals Cheat Sheet

### PR DESCRIPTION
**Pull request by novavex**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New US State Capitals Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

---

Instant Answer Page: https://duck.co/ia/view/us_state_capitals_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
@novavex Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
@moollaza I think this one can't be accepted.  If we include cheatsheets like this one,  we must accept all the place related cheatsheets.  Since their are hundreds of countries,  states and capitals its impossible to maintain.

**Comment by moollaza** [comment]
> @moollaza I think this one can't be accepted.

@gautamkrishnar regardless, this is unrelated to [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53) and so it should be ignored. Our focus right now is entirely on the Mission, all other PR's that are not essential are currently being ignored.

More details are in the message Dax has been posting: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3711#issuecomment-255587071

/cc @duckduckgo/community-leaders

**Comment by moollaza** [comment]
@novavex I'm sorry but we can't accept this PR right now.

Can I ask how you came to make this? Were you aware that our focus is on the Programming Mission?

If not, would you be interested in getting involved in the mission?

**Pull request closed without merging**
