### PR TITLE
Updated word list for passphrases goodie - fixes:#3510

### PR DESCRIPTION
**Pull request by gautamkrishnar**
Improved word list. Added words from https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases

fixes:#3510 

---

Instant Answer Page: https://duck.co/ia/view/passphrase

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hunterlang

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Thanks for taking this up so quickly @gautamkrishnar! Looks good to me. I'll just see if there are any review comments and if not, should be fine to merge.

**Comment by tagawa** [comment]
@moollaza I'm getting the same answer each time ("indian loyalty fight differ" when it's supposed to be random, even on a different device and on a different network: 
https://beta.duckduckgo.com/?q=random+passphrase&ia=answer

The code itself hasn't changed, only the word list, and the live IA is fine. Any ideas why this is happening? Is beta doing some sort of server-side caching?

**Comment by gautamkrishnar** [comment]
@moollaza please review this one...

**Comment by tagawa** [comment]
Apparently this is because the we're not seeding the random number generator. There's an issue for this: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3509

**Comment by gautamkrishnar** [comment]
@tagawa can we merge this one?

**Comment by gautamkrishnar** [comment]
@tagawa @moollaza @mintsoft Any update on this PR?

**Comment by moollaza** [comment]
@gautamkrishnar Thanks! This LGTM :+1:

It would be good to give credit somehow to the EFF for that list. Perhaps a comment in the code, or the file itself

**Comment by gautamkrishnar** [comment]
Thanks @moollaza :smile:

**Pull request merged**
