### PR TITLE
Created personal "Is Awesome" and Cheatsheet for Copy and Paste to Match Style on a Mac

### PR DESCRIPTION
**Pull request by AcriCAA**
**What does your Instant Answer do?**

Cheatsheet that shows the the key combination to paste and mac style on a mac. I am also requesting that my personal "Is Awesome" be made live. 

**What is the data source for your Instant Answer? (Provide a link if possible)**

https://support.apple.com/en-us/HT201236

**Why did you choose this data source?**
It's Apple's support page.

**Are there any other alternative (better) data sources?**
No. 

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

Digital Copywriters

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

No. 

**Are you having any problems? Do you need our help with anything?**
Don't think so.

**Where did you hear about DuckDuckHack? (For first time contributors)**
Zac

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screen shot 2015-08-04 at 1 05 06 pm

### CODE REVIEW

**Comment by moollaza** [comment]
@AcriCAA thanks a lot for contributing, we really appreciate it!

Can you please separate this into two separate PR's though? PR's that add new IA's can only add 1 IA at a time.

**Comment by moollaza** [comment]
The isAwesome is really meant as a tutorial for you. We're hoping to refrain from adding new ones to production (because they don't really add any value) but I can add it if you split it into a new PR. If you don't care to see the IsAwesome go live, then you can just remove it from this PR and I'll be able to review and merge your cheat sheet

**Comment by moollaza** [comment]
@AcriCAA actually now that I see your cheat-sheet -- do you have any more content for it? Or perhaps a wider topic that this info fits under? The idea is that cheat sheets should contain lots more information and sections. Checkout the tmux cheatsheet to see a good example: https://duckduckgo.com/?q=tmux+help&t=ffab&ia=cheatsheet

**Comment by AcriCAA** [comment]
Sure. I'll covert it to all Mac keyboard shortcuts.

**Comment by moollaza** [comment]
>Sure. I'll covert it to all Mac keyboard shortcuts.

Sweet, thanks!

**Comment by moollaza** [comment]
Shoot! I just realized we actually have a Mac keyboard shortcut Instant Answer. Please check if there's anything missing from it that you'd like to add!

https://duckduckgo.com/?q=mac+keyboard+shortcuts&t=fpas&ia=cheatsheet

**Comment by AcriCAA** [comment]
Yes. That's what this is. It's the existing Mac keyboard cheat sheet that
was in the repo but I just added the document shortcuts.

**Pull request closed without merging**
