### PR TITLE
New Indian States Cheat Sheet

### PR DESCRIPTION
**Pull request by sinwar**
This is the cheat sheet for the list of capitals of indian states-
indianstatesless

### CODE REVIEW

**Comment by daxtheduck** [comment]
@sinwar Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by sinwar** [comment]
Thanks @daxtheduck

**Comment by moollaza** [comment]
@sinwar thanks a lot for contributing, we really appreciate it!

Unfortunately though, this Instant Answers already exists!

You can see it here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/states-of-india.json

It looks like it could be improved by adding an `"alias"` for the phrase "indian states" so that it will trigger on the query "indian states cheat sheet"

**Comment by sinwar** [comment]
Ohh! I didn't search it.
Thanks @moollaza

**Pull request closed without merging**
