### PR TITLE
Dewey: Fix #1163 (move to template)

### LINKED ISSUE #1163: Convert HTML Goodies to use templates
Many legacy Goodies return HTML strings for rendering. This was previously acceptable as we did not have access to the Handlebars templates used in every Spice IA.

Now that we have templates, we should convert all Goodies returning HTML into templated Goodie that ideally won't need to actually declare any HTML! We have many built-in templates and most IA's can leverage these by specifying only the data and letting our template system do the rest of the work.

In some cases the use of a Handlebars sub-template is necessary and acceptable. In rare cases a custom template is required and we now support that (but please check with us first to make sure its absolutely necessary!)

Let's cleanup our Goodies and hopefully simplify them by moving to our new templates!

Details on template usage can be seen here: https://duck.co/duckduckhack/goodie_displaying

Note: Goodies also support JS and CSS now, which means we should remove any inline scripts and styles and if necessary, move them to separate CSS and JS files.

Here's a list of the existing IA's which return HTML:
- [x] Average.pm
- [x] BashPrimaryExpressions.pm
- [x] BinaryLogic.pm
- [x] BloodDonor.pm
- [x] CalendarToday.pm
- [x] Chess960.pm
- [x] ChineseZodiac.pm
- [x] ColorCodes.pm
- [x] ConvertLatLon.pm
- [x] CrontabCheatSheet.pm
- [x] CryptHashCheck.pm
- [x] CurrencyIn.pm
- [x] Cusip.pm
- [x] Dessert.pm
- [ ] Dewey.pm
- [x] Dice.pm
- [ ] FenViewer.pm
- [x] FIGlet.pm
- [ ] Frequency.pm
- [ ] FrequencySpectrum.pm (this one sorely needs conversion! It should move the styles and scripts into a CSS file and a [x] JavaScript file)
- [x] GoldenRatio.pm
- [x] GuitarChords.pm
- [x] HTMLEntitiesDecode.pm
- [x] HTMLEntitiesEncode.pm
- [ ] IDN.pm
- [x] IndependenceDay.pm
- [ ] IPS.pm
- [ ] JsKeycodes.pm ( there is a Spice PR which will convert this to use JS -- technically it could remain a Goodie and do [x] this...)
- [ ] KernelTaint.pm
- [ ] Latex.pm
- [ ] Loan.pm
- [ ] NameDays.pm
- [ ] NLetterWords.pm
- [ ] Palindrome.pm
- [x] PercentError.pm
- [x] Phonetic.pm
- [ ] Poker.pm
- [x] PrimeFactors.pm
- [x] PrivateNetwork.pm
- [x] PublicDNS.pm
- [ ] Randagram.pm
- [x] RandomName.pm
- [x] ResistorColors.pm
- [x] ReverseResistorColours.pm
- [ ] RouterPasswords.pm (currently offline -- should be converted to Fathead!)
- [x] RubiksCubePatterns.pm
- [ ] Shortcut.pm
- [x] SubnetCalc.pm
- [x] Sudoku.pm
- [x] SumOfNaturalNumbers.pm
- [x] SunInfo.pm
- [x] Teredo.pm
- [x] TimezoneConverter.pm
- [x] Tips.pm
- [x] UN.pm
- [x] Unicode.pm
- [ ] UnicodeFuzzySearch.pm
- [x] Unicornify.pm
- [ ] Unidecode.pm
- [x] UnixPermissions.pm
- [x] UnixTime.pm
- [x] Uptime.pm
- [x] VIN.pm
- [ ] Week.pm

---

If you'd like to work on converting any of these, please post below to let us know!

Thanks guys :smile:

### PR DESCRIPTION
**Pull request by AlterationBrick**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [x] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Change from displaying an html table to returning a list template.

###### Which issues (if any) does this fix?

Ref #1163 by removing html tags from goodie.

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/dewey

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @navneetzz

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gaulrobe** [comment]
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/Dewey.t will need to be updated here too

**Comment by AlterationBrick** [comment]
Hey all,
This is clearly unfinished. I'd appreciate input on:
- how to do links
- my idea of making the answer a key-val thing instead of sentences
Yes, I know the checks fail and the code is heavily commented.

**Comment by tagawa** [comment]
@AlterationBrick I'm not sure about links in the templates - probably using a handlebars file (I'd have to check) - but we probably don't need to include a link anyway. Currently, it just links to a general search for the Dewey category, e.g. "household", which I don't think is relevant for the user.

The key-value idea is good in my opinion. List results seem to work similar to this anyway: https://duckduckgo.com/?q=etymology%20in%20the%20dewey%20decimal%20system&ia=answer

And the comments are helpful - no need to apologise!

**Comment by AlterationBrick** [comment]
@tagawa Then I guess I could clean up the dewey.txt source file to get rid of the links, though I want to know what @crazedpsyc thinks.

**Comment by tagawa** [comment]
Thanks @AlterationBrick. For the missing topics, you could include it in this PR or just leave it this time and make an issue for it to be looked at separately - whichever suits you best.

**Comment by AlterationBrick** [comment]
If anyone's interested in taking up the task of changing the dewey.t file, I've reached a dead end trying to get it to work, and besides, I'm now doing a lot of coding for a summer job, so I'd rather spend less of my free time staring at error messages. The test file just needs to accomodate `structured_answer`, and not look for html.

**Comment by mintsoft** [comment]
@AlterationBrick I'll finish this off you; I'll cc you in so you can see what I did

**Comment by mintsoft** [comment]
Commits merged into: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3342

**Comment by tagawa** [comment]
@AlterationBrick Thank you very much for battling on and getting this far. Good luck with the summer coding!
And @mintsoft - thanks for picking it up so quickly.

**Comment by tagawa** [comment]
@AlterationBrick Ha, I know what you mean! I'm still hoping I won't get found out...

**Pull request closed without merging**
