### PR TITLE
Malayalam Language cheat sheet

### PR DESCRIPTION
**Pull request by gautamkrishnar**
New Malayalam Language cheat sheet...

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata post coming soon

**Comment by gautamkrishnar** [comment]
@jophab need your reviews

**Comment by gautamkrishnar** [comment]
@moollaza check this out

**Comment by jophab** [comment]
@gautamkrishnar there is already one malayalam cheat sheet #1850 which is near ready to merge.

**Comment by gautamkrishnar** [comment]
@jophab thnks :+1: my bad... :smile: closing this now...

**Comment by jophab** [comment]
@gautamkrishnar Lets make this a Hindi cheat sheet :+1: 
what do you say?

**Comment by gautamkrishnar** [comment]
@jophab i dont know hindi :stuck_out_tongue_winking_eye:

**Comment by jophab** [comment]
@gautamkrishnar yeah..i will have a try :+1:

**Pull request closed without merging**
