### PR TITLE
New Yarn Cheat Sheet

### PR DESCRIPTION
**Pull request by tricinel**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New Yarn Cheat Sheet`**

###### Description of changes

What changes does this PR introduce? 
Adding a cheat sheet for yarn, the new Javascript package manager. More info about yarn [here](https://yarnpkg.com/).

Screenshot
yarn-screenshot

---

Instant Answer Page: https://duck.co/ia/view/yarn_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tricinel

### CODE REVIEW

**Comment by daxtheduck** [comment]
@tricinel Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@tricinel this LGTM @tagawa @moollaza any idea why this hasn't deployed? The tests were failing due to metadata being stale, I've repushed those and played with the labels which normally tricks it, but no luck thus far

**Comment by tricinel** [comment]
@mintsoft Don't know :) Is there anything you guys need from me?

**Comment by akanshgulati** [comment]
@mintsoft I added the community review tag because it looked great to me but again as its a new package manager, I was looking for more reviews on it. You are right, it should be deployed on beta.

**Comment by rasikapohankar** [comment]
Hey @mintsoft, I had noticed that changing the title on another PR had caused it to get deployed, tried the same here! It has requested a deployment, I don't know how changing the title is related though :sweat_smile:

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=yarn cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/yarn_cheat_sheet_mobile.png?Mm418hC61t)

**Comment by daxtheduck** [comment]
@tricinel this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
