### PR TITLE
Pokemon GO cheat sheet: Added tips and key levels

### PR DESCRIPTION
**Pull request by tagawa**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [X] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [X] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Added new sections for "Tips" and "Key Levels"

###### Which issues (if any) does this fix?

None

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/pokemon_go_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tagawa

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
@jdorweiler Hi. I've made a few udpates to this live cheatsheet and deployed to beta. It seems to have worked - no error messages - but the changes are not visible in the beta server version, for example the new "Tips" section. Any ideas?

**Comment by jdorweiler** [comment]
@tagawa looks okay now? There were some problems with the goodies repo that were causing installs to fail.

**Comment by tagawa** [comment]
Yep, looks fine now. Thanks for the fix @jdorweiler

**Comment by GuiltyDolphin** [comment]
@tagawa Thanks! :dolphin:

**Comment by tagawa** [comment]
Ha, I forgot about my own PR! Thanks @GuiltyDolphin.

**Pull request merged**
