### PR TITLE
Molar mass

### PR DESCRIPTION
**Pull request by acampb311**
This is an incomplete version of an instant answer to calculate the molar mass of a chemical compound. Submitting a pull request after discussing with @moollaza because of an issue with using the 'share' function while loading YAML files.

https://duck.co/ia/view/molarmass

### CODE REVIEW

**Comment by daxtheduck** [comment]
@acampb311 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@acampb311 don't forget to create an IA Page for this Instant Answer and link it above ;)

**Comment by moollaza** [comment]
> an issue with using the 'share' function while loading YAML files.

@acampb311 have you added the elements.yml file to the repo yet? The share function is undefined because this IA won't be given a share function unless it has a share directory with files in it.

i.e. once you create `/share/goodie/molar_mass/elements.yml` the IA will have a share function available

**Comment by moollaza** [comment]
@acampb311 by the way, I just checked metcpan.org to see if there were any existing libraries we could leverage and it looks like http://www.perlmol.org/ might be useful. I didn't dig into it too much but it looks like `Chemistry::Pattern` may be able to parse a string into a Chemistry object and `Chemistry::Mol` may be able to calculate the Molar Mass. I'd suggest you take a look at see if it could help simplify or improve this :+1:

**Comment by moollaza** [comment]
@acampb311 Ping! I'm just checking in to see if you're still interested in finishing this one up? We'd love to see this go live!

There's absolutely no rush, just wanted to make sure you're not stuck on anything.

**Comment by edgesince84** [comment]
@acampb311, 
thanks again for working on  the Molar Mass IA! You’ve been doing a really good job here and we'd like you to help our community tackle the next big challenge - our mission to become the best search engine for programmers: https://duck.co/blog/post/297/help-for-programmers.

When you're ready to move on, please: 

- Create a new Instant Answer to increase our Programming IA coverage

OR

- Test live programming Instant Answers (or those in development) for bugs and suggest improvements 

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage).

Thanks again!

**Comment by mintsoft** [comment]
@acampb311 I'm going to close this PR for now; feel free to reopen it whenever you like :+1:

**Comment by Iambecomeroot** [comment]
What's the plan for this IA? If it is closed permanently, I am willing to work on a similar IA.

**Comment by acampb311** [comment]
@Iambecomeroot It's been a while since I took a look at this, I have been rather busy with school... The project is largely finished, the biggest remaining piece is that I am unsure about sanitizing user input and how far I had to handle things like missing parenthesis etc. If you would like, I can give you the code I have right now, this repo was just made to ask a general question and is out of date.

**Comment by acampb311** [comment]
@Iambecomeroot I just updated the version in my repository to the latest version I had in Codio. Apparently I didn't change it much. 
https://github.com/acampb311/zeroclickinfo-goodies/blob/molar_mass/lib/DDG/Goodie/MolarMass.pm

A little bit about the project (my code has very few comments and I hadn't touched Perl prior to this, so yeah).
This iteration should pull its information from the file in the DDG repo that has the elements in it. 

The recursive bit for parsing out the parenthesis is nasty. There is probably a better way to approach this problem that I was not able to think of. It just doesn't feel elegant. All that part does is find an opening parenthesis, grab the enclosed data, and call itself with the data from inside the parenthesis.

For the rest, if you have any questions, please don't hesitate to ask I'll see if I can remember what exactly my lil brain was doing at the time. 

So I took a look at the results and remembered that there were edge cases where bugs got in.
ddg1
ddg2

The first one is dead on,

The second one only distributes the hanging number onto the Pb (in this case) throwing off the result. I'd have to take a pretty deep dive into my logic to get it fixed...

If you decide to use some of my stuff as inspiration I wish you especially good luck, that's some hacky code.

**Comment by Iambecomeroot** [comment]
@acampb311 Thank you very much. I took a quick look at the code. It doesn't look too bad. I have had to work with much worse. Right now I have to study though. I will look at that in about a week.

**Comment by Iambecomeroot** [comment]
@acampb311 What would be the best way to go about this? Should I fork your fork or fork ddg's repo?

Also, do you have a better way to chat? I don't want to fill up this pr too much.

**Comment by acampb311** [comment]
@Iambecomeroot I honestly wouldn't mind at all if you just started a new repo entirely. I'm not sure how to transfer the IA page to you though. As for chat, I looked and you are on the slack channel, so I took the liberty of sending you a direct message there.

**Pull request closed without merging**
