### PR TITLE
Text Converter: Fix binary conversion bug.

### LINKED ISSUE #4513: Text Converter:  Ignore Binary to Decimal conversions greater than 11111111
I noticed that binary to decimal converter works fine only till 11111111, maybe it's a normal behavior, but it would be great to warn users instead of printing some strange values.

------

IA Page:  http://duck.co/ia/view/text_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

### LINKED ISSUE #4566: Text Converter:  Incorrect results for decimal to binary
I entered 1056760 and it gave me 1111111111000.  That is INCORRECT!  

The correct result is 100000001111111111000.

Using the incorrect result caused me some headaches, until I finally figured it out. 

I think this is an extremely serious error that could impact others as well.

I suggest you remove the bogus converter until it is repaired.   

------
IA Page:  http://duck.co/ia/view/text_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

### LINKED ISSUE #4567: Text Converter: Incorrect results for binary to hexadecimal
`101101` is converted to hex as `b1` (which is most likely because it is grouped as `1011` `01`). The numeric equivalent of that number is `2d` in hex (where the grouping should be done from right to left `10` `1101`, or left pad with two zeros before grouping from left).

------
IA Page:  http://duck.co/ia/view/text_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

### LINKED ISSUE #4570: Text Converter: incorrect conversion binary to decimal
OK (dec to bin):
 -2       ---->       1111111111111110 

UNEXPECTED (bin to dec):

1111111111111110      --->         255 254

------
IA Page:  http://duck.co/ia/view/text_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

### PR DESCRIPTION
**Pull request by vonaka**
## Description of new Instant Answer, or changes

Fixes #4513, fixes #4567, fixes #4570 and fixes #4566. For binary-to-decimal conversion we don't need to convert each byte separately. For binary-to-hexadecimal we need to go from the last byte to the first one.

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/text_converter

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@pjhampton care to review?

@vonaka can you please provide some test cases?

**Comment by vonaka** [comment]
@moollaza, sorry, but I'm not sure I understand, there is no such query for Text Converter that will bring some real value as result, I mean, one can't write _"100 binary to hex translator"_ for example ( _"100 binary to hex"_ brings us to Base Conversion ), but we can write _"binary to hex translator"_ and manually put 100 as 'argument', so I can't add any useful test, I guess. But once again, maybe I just don't understand something.

**Comment by lolo101** [comment]
Should also fix #4570

**Comment by vonaka** [comment]
@pjhampton, @moollaza, I added (lazy) fix for #4566. But I think it's a good idea to completely remove this strange and buggy Text Converter.

**Comment by pjhampton** [comment]
It's [offline](https://duck.co/ia/view/text_converter/json). I don't think it needs to be purged (from recollection, it was quite popular and what makes DDG great is being able to serve niche queries). But I don't think I would be comfortable it going live again unless there was a full unit test suite back-fitted. 

Hopefully I will get the time required at some stage to nurse this IA back to health.

**Comment by moollaza** [comment]
Deploying to Beta...

**Comment by moollaza** [comment]
@vonaka Thanks! This LGTM :+1:

**Pull request merged**
