### PR TITLE
jim-brighter's First Goodie

### PR DESCRIPTION
**Pull request by jim-brighter**
# Goodie Pull Request Template

Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**
returns "jim-brighter is awesome and has completed the first duckduckhack goodie"

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Just the first goodie from the tutorial

**What is the data source for your Instant Answer? (Provide a link if possible)**
none

**Why did you choose this data source?**
n/a

**Are there any other alternative (better) data sources?**
n/a

**What are some example queries that trigger this Instant Answer?**
duckduckhack jimbrighter

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
n/a

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
n/a

**Which existing Instant Answers will this one supercede/overlap with?**
n/a

**Are you having any problems? Do you need our help with anything?**
n/a

**Where did you hear about DuckDuckHack? (For first time contributors)**
Zac Pappis gave a tech talk at my university a few weeks ago

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screenshot 2014-12-15 23 05 49
## Checklist

Please place an 'X' where appropriate.

```
[x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[x] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [x] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by moollaza** [comment]
@jim-brighter it's live! https://duckduckgo.com/?q=+duckduckhack+jimbrighter&ia=answer

Sorry for the delay!

BTW, now that you've completed your first Goodie, we really hope you'll work on another! Feel free to check out our [Ideas Forum](https://duck.co/ideas) or look through our Github issues if you need something to work on!

**Comment by jim-brighter** [comment]
Thanks! I actually noticed this the other day when I decided to finish another one I had started a month or so ago. I'll be submitting a pull request for that one very soon.

**Comment by zekiel** [comment]
hey @jim-brighter  any way we can help you with your next IA? If you've got an idea, we'd love to help flesh it out.

**Comment by jim-brighter** [comment]
I honestly haven't really thought about it yet. My spring semester just started about a month ago and I've been pretty occupied with classes, but when I have some more free time I plan to come back to this again.

**Pull request merged**
