### PR TITLE
Added DNS records cheat sheet

### PR DESCRIPTION
**Pull request by timbadu**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [x] New Instant Answer
  - [x] Cheat Sheets: **`New DNS records Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Adds a DNS records cheat sheet to "cheat sheets"
###### Related Issues or Discussions

What issues or discussions (if any) does this PR address? Please provide the issue # or link.
###### People to notify

@mention any relevant people/organizations

---

Instant Answer Page: https://duck.co/ia/view/dns_records

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
@timbadu Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by timbadu** [comment]
I've included a link to the IA page at the bottom of my first comment.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=dns records cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/dns_records_mobile.png?1fVgEkBTh9)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=dns records cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/dns_records_mobile.png?C106VtUwyn)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=dns records cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/dns_records_mobile.png?Hpo5uny3Dy)

**Comment by pjhampton** [comment]
Thanks for this @timbadu!! It looks great! 👯 

I think maybe we can develop this a little further. I think it would be really useful to explain _what they're for_ rather than _what they are_. For example, **A Record** - _specifies which IP is assigned to a particular domain_.

What do you think?

**Comment by akanshgulati** [comment]
@timbadu your Instant Answer link has id "dns_records" while in your JSON file, the id is different due to which tests are failing. @pjhampton what will be the right way? I think a new IA should be created with cheatsheet as type.

**Comment by pjhampton** [comment]
Hey @akanshgulati 👋 

Thanks for the help 💙  ❤️  💛 . Emm, no. In this case I believe the tests failed because of something outside of the contributors control. I think we just need to rerun the test.

**Comment by sahildua2305** [comment]
Just rerun the tests, should be fine now 👍

**Comment by pjhampton** [comment]
Thanks @sahildua2305!! Let's hold back for now and let @timbadu take the cheatsheet forward.

**Comment by mintsoft** [comment]
@timbadu This looks good to me; it could be expanded with more terms if you wanted (DNAME, PTR, zone, AXFR) however it's probably fine to merge as is if you don't want to

**Comment by pjhampton** [comment]
Closing as this PR looks to have gone stale.

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄

**Pull request closed without merging**
