### PR TITLE
Conversions: Fix "Potential UPPERCASE trigger" warning

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
A one-liner to save us all pain?

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@GuiltyDolphin That will silence the errors, however technically Conversions does need support for case sensitive query handling (ms and mS are different units for example). However I'm not sure if there's any situation in which it's actually relying on the behaviour at the moment

**Comment by GuiltyDolphin** [comment]
@mintsoft I ran the tests and they seemed pretty happy, some of which have casing in their queries. I was just getting annoyed at the warning whenever I wanted to test all the Goodies together ^^

**Comment by mintsoft** [comment]
Hmm, sounds promising then; I think it'll probably be ok!

**Comment by GuiltyDolphin** [comment]
@mintsoft I'd like to discuss some stuff about the Conversions Goodie with you anyway, on Slack if we can.

**Comment by mintsoft** [comment]
@GuiltyDolphin Can do, I'm a little caught up this evening however I should be around tomorrow afternoon?

**Comment by GuiltyDolphin** [comment]
@mintsoft Sure! Until then.

**Comment by GuiltyDolphin** [comment]
@mintsoft Silence those warnings! ;)

**Pull request closed without merging**
