### PR TITLE
SHA256: Fixing cut off answers

### LINKED ISSUE #3332: SHA: When I SHA256 or SHA512 something, it gets cut off
E.g. `sha256 lol` should have `c9c1abc` after what I see below:
sha256-ddg

------
IA Page:  http://duck.co/ia/view/sha 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

### PR DESCRIPTION
**Pull request by mintsoft**
###### Which issues (if any) does this fix?

Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3332  I though this was resolved in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3196/files however I screwed that up

Looks Like:

breakfix
###### People to notify (@mention interested parties)

@tagawa @ArtskydJ

---

Instant Answer Page: https://duck.co/ia/view/sha

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
ping @jagtalon

**Comment by jagtalon** [comment]
Yas!

**Comment by jagtalon** [comment]
Thank you!

**Pull request merged**
