### PR TITLE
Security addons: Added Vivaldi to browser list

### PR DESCRIPTION
**Pull request by tagawa**
Following a [request on Twitter](https://twitter.com/arosecantrust/status/699594590379237376) I added Vivaldi do the list. It uses the same extensions as Chrome so adding it as "Google Chrome / Vivaldi" is also an option, but it wraps to the next line and looks ugly.

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@tagawa Thanks! This LGTM :+1:

**Comment by tagawa** [comment]
That was quick - thank you!

**Comment by moollaza** [comment]
@tagawa whoops! The tests are failing now -- can you please update?

**Comment by moollaza** [comment]
@tagawa I got it over in #2356

**Pull request merged**
