### PR TITLE
Apt-get: Add aliases

### PR DESCRIPTION
**Pull request by altern8tif**
Add `apt-get` and `aptget` to aliases for the apt-get cheatsheet.

-----
IA Page: https://duck.co/ia/view/apt_get_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by altern8tif** [comment]
@daxtheduck can't seem to find the IA page on (https://duck.co/ia) though.

**Comment by moollaza** [comment]
@altern8tif I'm a little behind moving completed IA's out of the pipeline -- this one was still in https://duck.co/ia/dev/pipeline --- I've added the link for you!

**Comment by moollaza** [comment]
@altern8tif Thanks! This LGTM :+1:

**Pull request merged**
