### PR TITLE
GibberishGenerator: Fix failing tests

### LINKED ISSUE #2707: GibberishGenerator: Tests randomly fail
I've just had a PR go boom with this randomly failing, if the test are executed like 20 times, then it'll fail 1-2/20:

randomtests

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
@mintsoft Fixes #2707 

---
IA Page: https://duck.co/ia/view/gibberish_generator

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@GuiltyDolphin whilst this does work to remove the random failures, it would appear that the tests no longer prove that when the user asked for french, they get french?

**Comment by GuiltyDolphin** [comment]
@mintsoft The problem was I was essentially having to check all possible characters for each 'language' - without setting the locale there doesn't seem to be a super-easy way to do this with regexes in Perl (unless I'm missing something); at least not without hard-coding everything.

I'll have another look at the code and see if I can find *all* possible characters for each 'language', then hard-code those.

**Comment by GuiltyDolphin** [comment]
@mintsoft Right, I've updated the regexes and added a few 'large' tests to improve the chances of catching errors. I've run the new tests 500 times without error - mind running it on your *(superior)* machine a bit to see if anything pops up?

**Comment by mintsoft** [comment]
@GuiltyDolphin I'll leave it running now and check on it once I get home

**Comment by GuiltyDolphin** [comment]
@mintsoft Thanks!

**Comment by mintsoft** [comment]
```
All tests successful.
Files=1, Tests=19,  1 wallclock secs ( 0.08 usr  0.00 sys +  1.26 cusr  0.04 csys =  1.38 CPU)
Result: PASS
Run: 5262
```

I'm sold I think!

**Comment by GuiltyDolphin** [comment]
@mintsoft That's quite a few runs you've done there :wink: Glad it's fixed!

**Pull request merged**
