### PR TITLE
New Erlang Cheat Sheet.

### PR DESCRIPTION
**Pull request by pjhampton**
## Erlang Cheat Sheet

https://duck.co/ia/view/erlang_cheat_sheet

### Suggested
https://duck.co/ideas/idea/6147/erlang-cheat-sheet

### Description
Erlang cheat sheet

This Pull Request is the Erlang Cheat Sheet. I consists of 9 sections:

  - Erlang Shell
  - File Types
  - Comparators
  - IO
  - Functions
  - Permutations
  - Types
  - Escape Sequences
  - Date and Time

### Data Source
No data source provided.

### Example Queries
No example queries.

### Triggers
No triggers applied.

**Screenshot 1 - Normal View (Default theme)**
screen shot 2016-02-23 at 13 10 03

**Screenshot 2 - Collapsed (Dark theme)**
screen shot 2016-02-23 at 13 07 52

### JSON Validation

The JSON has been validated at http://jsonlint.com/

### IA Page

https://duck.co/ia/view/erlang_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@pjhampton Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MrChrisW** [comment]
Hi @pjhampton thanks for the contribution, this is looking awesome! 

Are you able to update the sheet with some metadata? -  this will help a user get more information from a source website. Example:
`````
"metadata": {
     "sourceName": "Erlang",
     "sourceUrl": "http://erlang.org/"
   },
````
Cheers!

**Comment by pjhampton** [comment]
Sure thing @MrChrisW! I will update the commit soon.

**Comment by MrChrisW** [comment]
Thanks @pjhampton - LGTM :+1: 

@moollaza Can we get this deployed to beta for final review ?

**Comment by GuiltyDolphin** [comment]
@moollaza It's having some issues deploying, I think it might be due to the ID?

**Comment by moollaza** [comment]
@pjhampton @MrChrisW @GuiltyDolphin I've updated the IA Page ID and links in here

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Erlang Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/erlang_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

**Pull request merged**
