### PR TITLE
POTUS: Fixes #1863

### LINKED ISSUE #1863: POTUS: Should not trigger for "vice president of the united states"
@numbertheory 
Searching for "vice president of the united states" triggers this instant answer, giving the incorrect output of Barack Obama

------
IA Page:  http://duck.co/ia/view/potus

### PR DESCRIPTION
**Pull request by mintsoft**
Lo all,

Fixes #1863 

There're been 2 PR's for fixing this that have just died so I figured I'd just get it out of the way.

-------------------
IA Page: https://duck.co/ia/view/potus

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@mintsoft Pfft. It makes me wonder about the other 'solutions'.

**Comment by mintsoft** [comment]
@GuiltyDolphin I couldn't possibly comment.

**Comment by hemanth** [comment]
But, it's fixed for now!

**Pull request merged**
