### PR TITLE
Update intel-8085.json

### LINKED ISSUE #3115: Intel 8085 Cheat Sheet: No Link
Hello, When I am clicking the IITK website it is redirecting to a page which is giving 404. Please fix it

------
IA Page:  http://duck.co/ia/view/intel_8085_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jophab

### PR DESCRIPTION
**Pull request by jophab**
###### Which issues (if any) does this fix?

Fixes  #3115

###### People to notify @tagawa @mRse7enNIT 

Instant Answer Page: http://duck.co/ia/view/intel_8085_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Thanks for this update @jophab. Unfortunately I'm not able to load the source page: http://scanftree.com/microprocessor/Instruction-Set-In-8085
Is it working for you?

**Comment by jophab** [comment]
@tagawa Its working. but a little slow to load.
Do we need to have another source here?

**Comment by tagawa** [comment]
@jophab Oh yes, it's working for me now. OK then, that should be fine. It was probably just a temporary glitch. Thank you for improving IAs once again 😃

**Pull request merged**
