### PR TITLE
New array sorting cheat sheet

### PR DESCRIPTION
**Pull request by navneetzz**
**What does your Instant Answer do?**
My Instant answer provide reference to Big-O complexities of Array Sorting Algorithms.

**What is the data source for your Instant Answer? (Provide a link if possible)**
[Wikipedia](https://en.wikipedia.org/wiki/Sorting_algorithm)

**Why did you choose this data source?**
Because it's detailed reference to Sorting Algothims.

**Are there any other alternative (better) data sources?**
No

**Which communities will this Instant Answer be especially useful for?**
Coders and programmers

**Where did you hear about DuckDuckHack? (For first time contributors)**
Social media sites.

arraysorting

---
https://duck.co/ia/view/array_sorting_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
## [Array Sorting Cheat Sheet](https://duck.co/ia/view/array_sorting_cheat_sheet)

**Description**: Summary of Big-O time complexities for Array Sorting Algorithms

**Example Query**: [array sorting cheat sheet](https://beta.duckduckgo.com/?q=array sorting cheat sheet), [](https://beta.duckduckgo.com/?q=)

**Tab Name**: Answer

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/array_sorting_cheat_sheet)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/array_sorting_cheat_sheet)*

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=array sorting cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/array_sorting_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=array sorting cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/array_sorting_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@navneetzz Thanks! This LGTM :+1:

**Pull request merged**
