### PR TITLE
New Java Exception cheat sheet

### PR DESCRIPTION
**Pull request by AdiChat**
## New Java Exception Cheat Sheet

This PR creates a cheat sheet listing the various exceptions in Java.

Java uses exceptions to handle errors and other exceptional events. The use of exceptions to manage errors has some advantages over traditional error-management techniques.

Developer and Maintainer: [**AdiChat**](https://github.com/AdiChat)

IA page: [here](https://duck.co/ia/view/javaexception_cheat_sheet)

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@AdiChat Are you able to find any sources that we could scrape and use for a FatHead? I feel that a FatHead may be better able to answer these queries (`java ArithmeticException` etc.), most users will not be looking for a long list of each exception.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/javaexception_cheat_sheet_mobile.png?nXWcFfSvOi)

**Comment by marti1125** [comment]
Hi @AdiChat I suggest you create IA for a group of exceptions something like that http://rymden.nu/exceptions.html

The Top 10 Exception Types in Production Java 
http://blog.takipi.com/the-top-10-exceptions-types-in-production-java-applications-based-on-1b-events/

http://java2learn.com/top-10-exceptions/

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/javaexception_cheat_sheet_mobile.png?XYhyVEhZVg)

**Comment by AdiChat** [comment]
@GuiltyDolphin 
The documentation at Oracle ([here](https://docs.oracle.com/javase/7/docs/api/java/lang/Exception.html)) might be a good source to scrape data for use in a FatHead although I have not seen a complete listing of exceptions.
This is going to be a long list but I believe that it could be a useful source of information to direct users to specific FatHead results as users might not be aware of the various exceptions.

@marti1125 
Do you mean separate IA for each subtopic like `java.lang`? In that case, I should create a goodie to link to separate cheat sheets as most users _might_ tend to search `java exception cheat sheet` instead of `java rmi exception cheat sheet` and the like. 

Let me know your thoughts.

**Comment by GuiltyDolphin** [comment]
@AdiChat I don't think we want masses of cheat sheets for different exception types (a FatHead would be _much_ better suited). If you need to bump the triggering a bit you can always have a look at the `triggers.yaml` file.

**Comment by pjhampton** [comment]
Closing as this PR looks to have gone stale.

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄

**Pull request closed without merging**
