### PR TITLE
Unicode: Don't display control characters

### LINKED ISSUE #3326: Unicode: Control characters affect display of character information
Here's an example:
https://duckduckgo.com/?q=U%2B202E&ia=answer

The U+202E character is a right-to-left conversion character. When our code renders it, it writes the description right-to-left. We should make exceptions for such characters and not render them.

Affected characters, according to a [helpful tweet](https://twitter.com/FakeUnicode/status/748540297861341184), are:
U+202A
U+202B
U+202C
U+202D
U+202E
U+2066
U+2067
U+2068
U+2069

[Reported on Twitter](https://twitter.com/LucasWerkmeistr/status/748500151107469312)

---

IA Page:  http://duck.co/ia/view/unicode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cosimo

### PR DESCRIPTION
**Pull request by tagawa**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer
  - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [X] Improvement
  - [X] Bug fix: **`Unicode: Fix #3326`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Fixes bug by checking for control characters (e.g. right-to-left) and not rendering them.
###### Which issues (if any) does this fix?

Fixes #3326
###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/unicode

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cosimo

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Looks like this is not working on beta: https://beta.duckduckgo.com/?q=unicode+u%2B202e&ia=answer

**Comment by jdorweiler** [comment]
I added a link to the IA page link to the first post. Let me redeploy.

**Comment by tagawa** [comment]
Thanks @jdorweiler. Just running a deploy at the moment - should be finished soon.

**Comment by tagawa** [comment]
Yay, works now - thanks @jdorweiler! https://beta.duckduckgo.com/?q=unicode+u%2B202e&ia=answer

**Comment by mintsoft** [comment]
@tagawa Is the text supposed to be backwards for that? I'm guessing that's the right-to-left control character?

image1

**Comment by tagawa** [comment]
@mintsoft Ah no, the text shouldn't be reversed. Looks like something has broken. Thanks for checking.

**Comment by mintsoft** [comment]
@tagawa Ping! Just checking in, are you alright to finish this off or would you prefer to open it up to the community?

**Comment by tagawa** [comment]
Thanks for the reminder @mintsoft. I initially thought this fix was breaking because of an upper/lower case issue but that doesn't seem to be the case. I'm short of time at the moment so if it's possible to get community help that would be great.

**Comment by mintsoft** [comment]
@tagawa Rightyo, I'm going to close this then as I'm 99% sure that converting it to structured_answer will either resolve the issue or make this solution inapplicable. I'll keep the issue open and confirm it's resolved when converted

**Comment by tagawa** [comment]
That sounds perfect - thanks as always @mintsoft.

**Pull request closed without merging**
