### PR TITLE
Enhancement(html-beautifier): Added options and clear button.

### PR DESCRIPTION
**Pull request by akanshgulati**
## Description

Added Clear button and options for beautification.

## People to notify

@moollaza @tagawa 

---

Instant Answer Page: https://duck.co/ia/view/html_beautifier

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Now reading for testing on the beta server: https://beta.duckduckgo.com/?q=html+beautifier&ia=answer

**Comment by moollaza** [comment]
@akanshgulati would you mind merging `master` into your branch? I've update NameDays to stop it from failing. After that we'll be able to install this PR and get it live 👍

**Comment by moollaza** [comment]
@akanshgulati Ping! Would you be able to finish this one up? We'd love to get this live!

**Comment by moollaza** [comment]
@akanshgulati whoops, looks like this successfully deployed.  Thanks! This LGTM :+1: 💯

**Pull request merged**
