### PR TITLE
Fix dzil warnings

### PR DESCRIPTION
**Pull request by pfirsichbluete**
Running `dzil smoke --release --author` exhibited several warnings.
This Pull Request tries to address those warnings.

### CODE REVIEW

**Comment by moollaza** [comment]
@pfirsichbluete thanks for the fixing this -- can you explain the problem and solution a little more though? I saw the failing tests but didn't investigate the cause other then `dzil smoke` was running into issues

**Comment by moollaza** [comment]
@pfirsichbluete whoops sorry I though this was fixing the new problem causing the builds to fail -- I realize this is just about the warnings.

LGTM :+1:

**Comment by moollaza** [comment]
Care to update the Spice dist.ini as well with `main_module`?

**Comment by pfirsichbluete** [comment]
> Care to update the Spice dist.ini as well with main_module?

PR is at https://github.com/duckduckgo/zeroclickinfo-spice/pull/1654

But spice's `dzil smoke` also contains lots of other warnings too.
Will work through them (and the dist.ini of the other repos) the next days.

**Comment by moollaza** [comment]
@pfirsichbluete i think the `main_module` is the only thing that's necessary. I wouldn't bother with trudging through all the abstracts unless you ***really*** want to ;)

**Comment by moollaza** [comment]
I just don't want you to waste your time is all, but any and all improvements are of course welcome :+1:

**Pull request merged**
