### PR TITLE
Parsecron: adding support for start + interval arguments

### LINKED ISSUE #2239: ParseCron enhancement?
How feasible is this?

http://crontab.guru/#*_3/4_*_*_0

### PR DESCRIPTION
**Pull request by Mailkov**
IA Page: https://duck.co/ia/view/parse_cron

Fixes #2239

### CODE REVIEW

**Comment by daxtheduck** [comment]
## [ParseCron](https://duck.co/ia/view/parse_cron)

**Description**: show the next occurrence of a cron job in human-readable form

**Example Query**: [crontab * */3 * * *](https://beta.duckduckgo.com/?q=crontab * */3 * * *), [crontab 42 12 3 Feb Sat](https://beta.duckduckgo.com/?q=crontab 42 12 3 Feb Sat)

**Tab Name**: Answer

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/parse_cron)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/parse_cron)*

**Comment by GuiltyDolphin** [comment]
@Mailkov Sweet.

/cc @jbarrett

**Comment by jbarrett** [comment]
:+1: Very awesome, thanks @Mailkov!

**Comment by GuiltyDolphin** [comment]
@moollaza Can we get a deploy?

**Comment by moollaza** [comment]
@GuiltyDolphin @Mailkov deployed :+1:

**Comment by GuiltyDolphin** [comment]
@Mailkov Awesome! Thanks :+1:

**Pull request merged**
