### PR TITLE
Add tar cheat sheet

### PR DESCRIPTION
**Pull request by ghost**
**What does your Instant Answer do?**
Adds a cheat sheet for common operations with GNU tar

**What is the data source for your Instant Answer? (Provide a link if possible)**
Manpage for tar [(man.cx/tar)](http://man.cx/tar)

**Why did you choose this data source?**
Manpages are usually written by the developer or are scrutinised heavily

**Are there any other alternative (better) data sources?**
Not that I can think of

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Terminal users that always forget if it's a j or a z

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No

**Are you having any problems? Do you need our help with anything?**
No problems

**Where did you hear about DuckDuckHack? (For first time contributors)**
/r/linux

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
Image of tar cheat sheet

---

IA Page: https://duck.co/ia/view/tar_cheat_sheet

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Hey @jameshc, thanks for your contribution!
Since this is not connected to an IA idea we first need to evaluate it, but we'll get back to you soon :)
//cc @moollaza

**Comment by jagtalon** [comment]
Hey, @jameshc! This looks good although please make an IA page on https://duck.co/ideas and claim the idea. :)

**Comment by jagtalon** [comment]
Also this is perfect because I always forget those damn flags

**Comment by jagtalon** [comment]
Looks like there's an error in the JSON file:

screen shot 2015-08-29 at 5 05 39 pm

**Comment by jameshc** [comment]
There were some new lines in the file, no idea where they came from!

I have added a commit to fix them

**Comment by jagtalon** [comment]
@jameshc :+1:

**Comment by moollaza** [comment]
@jameshc congrats! It's live: https://duckduckgo.com/?q=tar+cheat+sheet&t=ffcm&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
