### PR TITLE
Timer: Triggering fixes

### LINKED ISSUE #4445: Timer: Doesn't trigger for "timer of x minutes"
### Description

Doesn't trigger for "timer of 5:15 minutes" but does for "timer for 5:15 minutes". Should be a simple addition.

## Steps to recreate

[timer of 5:15 minutes](https://duckduckgo.com/?q=timer+of+5%3A15+minutes&ia=web)

## People to notify

@mattr555 

---

Instant Answer Page: https://duck.co/ia/view/timer

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
## Description of new Instant Answer, or changes

- Adds joining word `of` to support queries like `timer of 5 minutes`.
- Prevents over triggering on queries requiring time math.

For the second one, I think it should still trigger the timer for queries of from `time of mm:ss+zz`(even though the one started is incorrect) as the timer is still relevant.(perhaps, this requires more discussion before approval)

## Related Issues and Discussions

Fixes #4445, #4346 

## People to notify

@mattr555 @pjhampton 

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/testing-reference/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/timer

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
Thanks @nalinbhardwaj

**Comment by bsstoner** [comment]
This was released to production 🚀

**Comment by nalinbhardwaj** [comment]
@mintsoft #4346 didn't get closed with this.

**Pull request merged**
