### PR TITLE
DDG_cheat_sheet: Remove unnecessary paranthesis on json data

### PR DESCRIPTION
**Pull request by NaveenKarippai**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`duckduckgo_cheat_sheet: Remove unnecessary paranthesis`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

According to cheathseet guidelines, we don't need extra paranthesis
enclosing each json "value". The unnecessary paranthesis could be removed
to make the cheatsheet more readable.

Provide an overview of the changes this pull request introduces.

* cleaned up cheathseet according to docs guidelines 

###### Which issues (if any) does this fix?

Fixes: #3141 

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/duckduckgo_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Qeole

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by zekiel** [comment]
@Qeole can you please review and OK this change before the [maintainer timeout period](http://docs.duckduckhack.com/maintaining/guidelines.html#overseeing-changes)? We'll merge if no response within 14 days.

**Comment by Qeole** [comment]
@zekiel Sorry for the delay, I had not seen the first notification (on a side note, would you know if there is a way to filter out the GitHub notification for the “duckduckhack-contributors” team? I'm not so active, I skip most of the emails and it tends to make me miss the important ones).

OK so, here is what I get with this PR:

ddg

This seems better than the previous version (capture available on issue #3141), in particular for the right column, and looks very correct to me.
**ACK**.

**Comment by zekiel** [comment]
@Qeole no worries! We appreciate you checking in on the stuff you're maintaining. The GitHub notification system isn't the most configurable but you can adjust how you receive notifications at https://github.com/settings/notifications 

We'll take a look at this asap -- looks like something weird is happening with beta.duckduckgo.com today but no worries, we'll fix! and merge when we can!

**Comment by zekiel** [comment]
That looks much better! Thank you @NaveenKarippai @Qeole Merging now!

**Pull request merged**
