### PR TITLE
Conversions: Improving accuracy of the US Gallon/Cubic Inch

### PR DESCRIPTION
**Pull request by mintsoft**
###### Which issues (if any) does this fix?

Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3221

###### People to notify (@mention interested parties)

@edgesince84 

---

Instant Answer Page: https://duck.co/ia/view/conversions

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
that was fast, thanks Rob!  ⏩

**Comment by mintsoft** [comment]
@edgesince84 Easy now it's all in the repo :+1:

**Comment by GuiltyDolphin** [comment]
@mintsoft Thanks! :dolphin:

**Pull request merged**
