### PR TITLE
New TextToSpeech Goodie

### PR DESCRIPTION
**Pull request by kirkins**
## Description of new Instant Answer, or changes

This is an interactive goodie for converting text to speech.

[Youtube Demo](https://www.youtube.com/watch?v=weCrfH8spiI)
untitled

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/TextToSpeech

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by kirkins** [comment]
Built with Firefox. Opening with an old version of chromium and it's not working.

Will have to fix it later.

**Comment by kirkins** [comment]
I had my cousin test on windows and he said it works on both Chrome and Firefox.

I have an edge case scenario on Chromium where a browser has voice capabilities but no voices installed. I'm going to add a fix that stops it from showing in that case.

P.S. thanks @pjhampton @mintsoft @moollaza, I your feedback on my past requests really helped me while writing this.

**Comment by kirkins** [comment]
Yep I fixed the issue on Chromium. It was what I thought. They shipped with [SpeechSynthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance) capabilities but no voices for that api to use. 

This fix will stop it from triggering on any browser without voices.

**Comment by mintsoft** [comment]
> This fix will stop it from triggering on any browser without voices.

AFAIK Firefox on linux also ships without any voices, so it might one to test

**Comment by kirkins** [comment]
@mintsoft firefox on my version of ubuntu 16.04 had no problems but it's probably different versions based on distros.

**Comment by kirkins** [comment]
@mintsoft any idea why this would error on beta deploy? 

The perl code is minimal. The only thing I do is [pass extra text](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4357/files#diff-b7f1cbd24fcbfeaa4412e6eec5d14f38R14) after the triggers into the structured answer.

**Comment by mintsoft** [comment]
Sadly no idea at all, I can't access any diagnostics for this I think @moollaza will have to look for us

**Comment by pjhampton** [comment]
Goodies don't auto deploy to beta in the case of malicious code in the PR. It seems that the DaxBot tried to deploy and then bailed when it couldn't. @moollaza can deploy this manually for you.

**Comment by mintsoft** [comment]
@moollaza Can we get this onto beta?

**Comment by pjhampton** [comment]
Hey @kirkins 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Comment by kirkins** [comment]
R u kidding me this was done :/

**Comment by pjhampton** [comment]
Hey @kirkins,

I understand your frustration - **I really do** 😞 . The reason why I need to close this is that:

1. It was unsolicited (ie. non high-impact)
2. It hasn't been tested thoroughly enough
3. There is nobody to maintain it going forward.

I also looked into the queries to check if people are actually searching for text to speech functionality. They're not. Unfortunately, this IA is a suck cost.

**Pull request closed without merging**
