### PR TITLE
Continuing #1387

### PR DESCRIPTION
**Pull request by javathunderman**
This IA provides HDFS Shell commands in a cheatsheet. Following text is the pull request form copied from a comment off the old PR. 

**HDFS Shell commands cheat sheet goodie**

What does your Instant Answer do?
Lists the commonly used HDFS shell commands for interacting with files and directories over HDFS

What is the data source for your Instant Answer? (Provide a link if possible)
http://hadoop.apache.org/docs/r2.7.1/hadoop-project-dist/hadoop-common/FileSystemShell.html#usage

Why did you choose this data source?
This is the official latest documentation of Apache Hadoop

Are there any other alternative (better) data sources?
Since this is the official documentation, there are no better sources.

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)
This will be mostly useful for DevOps working in the BigData field

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?
Yes (https://duck.co/ideas/idea/6228/cheat-sheet-for-hadoop-s-hdfs-shell-commands)

Are you having any problems? Do you need our help with anything?
Yes.
I was trying to split the commands into multiple lines so that I can give some alternatives of the command explained. There should be some provision for this. May be if we can specify multiple values(as a list) in the val section of the JSON which would then be rendered as multiple lines of text.

Where did you hear about DuckDuckHack? (For first time contributors)
Through a meetup group (mumbai meetup group)

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
(I'll get the images from the comment on the old PR soon.)

IA Page: https://duck.co/ia/view/hdfs_shell_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by javathunderman** [comment]
cc @moollaza

**Comment by moollaza** [comment]
> I was trying to split the commands into multiple lines so that I can give some alternatives of the command explained. There should be some provision for this. May be if we can specify multiple values(as a list) in the val section of the JSON which would then be rendered as multiple lines of text.

@javathunderman for now the simplest solution is to create another `key/value` and indicate it's an alternative

I have a PR that adds support for newlines and some other stuff but haven't gotten around to testing it. I could see it being useful for a codeblock, but if you're offering alternatives I'd say use two keys

**Comment by moollaza** [comment]
@javathunderman seeing as this is a new Cheat Sheet, our Beta deploy code is expecting your PR to only have 1 file in it. Can you move the changes to the comment in `cheat_sheets.js` to a separate PR please?

**Comment by javathunderman** [comment]
@moollaza No problem, doing that now.

**Comment by javathunderman** [comment]
@moollaza Should be good :+1:

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=hdfs shell cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/hdfs_shell_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=hdfs shell cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/hdfs_shell_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@javathunderman this LGTM :+1:

Thanks a lot for contributing (we really appreciate it :smiley:).

**Comment by moollaza** [comment]
@javathunderman congrats! It's live: https://duckduckgo.com/?q=hdfs+shell+cheat+sheet&ia=answer

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
