### PR TITLE
Issue #1163 - Convert VIN to use templates

### PR DESCRIPTION
**Pull request by Mailkov**
IA Page: https://duck.co/ia/view/vin

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
Deploying to Beta...

**Comment by mintsoft** [comment]
@moollaza LGTM too

**Comment by moollaza** [comment]
This seems OK, but I would love to turn this into a Spice. I see that Edmunds has an API, there are other paid ones too, there must be a reliable free API out there, or a Paid one we can get free access to!

**Comment by moollaza** [comment]
It looks like there Validate::VIN, but it only gives the potential year and country of manufacture. It can't determine if it's a real car or any other info. It may help to make the IA slightly more insightful

**Comment by mintsoft** [comment]
@moollaza my day-job is actually in a company that works in automotive finance, I'll see if there's any free APIs that we know of however I doubt there'll be one. We pay something like 25p per VIN lookup to get make, model, manufacturer and various other datacodes I believe

**Pull request merged**
