### PR TITLE
Eclipse cheat sheet: Added a new section and fixed typos

### PR DESCRIPTION
**Pull request by mayank7**
Added a new section and fixed typos in Eclipse cheat sheet.

IA Page: https://duck.co/ia/view/eclipse_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mayank7** [comment]
Reference: http://www.shortcutworld.com/en/win/Eclipse.html

**Comment by MrChrisW** [comment]
Hi @mayank7,

Thanks for your interest in making DuckDuckGo better, we appreciate your contributions. Due to the extensive number of PR's you've submitted we're having trouble getting to review all of them. 

Would you mind making a PR with all the CheatSheet improvements combined and separated by commits, you could do this by merging each branch into a new branch. Let me know if you have any issues doing this. 

Thanks

**Comment by mayank7** [comment]
@MrChrisW But for each PR, we mention the corresponding IA Page link and also I am not modifying in the same file with a new PR. Everytime I am creating a PR by modifying new cheat sheet.

**Comment by moollaza** [comment]
>But for each PR, we mention the corresponding IA Page link and also I am not modifying in the same file with a new PR.

@mayank7 it's OK to modify multiple cheat sheets in a single PR and link all their IA Pages. It won't be auto-deployed by our system though.

When making a PR that adds a **new** Instant Answer, it should only contain the necessary files and not include anything else

**Pull request closed without merging**
