### PR TITLE
Timer: Added some non-english triggers

### PR DESCRIPTION
**Pull request by ValeriaVG**
## Description of changes
PR Adds *temporizador*, *crônometro* & *таймер* triggers to [Timer](https://duck.co/ia/view/timer)

- /?q=temporizador&t=hq
- /?q=crônometro&t=hq
- /?q=таймер&t=hq

## Related Issues and Discussions
- https://github.com/duckduckgo/zeroclickinfo-spice/issues/3119

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Code**
- [x] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [x] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [x] There is no unnecessary files in place (such as editor config files)
- [x] There is no API keys / secrets present
- [x] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/timer

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
@duckduckgo/duckduckhack-contributors can anybody verify these are good triggers? I'm not seasoned in any of these languages.

**Comment by ozdemirburak** [comment]
chrônometro(crônometro actually) is not timer, instead it can be translated as stopwatch, temporizador is ok for both Spanish and Portuguese to refer timer, but I'm not a native speaker, so would be better if someone who is native comments.

**Comment by ValeriaVG** [comment]
Thank you for the review!

Just added basic translations functionality based on the trigger word language:

es_timer
pt_timer
ru_timer

**Comment by ValeriaVG** [comment]
All the functionality I got from https://github.com/duckduckgo/zeroclickinfo-spice/issues/3119 which seems to be opened for some time and had a *High-priority* tag.

**Comment by pjhampton** [comment]
Yeah, the scope of your PR has changed since this morning - I had to request changes so it wasn't merged without an extensive code review. I encourage you to continue to work on it while the community verifies the quality of the triggers.

**Comment by ValeriaVG** [comment]
Understood.
Thank you for the clarification. 👍

**Comment by tagawa** [comment]
This may have to go on hold until we have better international support for IAs. There are many IAs we could add triggers to and partial coverage for just a few IAs could be confusing for users and potentially hard to maintain without a proper process in place.

@moollaza has left comments on this in the past and I think they still stand, e.g. https://github.com/duckduckgo/zeroclickinfo-spice/pull/1703#issuecomment-87703743

**Comment by ValeriaVG** [comment]
@tagawa , I understand your position, but the method I suggested could be used for any existing or future AI. The comment you pointed was made 2 years ago. 

I don't think that there is a need for an overkill library holding on the whole translation for every single IA. Languages are different by it's nature and most of trigger phrases will need to be processed in the module itself.

So for this I offered to group international trigger words by their language, pass the language of the group which includes the word that triggered the IA to JS; and then change UI text based on that parameter.

In my opinion, storing the translations in JSON on the front (View) part of the IA is a good practice and will allow other contributors to add translations easily. I don't think it's an easy and fast task to translate all IA to all the languages. But it doesn't seem possible to do it all together and "at once".

If work on this issue is not needed at the moment, would you please somehow refer the ones that actually need some. 😄

**Comment by mintsoft** [comment]
I'm going to close this for now until we have some internationalisation support added more consistently to the IA platform

**Comment by pjhampton** [comment]
That most likely won't be for a long time. I think if there are quick wins like adding a couple of non-English triggers like we did with some other IAs then I say go for it, otherwise, it's a no go - like what this PR became after my first review.

**Pull request closed without merging**
