### PR TITLE
New Random Date Goodie

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
Ever wanted to get a random day of the week? Mayhaps you've been waiting for a way to generate random ISO-8601 compliant dates. Maybe, just maybe, you've been wanting to generate random dates for a specific format.

Well, ***look no further*** - with the new Random Date Goodie, you can do all of the above, and more!*

screenshot from 2016-04-12 20 59 11

screenshot from 2016-04-12 20 59 50

screenshot from 2016-04-12 21 00 35

But wait, I hear you cry, *I am a non-native English speaker and want results in my own tongue!*; well, have we got the thing for you! Just ensure your browser language preferences are set then bam! Success.

screenshot from 2016-04-12 21 01 53

*more may or may not be the exact same amount.

/cc @moollaza @mintsoft @MrChrisW 

---
IA Page: https://duck.co/ia/view/random_date

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
Cool :+1:

**Comment by GuiltyDolphin** [comment]
@zachthompson Any idea why the tests are failing? I'm using `test_language` and it is fine locally; it seems that the build is producing American formats rather than Malaysian formats for those tests.

/cc @moollaza

**Comment by GuiltyDolphin** [comment]
@mintsoft @zachthompson @moollaza Yo, ping. Any idea why tests are failing? It looks like this is the only Goodie using `test_language` rather than `test_location`, so it might be an issue with that?

Again, locally everything is fine - the tests on Travis don't seem to be taking into account the `test_language` settings though.

**Comment by GuiltyDolphin** [comment]
@moollaza Figured out the test issue - we don't have the latest version of `DateTime::Locale` installed; which means it isn't able to use the `ms_MY` locale.

Doing `cpanm DateTime::Locale` fixes the issue.

**Comment by mintsoft** [comment]
@GuiltyDolphin Any idea about how to trick Travis into doing that for the build?

**Comment by GuiltyDolphin** [comment]
@mintsoft I'm waiting for the dep to get updated on prod - @moollaza any news?

**Comment by moollaza** [comment]
@GuiltyDolphin Dep has been updated in prod 👍

**Comment by moollaza** [comment]
Killed the cache and restarted Travis build -- should force newest dep on Travis

**Comment by moollaza** [comment]
Okay killed all the caches... now it should work

**Comment by moollaza** [comment]
Damn, killed all the caches, and then it never tried installing DateTime::Locale, so the tests still fail.

We may have to force it in the Travis.yml

**Comment by moollaza** [comment]
@GuiltyDolphin can you get a PR working with that? I just don't want this to be merged and cause everything to fail..

**Comment by GuiltyDolphin** [comment]
@moollaza Sweet, that did it - we can now all enjoy random dates :smile:

**Comment by mintsoft** [comment]
Cool; LGTM. Can we get this on beta @moollaza

**Comment by GuiltyDolphin** [comment]
@mintsoft @moollaza Status? I'm pretty happy with this.

**Comment by GuiltyDolphin** [comment]
@moollaza This seems to have fallen by the wayside a bit, AFAIK this is complete, anything else need doing?

cc @zekiel

**Comment by moollaza** [comment]
@GuiltyDolphin whoops! Deploying to Beta for final testng..

**Comment by moollaza** [comment]
@GuiltyDolphin Thanks! This LGTM :+1:

**Comment by daxtheduck** [comment]
@GuiltyDolphin this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
