### PR TITLE
MS excel Cheat sheet

### PR DESCRIPTION
**Pull request by ankushg07**
https://duck.co/ia/view/microsoft_excel_cheat_sheet

### CODE REVIEW

**Comment by moollaza** [comment]
@ankushg07 please make sure you create an Instant Answer page for this and paste the link into the PR description. Without that we can't deploy this IA to Beta or merge it.

You can create the IA Page here: https://duck.co/ia/new_ia

**Comment by ankushg07** [comment]
@moollaza created the IA page and published it in description

**Comment by ankushg07** [comment]
@moollaza Sir updated the IA page

**Comment by ankushg07** [comment]
@moollaza @GuiltyDolphin any update??

**Comment by moollaza** [comment]
@ankushg07 Thanks and sorry for the delay!! This LGTM :+1:

**Pull request merged**
