### PR TITLE
added ascii art emoticon cheatsheet

### PR DESCRIPTION
**Pull request by lolpuddle**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [X] New Instant Answer
  - [x] Cheat Sheets: **`New ASCII Emoticons Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Enables ASCII Art Emoticons to be easily accessed through an instant answer cheatsheet. A small sample of popular ASCII Art Emoticons have been added to the cheatsheet and the description provides users with other available ASCII Art Emoticons which may not have been listed.
###### Related Issues or Discussions

I find myself searching for "shrug emoticon" or "shrug ascii emoticon" a lot and most results brought up don't allow me to copy/paste the text from the search results without entering their website. This improves my personal user experience using DuckDuckGo and I hope it'll do the same for others.
###### People to notify

@mention any relevant people/organizations

---

Instant Answer Page: https://duck.co/ia/view/ascii_emoticons

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @lolpuddle

### CODE REVIEW

**Comment by daxtheduck** [comment]
@lolpuddle Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by akanshgulati** [comment]
@lolpuddle Thanks for this PR. I have a doubt on the name of this IA. I searched a bit and found that "Emoji" is not the right work for ascii characters used for smileys and smirking face. Please see once because I find the title improper. Instead of `shrugging emoji`, `shrugging face` will look better. Please give your inputs on this.

**Comment by lolpuddle** [comment]
@akanshgulati I've made some of the suggested changes and thought about this a lot more. I think using ASCII Emoticon would be a lot more appropriate because emoji could be one day potentially be used for an actual unicode emoji cheat sheet. I've decided to rename everything to fit "ASCII Emoticon" instead.

**Comment by pjhampton** [comment]
Closing as this PR looks to have gone stale.

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄

**Pull request closed without merging**
