### PR TITLE
JS keycodes cheatsheet

### PR DESCRIPTION
**Pull request by andrey-p**
Finally! Here you go @jagtalon and @moollaza, sorry about the delay :)

**What does your Instant Answer do?**

Show Javascript keycodes.

**What is the data source for your Instant Answer? (Provide a link if possible)**

MDN: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Why did you choose this data source?**

MDN's pretty solid, and it also mentions some of the subtle cross-system differences.

**Are there any other alternative (better) data sources?**

http://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

Javascript developers.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

Nope.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

screenshot_2015-09-04_12-29-01

-----
IA Page: https://duck.co/ia/view/js_keycodes_cheat_sheet

### CODE REVIEW

**Comment by moollaza** [comment]
> Finally! Here you go @jagtalon and @moollaza, sorry about the delay :)

@andrey-p no need to apologize, I know you're busy doing a ton of other great work. This is looking great :+1: Thanks!

**Comment by moollaza** [comment]
@andrey-p I've pushed a commit that adds a bit of new content, and reformats the file a bit to match the usual formatting. I'm trying to figure out the best way to handle the `Symbols` section, and accidentally realized that we can create code blocks, inside of a code block!

screen shot 2015-09-04 at 13 38 41

/cc @abeyang @chrismorast any ideas on how the `Symbols` should look? Should I ditch the words?

**Comment by moollaza** [comment]
Another approach:

js_keycodes_help_at_duckduckgo

**Comment by abeyang** [comment]
@moollaza do we need the words? I recognize each of the symbols just fine without them...

**Comment by moollaza** [comment]
@abeyang I guess not? I like having them to make things explicit/descriptive.

**Comment by abeyang** [comment]
@moollaza I'd prefer without them, then -- feels cleaner and less cluttered.

**Comment by moollaza** [comment]
@andrey-p @abeyang alright, removed the words!

js_keycodes_cheat_sheet_at_duckduckgo

**Comment by abeyang** [comment]
:+1:

**Pull request merged**
