### PR TITLE
First attempt at a MAC address OUI lookup Goodie.

### PR DESCRIPTION
**Pull request by mogigoma**
# Goodie Pull Request Template

Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**

It displays the name and address of the vendor associated, and ostensibly the manufacturer of, a NIC.

**What problem does your Instant Answer solve (Why is it better than organic links)?**

Searching for this information requires another step, having to search on another, application-specific site.

**What is the data source for your Instant Answer? (Provide a link if possible)**

IEEE's OUI Database
http://www.ieee.org/netstorage/standards/oui.txt

**Why did you choose this data source?**

It was suggested in the Instant Answer Idea and should be the canonical source of information.

**Are there any other alternative (better) data sources?**

Not that I'm aware of.

**What are some example queries that trigger this Instant Answer?**

"mac address 14:D6:4D:DA:79:6A"
"mac address 2c-41-38-13-48-d2"
"ethernet address 00/00-03.ff:ff:FF"

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

System administrators, hackers, network administrators.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

MAC Address Vendor Lookup
https://duck.co/ideas/idea/192/mac-address-vendor-lookup

**Which existing Instant Answers will this one supercede/overlap with?**

It is related to the Random MAC Generator, tangentially.

**Are you having any problems? Do you need our help with anything?**

No.

**Where did you hear about DuckDuckHack? (For first time contributors)**

Twitter.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

mac-address-dlink
mac-address-private

## Checklist
Please place an 'X' where appropriate.

```
[x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[x] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Linux
        [x] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by mintsoft** [comment]
@moollaza @jagtalon ping

**Comment by jagtalon** [comment]
Thanks, @mintsoft. Checking it out!

**Comment by jagtalon** [comment]
@mogigoma the all-caps feels a bit jarring

screen shot 2015-01-15 at 10 43 10 am

If it was like this it looks better:

screen shot 2015-01-15 at 10 39 41 am

What do you think, @abeyang?

**Comment by abeyang** [comment]
I agree with @jagtalon -- can we change it so it's "normal" text (not necessarily Title Case). In addition, can we add break points and change the title font size to 1.143em? It should something look like this:

screen shot 2015-01-15 at 11 42 58 am

Otherwise, looks good!

**Comment by mogigoma** [comment]
@jagtalon I'll come up with some heuristic that looks good on the text, probably along the lines of "titlecase unless address already includes lowercase letters in which case assume it already has friendly capitalization in the source database".

@abeyang I originally had linebreaks with <br/> but it was suggested that I remove them. What is the approved way to add linebreaks in goodies?

**Comment by mintsoft** [comment]
@mogigoma putting each "line" in a `<p/>` is probably the easiest way; personally here I might use a `<ul><li/></ul>` structure but either works

**Comment by mintsoft** [comment]
@jagtalon what is the current "best practise" with regards to HTML & Structured Answers? I was under the impression that until the templates are finished the results are always being `html_enc` by duckpan? (issues like this: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/891 for example)

**Comment by mintsoft** [comment]
oops forgot to cc @moollaza

**Comment by jagtalon** [comment]
Yeah you're right about https://github.com/duckduckgo/zeroclickinfo-goodies/pull/884#issuecomment-70185818. No best practices yet until the templates are out.

**Comment by jagtalon** [comment]
I do like it wrapped in `<p>` or `<div>` just because it looks nice :)

**Comment by jagtalon** [comment]
@abeyang @mogigoma I think I'd like the text at the bottom to be "MAC Address: ff:ff:ff..." (I just capitalized some letters) what do you think?

**Comment by mogigoma** [comment]
@jagtalon Looks good, I'll get a new version out with suggested changes for review out by Monday.

**Comment by mogigoma** [comment]
I've integrated the comments thus far. The result is split across multiple lines, capitalization is added to any line that is all uppercase, and the first line of the result is slightly larger than the rest.

Here is a result that is already formatted in the OUI database:

2015-02-01-140541_1600x900_scrot

And here are two results that are auto-capitalized by the Goodie:

2015-02-01-140651_1600x900_scrot
2015-02-01-140524_1600x900_scrot

**Comment by abeyang** [comment]
Looks good! :+1:

**Comment by moollaza** [comment]
Sorry about the delay @mogigoma, this one is ready for merge!

Note: tests are failing because the test expects "mac address" as the `operation` when the IA returns `MAC Address`

I'll merge and then make a PR to fix.

**Comment by moollaza** [comment]
Whoops, actually the tests weren't expecting HTML in the `result` -- I'll fix it up

**Comment by moollaza** [comment]
Fixed in #983

**Comment by jagtalon** [comment]
Sweet!

**Comment by moollaza** [comment]
@mogigoma congrats! It's live :https://duckduckgo.com/?q=mac+address+14%3AD6%3A4D%3ADA%3A79%3A6A&ia=answer

**Pull request merged**
