### PR TITLE
Calculator: Add dark theme.

### PR DESCRIPTION
**Pull request by pjhampton**
## Description of new Instant Answer, or changes

Adds a dark theme to the calculator

screen shot 2017-07-14 at 5 24 41 pm
screen shot 2017-07-14 at 5 23 21 pm

## People to notify

cc/ @abeyang 

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/calculator

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
@duckduckgo/duckduckhack-contributors Any designers in the community want to make some comments here?

**Comment by pjhampton** [comment]
@duckduckgo/duckduckhack-contributors Any designers in the community want to make some comments here?

**Comment by mintsoft** [comment]
@pjhampton only observation I have is that the orange isn't used anywhere on the dark theme currently, buttons tend to be #4b4b4b

**Comment by pjhampton** [comment]
Yeah, @mintsoft. It's kind of strange, but I guess we want to draw attention to these special buttons. I'm open to another color palette. But I think for now we're just copying the onboard apple calculator

**Comment by adityatandon007** [comment]
@pjhampton I like the dark view except that blue border around display text box. I haven't seen the blue color used elsewhere in other goodies in dark mode. That color doesn't blend in with the dark theme.  

P.S. No offense, its just my point of view. I have certainly no issue if you want to stick to it.

**Comment by pjhampton** [comment]
@adityatandon007 no offense was taken! I see what you are saying. Blue is a common focus color cross browser. I'm totally up for changing it if we can come up with something better

**Comment by moollaza** [comment]
@pjhampton Thanks! This LGTM :+1:

**Comment by bsstoner** [comment]
This was released to production 🚀

**Pull request merged**
