### PR TITLE
GTA cheat codes & C String Formatting cheatsheets

### PR DESCRIPTION
**Pull request by javathunderman**
Reviving #1665. 

IA Page: https://duck.co/ia/view/gta_v_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=gta v cheatsheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/gta_v_cheat_codes_mobile.png)

**Comment by javathunderman** [comment]
To avoid merge conflicts, please merge #2171 before merging this one.

**Comment by moollaza** [comment]
@javathunderman thanks! I've ghosted the old IA Page with the id `gta_v_cheat_sheet` and changed your IA Page to use that ID. Can you please update the JSON accordingly?

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=gta v cheatsheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/gta_v_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=gta v cheatsheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/gta_v_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=gta v cheatsheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/gta_v_cheat_sheet_mobile.png)

**Comment by mintsoft** [comment]
@javathunderman can we add something to point out/trigger on only PS4 not XB1?

**Comment by javathunderman** [comment]
Ok, hopefully this doesn't break CI. I'm merging this PR with #2171 to avoid horrors with Git. :smile:

**Comment by javathunderman** [comment]
@mintsoft fixed that with latest commit!

**Comment by moollaza** [comment]
@javathunderman sorry but you need to add 1 IA at a time -- that's why beta isn't deploying the PR.

The code looks pretty good though. I would suggest you close these branches and make 2 new pr's from clean up to date branches and just do a single commit that adds the JSON as it is here
make sure to link the IA page in the PR

**Comment by javathunderman** [comment]
@moollaza working on that then...

**Pull request closed without merging**
