### PR TITLE
Coin: Triggers on 'coin flip'

### LINKED ISSUE #2646: Coin: Doesn't trigger on coin flip
@mattlehning 

------
IA Page:  http://duck.co/ia/view/coin

### PR DESCRIPTION
**Pull request by dbech**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

I updated a regex to accept 'coin flip'

###### Which issues (if any) does this fix?

Fixes #2646 - how specifically does it fix the issue?

###### People to notify (@mention interested parties)

@stevenmg 
---

Instant Answer Page: https://duck.co/ia/view/coin

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattlehning

Updated a regular expression that sets the number of coins to flip.

Now it will accept 'coin flip' and then flip 1 coin.

### CODE REVIEW

**Comment by daxtheduck** [comment]
@dbech Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@dbech Can you add a test for the new query shapes?

**Comment by GuiltyDolphin** [comment]
@dbech Do you want to update the template here?

**Comment by dbech** [comment]
@GuiltyDolphin yup, was just about to :)

**Comment by GuiltyDolphin** [comment]
@dbech Status? Are you still planning on updating the template?

**Comment by dbech** [comment]
@GuiltyDolphin Sorry I started a new job and have become a bit busy, I may not have time to update it to the templates for a bit

**Comment by mintsoft** [comment]
@GuiltyDolphin @dbech That's fine I think we can merge as is and do it separately?

**Comment by GuiltyDolphin** [comment]
@mintsoft @dbech Alrighty, thanks!

**Pull request merged**
