### PR TITLE
GnuPG Cheatsheet

### PR DESCRIPTION
**Pull request by jclement**
**What does your Instant Answer do?**

Cheatsheet for GnuPG

**What is the data source for your Instant Answer? (Provide a link if possible)**

GnuPG man pages at https://www.gnupg.org/documentation/manpage.en.html

**Why did you choose this data source?**

Official documentation for GnuPG.

**Are there any other alternative (better) data sources?**

Various quick references around the internet but this source is correct and exhaustive.

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

Software developers, privacy advocates

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

Yes. This one https://duck.co/ideas/idea/6317/gnupg-quick-reference

**Are you having any problems? Do you need our help with anything?**

Nope

**Where did you hear about DuckDuckHack? (For first time contributors)**

Been using you for ages.  Can't remember where I heard of DuckDuckGo.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

gnupg-ia

IA Page: https://duck.co/ia/view/gnupg_cheat_sheet

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Hey @jclement, thanks for the contribution!
It doesn't look like the idea on the forum is approved yet, so we need to evaluate it first, but we'll get back to you soon!
//cc @moollaza

**Comment by moollaza** [comment]
@jclement @MariagraziaAlastra approved! Thanks for contributing @jclement

**Comment by jagtalon** [comment]
@jclement checking it out!

**Comment by jagtalon** [comment]
:+1:

**Comment by moollaza** [comment]
@jclement congrats! It's live: https://duckduckgo.com/?q=gnupg+cheatsheet&t=ffcm&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
