### PR TITLE
Zodiac - Remove DateTime::Event::Zodiac Dependency

### LINKED ISSUE #2009: Zodiac: Dates for the Zodiacs
Hey all!

I'm working on internalizing the `Zodiac` Goodie because its dependencies cause a few issues.

I'm mostly sorted - but some of the tests are failing due to a few differences between the dates that I've used and those used by the dependency.

I've used [Wikipedia](https://en.wikipedia.org/wiki/Zodiac) as a source, and I've found some other sites that have agreed with it - but also some that have disagreed.

It's not always clear which year the Zodiac is for, and it seems that the dates can shift slightly?

Regardless, I've looked at the two main alternatives on CPAN: `Zodiac::Tiny` and `DateTime::Event::Zodiac` (the one that is currently used) and they both hardcode their dates - as have I.

Does anyone know a better source than Wikipedia for this? Or even, does anyone _know_ the correct dates?

I'd jut like to mention that I don't do astrology.

@duckduckgo/community-leaders

------ 

IA Page:  https://duck.co/ia/view/zodiac

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
Removes the `DateTime::Event::Zodiac` dependency.

See discussion on #2009 (although fixing this in a future PR may be wise).

---

[IA Page](https://duck.co/ia/view/zodiac)

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@GuiltyDolphin can you please fix the conflict here (it’s the removal of the Perl metadata) and then I'll be happy to deploy to beta!

**Comment by GuiltyDolphin** [comment]
@moollaza Done!

**Comment by jagtalon** [comment]
@GuiltyDolphin checking it out!

**Comment by jagtalon** [comment]
@GuiltyDolphin yeaaaa

**Comment by jagtalon** [comment]
:+1:

**Comment by moollaza** [comment]
@jagtalon @GuiltyDolphin this PR broke Zodiac -- we need to make sure these are tested on Beta. In this case it would have worked fine in DuckPAN, but this PR removed the Goodie Bundle version number which is necessary in production as all assets are versioned.

**Comment by GuiltyDolphin** [comment]
@moollaza Yikes - sure, I'll get this sorted. Most testing was done locally so that would explain not noticing!

**Pull request merged**
