### PR TITLE
Python Cheat sheet

### PR DESCRIPTION
**Pull request by IamRafy**
This is short cheat sheet of python programming language which include following things :   
- Invocation Options
- Environment Variables
- String Literal Escapes
- Operations on String
- Format codes
- File operations
- Posix functions
- Posix path functions

------
IA Page: https://duck.co/ia/view/python_cheat_sheet

### CODE REVIEW

**Comment by zekiel** [comment]
https://duck.co/ia/view/python_cheat_sheet

**Comment by ethanchewy** [comment]
This hasn't been worked on for a few weeks. I'm going to create a pull request with a more condensed python cheatsheet. Hopefully we can use merge both of these cheatsheet to make a better one.

**Comment by moollaza** [comment]
> This hasn't been worked on for a few weeks. I'm going to create a pull request with a more condensed python cheatsheet. Hopefully we can use merge both of these cheatsheet to make a better one.

Excellent. Thanks @ethanchewy :+1:

**Comment by IamRafy** [comment]
excellent . Thanks @ethanchewy @moollaza

**Pull request closed without merging**
