### PR TITLE
DB2 Cheat Sheet: Update Tablespace commands

### PR DESCRIPTION
**Pull request by vikashvverma**
IA Page: https://duck.co/ia/view/ibm_db2_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=IBM DB2 Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/ibm_db2_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=IBM DB2 Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/ibm_db2_cheat_sheet_mobile.png)

**Comment by GuiltyDolphin** [comment]
@vikashvverma Move into #2746 if still applicable.

**Pull request closed without merging**
