### PR TITLE
Create NepalEarthquakeRelief Goodie

### PR DESCRIPTION
**Pull request by wongalvis**
# Goodie Pull Request Template

Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**
Provide ways to help Nepal earthquake relief

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Provide some ways to help Nepal earthquake relief and links for "Read More".

**Why did you choose this data source?**
They are reliable and the info is straightforward.

**Are there any other alternative (better) data sources?**
There are plenty of articles about helping the earthquake relief.

**What are some example queries that trigger this Instant Answer?**
"Nepal earthquake", "Nepal relief", "Support Nepal"

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Everyone who wants to help Nepal's earthquake relief.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No.

**Which existing Instant Answers will this one supercede/overlap with?**
No.

**Are you having any problems? Do you need our help with anything?**
Would you mind giving suggestions for what should be included in category and topics under metadata?

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screencapture-tempo-rudolf-codio-io-5000-1431083628218

## Checklist
Please place an 'X' where appropriate.

```
- [X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [X] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

```

### CODE REVIEW

**Comment by mintsoft** [comment]
@zekiel This OK to do? @abeyang any thoughts about layout etc?

**Comment by mintsoft** [comment]
also ping @jagtalon

**Comment by zekiel** [comment]
The intent and concept are great but I think it wouldn't be the preferred result for people querying "nepal earthquake." It's more likely they want info on the earthquake itself. Also, the design is a bit too off for how many users are on mobile, large/small screens, etc.  

No worries tho--there are some clear solutions: 

1. Adjust trigger space to things like  "nepal earthquake relief" "support nepal" "nepal earthquake help" and the like. 

2. Simplify the purpose of the IA. If it's to list ways of helping, then it can be done without much explanation. Further, some charities are bound to get criticism. 

I would recommend
      Donate:  [Link to master list of vetted charities like http://www.charitynavigator.org/index.cfm?bay=content.view&cpid=1888#.VUKICBc32Gg ] 
      Raise Awareness: Activate members of your online and offline communities to help victims of the earthquake in Nepal.

3. Fit to a template? e.g. https://github.com/talsraviv/duckduckgo-documentation/blob/spice-templates-overview/duckduckhack/spice/spice_templates_reference.md#list_detail-template

**Comment by wongalvis** [comment]
A Goodie can use a Spice template?

**Comment by javathunderman** [comment]
Just curious, could we generalize this IA a bit? We could have it as the "Disaster Relief" IA or something and update it when a major disaster happens.

**Comment by wongalvis** [comment]
@javathunderman That's a very great idea, it could be done in due course however I think at this moment we could merge this PR to let the information become online asap.

**Comment by moollaza** [comment]
@wongalvis this is looking great! We should definitely be using the new Goodie templates though so the HTML doesn't need to be in the Perl. 

Here's some examples of Goodie templates; The logic is very similar to Spice templates: 
- https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Minecraft.pm
- https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/BPMToMs.pm

**Comment by wongalvis** [comment]
It's now using a template :)

**Comment by javathunderman** [comment]
ping @moollaza

**Comment by moollaza** [comment]
Hey guys, sorry for the delay, I'll take a look at this right now.

**Comment by moollaza** [comment]
Alright. This is definitely better but I'm not sure this paragraph conveys the message well. I see that the source is a 
"6 ways to donate" list and TIME has "Another 6 ways to donate" list. It may be best to use the new list template and simply list out all these charities, perhaps with a short description.

I'll speak to the team about how we want to handle this. The benefit of the list approach is that we can easily add to it if we get suggestions.

**Comment by mintsoft** [comment]
I'm going to close this as it's probably too old to be relevant now. Feel free to reopen if you disagree

**Pull request closed without merging**
