### PR TITLE
#DuckDuckHackCEK

### PR DESCRIPTION
**Pull request by gautamkrishnar**
This pull request is created to track the pulll requests submitted as the part duck duck go hackathon held at CEK on 26/9/2015.
http://www.meetup.com/Quack-Hack-Kochi/

NB: this PR is kept closed

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
## A warm welcome to our new contributors ##
@alfredmaliakal @geethuannie94 @athulya95 @chim7 @southernTiger @JAYALAKSHMIP @nikhilzac95 @vineethspph @boney96 @visal19 @cj0003 @karankrishna @Krishnenduk @njk8 @mesooryanarayananb

**Comment by gautamkrishnar** [comment]
cc @moollaza @mintsoft  @yegg :smile:

**Comment by tagawa** [comment]
Thanks for gathering this info together @gautamkrishnar. Is this another Kochi contribution? https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1609

**Comment by gautamkrishnar** [comment]
@tagwa yeah... :smile:

**Comment by gautamkrishnar** [comment]
@tagawa  we can use pull requests for gathering all info about an event on a page. 
Please create a label named events or DuckDuckHack to keep all the pull requests organized

**Comment by zekiel** [comment]
thanks @gautamkrishnar  great idea!

**Pull request closed without merging**
