### PR TITLE
explicitly mentioning the template_type for bash cheat sheet

### PR DESCRIPTION
**Pull request by sagarhani**

### CODE REVIEW

**Comment by mintsoft** [comment]
I'm not sure about the style changes here:
image
image
@abeyang @moollaza any thoughts?

**Comment by moollaza** [comment]
@sagarhani what about the `code` template? Best of both worlds...

I would lean towards terminal, because you do write these at a command line. But Code/Keyboard is a better use of space...

**Comment by GuiltyDolphin** [comment]
@moollaza @mintsoft This was resolved in #2233, it can be closed.

**Comment by mintsoft** [comment]
@GuiltyDolphin it's not been fixed for Bash in #2233

**Comment by GuiltyDolphin** [comment]
@mintsoft Errh.. Right sorry. But it has been resolved. The `template_type` is `code`.

**Pull request closed without merging**
