### PR TITLE
Zodiac: Fix broken images

### LINKED ISSUE #2751: Zodiac: Images aren't showing?
It looks like the images for this IA have broken in production. Possibly an internal issue, but I'm not sure yet. Let's investigate and determine the cause!

------
IA Page:  http://duck.co/ia/view/zodiac 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @n0mady

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
I broke something!

Fixes #2751

---
IA Page: https://duck.co/ia/view/zodiac
Maintainer: @n0mady

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@GuiltyDolphin thanks! Deploying to beta...

**Comment by GuiltyDolphin** [comment]
@moollaza Did I miss something? It doesn't appear to have done anything.

**Comment by moollaza** [comment]
>@moollaza Did I miss something? It doesn't appear to have done anything.

Whoops, yes - that version number needs to be part of the image path :+1:

**Comment by GuiltyDolphin** [comment]
@moollaza Fixed, want to try a re-deploy?

**Comment by moollaza** [comment]
Deployed.Thanks! This LGTM :+1:

**Pull request merged**
