### PR TITLE
New Screen Cheat Sheet

### PR DESCRIPTION
**Pull request by sevazhidkov**
IA Page: 
https://duck.co/ia/view/screen

### CODE REVIEW

**Comment by daxtheduck** [comment]
@sevazhidkov Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by sevazhidkov** [comment]
Sorry, didn't found https://duck.co/ia/view/gnu_screen_cheat_sheet

**Comment by tagawa** [comment]
Hi @sevazhidkov. No problem, and we really appreciate you going to the trouble of creating the cheat sheet. Although it's a duplicate, I see there are some items in your file that are not in the existing cheat sheet so perhaps you could add them with a new PR? For example exit and rename. The existing file is here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/gnu-screen.json

Also, we're currently trying to increase our coverage of programming search queries with this table of Instant Answers: https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage
If you'd like to have a go at filling in some of the gaps please dive in! And of course, let me know if you need any help. Thanks again.

**Pull request closed without merging**
