### PR TITLE
C char manipulation update

### PR DESCRIPTION
**Pull request by ManrajGrover**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`{c-char-manipulation}: {Adds toascii to the cheatsheet}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Provide an overview of the changes this pull request introduces.

This pull request adds `toascii` to the C Character Manipulation Cheatsheet. There were some other methods mentioned in the [source](http://www.gnu.org/software/libc/manual/html_mono/libc.html) but are not part of `ctype.h`. Please share your thoughts on this.

###### Which issues (if any) does this fix?

None

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/c_char_manipulation_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): 

@lemueldsouza

### CODE REVIEW

**Comment by daxtheduck** [comment]
@ManrajGrover Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by zekiel** [comment]
Thanks for the addition @ManrajGrover and welcome to DuckDuckHack! Please let me know if I can help you get started on your own Instant Answers. We'd also love to know if anything can be improved so be sure to reach out with any feedback. 

@lemueldsouza can you please review and OK this change before the [timeout period](http://docs.duckduckhack.com/maintaining/guidelines.html#overseeing-changes)? We'll merge as soon as either occurs.

**Comment by ManrajGrover** [comment]
Hey @zekiel ! Thank you for such warm welcome. :blush: 

There are many more libraries in C that have not been ported to IA. Good examples can be found [here](http://www.tutorialspoint.com/c_standard_library/). Should I develop their Instant Answers?

Also, there is an IA for react but not for react native. Although base is the same, yet both target different platforms, hence some methods differ. Should we create a separate cheat sheet for it?

**Comment by zekiel** [comment]
@ManrajGrover  of course! Just to note, Cheat Sheets are a simplified version of Instant Answers and don't have all the flexibility of a bigger implementation. If there's a lot of data, then it should be harnessed into a [Fathead](https://github.com/duckduckgo/zeroclickinfo-fathead/) or [Longtail](https://github.com/duckduckgo/zeroclickinfo-longtail/) answer. If there's an API to call the data in realtime, it can be a [Spice](https://github.com/duckduckgo/zeroclickinfo-spice/). 

Check out this post on programming IAs: https://duck.co/blog/post/297/help-for-programmers

**Comment by lemueldsouza** [comment]
@ManrajGrover  Looks good to me

**Comment by ManrajGrover** [comment]
@zekiel Sounds great! Thank you for sharing this. I'll get on with it then.

@lemueldsouza @zekiel Awesome! Let's land this then. :blush:

**Comment by zekiel** [comment]
Thanks again @ManrajGrover @lemueldsouza!

**Pull request merged**
