### PR TITLE
Language cheat sheets: add "play pronunciation" feature

### PR DESCRIPTION
**Pull request by Tykzz**
Provides a button near a phrase to play pronunciation audio if given in the JSON file.
19b5ec5e-c606-11e5-90a5-cb0f8d60df55

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
@Tykzz,  thanks again for helping improve the language cheat sheets! You’ve been doing a really good job here and we'd like you to help our community tackle the next big challenge - our mission to become the best search engine for programmers: https://duck.co/blog/post/297/help-for-programmers.

When you're ready to move on, please: 

- Create a new Instant Answer to increase our Programming IA coverage

OR

- Test live programming Instant Answers (or those in development) for bugs and suggest improvements 

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage).

Thanks again!

**Comment by Tykzz** [comment]
@edgesince84:
The changes I proposed haven't been even discussed after above 2 months. How come you expect me to spend more time on contributing here if you ignore this pull request?

**Comment by moollaza** [comment]
> How come you expect me to spend more time on contributing here if you ignore this pull request?

@Tykzz my sincere apologies, I thought I had gotten around to giving you feedback on this PR around the time I asked you to make it. Sometimes things fall through the cracks, but we're working to ensure that doesn't happen anymore. We really do appreciate you taking the time to submit this code and we did not intend to ignore this.

With regards to the changes you've proposed, as-is we can't use them because the client cannot make a direct request to any third-party, as we consider that a privacy breach (their IP will be exposed). So the code will need to be modified to proxy the request through DDG. As well, you've used the `<audio>` element and I'm not sure how well that would work across other desktop/mobile browsers. We have a soundplayer element which can be used here to ensure full browser/device support. Examples of its usage can be seen in the Forvo and Dicitonary Instant Answers.

On a higher level I'm more concerned about how this feature would be used moving forward. Do we have a source that can provide audio pronunciations for all or most of the other language cheat sheets we have?

Do you/we expect CheatSheet maintainers to go back and add a URL for each phrase in their cheat sheet? That approach seems like a lot of work.

I'm wondering if there's a way to dynamically add pronunciations, assuming we have a source that can be used. For example, Google's translate has a feature that allows audio to be played for the translated text across several languages. Could we emulate that? Bing seems to have a paid text-to-speech API, is there a free alternative? A solution like that seems more robust and would mean we wouldn't have to maintain an extra URL for every entry in all the language cheat sheets.

What are your thoughts on this?

---

If you really want to help DuckDuckHack though, our main focus right now is to make DuckDuckGo the best search engine for programmers, because then we can get more developers to join our community and have more people involved in DuckDuckHack. As the community grows, we'll have more people available to help improve and push the limits of the platform and Instant Answers, such as you've done here with this pull request.

**Comment by Tykzz** [comment]
> We have a soundplayer element which can be used here to ensure full browser/device support. Examples of its usage can be seen in the Forvo and Dicitonary Instant Answers.

Here is the code from Dictionary Instant Answer:
2016-04-21 08_09_19-book definition na duckduckgo

Is it enough to use these CSS classes plus _data-url_ to make it work? If not where can I find documentation for this?

> On a higher level I'm more concerned about how this feature would be used moving forward.

First of all, what is the main use case for a language cheat sheet? I think it's someone who doesn't know the language, trying to get some useful basic phrases that they can use visiting the country.
If so, what someone might think of a cheat sheet without pronunciation provided? That it's useless. Because in most cases pronunciation of a phrase won't be obvious.

> Do we have a source that can provide audio pronunciations for all or most of the other language cheat sheets we have?

> Do you/we expect CheatSheet maintainers to go back and add a URL for each phrase in their cheat sheet?

> For example, Google's translate has a feature that allows audio to be played for the translated text across several languages. Could we emulate that? Bing seems to have a paid text-to-speech API, is there a free alternative?

I think it should be possible to find audio for most of basic phrases. However TTS could be enabled by default. From what I found, it was possible to use Google TTS API for free but they've blocked the access not long ago and now it requires a paid API key.

I found a free alternative - [ResponsiveVoice.JS](http://responsivevoice.org/). It covers quite many languages but not all needed.

**Comment by moollaza** [comment]
> Is it enough to use these CSS classes plus data-url to make it work? If not where can I find documentation for this?

Unfortunately it's more complex than that. Here's how Forvo add's the players: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/forvo/forvo.js#L70


> I found a free alternative - ResponsiveVoice.JS. It covers quite many languages but not all needed.

This looks awesome. however it is not free for commercial uses -- is there anything else similar?

**Comment by Tykzz** [comment]
@moollaza 
> it is not free for commercial uses -- is there anything else similar?

Unfortunately I've not found anything else which would be free and with no limits like for the number of requests.
By the way, I didn't know that DDG search engine qualifies as commercial.

**Comment by moollaza** [comment]
> By the way, I didn't know that DDG search engine qualifies as commercial.

@Tykzz to most companies, we would be considered a commercial user because we are indirectly profiting. For example, there could be ads displayed alongside the cheat sheet, which we earn a profit from.

**Pull request closed without merging**
