### PR TITLE
Update Travis to use faster container-based (Docker) infrastructure

### PR DESCRIPTION
**Pull request by moollaza**
Travis offers a [new, faster infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) that uses Docker. The only downside is that it doesn't allow for `sudo` access. 

This PR cleans up the dist.ini (we have duplicate commands in the dist and travis.yml file) and updates travis.yml to install our only system dependency, GNU MPFR, via a shell script, to avoid the use of `sudo`

Travis also allows for caching of folders and packages, we could potentially cache the CPAN packages but I'm not sure about that

### CODE REVIEW

**Comment by jagtalon** [comment]
@moollaza @mintsoft 

> Goodies repo that contains the binaries of the system packages

Will get big when we add binaries for multiple platforms too!

> Actually there's a few other single-goodie repos

I think my main problem with separate repos (now that we're getting a lot) is that people don't see them. Too fragmented.

I don't think we should move the IAs that need MPFR and Guitar Chords somewhere else just because Travis Docker can't use them. I think as long as we can install it on TravisCI + Codio we shouldn't do anything.

**Comment by mintsoft** [comment]
@jagtalon I know what you mean, it feels like a difficult balance to get right. 

If I (for example) created a new goodie that had a requirement on a system module etc I presume there are implications for the live environment as well as Travis and dev. Out of curiosity, how is that handled? Is there something we can adapt for duckpan/Travis?

**Comment by jagtalon** [comment]
@mintsoft currently we have our own repo using Pinto although @malbin might have more insight into this problem

**Comment by jagtalon** [comment]
@moollaza We might be limited to what TravisCI can do similar to https://github.com/duckduckgo/zeroclickinfo-spice/pull/1456--we can't just edit .travis.yml :/

**Comment by moollaza** [comment]
Closing for now. Hopefully we fix this soon!

**Pull request closed without merging**
