### PR TITLE
Added game of thrones houses

### PR DESCRIPTION
**Pull request by zekiel**
//cc @moollaza 

---

IA Page: https://duck.co/ia/view/game_of_thrones_houses_cheat_sheet

### CODE REVIEW

**Comment by zekiel** [comment]
need to fix this up a little --- wip

**Comment by javathunderman** [comment]
Commenting for updates...

**Comment by zekiel** [comment]
updated (fixed capitalization). No other intended changes so removing WIP label. Please let me know if you'd like to see other changes.

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
@zekiel congrats! It's live: https://duckduckgo.com/?q=game+of+thrones+houses+cheat+sheet&ia=cheatsheet

**Pull request merged**
