### PR TITLE
New IndianArmyRanksCheatSheet Cheat Sheet

### PR DESCRIPTION
**Pull request by shadabk**
- [x] New Instant Answer
    - [x] Cheat Sheets: **`New  IndianArmyRanksCheatSheet Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}:  `**

###### Description of changes
Displays the ranks in Indian Army in decreasing order of authority. 

---

Instant Answer Page: https://duck.co/ia/view/indian_army_ranks_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @shadabk

### CODE REVIEW

**Comment by daxtheduck** [comment]
@shadabk Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@shadabk Do you think this would be better merged into https://duck.co/ia/view/military_rank? cc @lowellosaurus

**Comment by shadabk** [comment]
@GuiltyDolphin the two are different in a way that my cheat sheet doesn't provide the insignia or the same CSS formatting.

**Comment by lowellosaurus** [comment]
I've created a [pull request ](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3444) to add the Indian Armed Forces (all three major branches) to the [military rank]( https://duck.co/ia/view/military_rank) instant answer.

The only major feature that this cheat sheet has that the pull request above does not, is the inclusion of rank class (officer/JCO/NCO/enlisted). [Moollaza pointed out](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3299#issuecomment-229193910) an easy way to add on this grouping functionality, and after I get around to issuing a PR for that change, the MilitaryRank instant answer should have all of the features of this cheatsheet (and more!).

**Comment by tagawa** [comment]
Hi @shadabk. Thank you very much for this pull request. @lowellosaurus has just added the data from your cheat sheet into the existing army rank Instant Answer: https://beta.duckduckgo.com/?q=indian+army+ranks&t=ha&ia=answer

What do you think? Does it cover what's needed?

**Comment by shadabk** [comment]
@tagawa I have reviewed the improvement by @lowellosaurus , it works fine and covers what's needed.

**Comment by tagawa** [comment]
Thank you very much @shadabk. I'll close this then, and everything can be incorporated in #3444

**Pull request closed without merging**
