### PR TITLE
New Advanced Package Tool Cheat Sheet

### PR DESCRIPTION
**Pull request by tsimonq2**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**

###### Description of changes

This provides a cheat sheet for Debian's apt tool.

---

Instant Answer Page: https://duck.co/ia/view/advanced_package_tool

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tsimonq2

### CODE REVIEW

**Comment by daxtheduck** [comment]
@tsimonq2 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@tsimonq2 Hiya; thanks for the PR, however we already have an apt-get cheatsheet: https://duckduckgo.com/?q=apt-get+cheatsheet&ia=answer I think that would cover most of the content of this one? Are you interested in extending the aliases perhaps to cover both?

**Comment by tsimonq2** [comment]
@mintsoft Hello, I've asked the apt team themselves for clarification, and they would prefer us to cite apt instead of apt-get. I would be willing to work with the maintainer of the apt-get reference to get things converted over, that's just what I've been told from the team working on apt.

@abadojack and @altern8tif What would you like to do? I can go either way. :)

**Comment by abadojack** [comment]
@tsimonq2 Hey

 It would be more awesome if you made the necessary changes to the existing Cheat Sheet instead of creating a new one.

**Comment by tsimonq2** [comment]
@abadojack I'll do that, thanks. :)

**Pull request closed without merging**
