### PR TITLE
Esperanto cheat sheet: Correct grammatical errors

### PR DESCRIPTION
**Pull request by abadojack**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [* ] Improvement
    - [* ] Enhancement: **`Esperanto cheat sheet: Correct grammatical errors`**

###### Description of changes

Corrects grammatical errors in the current cheat sheet.

###### People to notify (@mention interested parties)
@GuiltyDolphin 

---

Instant Answer Page: https://duck.co/ia/view/esperanto_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @abadojack

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
Thanks, @abadojack, I'm a big fan of grammar corrections! 💃

**Comment by tagawa** [comment]
We also received the following feedback (thanks [Edward](https://twitter.com/EdwardVanWinkle)):

Basics

    I'm fine, thanks!
    Bone, dankon!
    (Also: Mi estas bone, dankon!)

Getting Help

    I am allergic.
    Mi estas alergia.
    (Mi havas alergion. - sounds better to me. It's literally, "I have an allergy." rather than "I'm alergy-y.")
    Can you repeat, please?
    Ĉu vi povus ripeti, bonvolu?
    How do you say "X" in Esperanto?
    Kiel oni diras "X" en esperanto?
    (Also: Kiel oni diras "X" esperante?)
    (I don't think languages and nationalities are capitalized in Esperanto.)
    Stop
    Ĉesu
    Do you speak English?
    Ĉu vi parolas la anglan?
    Write it down please!
    Bonvolu ĝin skribi!
    (Also, and perhaps slightly more natural: Bonvolu skribi ĝin!)
    Call an ambulance!
    Voku ambulancon!
    I am in danger!
    Mi estas en danĝero!
    (I'm honestly not sure about this one. It may be ok, but it sounds funny to me.)
    Can you help me?
    Ĉu vi povus helpi min?

Travelling

    Turn left.
    Turnu maldekstren.
    Where is the exit?
    Kie estas la elirejo?
    Is it far?
    Ĉu ĝi estas malproksima?
    Go straight ahead.
    Iru rekten.
    Do you have a city map?
    Ĉu vi havas urban mapon?
    (I fixed the accusative here.)
    (The above has the connotation of an "urban map." For "Do you have a map of the city?" I'd use: Ĉu vi havas mapon de la urbo?)

Etiquette

    Good morning
    Bonan matenon
    Good evening
    Bonan vesperon
    Good night
    Bonan nokton
    I'm sorry.
    Pardonu.
    Thank you (very much)
    (Koran) dankon
    You're welcome (for 'thank you')
    Nedankinde

**Comment by abadojack** [comment]
I have made the changes as per the feedback.

**Comment by abadojack** [comment]
Could someone merge this please

**Comment by mintsoft** [comment]
@tagawa Is this good to go?

**Comment by tagawa** [comment]
Thank you for implementing those so quickly @abadojack. We haven't received any further comments over the weekend so merging this.

Thanks for another good Instant Answer. If you'd like inspiration for more, feel free to take a look at the programming IA coverage table (if you haven't already): https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage

**Pull request merged**
