### PR TITLE
francisbrito's First Goodie

### PR DESCRIPTION
**Pull request by francisbrito**
**What does your Instant Answer do?**
Tells the world how awesome I'm for creating my first goodie.

**What are some example queries that trigger this Instant Answer?**
duckduckhack francisbrito

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Me and my dev. friends

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No

**Where did you hear about DuckDuckHack? (For first time contributors)**
At the "We're hiring" article in [Duck.co](https://duck.co/help/company/hiring)

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
duckduckhack-francisbrito

## Checklist
Please place an 'X' where appropriate.

```
- [X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [X] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

```

### CODE REVIEW

**Comment by mintsoft** [comment]
@francisbrito Congratulations on your first goodie! :tada:

**Comment by francisbrito** [comment]
Woot! Thanks @mintsoft

**Comment by moollaza** [comment]
@francisbrito congrats! It's live: https://duckduckgo.com/?q=duckduckhack+francisbrito&ia=answer

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Comment by francisbrito** [comment]
Awesome. Thank you very much @moollaza!

**Pull request merged**
