### PR TITLE
Add brackets.json

### PR DESCRIPTION
**Pull request by KK4OXJ**
**What does your Instant Answer do?**
Provides a cheatsheet of keyboard shortcuts for [Brackets](http://brackets.io)

**What is the data source for your Instant Answer? (Provide a link if possible)**
https://github.com/adobe/brackets/wiki/Brackets-Shortcuts

**Why did you choose this data source?**
It was the only list I could find

**Are there any other alternative (better) data sources?**
Not that I know of (if there are, please let me know!)

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Developers who use Brackets

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No, should I have created a submission over there? 

**Are you having any problems? Do you need our help with anything?**
Since some of the extensions cause certain keyboard shortcuts to have `Cmd + G` do different stuff than `Ctrl + G`, I left out the extensions and CodeMirror sections which I originally had. If someone is able to sort out how to do all of the keyboard shortcuts so I know how to put them in for non-Mac, I'd love to do that, but I don't know how to put them in the way they are. 

**Where did you hear about DuckDuckHack? (For first time contributors)**
Not sure, I've been using DuckDuckGo and wishing I could make an IA for it for a long time :smile: 

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
brackets cheatsheet

### CODE REVIEW

**Comment by moollaza** [comment]
@KK4OXJ thanks for your contribution!

Can you please fill out the [pull request template](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/pull_request_template_cheat_sheet.md) and edit your initial comment. Once completed, we'll be sure to review your PR and give you some feedback.

Thanks!

**Comment by KK4OXJ** [comment]
@moollaza is that good? ^

**Comment by moollaza** [comment]
@KK4OXJ apologies for the delay! Excellent work though, this LGTM :+1:

Thanks a lot for contributing (we really appreciate it :smiley:). We invite you to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

**Comment by KK4OXJ** [comment]
@moolaza Cool! & I definitely plan on doing more stuff with DuckDuckGo IAs soon :smiley:

**Pull request merged**
