### PR TITLE
Add MySQL functions

### PR DESCRIPTION
**Pull request by himanshu53**
###### What does your Pull Request do (check all that apply)?
- [x] Improvement
  - [x] Enhancement: **`{PHP Cheat Sheet}: {Added MySQL functions}`**
###### Description of changes

Added MySQL functions to this cheat sheet
###### Which issues (if any) does this fix?

https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3183
###### People to notify (@mention interested parties)

@rathoreanirudh @shahbaz17 

---

Instant Answer Page: https://duck.co/ia/view/php_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rathoreanirudh

### CODE REVIEW

**Comment by daxtheduck** [comment]
@himanshu53 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by alohaas** [comment]
Hey thanks @himanshu0113! Do you think you can add a source to the metadata for where you got the list of MYSQL functions?

**Comment by ManrajGrover** [comment]
@zekiel @moollaza Looks like maintainer period is over now. :smile: Lets land this.

**Comment by zekiel** [comment]
@himanshu0113  would you like to add a source per @alohaas' comment? 

@ManrajGrover  we can merge any time now, just waiting to see if we can add a source here.

**Comment by himanshu0113** [comment]
Hey @alohaas @zekiel  @ManrajGrover , sorry for this late reply. Actually I am not the maintainer of this cheat sheet, so I dont know its source. Its @himanshu53 :P

**Comment by himanshu53** [comment]
Sorry for the late reply, Here is  a link of MySQL functions source.
Hey @alohaas , it's me who did the changes and you mentioned another @himanshu0113 .
:-)

**Comment by shahbaz17** [comment]
I guess now this cheatsheet is ready to be merged ??
What do you say @alohaas @zekiel  ???

**Comment by alohaas** [comment]
Thanks @himanshu0113  and @shahbaz17 !

**Comment by alohaas** [comment]
It looks like there are some conflicts with the branch. @himanshu53 can you look into it?

**Comment by GuiltyDolphin** [comment]
@himanshu53 Those conflicts are still hanging around, have you had a chance to look into this?

**Comment by pjhampton** [comment]
Closing as this PR looks to have gone stale.

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄

**Pull request closed without merging**
