### PR TITLE
Update PR Template with more explicit instructions

### PR DESCRIPTION
**Pull request by moollaza**
Thoughts?

/cc @zekiel @talsraviv @tagawa

### CODE REVIEW

**Comment by zekiel** [comment]
:+1:

**Comment by tagawa** [comment]
clicking the, "Preview changes"
->
clicking the "Preview changes"
(no comma)

**Comment by moollaza** [comment]
@zekiel @tagawa thanks! I added a gif too, should help make things super clear

**Comment by tagawa** [comment]
View the **raw** text by visiting
->
Use the **raw** text at

Perhaps?

**Comment by moollaza** [comment]
@tagawa :+1:

**Comment by tagawa** [comment]
Make sure you don't include
->
Don't include

Just trying to think of ways to make it less verbose, as the template itself already has a lot of text (especially for non-native English speakers).

**Comment by moollaza** [comment]
@tagawa :+1:

**Comment by tagawa** [comment]
easier for everyone to read
->
easier for everyone to read.

Last one, I promise!

**Pull request merged**
