### PR TITLE
Rahul/bmi calc

### PR DESCRIPTION
**Pull request by rahuldecoded**
Modify the bmi calculator

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by rahuldecoded** [comment]
Want to modify this existing IA

https://duck.co/ia/view/interactive_bmi_calculator

**Comment by edgesince84** [comment]
Hi Rahul, we'll check this one out for you soon

**Comment by tagawa** [comment]
Hi @rahuldecoded. It looks like this pull request is empty - is that intentional or are you planning to push more changes?

**Comment by gaulrobe** [comment]
We should be careful here because of #2118

Lots of people wanted to try finishing that IA up, but @vishivish18 was the first. Maybe if @rahuldecoded or any of the others want to work with @vishivish18 that'd be fine?

**Comment by rahuldecoded** [comment]
On Thu, Jun 23, 2016 at 11:46 PM, Robert Gaul <notifications@github.com>
wrote:

> We should be careful here because of #2118
> <https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2118>
>
> Lots of people wanted to try finishing that IA up, but @vishivish18
> <https://github.com/vishivish18> was the first. Maybe if @rahuldecoded
> <https://github.com/rahuldecoded> or any of the others want to work with
> @vishivish18 <https://github.com/vishivish18> that'd be fine?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3265#issuecomment-228136946>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AO9bqecWhpJ3JOfdPvR3FsXAbOKtW9d6ks5qOs2OgaJpZM4I4APv>
> .
>
Ya that's why I am backing off from this IA. I will make a new IA later
after I finish my exam.

**Comment by moollaza** [comment]
> Ya that's why I am backing off from this IA. I will make a new IA later
> after I finish my exam

@rahuldecoded I'll close this for now. If needed we can re-open later 👍

**Pull request closed without merging**
