### PR TITLE
Apache Pig Cheat Sheet: trailing whitespaces fix

### PR DESCRIPTION
**Pull request by 122131**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [X] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [X] Enhancement: **`Apache Pig Cheat Sheet: Trailing whitespaces fix`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Removed trailing whitespaces

---

Instant Answer Page: https://duck.co/ia/view/apache_pig_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mohan08p

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by 122131** [comment]
I would like to remove other trailing whitespaces in other cheat sheets... Do I need to open different pull requests or one is enough?

**Comment by 122131** [comment]
I'll open a more complete one when i have fixed all trailing whitespaces in Travis CI build.

**Comment by 122131** [comment]
fixed in #3280

**Pull request closed without merging**
