### PR TITLE
Calculator: Amend fact() display to show factorial()

### LINKED ISSUE #1917: Calculator: Operation for `fact()` should be "factorial"
When computing only the factorial of a number, regardless of the query, we should show the operation as "factorial" instead of "fact"

i.e. it should look like this:

fact_3__at_duckduckgo

---

IA Page:  http://duck.co/ia/view/calculator

### PR DESCRIPTION
**Pull request by altern8tif**
Fixes #1917.

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata post coming soon

**Comment by GuiltyDolphin** [comment]
@altern8tif I'm working on re-writing the calculator. See [this](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1880) issue. I'm almost ready to make a PR. In the new calcuator, the factorial function does indeed display `factorial(ARG)`.

**Comment by altern8tif** [comment]
@GuiltyDolphin Ah ok... I guess I'll close this PR then?

**Comment by GuiltyDolphin** [comment]
It's up to @moollaza or @mintsoft I guess, but it might cause some merge conflicts as we'd be changing the same file.

**Comment by altern8tif** [comment]
@GuiltyDolphin no worries... It'll be easier if I close it :+1:

**Pull request closed without merging**
