### PR TITLE
Excel cheatsheet: Add aliases and fix typo

### PR DESCRIPTION
**Pull request by tagawa**
https://duck.co/ia/view/microsoft_excel_cheat_sheet

Maintainer: @ankushg07

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Microsoft Excel cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/microsoft_excel_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Microsoft Excel cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/microsoft_excel_cheat_sheet_mobile.png)

**Comment by ankushg07** [comment]
@tagawa @moollaza thank you for fixing typos 
will surely take care of these small mistakes 
alias LGTM 
thanx @tagawa

**Comment by tagawa** [comment]
@ankushg07 You're welcome - and thanks for creating another instant answer!

**Pull request merged**
