### PR TITLE
support of multiplication unicode

### PR DESCRIPTION
**Pull request by RomainLG**
Sorry for the lack of description it's #1243 fix

Will need to add support to the minus unicode if we go that way.

But the whole thing is unnecessary IMO

### CODE REVIEW

**Comment by moollaza** [comment]
@RomainLG I believe you should be OK to put the actual Unicode character in the code, but you'll need to add `use utf8;` to the package.

> But the whole thing is unnecessary IMO

I agree it's not very likely to occur, but it doesn't hurt to support this. Makes it seem way more "magical" when it actually works without the user expecting it to :smile:

**Comment by moollaza** [comment]
@RomainLG it looks like another contributor has made a PR wich adds this functionality (though they did it after you!)

Would you like to update your PR accordingly, or shall I close this and merge theirs?

See #1262

**Comment by RomainLG** [comment]
@moollaza 

Merge his! He did it better than I did!

I've got some question though, he used the unicode `×` directly whereas I used the corresponding code `\x{00D7}` because upon testing the unicode wasn't working.

Any idea why it's that way? Is it better to use the unicode?

What is the `*.t` file use? It's so the instant answer can get tested automatically?

**Comment by mintsoft** [comment]
@RomainLG Sorry for the delay. Personally I prefer to `use utf8` and have the symbols in the source as it's easier to see what's happening at a glance rather than having to look up codes. 

The `*.t` file is so we can write tests to ensure that we don't break existing functionality when we improve or extend instant answers!

**Comment by mintsoft** [comment]
@RomainLG I'm going to close your PR for the time being in favour of https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1264 Thanks for the contribution anyway!

**Pull request closed without merging**
