### PR TITLE
DjangoModelCheatSheet: Change template_type to reference, add more triggering aliases

### LINKED ISSUE #2940: Django Instant answer suggestions
Hi there,

I was just testing the Django Instant Answers, and saw that it only seems to come up when you search for "Django Model Cheat Sheet" - which won't get new users to find it. I think it'd be great if it also comes up when the user searches:

- Django model reference
- Django model
- Django model field
- Django model fields
- Django model Relationships (maybe not this one, not sure)
- and probably almost anything that has https://docs.djangoproject.com/en/stable/topics/db/models/ as a top result.

In my testing, the cheat sheet didn't show up on the DDG beta site for any of those searches, but did show up if I specifically put in "cheat sheet" after "django model", but let me know if I'm testing incorrectly! Thanks!

https://duck.co/ia/view/django_model_cheat_sheet

### PR DESCRIPTION
**Pull request by sahildua2305**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [x] Bug fix: **`DjangoModelCheatSheet: Fix #2940`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Provide an overview of the changes this pull request introduces.

IA now has more triggers as mentioned in the issue and has template_type = `reference` which makes more sense in this case since more users will be looking for `Django model reference` rather than `Django model commands`. This is my opinion. I am seeking suggestions about this.

###### Which issues (if any) does this fix?

Fixes #2940 

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/django_model_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): 
@pjhampton

### CODE REVIEW

**Comment by daxtheduck** [comment]
@sahildua2305 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
Thanks for making quick work of this, @sahildua2305.  We'll get some eyes on this soon! cc  @moollaza

**Comment by sahildua2305** [comment]
@edgesince84 I am not sure about the Travis build failing though.

**Comment by pjhampton** [comment]
Yeah, definitely @sahildua2305. Thanks for all your help! 
See this! https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/builds/136445644#L678 😉

**Comment by pjhampton** [comment]
Yeah, @sahildua2305. I believe it is just that bi-gram that is causing the problem! 🎸

**Comment by sahildua2305** [comment]
@pjhampton Thanks for pointing me at the error message. Made the changes, works now.

**Comment by edgesince84** [comment]
@pjhampton 🙇 thanks for the input

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

**Comment by pjhampton** [comment]
Thanks so much @sahildua2305! Great job as usual.

**Pull request merged**
