### PR TITLE
Issue #1418 - Factorial: Move integration into Calculator.pm

### PR DESCRIPTION
**Pull request by Mailkov**
I added factorial function to calculator, 
now I don't know if Factorial.pm and Factorial.t must be deleted

-----
IA Page: https://duck.co/ia/view/calculator

### CODE REVIEW

**Comment by moollaza** [comment]
@Mailkov this is looking awesome!

Can this handle factorials as sub-expressions? e.g `factorial(3) + 34`

**Comment by moollaza** [comment]
> now I don't know if Factorial.pm and Factorial.t must be deleted

Yes, they can be removed in this PR :+1:

**Comment by Mailkov** [comment]
@moollaza
> Can this handle factorials as sub-expressions? e.g factorial(3) + 34

Yes, the answer is 40

**Comment by daxtheduck** [comment]
Automated screenshot from https://beta.duckduckgo.com
                
                mobile: https://ia-screenshots.s3.amazonaws.com/calculator_mobile.png

**Comment by Mailkov** [comment]
@moollaza 
I'm noticing that some expressions do not work: e.g sin(10)+sin(10) 
I think it is a bug .... There is an issue about this bug?

**Comment by mintsoft** [comment]
@Mailkov not explicitly, I'd probably raise an issue for it if I were you so we can tackle it separately

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=$3.43+$34.45)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/calculator_mobile.png)

**Comment by moollaza** [comment]
@Mailkov Thanks! This LGTM :+1:

**Pull request merged**
