### PR TITLE
hindi cheat sheet

### PR DESCRIPTION
**Pull request by santoshdistro**
What does your Instant Answer do?

Provides basic English to Hindi translation

What is the data source for your Instant Answer? (Provide a link if possible)

http://www.omniglot.com/language/phrases/hindi.php

Why did you choose this data source?

It provides most common hindi word spoken

Are there any other alternative (better) data sources?

Yes

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)

Traveler

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?

No

Are you having any problems? Do you need our help with anything?

NO

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
hindi

### CODE REVIEW

**Comment by daxtheduck** [comment]
@santoshdistro Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub username:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MariagraziaAlastra** [comment]
Hey @santoshdistro, thanks for your contribution!
Is [this](https://duck.co/ia/view/english_to_hindi_cheat_sheet) the IA Page for your cheat sheet? 
If yes, could you please link to it in your first comment here?
Find more info [in the docs](http://docs.duckduckhack.com/submitting/pull-request.html#submitting-a-pull-request).
Thanks!

**Comment by jophab** [comment]
@santoshdistro A hindi chaet sheet is already there.
check this and eidt/add content.then make a new pr :+1:  
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/language/hindi.json

**Comment by moollaza** [comment]
Closing as a duplicate. @santoshdistro thanks for contributing, please make sure your Instant Answer doesn't already exist.

As @jophab said, checkout the existing cheat sheet. I don't think any changes are necessary but if you think so please submit a pull request for discussion.

**Comment by tagawa** [comment]
@santoshdistro, thanks again for trying to create the Hindi cheat sheet! Sorry it wasn't merged but you’ve done a really good job here and we'd like you to help our community tackle the next big challenge - our mission to become the best search engine for programmers: https://duck.co/blog/post/297/help-for-programmers.

When you're ready to move on, please: 

- Create a new Instant Answer to increase our Programming IA coverage

OR

- Test live programming Instant Answers (or those in development) for bugs and suggest improvements

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage).

Thanks again!

**Pull request closed without merging**
