### PR TITLE
Bug Fix: Restore Heroku Cheat Sheet

### PR DESCRIPTION
**Pull request by laurenancona**
This restores the original Heroku Cheat Sheet (https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1730) which for some reason was deleted from master in https://github.com/duckduckgo/zeroclickinfo-goodies/commit/721dd1efc2566d214bb0cc76669da79e3f588d29. I've some proposed updates coming in a separate PR.

@GuiltyDolphin 

---

Instant Answer Page: https://duck.co/ia/view/heroku_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @checkaayush

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@laurenancona Would you mind doing this as a revert? (Just find the commit and `revert` it); that'd add some useful info (and make it clearer what this does).

**Comment by laurenancona** [comment]
Ok @GuiltyDolphin, that should do it for now.

**Comment by mintsoft** [comment]
Many Thanks @laurenancona

**Pull request merged**
