### PR TITLE
Minecraft: Links switched to HTTPS

### PR DESCRIPTION
**Pull request by 122131**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer
  - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [x] Enhancement: **`{Minecraft}: {Links switched to HTTPS}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Used secure connections for main source links (to Gamepedia) and remote image source links (to minecraftxl), as proposed by @jomo in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3284#issuecomment-234307899
###### People to notify (@mention interested parties)

@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/minecraft

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @engvik

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
HTTPS is always appreciated!

**Comment by alohaas** [comment]
@122131 I deployed your changes to the beta server and it looks like the image source is not loading https://beta.duckduckgo.com/?q=cake+minecraft&ia=answer 😢

**Comment by 122131** [comment]
@alohaas It's really strange... I can see the images directly from HTTPS sources, but it seems that the URL used doesn't load.

So:
**https**://www.minecraftxl.com/images/wiki/recipes/cake-crafting.png    **Works**

//images.duckduckgo.com/iu/?u=**https**%3A%2F%2Fwww.minecraftxl.com%2Fimages%2Fwiki%2Frecipes%2Fcake-crafting.png&f=1 **Doesn't work**

_BUT_

**http**://www.minecraftxl.com/images/wiki/recipes/cake-crafting.png   **Works**

//images.duckduckgo.com/iu/?u=**http**%3A%2F%2Fwww.minecraftxl.com%2Fimages%2Fwiki%2Frecipes%2Fcake-crafting.png&f=1 **Works**

@moollaza, do you have any ideas? :confused:

**Comment by tagawa** [comment]
Strange - another IA, Military Rank, pulls in images from Wikipedia over HTTPS successfully, for example: `//images.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F0%2F0d%2FArmy-POL-OR-01.svg&f=1`

I'm not sure what's happening here so we probably need to wait for @moollaza to return with his advice.

**Comment by jomo** [comment]
The culprit is probably missing SNI support in the DDG image proxy. upload.wikimedia.org doesn't use SNI whereas any website using CloudFlare (including minecraftxl.com) requires SNI since CloudFlare serves many websites with different certificates on a single IP.

Looks like the image proxy indeed does not send the SNI extension: https://images.duckduckgo.com/iu/?u=https://sni.velox.ch/&f=1

**Comment by jomo** [comment]
FWIW, the proxy also forwards all of a client's request headers. I don't think that's intended and there might be some privacy concerns.

**Comment by edgesince84** [comment]
thanks for the review, @jomo!

**Comment by tagawa** [comment]
Thanks @jomo. I've passed that on to our ops team to investigate, so I'm putting this on hold until we get that sorted.

**Comment by mintsoft** [comment]
@122131 Apologies it took so long to get around to this; if you can resolve the conflicts on the branch I think it'll be good to go 👍

**Comment by moollaza** [comment]
@mintsoft I don't think we ever got around to adding SNI support...

Deploying to Beta to test this out.

We may have to close this until a later time as this PR and SNI support are a low priority right now.

**Comment by moollaza** [comment]
Looks like the images aren't working. Unfortunately I'm going to have to close this.

@122131 thanks for the awesome work, sorry we can't use this right now. If/when we add SNI support we can re-visit this.

**Pull request closed without merging**
