### PR TITLE
New 2048 Game Goodie

### PR DESCRIPTION
**Pull request by moollaza**
Continuing PR #1885 

Partially addresses #1637 -- _still some work to be done!_

-----
IA Page: https://duck.co/ia/view/game_2048

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@codenirvana are you still interested in finishing this up?

- It looks like the responsiveness is breaking when we reach mobile sizing
- We should use our own font-size, color and background-color classes in the HTML where possible to simplify the CSS. This also helps ensure it works for the dark theme
- Disable on mobile (for now), until we add in handling for swiping on mobile

Once those are fixed this can go live!

**Comment by moollaza** [comment]
@duckduckgo/community-leaders anyone interested in getting this one ready for launch?

I think the major remaining problem is the Mobile UI + functionality. We need to disable this on mobile until we add support for touch events.

After that I think this is as good as we need a V1 to be :+1:

**Comment by moollaza** [comment]
@Roysten you mentioned you were interested before -- are you still?

**Comment by Roysten** [comment]
@moollaza I can look into it. I have not followed the development on this PR, can you clearly state what still needs to be done? Your last two messages on this PR confuse me :-)

Do you want to disable the mobile functionality? If not, is there a solution for touch events? The last time I worked on this goodie you were going to discuss it internally, if my memory serves me right.

**Comment by codenirvana** [comment]
@moollaza thanks for fixing the conflicts and continuing this PR. Sorry to left this in middle, I was busy with my college projects for the past 3 months that I almost forgot about this!

I think the touch events was working previously but their are some responsiveness bugs in small screen. According to me work left is:
- [ ] Disable this on mobile.
- [ ] Animating tiles

Due to its previous structure and functionality its impossible to animate the tiles. So in order to add tile animations we need to start creating this from the beginning or leave as it is i.e, without tile animation.

**Pull request closed without merging**
