### PR TITLE
Convert Atbash to text template

### PR DESCRIPTION
**Pull request by mintsoft**
Lo,

Fixes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1887 by switching to the text template

https://duck.co/ia/view/atbash

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata post coming soon

**Comment by moollaza** [comment]
deploying to beta...

**Comment by tagawa** [comment]
I'd forgotten about this one. Thanks @mintsoft.

**Comment by moollaza** [comment]
@mintsoft I've added in `html_enc()` to fix: https://beta.duckduckgo.com/?q=atbash+%3Cscript%3E%3C%2Fscript%3E

**Comment by moollaza** [comment]
@mintsoft Thanks! This LGTM :+1:

**Pull request merged**
