### PR TITLE
mougias's First Goodie

### PR DESCRIPTION
**Pull request by mougias**
# Goodie Pull Request Template

Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**
It says that I'm awesome!

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Organic links don't say that I'm awesome =(

**What is the data source for your Instant Answer? (Provide a link if possible)**
Plain text

**Why did you choose this data source?**
Because you asked me to!

**Are there any other alternative (better) data sources?**
My ex girlfriend.

**What are some example queries that trigger this Instant Answer?**
duckduckhack mougias

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
community is a general word.  individuals would be more appropriate

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Nope

**Which existing Instant Answers will this one supercede/overlap with?**
None

**Are you having any problems? Do you need our help with anything?**
Nope

**Where did you hear about DuckDuckHack? (For first time contributors)**
remoteworkhunt.com

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

## Checklist
Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:

    None of the ones below.  I'm on Windows 10 technical review, Google Chrome

    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by mintsoft** [comment]
@mougias Congratulations on your first goodie!

**Comment by mougias** [comment]
@mintsoft  hi, thanks =)

good luck with your project.  It's a nice thing to give out to people and you seem to be doing a great job so far.  I hope to find the time to get involved more.

**Comment by moollaza** [comment]
>  I hope to find the time to get involved more.

@mougias that's great to hear! If you don't have the time to develop a new Instant Answer, there's always Github Issues that need someone to tackle them!

**Comment by moollaza** [comment]
@mougias congrats! It's live: https://duckduckgo.com/?q=duckduckhack+mougias&ia=answer

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Pull request merged**
