### PR TITLE
New HistoricalEvents Goodie

### PR DESCRIPTION
**Pull request by moollaza**
## Description of new Instant Answer, or changes
Provides a link to further information for various historical events

## People to notify
@nilnilnil 

---

Instant Answer Page: https://duck.co/ia/view/historical_events

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
One alternative approach I considered for the triggers was to have a list of all the query formats in YAML with a placeholder for event name, and then build the triggers by injecting the event names. That approach might be a little easier to understand?

e.g.

```yaml
---
# query templates
- did the _EVENT_ happen
- did the _EVENT_ really happen
- did the _EVENT_ actually happen
- is the _EVENT_ real
- is the _EVENT_ true
- was the _EVENT_ real
- was the _EVENT_ true
```

**Comment by moollaza** [comment]
@b2ddg this is now live on Moollaza

- https://moollaza.duckduckgo.com/?q=did+the+moon+landing+happen%3F&ia=answer

**Comment by daxtheduck** [comment]
@moollaza this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
