### PR TITLE
Fix regular expression for angle brackets

### LINKED ISSUE #2097: Feature request: Support line breaks in cheat sheets
For example being able to include code such as:
```
switch control expression {
  case pattern 1:
    statements
  case pattern 2 where condition:
    statements
  case pattern 3 where condition, pattern 4 where condition:
    statements
  default:
    statements
}
```
Suggestion by @gautamkrishnar

### PR DESCRIPTION
**Pull request by vikashvverma**
Many of the cheat sheets that are using (&lt;br/&gt;) for new line are not displayed properly.
This PR introduces line breaks and fixes #2097

### CODE REVIEW

**Comment by daxtheduck** [comment]
@vikashvverma Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub username:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@vikashvverma thanks for this. We made a conscious decision not to allow HTML tags inside the cheat sheet though and I'd like to keep it that way. I'd rather add support for `\n` and `\t`, which I've started in another PR, but haven't gotten around to testing and fixing all the cheat sheets that would need to be updated.

Would you be interested in doing that?

**Comment by moollaza** [comment]
@vikashvverma this is the PR I started, you can see the changes I was planning to make: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1536/files

**Comment by vikashvverma** [comment]
@moollaza Yeah I know that. HTML tags are not JSON standard for new line ( \n ) but I had seen a few cheat sheets using HTML breaks. SO I made the change. I would be interested in fixing this in all cheat sheets. What do you say?

Should I work on your branch or what?

**Comment by moollaza** [comment]
>SO I made the change. I would be interested in fixing this in all cheat sheets. What do you say?

Perfect, thanks!

> Should I work on your branch or what?

If you'd like to, I don't personally care if you carry over my commits or not, as long as there's a PR that works :+1: 

> Also we are in different time zones, so there might be delay in my reply.

Understood, that's no problem :)

**Comment by vikashvverma** [comment]
@moollaza I think you can merge your branch with fixed regex in *cheat_sheets.js*.

I can update other cheatsheet(s) and make PR(S).

**Comment by moollaza** [comment]
@vikashvverma I think I was attempting to do too much in a single PR, and don't have the time right now to go back through that PR.

Can you make a new PR to add support for tabs and newlines and then we can get that part sorted out?

The other aspect of my PR was better handling of `{}` and `[]`. I was hoping to explicitly handle any `[]` or `{}` as a key separator unless escaped with `\\`.

Many contributors don't realize that single keys ***don't*** need to be wrapped in `[]` and so that's a common error we have them fix: `"key": "[F2]"` -> `"key": "F2"`

**Comment by moollaza** [comment]
The other part I wanted to do was add an `ignoreBrackets` flag or let you specify which kind of brackets should be ignored. That way when doing code snippets, we won't need to escape every `[]` which should make the content a little cleaner

**Comment by vikashvverma** [comment]
@moollaza Sure, I will make a new PR to allow support for `\n` and `\t`. What about `ignoreBrackets` flag?

**Comment by vikashvverma** [comment]
@moollaza created a new PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2627

**Comment by moollaza** [comment]
Closing as we have implemented newline support and should remove any `<br>`

**Pull request closed without merging**
