### PR TITLE
apt-get cheat sheet: Fix issue 3316

### PR DESCRIPTION
**Pull request by abadojack**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [*] Improvement
    - [*] Bug fix: **`apt-get cheat sheet: Fix issue 3316`**
   
{Short Description}`**

###### Description of changes

Provide an overview of the changes this pull request introduces.

###### Which issues (if any) does this fix?

Fixes [issue 3316](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3316) - Add sudo prefix to listed commands.

###### People to notify (@shahbaz17)

---

Instant Answer Page: http://duck.co/ia/view/apt_get_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by shahbaz17** [comment]
https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3316#issuecomment-229298858

**Comment by abadojack** [comment]
@moollaza Could you please merge this ?

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

**Pull request merged**
