### PR TITLE
CeramicCapacitorCodes: new IA for decoding ceramic caps

### PR DESCRIPTION
**Pull request by mintsoft**
###### What does your Pull Request do (check all that apply)?

New Instant Answer for decoding cryptic ceramic capacitor codes.

---

Instant Answer Page: https://duck.co/ia/view/ceramic_capacitor_decoding

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@duckduckgo/duckduckhack-contributors This could do with a review :)

**Comment by lights0123** [comment]
I'd suggest even just triggering on "capacitor" - I wouldn't initially think to specify one as ceramic. Is there any chance of other types of capacitors interfering with this IA? Electrolytic ones generally just have the value right on there.

**Comment by mintsoft** [comment]
> is there any chance of other types of capacitors interfering with this IA

I would guess probably not, tantalum caps usually have the same markings too. I guess SMD components might be where this comes unstuck, but the majority of passives don't have anything marked on them anyway due to size constraints

**Comment by lights0123** [comment]
I just looked through my history - I made 3 searches several months apart for "103 capacitor", so my vote would be for that. SMD resistors often have similar codes, but you would still need to add "capacitor" for this IA to trigger. "103 resistor" already (incorrectly - ???) returns 100Ω, so why not the same for capacitors?

**Comment by mintsoft** [comment]
That's good enough for me, I'll extend the triggering

**Comment by mintsoft** [comment]
Extended, will now respond to "103 capacitor" and "capacitor 103"

**Comment by pjhampton** [comment]
Hey @mintsoft 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Pull request closed without merging**
