### PR TITLE
Selenium white space triggering travis warning

### PR DESCRIPTION
**Pull request by kirkins**
## Description of new Instant Answer, or changes

```
# Testing selenium....................... 1 WARNING

# 	 -> WARN: Trailing whitespace in key 'driver.get('http://www.example.com') 
```

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/selenium

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by kirkins** [comment]
Another strange testing error. There is no way this should fail given it only removes a single white space which `travis.cli` was complaining about in the first place.

**Comment by kirkins** [comment]
I've seen [this line](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/.travis.yml#L22) fail multiple times on several commits. 

Not sure why, works fine when I run it manually on Codio.

**Comment by moollaza** [comment]
> I've seen this line fail multiple times on several commits.
> 
> Not sure why, works fine when I run it manually on Codio.

That's really odd -- that must be a problem on Travis end as duckpan.org hasn't had any problems.

**Comment by moollaza** [comment]
> There is no way this should fail given it only removes a single white space which travis.cli was complaining about in the first place.

@kirkins AFAIK those warnings don't cause the travis test to fail, that's why it reports it as a WARN. Can you show me where it caused a failure?

**Comment by kirkins** [comment]
@moollaza you're absolutely right, I'm just fixing the warning because I'm bored.

**Comment by kirkins** [comment]
@moollaza I was saying the line that says:

` - dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm --quiet --notest --mirror http://www.cpan.org/ --mirror http://duckpan.org`

In the travis.cli file seems to fail sometimes, as I've seen it fail a few times in cases where the tests just had to be re-run.

**Comment by bsstoner** [comment]
This was released to production 🚀

**Pull request merged**
