### PR TITLE
Base64: Escape result of base64.

### PR DESCRIPTION
**Pull request by jagtalon**
Old:
screen shot 2015-02-19 at 4 29 33 pm

New:
screen shot 2015-02-19 at 4 28 48 pm

### CODE REVIEW

**Comment by moollaza** [comment]
FTR, I Figured out that "in progress" thing -- somehow there was a Waffle.io hook added. I've now removed it

**Comment by jagtalon** [comment]
@moollaza you mean travis?

**Comment by moollaza** [comment]
@jagtalon no the "in progress" label that were being automatically added

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by jagtalon** [comment]
@moollaza oh oops missed that

**Comment by mintsoft** [comment]
Thanks @moollaza that was confusing me!

**Pull request merged**
