### PR TITLE
sublime text cheat sheet

### PR DESCRIPTION
**Pull request by codenirvana**
**What does your Instant Answer do?**
A cheat sheet that lists Sublime Text keyboard shortcuts.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
It summarizes most of the keyboard shortcuts so you don't have to go through several links/sources.

**What is the data source for your Instant Answer? (Provide a link if possible)**
[Cheatography](http://www.cheatography.com/njovin/cheat-sheets/sublime-text-2-windows)

**Why did you choose this data source?**
List all the most commonly used Sublime Text keyboard shortcuts.

**What are some example queries that trigger this Instant Answer?**
* sublime text cheat sheet
* sublime cheat sheet
* sublime text keyboard shortcuts
* sublime keyboard shortcuts

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Sublime text editor lovers.

**Which existing Instant Answers will this one supersede/overlap with?**
None

**Are you having any problems? Do you need our help with anything?**
No

**What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?**
No

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

Sublime text cheat sheet

------
https://duck.co/ia/view/sublime_text_cheat_sheet

### CODE REVIEW

**Comment by moollaza** [comment]
@codenirvana thanks *again* for contributing, we really appreciate it! We'll be sure to review this shortly and give you some feedback!

**Comment by mintsoft** [comment]
@codenirvana Nice to see you're clearly finding the cheatsheet creation easy!

**Comment by mintsoft** [comment]
The only real issue I can see here is that some of the shortcuts look a little squished, especially the stuff in selection.

**Comment by codenirvana** [comment]
@mintsoft Yes, don't know how to fix that.
Why its not showing 2 keys on the same line like 'Ctrl + Shift' in Selection block only.

**Comment by abeyang** [comment]
Hey @codenirvana , let's try this -- let's remove all the `+`.

So this is BAD:

`[Ctrl] + [Alt] + [Delete]`

And this is GOOD:

`[Ctrl][Alt][Delete]`

Let's make those modifications and see how they'll look. Thanks!

**Comment by moollaza** [comment]
@abeyang you actually still need spaces between the keys otherwise it won't work properly:

```
[Ctrl] [Alt] [Del]
```

**Comment by codenirvana** [comment]
@moollaza @abeyang removed all the + but still the problem with keys in 'Selection' section is not solved.
screenshot

**Comment by moollaza** [comment]
@codenirvana this is great for now -- we're working on some UI fixes that will address any problems. But for now, the data is good :+1:

**Comment by moollaza** [comment]
@codenirvana whoops, I just noticed you have some single keys wrapped in `[]` (i.e. [F4], [F11], etc) those aren't necessary -- I'll fix.

**Comment by codenirvana** [comment]
@moollaza Should I update my previous cheat sheets with this new syntax(without +) ?

**Comment by abeyang** [comment]
@codenirvana if you can, yes please! Looks a lot cleaner without the `+`'s.

**Comment by moollaza** [comment]
@codenirvana congrats! It's live: https://duckduckgo.com/?q=sublime+text+cheat+sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
