### PR TITLE
Update toontown.json

### PR DESCRIPTION
**Pull request by Justforahorror**
updated name,aliases and sourceName of toontown.json

### CODE REVIEW

**Comment by daxtheduck** [comment]
@Justforahorror Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Zip Code:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub ID:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by moollaza** [comment]
@Justforahorror this LGTM :+1:

Thanks a lot for contributing (we really appreciate it :smiley:). We invite you to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

**Comment by Justforahorror** [comment]
@ :+1:

**Comment by moollaza** [comment]
@Justforahorror thanks again for updating this Cheat Sheet! I wanted to get in touch with you to see if there’s anything I can help you with, or if you’d like me to suggest some more ways in which you can help out (bugs, new IA’s etc)?

I’m reaching out to our recent, successful contributors to see what brought them to DuckDuckHack, and what else you’d like to work on? Perhaps something more difficult like a full Goodie or API-Powered Spice Instant Answer?

Also if you have any feedback or thoughts on your experience contributing to DuckDuckHack I’d really appreciate it!

Cheers!

**Pull request merged**
