### PR TITLE
New Html beautifier Goodie

### PR DESCRIPTION
**Pull request by akanshgulati**
- [ ] New Instant Answer
    - [ ] Other: **`HTML Beautifier`**
What changes does this PR introduce? 
It will reformat the html code to have proper indentation for nested tags making it easier for user to read and debug code. 
###### People to notify

@tagawa @moollaza 

---

Instant Answer Page: https://duck.co/ia/view/html_beautifier

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tagawa

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Nice work @akanshgulati! This is now on the beta server for testing and looking good: https://beta.duckduckgo.com/?q=beautify+html&ia=answer

**Comment by akanshgulati** [comment]
@tagawa It has a external library which needs to be uploaded first on DDG host. First, deploy the library there.

**Comment by tagawa** [comment]
@akanshgulati OK, I think this has to be done by @moollaza, similar to #3640 and #3635

**Comment by tagawa** [comment]
Thanks for the update @akanshgulati.
@moollaza I think we have to add the library to the backend - is that right?

**Comment by moollaza** [comment]
Yup I have an internal PR that adds the libs to DDG.require. I will test it with this IA and then merge both 👍

**Comment by moollaza** [comment]
@akanshgulati this is now live on beta.

It looks like the beautifier isn't working very well though. It seems to only fix some indentation and doesn't remove empty newlines. Can this be configured further?

beautify_html_at_duckduckgo

**Comment by moollaza** [comment]
@akanshgulati it seems to work better when you have `<html>` -- Either way this is OK for now 👍

**Comment by moollaza** [comment]
beautify_html_at_duckduckgo

**Comment by daxtheduck** [comment]
@akanshgulati this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
