### PR TITLE
Hindu / Vedic calendar Panchangam Instant Answer (Goodie)

### PR DESCRIPTION
**Pull request by kmg**
**What does your instant answer do?**
It provides the hindu calendar called [Panchangam](https://en.wikipedia.org/wiki/Panchangam) for a particular day and defaults to today.

**What problem does your instant answer solve (Why is it better than organic links)?**
It is better than organic links when you quickly want to verify the hindu calendar details of a particular day
and not have to deal with clunky date widgets / select dropdowns.

**What is the data source for your instant answer? (Provide a link if possible)**
Date::Indian perl module is used to calculate the answer

**Why did you choose this data source?**
Date::Indian gives correct answers which matches with hard copy panchangams available in India

**Are there any other alternative (better) data sources?**
Desktop programs like [Jagannatha Hora](https://en.wikipedia.org/wiki/Jagannatha_Hora) calculate with better precision for different locations

**What are some example queries that trigger this instant answer?**
panchangam, panchangam 1 year ago, panchangam 12/12/12

**Which communities will this instant answer be especially useful for? (gamers, book lovers, etc)**
People interested in vedic / hindu / lunar / sidereal time keeping and astrology.

**Is this instant answer connected to a DuckDuckHack [instant answer idea](https://duck.co/ideas)?**
No

**Which existing instant answers will this one supercede/overlap with?**
Currently the queries "panchangam"/"panjika" returns the wikipedia summary which this goodie will overlap with

**Are you having any problems? Do you need our help with anything?**

Is there a better template to display this data ?
Is it OK to reuse the record template html structure and classes ?
Is it OK to provide Previous and next day links ? Are there icons for left and right arrows ?

****Note:** Please attach a screenshot for new instant answer pull requests, and for pull requests which modify the look/design of existing instant answers.
image
## Checklist

Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[X] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Linux (Ubuntu)
        [X] Google Chrome   
        [X] Firefox         

    - Android
        [X] Firefox         
        [X] Native Browser  
        [X] Google Chrome   
```

### CODE REVIEW

**Comment by zekiel** [comment]
@kmg anything we can help with here?

**Comment by jagtalon** [comment]
Closing for now. Can always re-open! :D

**Comment by javathunderman** [comment]
@jagtalon @moollaza I might take this one up- are there any overlapping IAs?

**Comment by abeyang** [comment]
@javathunderman , one thing to note is that this particular IA only observes the Hindu Calendar from only one specific location... in order for this to be useful to more people, we'll need to open this up to more locations. My limited research into this suggests that this should be a spice, and not a goodie, as it becomes quite complex (but feel free to prove me wrong!).

**Pull request closed without merging**
