### PR TITLE
Added string manipulation Parameter Expansion to Bash cheat sheet

### PR DESCRIPTION
**Pull request by ZanyMonk**
# [Bash Cheat Sheet](https://duck.co/ia/view/bash_cheat_sheet)

Full description of Parameter Expansion features was missing (substring replacement, extraction, deletion).

PS: I've just discovered the dev side of DDG. I love you <3

### CODE REVIEW

**Comment by daxtheduck** [comment]
@ZanyMonk Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@synbit You cool with this?

**Comment by synbit** [comment]
Didn't have the chance to look at it yet; should do tomorrow though

**Comment by synbit** [comment]
Looks good, one suggestion: we seem to be going for the lot here, so why leave `${parameter^pattern}`, `${parameter^^pattern}`, ``${parameter,pattern}` and `${parameter,,pattern}` out? These are used to convert the case of `pattern`, which should not attempt to match more than one character (see [docs](https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion) for the details).

**Comment by mintsoft** [comment]
@ZanyMonk You OK with the provided feedback?

**Comment by ZanyMonk** [comment]
Hey !
You're absolutely right @synbit, i missed the case switching parameter expansions. I suppose we can even mark `pattern` as optionnal while it works with an empty pattern.
What do you think of something `${str^[substr]}` or is it ambiguous and you prefer to dissociate the two possible forms ?

**Comment by synbit** [comment]
Knowing that `substr` is optional is useful. However, I believe `${str^[substr]}` is not clearly indicating that. What if we include this information in the description instead? This way we could avoid adding keys to the already lengthy cheat sheet whilst we include the information we want. Would you say that's sensible @ZanyMonk ?

**Comment by ZanyMonk** [comment]
@synbit yup. I've pushed what was missing. Thank you for the suggestion !

Ps: sorry for multi-push, i have some indentation problems.

**Comment by synbit** [comment]
@ZanyMonk thank you!

@mintsoft I believe that's fine; unless you see any problems you can make-go-live I suppose?

**Comment by mintsoft** [comment]
LGTM; thanks @ZanyMonk

**Comment by zekiel** [comment]
@ZanyMonk  this is now on the programming coverage table but I'm guessing the coverage of shell-related queries isn't that great w/ just cheat sheets. Are there particular queries like syntax that you'd recommend IA coverage for next? https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage

We could probably investigate some internal data to help solve them in buckets.

**Comment by ZanyMonk** [comment]
@zekiel I have to say I have no clue about that. Most of the time, cheat sheets are enough in my opinion. There is already an IA based on StackOverflow answers that works very well on Bash/shell related problems.
Maybe we could try to find or build a DB with a bunch of shell tricks ?

**Comment by zekiel** [comment]
@ZanyMonk  something like http://overapi.com/shellscript ?

**Comment by edgesince84** [comment]
hey @ZanyMonk thank you again for your contribution to DuckDuckHack, we really appreciate it! I'm reaching out to let you know that we recently launched a new forum with the initiative of improving programming-related searches, and I hope you'll [join us](https://forum.duckduckhack.com/)!

There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Pull request merged**
