### PR TITLE
Conversions: Adding more temperature tests

### PR DESCRIPTION
**Pull request by mintsoft**
We've had a few issues around temperature conversion accuracy so I'm producing tests for all combinations of the 4 supported units  (80 tests) and verifiying the results against WA as I'm going. 

I'll leave any failing tests that I encounter so we can look at resolving the issues.

cc @elohmrow

### CODE REVIEW

**Comment by elohmrow** [comment]
@mintsoft thanks!

**Comment by mintsoft** [comment]
@elohmrow I think this is now covering all the problem cases as of https://github.com/duckduckgo/zeroclickinfo-goodies/commit/1a5aaf992290f0d081b1d22d6dd9215b01b48290

**Comment by mintsoft** [comment]
```
rob@set $ prove -Ilib t/Conversions.t
t/Conversions.t .. 84/?
    #   Failed test 'Expected result but dont get one on 0 fahrenheit in fahrenheit'
    #   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 78.
    # Looks like you failed 1 test of 1.

#   Failed test 'Query: 0 fahrenheit in fahrenheit'
#   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 80.
t/Conversions.t .. 128/?
    #   Failed test 'Expected result but dont get one on 0 celsius in celsius'
    #   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 78.
    # Looks like you failed 1 test of 1.

#   Failed test 'Query: 0 celsius in celsius'
#   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 80.

    #   Failed test 'Expected result but dont get one on -87 fahrenheit in kelvin'
    #   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 78.
    # Looks like you failed 1 test of 1.

#   Failed test 'Query: -87 fahrenheit in kelvin'
#   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 80.

    #   Failed test 'Expected result but dont get one on -87 celsius in kelvin'
    #   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 78.
    # Looks like you failed 1 test of 1.

#   Failed test 'Query: -87 celsius in kelvin'
#   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 80.

    #   Failed test 'Expected result but dont get one on -7 fahrenheit in kelvin'
    #   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 78.
    # Looks like you failed 1 test of 1.

#   Failed test 'Query: -7 fahrenheit in kelvin'
#   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 80.

    #   Failed test 'Expected result but dont get one on -7 celsius in kelvin'
    #   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 78.
    # Looks like you failed 1 test of 1.

#   Failed test 'Query: -7 celsius in kelvin'
#   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 80.

    #   Failed test 'Deep: full ZCI object'
    #   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 76.
    #     Structures begin differing at:
    #          $got->{structured_answer}{result} = '3.16 * 10<sup>-14</sup> K'
    #     $expected->{structured_answer}{result} = '0 K'
    # Looks like you failed 1 test of 1.
#   Failed test 'Query: 0 kelvin in rankine'
#   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 80.

    #   Failed test 'Expected result but dont get one on 0 rankine in rankine'
    #   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 78.
    # Looks like you failed 1 test of 1.

#   Failed test 'Query: 0 rankine in rankine'
#   at /home/rob/perl5/lib/perl5/DDG/Test/Goodie.pm line 80.
# Looks like you failed 14 tests of 221.
t/Conversions.t .. Dubious, test returned 14 (wstat 3584, 0xe00)
Failed 14/221 subtests

Test Summary Report
-------------------
t/Conversions.t (Wstat: 3584 Tests: 221 Failed: 14)
  Failed tests:  125, 146, 157-158, 161-162, 167-168, 177-178
                181-182, 187-188
  Non-zero exit status: 14
Files=1, Tests=221,  6 wallclock secs ( 0.47 usr  0.02 sys +  6.00 cusr  0.10 csys =  6.59 CPU)
Result: FAIL
```

**Comment by mintsoft** [comment]
@elohmrow Ignoring the tautology tests (0 K in K), it looks like the only outstanding problem is the one mentioned in https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1729; 

I'm in two minds with the tautology too, I kind of think that it should work. Why *wouldn't* we be able to convert from Kelvin into Kelvin?

**Comment by elohmrow** [comment]
@mintsoft i agree based purely on the fact that i believe any valid factor+unit should be convertible to any other factor of the same type.  so 0K should certainly give back 0K.

**Comment by elohmrow** [comment]
@mintsoft i have changed C::P (locally) to use Convert::Temperature for now.  it will go out in the next C::P release to CPAN (0.031)

**Comment by mintsoft** [comment]
@elohmrow sounds good, can you ping me once the new C::P is out? I can re-run these tests and hopefully they should be all green!

**Comment by elohmrow** [comment]
@mintsoft yes, i will ~ i have a local C::P now that is written using Moo and has an optional constructor arg to use it as a service with an external data file (this will make it easier in the future, for example, to add units) ... i have added a good number of tests, and i will incorporate as many of yours into the C::P suite as possible before i make the release.

**Comment by mintsoft** [comment]
@elohmrow Sounds good! Excited to see it :+1:

**Comment by elohmrow** [comment]
@mintsoft qq: i've never had to distribute data with a perl module before; it is turning out to not be easy; that is, <code>prove -Ilib Convert-Pluggable.t</code> works great _from within t/_, but not outside of t/, which is where little things like <code>make test</code> happen.  I've tried these things: http://perltricks.com/article/25/2013/5/20/Old-School-Object-Oriented-Perl ... any other ideas?

Long and short is - you can create a C::P object two ways now ... one is by passing the constructor a data file location.  How can I handle that during <code>make test</code>?

**Comment by mintsoft** [comment]
@elohmrow one option is to use the paths based on the script file rather than the cwd of the parent;
something along the lines of:
```perl
use File::Basename;
my $loading_file = dirname(__FILE__)."../data/filesource.json";
``` 
within the module  should always operate relative to the base directory (assuming that the module is in `/lib`)

**Comment by elohmrow** [comment]
@mintsoft ++

**Comment by jagtalon** [comment]
Thanks, @mintsoft @elohmrow! I'm excited to see these tests pass as well!

giphy

**Comment by elohmrow** [comment]
@jagtalon very busy lately but trying :)

**Comment by jagtalon** [comment]
@elohmrow Oh I didn't mean to rush you! Take your time :smile:

**Comment by mintsoft** [comment]
@elohmrow In C::V 0.031 is it anticipated that these tests should pass?

**Comment by elohmrow** [comment]
@mintsoft - will check tonight - traveling now :)

**Comment by elohmrow** [comment]
@mintsoft ~ ok, i have added all these tests to the main C::P suite ... i will get back with you tomorrow, as i recall converting X to X doesn't seem to work.  hopefully i will get everything to pass by then :)

**Comment by elohmrow** [comment]
@mintsoft ~ done traveling for $one_day ... looking at this today :+1:

**Comment by mintsoft** [comment]
@elohmrow cool, let me know if I can be of any help

**Comment by elohmrow** [comment]
@mintsoft ~ almost everything passes on C::P 0.31; a few though don't seem to trigger.  i am traveling again today but will check tomorrow on the non-triggering ones.  thanks for your help!

**Comment by elohmrow** [comment]
@mintsoft ~ down to 16 fails in 669 tests ... had a lot of weird rounding errors (and different results at times based on machine) so now precision is always used ... user may set it in the convert process, but it defaults to 3.  will continue on those 16 fails.

**Comment by elohmrow** [comment]
@mintsoft ~ all tests passing! I completely re-wrote how temperatures are converted, because it was actually just plain wrong in some cases.  i'm cleaning up the code now.  as soon as it's indexed by CPAN, I'll post back here.

**Pull request closed without merging**
