### PR TITLE
Should disable spellcheck

### PR DESCRIPTION
**Pull request by tgckpg**
## Type of Change

- [ ] New Instant Answer
    - [ ] Cheat Sheet
- [X] Improvement
    - [ ] Bug fix
    - [X] Enhancement
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.)

## People to notify

---

IA Page: https://duck.co/ia/view/{ID}

Forum Topic:

Most words in JSON files are mostly non spellcheck-able. Those red underlines are somewhat distracting.

### CODE REVIEW

**Comment by daxtheduck** [comment]
@tgckpg Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by sahildua2305** [comment]
Thanks for this PR, @tgckpg. I will review this in a while.

**Comment by sahildua2305** [comment]
@tgckpg I don't spellcheck enabled anyway. Can you attach screenshot where you see it spellchecking in the IA `textarea`?

**Comment by tgckpg** [comment]
Screenshot
```
{
    "status": false,
    "data": {
        "Locale": "en_us",
        "Status": "CC",
        "DRStatus": true,
        "CustIP": "10.10.0.133",
        "ResponseCode": 37,
        "Invoice": "AB5081dd65-d",
        "AdditionalResponse": "",
        "TxnType": 7,
        "CupsecLastSystemTraceNum": "",
        "CloseBatchTime": "",
        "Amount": 500,
        "CupsecSettleDate": "",
        "ActualAmount": null,
        "Eci": "07",
        "CardBrand": "",
        "MerchantID": 158492017581354,
        "ApprovalCode": "",
        "TimeStamp": "20161104020258",
        "CurrencyCode": 344,
        "DRResponseCode": 0,
        "DDMerchantID": null,
        "RRNumber": "",
        "PostingDate": null
    },
    "mesg": "OK"
}
```

**Comment by mintsoft** [comment]
@tgckpg it's not been deployed live yet; it should happen in the next week or so

**Pull request merged**
