### PR TITLE
Issue #1163 - Convert Cusip to use templates

### PR DESCRIPTION
**Pull request by Mailkov**
IA Page: https://duck.co/ia/view/cusip

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@Mailkov this is now deployed on Beta!

**Comment by mintsoft** [comment]
@moollaza LGTM

**Comment by moollaza** [comment]
We should drop the period at the end. Otherwise LGTM

**Comment by moollaza** [comment]
Thanks @Mailkov

**Pull request merged**
