### PR TITLE
update Goodies template to meet new DuckPAN changes

### PR DESCRIPTION
**Pull request by moollaza**
//cc @mwmiller 

Coincides with changes to DuckPAN: https://github.com/duckduckgo/p5-app-duckpan/pull/143

---

This should be changed at the same time as the Goodie Quickstart Tutorial otherwise the tutorial won't make any sense

### CODE REVIEW

**Comment by jagtalon** [comment]
@moollaza what's the status of this one?

**Comment by moollaza** [comment]
It's dependent on the docs being updated to explain the new structured answer. Can leave it open until I get around to that...

**Comment by mintsoft** [comment]
@moollaza @jagtalon aren't they already documented? https://duck.co/duckduckhack/goodie_advanced_handle_functions#using-structured-responses

**Comment by moollaza** [comment]
@mintsoft sorry, to clarify I mean that the Goodie QuickStart Tutorial would need to be updated as well so that the template and tutorial are aligned.

**Comment by javathunderman** [comment]
@moollaza Saw this in the stale branches- any status updates?

**Comment by javathunderman** [comment]
ping @moollaza, any updates?

**Comment by moollaza** [comment]
We're not ready to move ahead with this. Would require a complete re-write of the Quickstart which we don't need to do for now.

**Comment by mintsoft** [comment]
@moollaza is it worth just closing this and throwing it away in that case?

**Comment by moollaza** [comment]
I guess so... :+1:

**Pull request closed without merging**
