### PR TITLE
New Counties of Northern Ireland cheat sheet.

### PR DESCRIPTION
**Pull request by pjhampton**
## Counties Of Northern Ireland

https://duck.co/ia/view/counties_of_ni_cheat_sheet

### Description
Northern Ireland has six counties; Antrim, Armagh, Down, Fermanagh, Londonderry / Derry and Tyrone. This IA lists them along with their county town.

### Data Source
https://en.wikipedia.org/wiki/Counties_of_Northern_Ireland

### Example Queries
counties of northern ireland, northern ireland counties, ni counties

### CODE REVIEW

**Comment by daxtheduck** [comment]
@pjhampton Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
## [Counties Of Northern Ireland](https://duck.co/ia/view/counties_of_northern_ireland)

**Description**: Northern Ireland has six counties; Antrim, Armagh, Down, Fermanagh, Londonderry / Derry and Tyrone. This IA lists them along with their county town.

**Example Query**: [counties of northern ireland](https://beta.duckduckgo.com/?q=counties of northern ireland), [northern ireland counties, ni counties](https://beta.duckduckgo.com/?q=northern ireland counties, ni counties)

**Tab Name**: Answer

**Source**: https://en.wikipedia.org/wiki/Counties_of_Northern_Ireland

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/counties_of_northern_ireland)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/counties_of_northern_ireland)*

**Comment by moollaza** [comment]
@pjhampton thanks for this. Unfortunately I'm not sure the cheat sheet would ever really get triggered and I don't think it's substantially better than the Wiki article which will be the first result. Cheat Sheets still require a specific trigger word like "cheat sheet", "reference", "help" to be part of the query, so it would require a pretty verbose query: "counties of norther Ireland cheat sheet" to see this.

Most people are likely to search "counties of northern Ireland" and our Wiki Instant Answer for that article will show.

I'm going to close this but if you disagree we can definitely talk about it.

In general I'd like us to avoid cannibalising Wiki pages/tables unless absolutely necessary and the query is likely to occur. 

/cc @duckduckgo/community-leaders any thoughts on this?

**Comment by pjhampton** [comment]
@moollaza Sure. I understand you guys need to ensure quality. I shall close the other two.

**Comment by GuiltyDolphin** [comment]
@moollaza With #2170 the triggering could be a bit more lenient, and actually trigger on `countries of northern Ireland` (or similar).

But I speaketh of things that have not yet come to pass!

Just a note :wink:

**Comment by pjhampton** [comment]
Thanks @GuiltyDolphin ... now I think back I think it may have been a poor choice of cheat sheet. @moollaza don't forget to delete the duck.co IA pages for those 3.

**Comment by GuiltyDolphin** [comment]
@pjhampton Meh, there's a *lot* of scope for cheat sheets - as we open it up more to the general public we'll be getting a lot of weird, wonderful and wacky stuff I expect.

**Pull request closed without merging**
