### PR TITLE
New Supercollider Apocalypse Checker Instant Answer

### PR DESCRIPTION
**Pull request by AlterationBrick**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [x] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Adds an easter egg that determines whether the Large Hadron Collider has destroyed the world yet. Just for giggles; reject it if you don't like it, because it only took about an hour of my time.

###### Related Issues or Discussions 

N/A

###### People to notify

@mention any relevant people/organizations

---

Instant Answer Page: https://duck.co/ia/view/has_the_large_hadron_collider_destroyed_the_world_yet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by AlterationBrick** [comment]
I apologize if this has messed with Dewey; that wasn't my intention and Git isn't my strong suit.

**Comment by GuiltyDolphin** [comment]
@AlterationBrick Did you checkout from the wrong branch? Try (on a backup branch) rebasing onto master, and remove any commits that aren't for this IA; if you need help just search for `git interactive rebasing`.

**Comment by AlterationBrick** [comment]
@GuiltyDolphin Haha that's exactly what I did. I'll fix it.

**Comment by AlterationBrick** [comment]
Moving to new PR, #3597

**Pull request closed without merging**
