### PR TITLE
Poker Hand Probabilities Cheat Sheet

### PR DESCRIPTION
**Pull request by thefrieddan1**
**What does your Instant Answer do?**
provides a quick view to poker hands and probability for each hand.

**What is the data source for your Instant Answer? (Provide a link if possible)**
Wikipedia
https://en.wikipedia.org/wiki/List_of_poker_hands

**Why did you choose this data source?**
I find it and believe it to be reliable in this specific subject.

**Are there any other alternative (better) data sources?**
Yes. many. those I found using duck duck go search are included in commercial poker web sites.

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
poker players.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
It is from the Cheat Sheet Ideas at:
https://duck.co/duckduckhack/goodie_cheat_sheets#cheat-sheet-ideas

**Are you having any problems? Do you need our help with anything?**
I found the tutorial excellent and very detailed I hope this contribution is OK and to contribute more and in meaningful ways.

**Where did you hear about DuckDuckHack? (For first time contributors)**
I just clicked on the logo at the search and read from there.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
poker-hands

### CODE REVIEW

**Comment by moollaza** [comment]
@thefrieddan1 thanks a lot for contributing. I actually just merged an older PR which provides a Poker Hands Cheat Sheet. That Cheat Sheet doesn’t give the probabilities though. I think it would be best to change your PR so that it adds a new section to the existing Poker Hands Cheat Sheet.

Also I prefer the `name` and `description` you've used.

Any thoughts?

**Comment by thefrieddan1** [comment]
Sounds good to me.
I will make the changes and PR again.
By the way I dont see the poker hand cheat sheet you merged to production.
What is the search term I need to perform to see it in duck duck go? ( i
tried "poker hand cheat sheet" , "poker hands cheat sheet" and "poker cheat
sheet"  )

Thanks.

**Comment by seisfeld** [comment]
I'm new to the workflow as well, but i assume merges to the master repo here don't show up in production immediately. Regarding you question what the triggers will be, AFAIK they are the same for all the cheat sheets. So in this case "poker" and any of these:

```
triggers startend => (
    'char', 'chars',
    'character', 'characters',
    'cheat sheet', 'cheatsheet',
    'command', 'commands',
    'example', 'examples',
    'guide', 'help',
    'quick reference', 'reference',
    'shortcut', 'shortcuts',
    'symbol', 'symbols',
    'key bindings', 'keys', 'default keys'
);
```

From: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/CheatSheets.pm

**Comment by mintsoft** [comment]
@seisfeld That's absolutely correct

**Comment by moollaza** [comment]
@thefrieddan1 Ping! I'm just checking in to see if you're still interested in finishing this one up? We'd love to see this go live!

There's absolutely no rush, just wanted to make sure you're not stuck on anything.

**Comment by seisfeld** [comment]
@moollaza I'd offer a hand to finish up the merge of this one with the poker hands cheat sheet. Just give me a shout if i should start with that.

**Comment by moollaza** [comment]
>@moollaza I'd offer a hand to finish up the merge of this one with the poker hands cheat sheet. Just give me a shout if i should start with that.

@seisfeld please do! That would be amazing :+1:

**Comment by seisfeld** [comment]
I created new PR #1601 to finish this one here. Can be closed once #1601 is merged.

**Comment by mintsoft** [comment]
Closing this in favour of #1601

**Pull request closed without merging**
