### PR TITLE
New heap operations cheat sheet

### PR DESCRIPTION
**Pull request by navneetzz**
**What does your Instant Answer do?**
My Instant answer provide reference to Big-O complexities of Heap operations.

**What is the data source for your Instant Answer? (Provide a link if possible)**
[Wikipedia](https://en.wikipedia.org/wiki/Heap_%28data_structure%29)

**Why did you choose this data source?**
Because it's detailed reference to Heap operations.

**Are there any other alternative (better) data sources?**
No

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Coders and programmers

**Where did you hear about DuckDuckHack? (For first time contributors)**
Social media sites.

heap

---
https://duck.co/ia/view/heap_operations_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
## [Heap Operations Cheat Sheet](https://duck.co/ia/view/heap_operations_cheat_sheet)

**Description**: Summary of Big-O time complexities for Heap operations.

**Example Query**: [heap operation cheat sheet](https://beta.duckduckgo.com/?q=heap operation cheat sheet), [](https://beta.duckduckgo.com/?q=)

**Tab Name**: Answer

**Source**: Wikipedia

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/heap_operations_cheat_sheet)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/heap_operations_cheat_sheet)*

**Comment by GuiltyDolphin** [comment]
I see no issues. Lets deploy to Beta @moollaza.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=heap operation cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/heap_operations_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=heap operation cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/heap_operations_cheat_sheet_mobile.png)

**Comment by GuiltyDolphin** [comment]
@moollaza This looks pretty good to me!

My only complaint would be that the formatting of the values could be a bit better - maybe this could be achieved through a template type for math?

:+1:

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=heap operation cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/heap_operations_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
