### PR TITLE
New P5js Cheat Sheet

### PR DESCRIPTION
**Pull request by apenman**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New p5.js Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Adds a cheat sheet for p5.js.
Uses references from http://p5js.org/reference/

###### Which issues (if any) does this fix?

Fixes #NNNN - how specifically does it fix the issue?

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/p5js_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @apenman

### CODE REVIEW

**Comment by daxtheduck** [comment]
@apenman Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gaulrobe** [comment]
@apenman this is very handy!

Might you be interested in making it a Fathead though? Some perks of it being a Fathead is better querying and we could provide code snippets for people!

For example, a query for `p5 brightness` could immediately have an IA result with `Extracts the HSB brightness value from a color or pixel array.` and the code snippet that is on http://p5js.org/reference/#/p5/brightness.

Just a thought! See http://docs.duckduckhack.com/resources/fathead-overview.html if you are interested, otherwise having a cheatsheet is good too!

**Comment by apenman** [comment]
@gaulrobe I think you're right about it being a fathead, it seems like it fits that structure a bit better! I'll start looking into fatheads more and get to work on it soon.

Still new around here so apologies for any little mistakes

**Comment by gaulrobe** [comment]
@apenman no apologies needed! The cheat sheet is definitely valuable, but if we can provide more instant answers to API queries I think that'd be great :)

Please don't hesitate to let any of us know if you have any questions as you go!

**Comment by edgesince84** [comment]
hey @apenman  -- need any help moving forward?  We would love to see a new JS Instant Answer!

**Comment by apenman** [comment]
hi @edgesince84 - I think I'm good moving forward for now. Been busy with work but I've started on getting the code written to generating the output.txt file for the fathead. Should be making more progress over the next week! Thanks

**Comment by edgesince84** [comment]
That's great to hear @apenman!  thanks 👍

**Pull request closed without merging**
