### PR TITLE
Fix translation mistake

### PR DESCRIPTION
**Pull request by vikashvverma**
This PR fixes translation in Hindi cheat sheet.

IA Page : https://duck.co/ia/view/hindi_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by vikashvverma** [comment]
@moollaza @GuiltyDolphin Can you review this.

**Comment by GuiltyDolphin** [comment]
@vikashvverma I found this table:

screenshot from 2016-02-16 08 28 17


So perhaps we should do:

`Thank you (formal/informal)`...`dhanyvaad/shukriyaa`. For both? (According to that table).

**Comment by vikashvverma** [comment]
@GuiltyDolphin That is another way of writing शुक्रिया but this is the prefered one in Hindi.

**Comment by GuiltyDolphin** [comment]
@vikashvverma Alrighty, LGTM then :+1:

I don't speak Hindi so I have to look these things up :wink:

**Comment by vikashvverma** [comment]
Sure, I think [ this](https://hi.wiktionary.org/wiki/%E0%A4%B6%E0%A5%81%E0%A4%95%E0%A5%8D%E0%A4%B0%E0%A4%BF%E0%A4%AF%E0%A4%BE) may help you.

**Comment by GuiltyDolphin** [comment]
Nice.

**Comment by vikashvverma** [comment]
Thanks

**Pull request merged**
