### PR TITLE
ccTLD goodie

### PR DESCRIPTION
**Pull request by javathunderman**
Continuing from #581. 

I have not changed the code at all.

Hopefully I can get this moving and live.

### CODE REVIEW

**Comment by MrChrisW** [comment]
Hey @javarhunderman I have a few concerns surrounding this IA.

+ Currently most TLDs are handled by the Wiki IA https://duckduckgo.com/?q=.my&ia=about

+ It seems unmaintainable to have a list that needs updating when a new TLD comes along. 

Anyway I know you're just bringing back abandoned IAs (which I think is awesome BTW) I just wanted to put these issues on the table :smile:

**Comment by javathunderman** [comment]
@MrChrisW I thought we could expand this to include gTLDs as well (since those aren't covered by Wikipedia), but there's a ton of those. Perhaps this should be migrated to a Spice?

**Comment by mintsoft** [comment]
@javathunderman If you can find a good API for it then absolutely! Otherwise the goodie option is the only valid one

**Comment by javathunderman** [comment]
I’ll look for one, should start development on the new Spice this week (hopefully). In the meanwhile, I think this can be closed.

**Comment by javathunderman** [comment]
Closing because this does better as a Spice.

**Comment by javathunderman** [comment]
@mintsoft Apparently Namecheap has one- https://www.namecheap.com/support/api/methods/domains/get-tld-list.aspx

Also found this one- http://freedomainapi.com/api-documentation.html

Going to move this over to a duck.co post for more people to weigh in on...

**Comment by javathunderman** [comment]
@mintsoft Going to open a PR soon. It's failing tests and I need a little help.

**Comment by mintsoft** [comment]
@javathunderman no problem; just ping me when it's accessible

**Pull request closed without merging**
