### PR TITLE
Update angularjs.json

### PR DESCRIPTION
**Pull request by abhi2303237**
-----
IA Page: https://duck.co/ia/view/angular_js_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@abhi2303237 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub ID:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata post coming soon

**Comment by moollaza** [comment]
@abhi2303237 Thanks for contributing and welcome to DuckDuckHack!

Please follow the above instructions to link the IA Page (so that we can deploy your changes to beta.duckduckgo.com!)

Also, it's always preferred that developers provide a description of the changes made and reasons why, in the Pull Request description.

**Comment by moollaza** [comment]
@abhi2303237 this LGTM :+1:

Thanks a lot for contributing (we really appreciate it :smiley:). We invite you to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

**Comment by moollaza** [comment]
Hey @abhi2303237, thanks again for fixing the AngularJS Cheat Sheet! You did a great job. We at DuckDuckGo, the DuckDuckHack community, and all the people who will encounter this Instant Answer really appreciate it.

We could really use your help on something else now. There was a great suggestion about improving the Tips Goodie triggers in issue #1044 and I think you'd similarly do a great job with it. Please comment on this issue if you'd be willing to take it up!. 

I think it is a good fit for you, but I'm of course not entirely sure, so I'd love to chat if you're around this week or next. Please message me on slack (@moollaza) or send me an email (moollaza@duckduckgo.com) if you'd be interested in talking. 

Thanks again!

**Pull request merged**
