### PR TITLE
Added MD4 Goodie

### PR DESCRIPTION
**Pull request by rafacas**
**What does your Instant Answer do?**
Computes the MD4 cryptographic hash function.
**What problem does your Instant Answer solve (Why is it better than organic links)?**
Users interested in the MD4 hash of a string will be able to get it as an Instant Answer instead of going to a specific page that calculates it or writing a small script.
**What is the data source for your Instant Answer? (Provide a link if possible)**
None
**Why did you choose this data source?**
N/A
**Are there any other alternative (better) data sources?**
N/A
**What are some example queries that trigger this Instant Answer?**
md4 this string
md4sum this string
MD4 this string
md4 hash of this string
md4 base64 this string
**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
People interested in cryptography or users who already use the Instant Answer MD5 or SHA.
**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No
**Which existing Instant Answers will this one supercede/overlap with?**
None
**Are you having any problems? Do you need our help with anything?**

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
md4

## Checklist
Please place an 'X' where appropriate.

```
- [x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [x] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [x] Tested cross-browser compatibility
    Please let us know which browsers/devices you've tested on:
    - Mac OSX
        - [x] Google Chrome
        - [x] Firefox
```

### CODE REVIEW

**Comment by mintsoft** [comment]
@rafacas Thanks for the new IA. this looks perfect to me! 

@abeyang any design feedback?

**Comment by abeyang** [comment]
:+1:

**Comment by moollaza** [comment]
Whoops forgot to confirm the Perl dependency was added :facepunch:

**Comment by moollaza** [comment]
@rafacas I know it's a little late, but I just realized we may have overlooked the trigger of this IA. I can imagine potential queries that might be searches starting with `md4

**Comment by rafacas** [comment]
@moollaza you're right, those searches would trigger the IA and I agree they shouldn't.

I've looked at the Base64 Goodie but I cannot see how those searches would be avoided there. I think "base64 implementation" and "base64 algorithm" would also trigger the Base64 Goodie.

I could try to implement your suggestion with the new Goodie Templates (btw, are thy published? I cannot find them) although I don't know any JS.

**Comment by mintsoft** [comment]
@rafacas ifaik they're not actually published yet, however we'll get a tutorial ready once they are. We're always here to help if you've got any problems around the JS anyway!

**Comment by moollaza** [comment]
@rafacas @mintsoft correct, this problem [does exist](https://duckduckgo.com/?q=base64+encoding+algorithm&ia=answer) for Base64 which sucks, and should be addressed.

At this point everything for the new Goodies templates is implemented, but we now need to write some docs and create some examples.

**Comment by rafacas** [comment]
@moollaza @mintsoft Ok, as soon as the new Goodies templates docs are published I'll start working on the migration of the hashes algorithms to the new templates. I'll probably ask for help with JS ;)

**Comment by moollaza** [comment]
@rafacas congrats! It's live: https://duckduckgo.com/?q=md4+this+string&ia=answer

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Comment by rafacas** [comment]
Thanks @moollaza! I'll stick around :)

**Pull request merged**
