### PR TITLE
alexishancock's  LGBT Terms Cheat Sheet Goodie

### PR DESCRIPTION
**Pull request by alexishancock**
**What does your Instant Answer do?**

Trigger a cheat sheet for LGBT Terms

**What problem does your Instant Answer solve (Why is it better than organic links)?**

Clears misconceptions quickly on terms regarding LGBT people and their lives

**What is the data source for your Instant Answer? (Provide a link if possible)**

http://web.jhu.edu/LGBTQ/glossary.html

**Why did you choose this data source?**

It's an official source approved by academia

**Are there any other alternative (better) data sources?**

Safezone Project's PDF training material

**What are some example queries that trigger this Instant Answer?**

lgbt cheat sheet

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

Education

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

Yes https://duck.co/ideas/idea/5974/lgbtq-terms

**Which existing Instant Answers will this one supercede/overlap with?**

None identified

**Are you having any problems? Do you need our help with anything?**

No

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

screen shot 2015-06-20 at 1 22 49 am

## Checklist
Please place an 'X' where appropriate.

```
- [x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility
    Please let us know which browsers/devices you've tested on:

    - Mac OSX
        - [x] Google Chrome
        - [x] Firefox
```

@nilnilnil This is initially for DuckDuckGo hiring process but also linked with an instant answer idea I submitted. Hoping maybe this can come to fruition. Thank you.

------

IA Page: https://duck.co/ia/view/lgbt_cheat_sheet

### CODE REVIEW

**Comment by jarmokivekas** [comment]
The content of the cheat sheet looks good to me :+1: . It contains has all the things I expected it to have. I have a few points of feedback, though I guess they are mostly due to the current cheat sheet architecture.

1. Some values have a `.` at the end of the sentence some don't.

2. Would be nice to have this cheat sheet trigger in variations of `LGBT` (`LGBT+`, `LGBTQIA` etc.).

3. The cheat sheet IA triggering is liberal. Among the sensible ones, also `LGBT characters` (probably referring to media/popular culture) and `LGBT commands` (umm...?) trigger this cheat sheet currently. See [all the trigger words](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/9dd190f2ed5999ee4c88124b288529f42420fade/lib/DDG/Goodie/CheatSheets.pm#L11).

4. I feel like there should be a clearer thematic break between the explanations so the text doesn't create long columns. It's unclear at a glance where the explanation for a certain key starts. Maybe something along the lines of:
breaks
 
I think I'll make a separate issue regarding the triggering, since it effects many of the other cheat sheets as well.

**Comment by mintsoft** [comment]
I'm not sure if a cheatsheet at the moment is the best format for this IA; given the complexity of the answers (i.e. length). It might be better placed to use the item/detail templates.

Have the name of the term in the item, which when clicked presents the definition (specifying-codeitemcode-and-codedetailcode-templates)

It's not as quick to see the information, but it may be a little tidier?

**Comment by alexishancock** [comment]
@jarmokivekas Thank you for the feedback!
@mintsoft I was wondering if there was a better template I could use. I just wasn't sure if there was one. SInce the answers are complex ones and I'd like all the info present, I will look into those item/detail templates. Do you have an example I could reference?

**Comment by moollaza** [comment]
@alexishancock thanks a lot for contributing! We really appreciate it.

I think @mintsoft is correct though that a cheat sheet may not be the best way to implement this. My other concern is that it looks like all these terms exist on Wikipedia already and so searching any of them individually produces an adequate description.

Similarly, there's a Wikipedia category page for "LGBT Terms", so we currently show a large disambiguation view for them, when searched: https://duckduckgo.com/?q=lgbt+terms

There's definitely something to be made of this though, so I'll speak to the team to gather their opinions on how we should proceed here.

**Comment by alexishancock** [comment]
@moollaza Oh I see. Well definitely let me know if you guys see a use for it. I wanted to create something for folks who may not even know what terms to look up. Considering how terms like "cisgender" are so foreign to others still. Thank you for stepping in and showing me what DuckDuckGo already provides.

**Comment by moollaza** [comment]
@alexishancock we had a talk and agreed that we're going to accept this for now and then later down the line, find a better way to display/layout Cheat Sheets similar to this.

**Comment by alexishancock** [comment]
@moollaza I'm glad to hear that! Thank you for discussing this.

**Comment by moollaza** [comment]
@alexishancock congrats! It's live: https://duckduckgo.com/?q=lgbt+cheat+sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
