### PR TITLE
fix(c-cheatsheet): Added string related methods

### PR DESCRIPTION
**Pull request by akanshgulati**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer
  - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
  - [x] Bug fix: *_`C cheat sheet: Fix` #3615 *_
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

What changes does this PR introduce? 
It adds string related methods to make the cheetsheet more clear and remove confusion of integer and string operators to a great extent.
###### Related Issues or Discussions

What issues or discussions (if any) does this PR address? Please provide the issue # or link.
###### People to notify

@mention @moollaza @tagawa 
---

Instant Answer Page: https://duck.co/ia/view/c_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @harisphnx

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by harisphnx** [comment]
I am not sure whether adding library functions and their details is this cheatsheet makes sense. I have 2 concerns regarding this,

1) Others (already included in the chaetsheet) are just basic C language features, but methods/functions fall into Library provided features.

2) It doesn't make sense to add just a handful of string functions, and that too without a proper explanation of their parameters and how to use them.

**Comment by mintsoft** [comment]
> 2) It doesn't make sense to add just a handful of string functions, and that too without a proper explanation of their parameters and how to use them.

@harisphnx I couldn't agree more, that was basically what I was attempting to articulate during the discussion in https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3615; although I can't deny the OP's argument around confusion to new comers from C's handling of 'strings'

**Comment by akanshgulati** [comment]
@mintsoft I too understand that we have to add extra library for using it but the only way I thought of reducing the confusion. It will somehow give a brief idea that for strings, we have to take another approach. I also wanted to add extra information but the template restricted me that.

**Comment by tagawa** [comment]
Another option may be to create a separate cheatsheet, similar to the specialised cheatsheets we have for C++ https://duck.co/ia?topic=c-

**Comment by mintsoft** [comment]
@tagawa That seems like a good solution to me; although ultimately it's up to @harisphnx as maintainer 👍

**Comment by harisphnx** [comment]
I would also recommend going for a separate cheatsheet for dedicated sections like string handling, IPC, network, file, etc. To keep things clear, and to give enough space for that section to be covered fairly.

Although, we can think about adding a note at the end of this cheatsheet to redirect people to the different sections (if that is what they were looking for).

PS : I do not want this work to go waste.

**Comment by akanshgulati** [comment]
@harisphnx I am in favour to making different cheatsheet but again, we have to revamp our C cheatsheet because making two cheatsheet won't be effective that much if confusion still persists. 
No issues in the inputs given in this PR, will migrate those changes if that will make things better.

**Comment by mintsoft** [comment]
@harisphnx Sorry, just to clarify. Is this OK to merge as-is or do you want some changes made?

**Comment by harisphnx** [comment]
@mintsoft, I wanted this to be made into a separate cheatsheet for functions related to string in C. Adding it here in this general cheatsheet is vague.

Sorry for the late reply, and for being unclear last time.

**Comment by mintsoft** [comment]
No problem @harisphnx 👍 

@akanshgulati are you OK making the changes requested: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3701#issuecomment-255695200

**Comment by akanshgulati** [comment]
@mintsoft yes, I am fine with this and will create a new cheatsheet for that purpose.

**Pull request closed without merging**
