### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by gautamkrishnar**
The example given for goodie was `NPM Goodie` and the screenshot and links given below is of `Javascript minifier goodie`. Changing the example.

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
@mintsoft Thanks 😄

**Comment by sahildua2305** [comment]
Probably lame, but the moment I read it, I wanted to add my name along with that mention of `JavaScript Minifier` 😛 

Can I? @mintsoft @tagawa

**Comment by gautamkrishnar** [comment]
@sahildua2305 hehehe 😄 😛 😉

**Pull request merged**
