### PR TITLE
Cheat Sheet: Fixes #2022

### LINKED ISSUE #2022: Shell cheat sheet: ambiguous or incorrect
The file in question is:
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/shell.json
If this cheat sheet is for bash (as the source URL implies), then the Variables section is incorrect.  Otherwise it's just ambiguous what shell language the cheat sheet is for.

### PR DESCRIPTION
**Pull request by mbionchi**
Fixes #2022 

https://duck.co/ia/view/bash_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@mbionchi Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub username:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
@mbionchi add some aliases to trigger this on shell query as well

``` 
"aliases": [
"shell language",
 "shell"
    ]
 ```

**Comment by gautamkrishnar** [comment]
Fixes #2022

**Comment by moollaza** [comment]
@mbionchi @gautamkrishnar agreed -- let's add in some aliases :+1:

**Comment by mbionchi** [comment]
@gautamkrishnar @moollaza added some aliases.  I also realized that there is no template_type in this cheat sheet -- what do you think it should be?  The cheat sheet is really diverse -- there are code snippets, key combinations, etc -- is there a facility that will allow to have different template types for individual sections?

**Comment by moollaza** [comment]
> is there a facility that will allow to have different template types for individual sections?

@mbionchi no, we'd need to choose 1 type, and I hadn't noticed how big this Cheat Sheet is and how mixed the content is.

It seems to me that the shortcuts section could potentially be it's own Cheat Sheet. We're working on ways of better grouping related cheat sheets, so that ideally "bash cheat sheet" would be able to surface multiple related keys.

For now I guess the `keyboard` or `code` template is best

I think it would be good to p

**Comment by mbionchi** [comment]
@moollaza I added the "code" template and I think it looks reasonable (for now).  Is there a way I can jump in on grouping the related cheat sheets project also?

**Comment by moollaza** [comment]
> Is there a way I can jump in on grouping the related cheat sheets project also?

We haven't yet discussed how this would work or look, but AFAICT, all necessary changes would be made in the open.

Would you be interested in investigating what a potential solution might look like? If so, it would be great if you could create an issue outlining how you think it should look/work.

Ideally, we'd want a way to collect all cheat sheets related to a search term and present them in our standard tile view. Clicking a tile would expand the detail area to show the cheat sheet contents.

Does that make sense?

**Comment by mbionchi** [comment]
@moollaza Yeah, that makes total sense.  I'm not confident enough produce a full-stack demo though (i'm a back-end person), so I'll perhaps wait until there's some progress on that.

BTW, what's with travis failing on this and my other PR?

**Comment by moollaza** [comment]
> @moollaza Yeah, that makes total sense. I'm not confident enough produce a full-stack demo though (i'm a back-end person), so I'll perhaps wait until there's some progress on that.

Understood, that's no problem :+1: 

> BTW, what's with travis failing on this and my other PR?

It's not your fault, we had some changes to a dependency for the Conversions IA which was causing tests to fail. That problem has since been fixed so moving forward things should be fine. If really you want to get rid of it, you should be able to merge our master branch into your PR.

**Comment by jagtalon** [comment]
@mbionchi looks good! :+1:

**Comment by edgesince84** [comment]
@mbionchi,  thanks again for fixing the Bash Cheat Sheet! You’ve done a really good job here and we'd like you to help our community tackle the next big challenge - our mission to become the best search engine for programmers: https://duck.co/blog/post/297/help-for-programmers.

When you're ready to move on, please: 

- Create a new Instant Answer to increase our Programming IA coverage

OR

- Test live programming Instant Answers (or those in development) for bugs and suggest improvements 

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage).

Thanks again!

**Pull request merged**
