### PR TITLE
Prove: Added -PPretty option

### PR DESCRIPTION
**Pull request by tagawa**
Following a [request on Twitter](https://twitter.com/oylenshpeegul/status/709907229508571137)

Also capitalised the descriptions.

---
https://duck.co/ia/view/prove_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MrChrisW** [comment]
@tagawa LGTM

**Comment by tagawa** [comment]
Thanks for the quick merge @MrChrisW

**Comment by moollaza** [comment]
@tagawa @MrChrisW Next time, we need to make sure we wait for maintainer approval ;)

We're modifying the content so the maintainer needs to approve the change

**Comment by MrChrisW** [comment]
@moollaza Oops... :disappointed: good point! I'll remember for next time :pushpin:

**Pull request merged**
