### PR TITLE
Titlecase: Converting to text template

### PR DESCRIPTION
**Pull request by mintsoft**
###### Description of changes

Ref: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767

---

Instant Answer Page: https://duck.co/ia/view/title_case

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moollaza (you're the maintainer on this!?)

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@mintsoft Thanks! :dolphin:

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors If anyone is interested in Maintaining this Instant Answer, it's all yours :)

I'm not sure why I'm the current maintainer...

**Comment by pjhampton** [comment]
@moollaza assign it to me.

**Pull request merged**
