### PR TITLE
Improved spelling/phrasing and dropped a phrase

### PR DESCRIPTION
**Pull request by Retzudo**
- It's 'Gute Nacht', not 'Guten Nacht'
- 'night' is not a proper noun
- Nobody says 'Guten Mittag'
- Changed 'Ruf die Polizei' to a formal version to match the rest of the phrases
- 'Police' is not a proper noun
- Rephrased 'Please speak more slowly!' to be a question in both languages
- 'heisst' -> 'heißt'
- 'Dinner on the town' -> 'Going out for Dinner'

Source: native speaker

### CODE REVIEW

**Comment by moollaza** [comment]
@Retzudo thanks a lot! I'll get our community translation managers to confirm this is good (which I clearly should have done before! :dizzy_face: )

**Comment by to-ba** [comment]
Gute Nacht: yes
    'night' is not a proper noun: english issue
    Nobody says 'Guten Mittag': yes
    Changed 'Ruf die Polizei' to a formal version to match the rest of the phrases: »Die Polizei anrufen«
    'Police' is not a proper noun: english issue
    Rephrased 'Please speak more slowly!' to be a question in both languages: english issue
    'heisst' -> 'heißt': yes
    'Dinner on the town' -> 'Going out for Dinner': english issue

**Comment by moollaza** [comment]
@to-ba thanks a lot for the review! I'll can try to provide some better English phrases?

- "Going out for Dinner" -> "Going out for dinner"
- "Can you speak more slowly, please" -> "Can you speak slower, please" OR "Can you please speak slower"

I think that's it?

**Comment by moollaza** [comment]
@Retzudo @to-ba I forgot that another user also submitted some changes yesterday that need reviewing. Would you two like to chime in on that PR so we can all agree on what should be changed?

Thanks!

https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1358

**Comment by moollaza** [comment]
@Retzudo these changes have now been added in #1566 

Thanks again for submitting your fixes we really appreciate it! Apologies that we didn't merge it sooner though.

We invite you to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

**Pull request closed without merging**
