### PR TITLE
New Telegu CheatSheet

### PR DESCRIPTION
**Pull request by roxxup**
edits - "Capitalised , Added more sections , Removed hindi and assemese , proper exclamation marks "

### CODE REVIEW

**Comment by roxxup** [comment]
The command "dzil smoke --release --author" exited with 29. how to correct this !

**Comment by roxxup** [comment]
IA: https://duck.co/ia/view/telugu_language_cheat_sheet

**Comment by GuiltyDolphin** [comment]
@roxxup You should only be modifying one file (the cheat sheet). It might be easier if you were working off of a branch other than `master`.

**Comment by roxxup** [comment]
@GuiltyDolphin so , i need to shift to a branch and make a pull request from there ?

**Comment by roxxup** [comment]
should i remove everything and clone again because i think i messed up the
repo

**Pull request closed without merging**
