### PR TITLE
svdsande sublime text cheat sheet goodie

### PR DESCRIPTION
**Pull request by svdsande**
What does your Instant Answer do?
This instant answer or cheat sheet provides a large list of Windows keyboard shortcuts for Sublime Text. Which is a cross-platform text and source code editor available for Windows, Linux and Mac.

What problem does your Instant Answer solve (Why is it better than organic links)?
There is documentation available for Sublime Text but one part it is unofficial, and the list of keyboard shortcuts for Windows/Lunix is a draft and may contain wrong information. This cheat sheet should give DuckDuckGo users clear information about what shortcuts are available for Sublime Text. :)

What is the data source for your Instant Answer? (Provide a link if possible)
I have Sublime Text installed on my computer and wrote all the keyboard shortcuts down from the application menu.

Why did you choose this data source?
Because I know that this information is accurate and also works within Sublime Text.

Are there any other alternative (better) data sources?
There is a list available with keyboard shortcuts for Windows/Lunix but it is a draft and may contain wrong information:  http://sublime-text-unofficial-documentation.readthedocs.org/en/sublime-text-2/reference/keyboard_shortcuts_win.html?highlight=shortcuts

What are some example queries that trigger this Instant Answer?
- sublime cheat sheet
- sublime text cheat sheet

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)
This instant answer is very useful for everyone who uses Sublime Text, these are mainly programmers and webdevelopers.

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?
Unfortunately this instant answer is not connected to a DuckDuckHack instant answer. :(

Which existing Instant Answers will this one supercede/overlap with?
When I searched "sublime text cheat sheet" on DuckDuckGo I found three software instant answers but no cheat sheets. My cheat sheet could overlap the software instant answers.
software

Are you having any problems? Do you need our help with anything?
I followed the cheat sheet tutorial on DuckDuckHack which was very clear: https://duck.co/duckduckhack/goodie_cheat_sheets Add the beginning I had some problems with formatting my json right, button after using a json Validator I found the solution quickly.

Where did you hear about DuckDuckHack? (For first time contributors)
I found a link on the DuckDuckGo website to DuckDuckHack, after that I read the documentation/tutorials and I was immediately hooked.

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
screenshot one
screenshot two

### CODE REVIEW

**Comment by moollaza** [comment]
@svdsande thanks a lot for contributing, we really appreciate it!

There's just one problem -- someone else already has a Sublime Text Cheatsheet in progress!

Please checkout #1196. Perhaps you can offer some improvements to that Cheat Sheet?

Alternatively, is there something else you'd like to work on? Another cheat sheet perhas?

As our documentation mentions, please check with us first before working on anything so we can prevent you from working on something that's already done/in-progress!

**Comment by svdsande** [comment]
@moollaza Thanks for your comment! That's totally my fault I should first have checked if someone else was building a Sublime Text cheat sheet. I am new to DuckDuckHack so I have a lot to learn! :) Tomorrow I will start building a new cheat sheet, but before that I will check the other cheat sheet projects.

**Comment by moollaza** [comment]
@svdsande thanks a lot for understanding. Would you like to update this PR (or make a new one) to add improvements to the existing Sublime Text Cheat Sheet?

**Comment by moollaza** [comment]
ping! @svdsande are you interested in modifying your PR so that it updates the existing Sublime Text Cheat Sheet?

**Comment by svdsande** [comment]
@moollaza Sorry for my late response! :sob: I would like to update my pull request so it can updates the existing Sublime Text cheat sheet. Can you tell me how I can do that because I have never done that before. :sweat_smile:

**Comment by moollaza** [comment]
Closing this as it's been moved to a new PR

**Pull request closed without merging**
