### PR TITLE
CurrencyIn: fixes #1599

### LINKED ISSUE #1599: CurrencyIn: The currency in Poland is the Polish zÅoty (PLN)
If you search for "[what is the currency of poland](https://duckduckgo.com/?q=what+is+the+currency+of+poland&t=canonical&ia=answer)" the answer will be "The currency in Poland is the Polish zÅoty (PLN)", while it should be "The currency in Poland is the Polish złoty (PLN)"

IA Page:  http://duck.co/ia/view/currency_in

### PR DESCRIPTION
**Pull request by ozdemirburak**
poland
vietnam

### CODE REVIEW

**Comment by mintsoft** [comment]
@ozdemirburak would adding just `use utf8;` into the `.pm` have fixed it also?

**Comment by ozdemirburak** [comment]
@mintsoft unfortunately no.

**Comment by mintsoft** [comment]
@ozdemirburak Fair enough; can you add a test or two into https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/CurrencyIn.t to cover the unicode cases?

**Comment by ozdemirburak** [comment]
@mintsoft added.

**Comment by mintsoft** [comment]
Cool, thanks for the fix @ozdemirburak it looks good to me. 

If you're interested at all, this is one of the of the IA's we have on a list to remove all the HTML from and use the built-in templates; https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1163

**Pull request merged**
