### PR TITLE
CheatSheets: Fix whitespace (attributes)

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
@zachthompson This fixes a bunch of whitespace issues picked up by #2740 (I also thought I'd kill of some other whitespace issues at the same time) - I'm including it separately so there isn't as much clutter on that PR (and you get to see the new reporting).

*Note:* The primary aim of this PR is *not* to clean up *general* whitespace, but rather *specific* forms of whitespace (within attributes) picked up by #2740. Other whitespace corrections are included as an... *'automatic'* bonus.

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by altern8tif** [comment]
@GuiltyDolphin I think this might have been brought up before (probably by @moollaza)... 

Using [HoundCI](http://www.houndci.com) would allow us to directly fix trailing whitespace in code (by implementing a style guide) rather than throwing warnings which still requires a PR to fix... They use JSHint which should work for fixing JSON files...

**Comment by GuiltyDolphin** [comment]
@altern8tif This isn't for trailing whitespace in general - just in certain attributes within the cheat sheets. Vim just automatically sorts out trailing whitespace for me so I thought I'd include it (I use `git add --patch` a lot - a pain with whitespace corrections).

We should note that not *all* fields have to be corrected - only certain `val`, `trn` etc...

If you want to know more about what is *actually* being checked, just have a look at #2740.

**Comment by altern8tif** [comment]
@GuiltyDolphin Ah ok I see... Yea I've got Sublime Text set up to sort out trailing whitespace for me too.

Also realised that style guides are being talked about in #2289 already... Hope that we can implement some kind of style guide to keep code more consistent.  Maybe it's just my OCD, but I sometimes feel a bit uneasy when I see files using different spacing/tabs :grimacing:

**Comment by GuiltyDolphin** [comment]
@altern8tif Yeah - we're automating more and more though, so if people follow the *existing* style introduced by the tools we should all live happily - if they don't... Then :cry:

**Comment by moollaza** [comment]
@GuiltyDolphin Thanks! This LGTM :+1:

**Pull request merged**
