### PR TITLE
convert router passwords goodie to structured answer

### PR DESCRIPTION
**Pull request by kirkins**
## Description of new Instant Answer, or changes

This returns a structured answer for router passwords goodie.

## Related Issues and Discussions

#1163

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/Router_Passwords

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by kirkins** [comment]
This instant answer would probably be better as a cheat sheet, but I'm trying to achieve my goal of converting all the remaining answers.

I figure if it's still in the code base, we might as well convert it to a structured answer, it's not high priority now but it was when I started, so I'd like to finish the task (#1163).

**Comment by kirkins** [comment]
@mintsoft I will keep your review on #4255 & #4254 in mind for this request (and #4061).

I appreciate the feedback, trying to get good with Perl (strange but interesting language).

**Comment by moollaza** [comment]
@kirkins this IA was taken offline years ago because we suspected it was causing a memory leak. I think its probably best to simply remove it from the repo at this point. There's no evidence anyone wants or will use this.

At 4K LOC, I don't think this would be appropriate for a cheat-sheet unless we seriously cut down the data to maybe the top 50 routers or so.

Sorry to have wasted your time on this.

**Comment by kirkins** [comment]
@moollaza no problem, that makes sense.

**Pull request closed without merging**
