### PR TITLE
Elixir Cheat Sheet: Remove duplicate "String.reverse/1"

### PR DESCRIPTION
**Pull request by optikfluffel**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Provide an overview of the changes this pull request introduces.
This PR remove the duplicate of `String.reverse/1` in the Elixir Cheat Sheet. Also I fixed some inconsistent usage of spaces.

---

Instant Answer Page: https://duck.co/ia/view/elixir_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

### CODE REVIEW

**Comment by daxtheduck** [comment]
@optikfluffel Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Super thanks @optikfluffel! 
Good catch 😄  I must not have had my morning coffee when writing that list.

LGTM :shipit:

**Comment by optikfluffel** [comment]
Any updates on this?

**Comment by pjhampton** [comment]
@duckduckgo/community-leaders merge when ready 👍

**Comment by tagawa** [comment]
@optikfluffel Sorry for the delay in this. Deploying to beta now so we can double-check it before merging.

**Comment by tagawa** [comment]
Looks perfect to me. Thank you for the fix @optikfluffel!

**Pull request merged**
