### PR TITLE
Added cheat sheet for United Nations

### PR DESCRIPTION
**Pull request by aiyankovil**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New United Nations Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Added cheat sheet for united nation members and year of admission

---
https://duck.co/ia/view/un_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@aiyankovil Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gaulrobe** [comment]
@aiyankovil I'm wondering if this should be renamed from `un_cheat_sheet` to `united_nations_cheat_sheet` in order to be more verbose? Then you could add an `alias` for `un`? Just a thought.

**Comment by aiyankovil** [comment]
@gaulrobe sir,thks for suggesting. actually if i am changing the id to united_nations_cheat_sheet it will effect my IA page ,which has already been set to un_cheat_sheet. But i can add the alias for United nations

**Comment by gaulrobe** [comment]
@aiyankovil this is looking pretty good! Could you run the JSON through something like https://jsonformatter.curiousconcept.com/ so that we get standardized formatting? Thanks! :smile:

**Comment by aiyankovil** [comment]
@gaulrobe sir, has done what has been specified.thks

**Comment by zekiel** [comment]
LGTM!

**Pull request merged**
