### PR TITLE
Fix #1816 Replace <br> with linebreaks in java cheatsheet

### LINKED ISSUE #1816: CheatSheets: Java cheatsheet overlap on wide screens
I'm not sure if this is just the Java cheatsheet or not, but I couldn't reproduce with other cheatsheets. I guess something to do with the line length here?

screenshot_2015-11-25_16-03-02

https://duck.co/ia/view/java_cheat_sheet

### PR DESCRIPTION
**Pull request by MoriTanosuke**
Fixes #1816

* Remove `0x00ad` values from text
* Replace multiple `&nbsp;` with `\t`
* Fix minor typo

Instant Answer Page: https://duck.co/ia/view/java_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@MoriTanosuke Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
Thanks for the PR @MoriTanosuke!  I know @moollaza said your fixes already looked good, so this should be nice and easy

**Comment by moollaza** [comment]
@MoriTanosuke Thanks! This LGTM :+1:

**Comment by edgesince84** [comment]
hey @MoriTanosuke, thank you for your contribution to DuckDuckHack, we really appreciate it! I'm reaching out to let you know that we recently launched a new forum with the initiative of improving programming-related searches, and I hope you'll [join us](https://forum.duckduckhack.com/)!

There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Pull request merged**
