### PR TITLE
improving php cheatsheet

### PR DESCRIPTION
**Pull request by Sayanc93**
IAs:
- https://duck.co/ia/view/php_cheat_sheet
- https://duck.co/ia/view/git_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@Sayanc93 it looks like your Git cheat sheet commits were included here -- can you please remove them?

**Comment by Sayanc93** [comment]
I removed the commit

**Comment by Sayanc93** [comment]
can this be merged?

**Comment by moollaza** [comment]
@Sayanc93 Thanks! This LGTM :+1:

**Pull request merged**
