### PR TITLE
New Backbone.js Cheat Sheet

### PR DESCRIPTION
**Pull request by vikashvverma**
**What does your Instant Answer do?**

This instant answer is a quick reference of Backbone.js, a JavaScript framework with a RESTful JSON interface.

**What is the data source for your Instant Answer? (Provide a link if possible)**

[ http://backbonejs.org/](http://backbonejs.org/)

**Why did you choose this data source?**

This is official source for Backbone.js.

**Are there any other alternative (better) data sources?**

Since the source is the official Backbone.js, I don't think there is any other better source.

**Which communities will this Instant Answer be especially useful for? (gamer, book lovers, etc)**

Programmers

**Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?**

No

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

screen shot 2016-02-16 at 9 25 53 pm

IA Page: [ https://duck.co/ia/view/backbone_js_cheat_sheet](https://duck.co/ia/view/backbone_js_cheat_sheet)

### CODE REVIEW

**Comment by vikashvverma** [comment]
@moollaza Can you review this?

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=BackboneJS Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/backbone_js_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=BackboneJS Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/backbone_js_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=BackboneJS Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/backbone_js_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@vikashvverma Thanks! This LGTM :+1:

**Pull request merged**
