### PR TITLE
New Answer Goodie

### PR DESCRIPTION
**Pull request by aanarres**
Added 'If you could hack your search engine, what would you do?' goodie : born out of the fun I had when I read that question in DDG documentation.

Now that it's working, I don't know if it's of interest... but it was fun. :smile: 

IA page: https://duck.co/ia/view/ifyoucould

### CODE REVIEW

**Comment by daxtheduck** [comment]
@aanarres Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@aanarres In its current state, I'm not sure this is terribly useful.

I can see it being quite handy if we have it say, return Instant Answer ideas from `duck.co` or maybe even examples of existing Instant Answers; though I think that would be better suited for Spice.

**Comment by aanarres** [comment]
Oh, you're right, that sounds cool! Let me think about it.

**Comment by mintsoft** [comment]
@aanarres I think I'm going to close this for now; gimme a shout if you want to revive it and we can reopen whenever

**Pull request closed without merging**
