### PR TITLE
Update Cantonese Cheat Sheet

### PR DESCRIPTION
**Pull request by wongalvis**
Updates to use transliterations in template

-----
IA Page: https://duck.co/ia/view/cantonese_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by wongalvis** [comment]
@moollaza The language template cannot be previewed on my Codio, cannot find it in the list of templates in DuckDuckHack too.

**Comment by moollaza** [comment]
@wongalvis apologies, it still needs to be added to the documentation -- it's a new `template_type` for Cheat Sheets.

You can see examples here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/language/malayalam.json#L20

not the `template_type` and the new `trn` key that's being used.

**Comment by wongalvis** [comment]
Updated @moollaza but still couldn't preview in Codio.

**Comment by moollaza** [comment]
@wongalvis apologies, I just merged a PR that switched this to the `language` template, but doesn't implement the `trn` portion -- can you pull master into this PR to remove the conflicts? It should auto-deploy to beta then.

The IA should definitely work with the language template in DuckPAN though. I notice it's not in the `language` subdirectory either so moving it there would be good. I don't think that should have any effect on it working in DuckPAN though.

Are you seeing any errors? Check the console?

**Comment by wongalvis** [comment]
Is this alright? @moollaza

**Comment by moollaza** [comment]
@wongalvis Thanks! This LGTM :+1:

**Pull request merged**
