### PR TITLE
New Indian States Census Cheat Sheet

### PR DESCRIPTION
**Pull request by vikashvverma**
This PR creates a cheat sheet to show census of indian states.

Screenshot:

screen shot 2016-02-22 at 11 14 36 pm

IA Page: [https://duck.co/ia/view/indian_states_census](https://duck.co/ia/view/indian_states_census)

### CODE REVIEW

**Comment by daxtheduck** [comment]
## [Indian States' Census](https://duck.co/ia/view/indian_states_census)

**Description**: Displays census of all the Indian States

**Example Query**: [census indian states cheat sheet](https://beta.duckduckgo.com/?q=census indian states cheat sheet), [indian states census cheat sheet](https://beta.duckduckgo.com/?q=indian states census cheat sheet)

**Tab Name**: Answer

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/indian_states_census)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/indian_states_census)*

**Comment by zekiel** [comment]
@vikashvverma  this is a difficult cheat sheet to have around because it will be out of date as soon as newer data is published. What about making a Spice for it using an API like http://api.population.io/ or similar?

**Comment by vikashvverma** [comment]
@zekiel This API doesn't give state wise population for a particular country.

It gives country wise population.
Also we have a world population cheat sheet https://beta.duckduckgo.com/?q=world+population+cheat+sheet&ia=cheatsheetscontroller

There seems to be no linked IA page with it.

This might be converted to a spice

**Comment by zekiel** [comment]
@vikashvverma maybe one over at mashape?

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=census indian states cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/indian_states_census_mobile.png)

**Comment by vikashvverma** [comment]
@zekiel I will try mashape

**Comment by zekiel** [comment]
@vikashvverma cool -- let us know if you want to re-open this but we'll close for now to keep it out of the queue.

**Pull request closed without merging**
