### PR TITLE
adds poker hands probabilities to poker hands cheat sheet (completes #1383)

### PR DESCRIPTION
**Pull request by seisfeld**
@moollaza Here you go. I merged PR #1383 into the poker hands cheat sheet. Once this is merged, #1383 can be closed. This is how it looks now:

poker-hands

### CODE REVIEW

**Comment by mintsoft** [comment]
This LGTM

**Comment by moollaza** [comment]
:+1:

**Comment by moollaza** [comment]
Thanks guys!

**Comment by seisfeld** [comment]
You're welcome @moollaza. I'm always happy if i can help out or give a hand on new PRs. :)

**Pull request merged**
