### PR TITLE
CSS Colors: CSS fixing added (fixes #3542)

### LINKED ISSUE #3542: CSS Colors: Remove vertical divider after 'Show more'
screen shot 2016-08-19 at 9 13 03 am
   

------
IA Page:  http://duck.co/ia/view/css_colors 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

### PR DESCRIPTION
**Pull request by khanujasunny**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer
  - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
  - [X] Bug fix: **`CSS Colors: Fix #3542`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

What changes does this PR introduce? 
###### Related Issues or Discussions

Fixes #3542 
###### People to notify

@hchienjo @moollaza 

---

Instant Answer Page: https://duck.co/ia/view/css_colors

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

### CODE REVIEW

**Comment by daxtheduck** [comment]
@khanujasunny Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@khanujasunny thanks for trying to fix the issue here.

I had left a comment about a better solution to this problem here: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3542#issuecomment-250566186

Can you add a "More at" URL to this Instant Answer instead of removing the divider?

**Comment by moollaza** [comment]
@khanujasunny Ping! Would you be able to finishing this one up? We'd love to get this live!

**Comment by moollaza** [comment]
This PR is being closed due to inactivity. If you're still interested in finishing, please let me know and I'll gladly re-open it for you!

**Comment by moollaza** [comment]
Actually, it looks like this issue was already resolved, so this PR is no longer needed 👍

**Pull request closed without merging**
