### PR TITLE
Goodbye metadata...mostly

### PR DESCRIPTION
**Pull request by zachthompson**
Remove unneeded metadata from modules.

### CODE REVIEW

**Comment by zachthompson** [comment]
Need to address the missing metadata issue.

**Comment by russellholt** [comment]
I'm ready for this

**Comment by zachthompson** [comment]
ugh, all checks passed, conflicts merged.  Please give this a look.

**Comment by russellholt** [comment]
screenshots / query tester @moollaza

**Comment by moollaza** [comment]
Tests are failing due to unrelated Conversions issue with Travis. They pass locally :+1:

**Comment by moollaza** [comment]
THANKS! THIS LGTM :+1: :+1:

**Pull request merged**
