### PR TITLE
Update presidents.yml

### PR DESCRIPTION
**Pull request by itsN1X**
Adding Donald.

## Description of new Instant Answer, or changes
Update knowledgebase

---

Instant Answer Page: https://duck.co/ia/view/potus

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by adityatandon007** [comment]
@itsN1X This IA is not currently active.

**Comment by itsN1X** [comment]
But the update can be merged, right?
We don't want to return outdated IAs now, do we?
I've only updated facts!

**Comment by moollaza** [comment]
@itsN1X please update the tests to pass for this to be mergeable

**Comment by itsN1X** [comment]
Refer pr #3923

**Comment by gautamkrishnar** [comment]
Btw @itsN1X you dont have to open a new pr for the tests, Can you please make changes in this PR itself?
Just edit the contents of https://github.com/itsN1X/zeroclickinfo-goodies/blob/57f905d43d46d790c146b72b12fc35cf11487164/t/POTUS.t and replace it with the contents of that PR.
Closing #3923

**Comment by itsN1X** [comment]
Hey, I merged updates into patch-1.  The CI -build is successful.
Review this @gautamkrishnar

**Comment by gautamkrishnar** [comment]
Sorry @itsN1X you merged it into your master. Sorry for the confusion. I will do the tests myself...

**Comment by gautamkrishnar** [comment]
@moollaza Good to review...

**Comment by itsN1X** [comment]
Everything's working now, right?

**Comment by gautamkrishnar** [comment]
Yes absolutely @itsN1X 😄

**Comment by itsN1X** [comment]
@moollaza  merge?

**Pull request merged**
