### PR TITLE
Created tennis cheat sheet

### PR DESCRIPTION
**Pull request by tagawa**
**What does your Instant Answer do?**
Shows key facts about tennis such as scoring system, history, match and shot types, etc.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
The information is in one place and easier to skim than reading full articles.

**What is the data source for your Instant Answer? (Provide a link if possible)**
https://en.wikipedia.org/wiki/Tennis and linked sub-pages on Wikipedia.

**Why did you choose this data source?**
Because it's Wimbledon time!

**Are there any other alternative (better) data sources?**
Perhaps from the International Tennis Federation website but there may be usage restrictions.

**What are some example queries that trigger this Instant Answer?**
```tennis cheatsheet```
```tennis cheat sheet```

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Tennis fans, both players and watchers, and those just getting into tennis.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No

**Which existing Instant Answers will this one supercede/overlap with?**
None that I'm aware of.

**Are you having any problems? Do you need our help with anything?**
Nope.

**Where did you hear about DuckDuckHack? (For first time contributors)**

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
tennis-cheatsheet

## Checklist
Please place an 'X' where appropriate.

```
- [x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [x] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Linux (Ubuntu 14.04)
        - [x] Chromium
        - [x] Firefox
        - [x] Opera
```

-----
IA Page: https://duck.co/ia/view/tennis_cheat_sheet

### CODE REVIEW

**Comment by MrChrisW** [comment]
Awesome stuff @tagawa as usually do you mind filling out the [PR Template](https://raw.githubusercontent.com/duckduckgo/zeroclickinfo-goodies/master/pull_request_template_goodie.md) :+1:

**Comment by tagawa** [comment]
Thanks @MrChrisW, just doing it now.

**Comment by MrChrisW** [comment]
@tagawa Sorry thought you might be! :smile:

**Comment by tagawa** [comment]
No need to apologise for your efficiency! Should be OK now.

**Comment by MrChrisW** [comment]
@tagawa Just noticed this [Racket vs. Racquet](https://en.wikipedia.org/wiki/Racket_(sports_equipment)#Spelling) - not a problem, just wondering which word is preferred, it looks like `Racquet` is the one used in the [Tennis wiki](https://en.wikipedia.org/wiki/Tennis) article :stuck_out_tongue_winking_eye:

**Comment by tagawa** [comment]
@MrChrisW Yes, I was wondering the same thing. I stuck with racquet as it's used on Wikipedia but I'm happy to change it racket if that's more widely understood.

**Comment by moollaza** [comment]
This LGTM :+1:

**Comment by moollaza** [comment]
Thanks guys!

**Comment by tagawa** [comment]
Great, thank you @MrChrisW and @moollaza

**Pull request merged**
