### PR TITLE
New BBCode Cheat Sheet

### PR DESCRIPTION
**Pull request by x-15a2**
**What does your Instant Answer do?**
- Provides a cheatsheet for BBCodes (used by many online forums, including the DDG forums)

**What is the data source for your Instant Answer? (Provide a link if possible)**
- http://bbcode.org
- http://bbcode.org/reference.php

**Why did you choose this data source?**
This is pretty much the defacto resource for BBCodes

**Are there any other alternative (better) data sources?**
- There are others, but most are specific to particular forum software BBCode implementations. The source that I selected is primarily the standard codes used by most forums.

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
- Those that use online forums on other online communities that support BBCode formatting.

**Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?**
- Yes, one that I suggested: https://duck.co/ideas/idea/6214/bbcode-cheatsheet

**Are you having any problems? Do you need our help with anything?**
- I didn't have problems with this cheatsheet, but now I'm having problems testing new and existing cheatsheets. I think that I need to do a clean download of the entire project in Codio from the top down, but can't figure out how to do so. I'm quite the dunderhead.

**Where did you hear about DuckDuckHack? (For first time contributors)**
- I've been part of the DDG community for a long time and am a ComLeader, so I figured it was time to give it a go.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
- Well, it looks great. Unfortunately I can't get duckpan server to work any more (see above) so I can't provide a screenshot.

-----
IA Page: https://duck.co/ia/view/bbcode_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@x-15a2 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by moollaza** [comment]
@x-15a2 thanks for your contribution!

Can you please fill out the [pull request template](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/pull_request_template_cheat_sheet.md) and edit your initial comment. Once completed, we'll be sure to review your PR and give you some feedback.

Thanks!

**Comment by moollaza** [comment]
@x-15a2 I've continued and merged this in the above PR, #1644

**Comment by moollaza** [comment]
>I didn't have problems with this cheatsheet, but now I'm having problems testing new and existing cheatsheets. I think that I need to do a clean download of the entire project in Codio from the top down, but can't figure out how to do so. I'm quite the dunderhead.

@x-15a2 if you go to your dashboard on Codio you should be able to view all your "boxes". You can delete your current DuckDuckHack box and then follow the steps in the docs to fork the DuckDuckHack project on Codio again.

**Comment by moollaza** [comment]
@x-15a2 congrats! It's live: https://duckduckgo.com/?q=bbcode+cheat+sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
