### PR TITLE
rails-devops-cheat-sheet

### PR DESCRIPTION
**Pull request by mohan08p**
rails-devops

IA page: https://duck.co/ia/view/rails_devops_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Rails Devops Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/rails_devops_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Rails Devops Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/rails_devops_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Rails Devops Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/rails_devops_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Rails Devops Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/rails_devops_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@mohan08p This LGTM :+1:

Thanks again for taking the time to contribute! We really appreciate it :smiley:

**Pull request merged**
