### PR TITLE
New FontAwesome Icons Cheat Sheet. Implemented #2256

### PR DESCRIPTION
**Pull request by mr-karan**
Link to IA : https://duck.co/ia/view/fontawesome_icons_cheat_sheet

ddg

### CODE REVIEW

**Comment by daxtheduck** [comment]
@mr-karan Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub username:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mr-karan** [comment]
Hey. Can anyone explain why I got a Travis CI build fail on this PR? I think it passed all tests given in auto-generated  test file

**Comment by mr-karan** [comment]
As I had a trigger  `fa cheat sheet` in it but since this is a goodie,the regular cheat sheet Perl code was being triggered but as there are no `json` files in `cheat_sheets/` directory, it caused the test to fail in Travis CI. As suggested by @tagawa on Slack group, I have removed the test file. 
Hope this is alright now.

**Comment by moollaza** [comment]
@mr-karan I'm sorry but this is heading in the wrong direction. Goodies should not be loading pure HTML -- that's why we have templates. As well, we cannot load the CSS via a CDN (or any 3rd party website) as that is a privacy leak. The CDN would see the user's IP which breaks our terms.

If this is a cheat sheet it should be using our standard JSON format. For now, let's stick to the `reference` template with the icon names and the required CSS classes. We plan to add image support, so if there are images available for the icons we could add that in to V2 to make it more useful.

I'll talk to the team to see if there is a better approach to this, but we should definitely avoid making it a standalone Goodie.

**Comment by mr-karan** [comment]
Alright, I will get back to the standard JSON format with icon names as key and CSS classes as values. Should I open a new PR for this ?

**Comment by moollaza** [comment]
@mr-karan thanks for understanding.

>Should I open a new PR for this ?

Yes please!

**Pull request closed without merging**
