### PR TITLE
2048 rewrite

### PR DESCRIPTION
**Pull request by Roysten**
This pull request is an attempt to solve issue #1637.

**What does your Instant Answer do?**
2048

**What are some example queries that trigger this Instant Answer?**
* play 2048
* play 2048 6

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
gamers, people at the office...

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
https://duck.co/ia/view/game_2048

**Which existing Instant Answers will this one supercede/overlap with?**
none

**Are you having any problems? Do you need our help with anything?**
* How are we going to handle winning/losing? Right now it's an alert, but it should be something more polished.
* In the proposed design all possible tiles are listed on the right side, why? Isn't it a part of the game discovering what color the next tile will be?
* Swipe support for mobile devices would be nice though... unfortunately jQuery mobile is not supported and I'm not really eager to implement touch events myself. Any ways to get this done easily?

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
imgur

## Checklist
Please place an 'X' where appropriate.

```
- [x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 10
        - [] Google Chrome
        - [x] Firefox
        - [] Opera
        - [] IE 11
        - [] Microsoft edge
        
    - Windows 8
        - [] Google Chrome
        - [x] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [x] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Linux
        - [] Google Chrome
        - [x] Firefox
        
    - Mac OSX
        - [] Google Chrome
        - [x] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

```

Progress so far:
* Refactored code, now all tiles have an object which stores row, column and value -> all but one nested for loop have been removed;
* Random generation of new tiles has been simplified, now it simply loops through all tiles (not very expensive, just 16 max) and stores the free tiles. After that is done it will randomly pick one out of that list.
* Fixed a bug in game-over detection;
* Fixed misbehaving event listeners;
* Implement suggested design.

To-do:
* Test files

-----
IA Page: https://duck.co/ia/view/game_2048

### CODE REVIEW

**Comment by moollaza** [comment]
> How are we going to handle winning/losing? Right now it's an alert, but it should be something more polished.

@Roysten we could overlay the game with a nice message -- I'll have the team think about a design. I image a green background that says "You Win" or red with "You Lose".

As a replacement of the native alert we have `DDG.page.notify()`. You can run `DDG.page.notify("Game Over")` on a search page to see a pretty message appear and go away. We use it in a few places, like notifying when you've switched DDG themes.

> In the proposed design all possible tiles are listed on the right side, why? Isn't it a part of the game discovering what color the next tile will be?

@Roysten sorry about the confusion, the tiles were just there to show how they should all look, they're not intended to be there in the final game. What you have so far looks perfect.

> Swipe support for mobile devices would be nice though... unfortunately jQuery mobile is not supported and I'm not really eager to implement touch events myself. Any ways to get this done easily?

This is a good question. We have implemented native swipe support for images (after clicking an image, you can swipe to go to the prev/next image). I'll need to speak with the frontend team to see how we're handling that!

**Comment by moollaza** [comment]
@Roysten @abeyang the game is now live on Beta: https://beta.duckduckgo.com/?q=play%202048

@abeyang I have some questions:

- Should we have a default "Start Game" screen (right now we need the user to click into the game to signal that the game should have the focus, while playing
- Similarly, should we have a "Game Over" screen that shows them they won/lost? I think a "Restart" button would be nice, but a refresh/requery also works.

**Comment by abeyang** [comment]
@Roysten it's looking good! However, the color scheme is still in the works -- we're working on that in the meantime!

Quick question -- how difficult would it be to add animation to the tiles? Almost [all](http://threesjs.com/) [variations](http://2048game.com/) [of](http://2048game.com/variations/5x5.html) [2048](http://www.romaincousin.fr/2048/) show the tiles move from one spot to the next...

**Comment by Roysten** [comment]
@abeyang In it's current form it isn't possible to add such animations because the board is built using a table. We can work around this limitation by rewriting the board as a grid of divs, which then can be animated using css transitions.
I will look into it, but I won't have a lot of time this week, since I have to study for my exams :( Next week I will have more time available.

**Comment by moollaza** [comment]
@Roysten we've been discussing this PR and the Game internally and have decided that so far this is looking great but there's some additional features we'd like to have and some minor fixes we'd like to make.

I don't want to hold up this PR any long so I'm going to merge it for you. Thanks again for taking the time to work on this stuff, we really appreciate it.

We're going to decide on our requirements for this Instant Answer to be ready for launch and I'll post another task.

If you'd like to implement the requirements we'd be happy to see you do it, if not, that's perfectly alright.

**Pull request merged**
