### PR TITLE
Remove id/name from Perl modules and tests

### PR DESCRIPTION
**Pull request by zachthompson**
Shouldn't need these coming from the answer any longer, except cheat sheets which have a parent/child relationship.

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@zachthompson It's official then? Want me to remove the ID/name from PRs that introduce a template?

Also, might want to mention it over on #2767 to make sure we don't introduce any more names/IDs :dolphin:

**Comment by zachthompson** [comment]
Not quite yet.  @moollaza isn't finished with regression testing it.

**Comment by moollaza** [comment]
Successfully deployed this to moollaza.duckduckgo.com.

AFAICT nothing broken and everything is working as expected.

@zachthompson shall we pull the trigger?

**Comment by zachthompson** [comment]
Do it :boom:

**Comment by moollaza** [comment]
Done!

**Comment by russellholt** [comment]
:+1:

**Pull request merged**
