### PR TITLE
Minor Bug Fixes into Safari Cheat Sheet

### LINKED ISSUE #1811: Safari Cheat Sheet: Add tab switching
Please add the following shortcuts:

Control-tab: Switch tabs (forward)
Shift-control-tab Switch tabs (reverse)

/cc @ankushg07

### PR DESCRIPTION
**Pull request by ankushg07**
fixes #1811

sorry for inconvenience caused
but a minor correction was needed to be made

### CODE REVIEW

**Comment by daxtheduck** [comment]
@ankushg07 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub ID:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by moollaza** [comment]
@ankushg07 looks like your branch has merge conflicts? Please make sure your branch is up to date with our master branch

**Comment by ankushg07** [comment]
@moollaza well i tried to do so but conflict is not resolving 
could you plz help me with this

**Comment by ankushg07** [comment]
@tagawa  sir i followed the steps but here i am getting the conflict of branches 
how to resolve it

**Comment by tagawa** [comment]
@ankushg07 I'm afraid I'm not very good with merge conflicts. There's a link above (below the merge conflict message) that says "command line instructions". If you click that it will display what Git commands to use - hopefully that will work.

**Comment by MrChrisW** [comment]
@ankushg07 Try the following to merge the upstream repository into your fork & branch

````bash
git remote add upstream git@github.com:duckduckgo/zeroclickinfo-goodies.git
git fetch upstream
git merge upstream safari
git push
````

**Comment by gautamkrishnar** [comment]
fixes #1811

**Comment by ankushg07** [comment]
@MrChrisW got an error "permission denied " :(

**Comment by MrChrisW** [comment]
@ankushg07 It looks like there is no longer any merge conflicts ! We'll review this shortly. Thanks

**Comment by moollaza** [comment]
uh oh, looks like there's merge conflicts again. Things are changing very quickly ;)

**Comment by altern8tif** [comment]
@moollaza good to close... thanks!

**Comment by MrChrisW** [comment]
Fixed by @altern8tif in #2039

**Pull request closed without merging**
