### PR TITLE
IDN: Structured Answer

### PR DESCRIPTION
**Pull request by kirkins**
## Description of new Instant Answer, or changes

- Convert to structured answer.
- Replace tabs with spaces.

## Related Issues and Discussions

#1163

## People to notify

@mintsoft sorry to spam you, I'm into Perl right now and I want to finish #1163 so I can work on a new Goodie.

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [x] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [x] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [x] There is no unnecessary files in place (such as editor config files)
- [x] There is no API keys / secrets present
- [x] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/IDN

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
I've not had a chance to check this in a browser as my duckpan is screwed at the moment, however code wise looks fine

**Comment by mintsoft** [comment]
I think this would be better with the input passed as the subtitle, then just the answer as the title. It looks a bit confusing at the moment 
screenshot_2017-07-18_00-08-40

**Comment by mintsoft** [comment]
@kirkins can you rebase, I'm not sure what's wrong with the tests because it works OK on master

**Comment by mintsoft** [comment]
Thanks @kirkins

**Pull request merged**
