### PR TITLE
SkyscannerAPICheatSheet: Add columns parameter to the cheatsheet for testing #3353

### PR DESCRIPTION
**Pull request by sahildua2305**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`SkyscannerAPICheatSheet: Add columns parameter`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### People to notify (@mention interested parties)
@moollaza please deploy this on beta so that we can test how #3353 works :wink: 

---

Instant Answer Page: https://duck.co/ia/view/skyscanner_apis_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @samheyman

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@sahildua2305 looks like the initial display isn't correct, but once expanded it looks great

**Comment by sahildua2305** [comment]
@moollaza That's because the non-expanded view has lesser width than the expanded view. So it can't accommodate the two columns of larger width. Is it not good enough to proceed? Anyway, we show 2 columns for a 3 column cheat sheet. I think showing 1 column for a 2 column cheat sheet will be good enough. What do you think?

**Comment by moollaza** [comment]
> So it can't accommodate the two columns of larger width.

Understood. I think we may want to adjust the initial view to support two columns like we do for the usual display but I'll have to check with the design team.

This LGTM 👍

**Pull request merged**
