### PR TITLE
POTUS Fixes: #1863

### PR DESCRIPTION
**Pull request by pecey**
Modified the trigger to prevent queries such as `abc POTUS` from being executed

IA Page: http://duck.co/ia/view/potus

### CODE REVIEW

**Comment by daxtheduck** [comment]
@pecey Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub username:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@pecey Thanks for the PR, can you edit the description of the PR to reference the IA page? Then Dax will link the changes correctly :+1:

**Comment by pecey** [comment]
@mintsoft: IA Page added.

**Comment by mintsoft** [comment]
Also can you limit the changes in this PR to be just to the POTUS IA, currently it's showing changes for linux-commandline.json too

**Comment by pecey** [comment]
@mintsoft: I actually issued a pull from my master branch initially and messed things up. I am not sure how to remove that stuff.

**Comment by mintsoft** [comment]
I think you've got some commits in your master which are not in the actual master, so when you've branched they've come with it. One option is to revert your branches master so that it's absolutely in line with ours.

Another option is to bomb your fork, re-fork and then immediately branch. It's probably best if changes are never made to your forked master, as it causes issues if multiple PRs come from the same fork at the same time.

**Comment by pecey** [comment]
Should I get rid of my fork, re-fork and then submit another request?

**Comment by mintsoft** [comment]
It's probably the easiest way if you're not that familiar/comfortable with git

**Comment by pecey** [comment]
Okay. And how do I reference this PR in that?

**Comment by mintsoft** [comment]
Either close this one and reopen, (maybe) the PR will automatically follow the new fork (I'm not completely sure)

**Pull request closed without merging**
