### PR TITLE
Update atom.json

### PR DESCRIPTION
**Pull request by jophab**
https://duck.co/ia/view/atom_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jophab** [comment]
@moollaza I cant fix the intendation.
GH automatically makes it in hard tabs even though i specify its 4 spaces

**Comment by moollaza** [comment]
> GH automatically makes it in hard tabs even though i specify its 4 spaces

@jophab then please use a local editor, or manually enter the spaces? The GH editor has always worked for me..

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=atom for windows help)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/atom_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=atom for windows help)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/atom_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=atom for windows help)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/atom_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=atom for windows help)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/atom_cheat_sheet_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=atom for windows help)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/atom_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@jophab Thanks! This LGTM :+1:

**Pull request merged**
