### PR TITLE
IRC Cheat Sheet

### PR DESCRIPTION
**Pull request by namandistro**
screenshot from 2015-07-27 18 27 24

-----
IA Page: https://duck.co/ia/view/irc_cheat_sheet

### CODE REVIEW

**Comment by mintsoft** [comment]
@namandistro Thanks for this! Sorry it's taken a while to get to.

One thing that'st just stood out to me at first glance is that I thought all commands were prefixed with `/` not `$`. I.e `/nick mintsoft` would change my nick not `$nick mintsoft` ?

**Comment by namandistro** [comment]
@mintsoft All those command are the terminal one and i saw the git command starts with $ so i thought that symbol will make sense rather than this /

**Comment by mintsoft** [comment]
@namandistro Ah, I see what the confusion is here. The `$` on the git ones is used to indicate that it's a shell command and that it should be executed as such (this is a fairly common thing within the *nix sphere). 

When you say "terminal ones" do you mean within a specific IRC client?

**Comment by namandistro** [comment]
@mintsoft This command varies from client to client some gives us god gui some ask directly the channel name i made a cheat sheet to give all the command we can use from our shell to access it... So this are the basic commands you need to use for IRC from telnet a short video where you can understand what i am talking about https://www.youtube.com/watch?v=oZ81n_0M63g&noredirect=1

**Comment by mintsoft** [comment]
AH I see, I didn't realise it was essentially telnet. Other IRC clients I've used always require `/` infront of  commands. Either way, I'm not sure if `$` is right for this. 

@moollaza @jagtalon @MrChrisW @mattr555  Any opinions?

**Comment by namandistro** [comment]
Ya, But that thing depends on client to client but as default all this command will be used at backend...

**Comment by MrChrisW** [comment]
@mintsoft I tend to agree with using the forward-slash format.

@namandistro I understand what you're saying, the **forward slash** standard is based on the **client-side** and not directly implemented nor enforced by the IRC protocol.

However its become the standard of almost all IRC clients (GUI and CLI), using the `/` to interpret a command and send a raw command to the IRC server. 

You'll also find this (forward slash) mentioned on any other help guides online.

+ http://www.ircbeginner.com/ircinfo/ircc-commands.html

+ http://web.cortland.edu/flteach/methods/obj2/irc-cmds.html

Therefore I think its appropriate to use `/` here as oppose to `$`. 

On a side note, I don't think the people using telnet or a raw socket connection to an IRC server would necessarily need a CheatSheet :smile:

**Comment by mintsoft** [comment]
I suppose a compromise would be to not have anything at the start of each command, I.e. `nick mint`?

**Comment by namandistro** [comment]
So @MrChrisW and @mintsoft What is the final recommendation is hould use $ or /. ?

**Comment by mintsoft** [comment]
@namandistro I think `/`

**Comment by namandistro** [comment]
@mintsoft i made the recommended changes

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
@namandistro Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Comment by moollaza** [comment]
@namandistro @sagarhani congrats! It's live: https://duckduckgo.com/?q=irc+cheat+sheet&t=ffab&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
