### PR TITLE
Add Jasmine.js to Goodies repo

### PR DESCRIPTION
**Pull request by moollaza**
## Description of new Instant Answer, or changes
- Add jasmine to `.travis.yml`, installs and executes jasmine
- Add generated jasmine.json file to repo

This will enable us to start unit testing out Instant Answer JavaScript 😃 

You can see this in action in the JS Conversions PR: #4135 

## People to notify
@duckduckgo/community-leaders 

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Ready to merge?**

- [x] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [x] For larger commits, has this been approved be more than one community member?
- [x] The number of reviews is appropriate for this type of PR
- [x] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Thanks @moollaza! 💯  ✨  🚀

**Comment by gautamkrishnar** [comment]
Great job @moollaza. So, We need to add test specs for other JS IAs as well right?.  I am interested in working on this once my exams are over 😄 ❤️

**Comment by pjhampton** [comment]
@gautamkrishnar testing the existing ones? This kind of violates TDD principles. We should only be adding tests to legacy IAs if we're extending them.

The two top priority ones are Calculator and Conversions. I would LOVE your help on them!

**Comment by gautamkrishnar** [comment]
Okay 👍 Thanks @pjhampton I was actually confused... Now its clear... 😄

**Pull request merged**
