### PR TITLE
More fixes and improvements to the German cheat sheet.

### PR DESCRIPTION
**Pull request by homeworkprod**

### CODE REVIEW

**Comment by moollaza** [comment]
@homeworkprod thanks a lot for making this PR! We just merged some fixes to this IA so your PR now has conflicts. If there's still existing problems, feel free to update your PR. If not please close it!

**Comment by homeworkprod** [comment]
@moollaza, I have rebased and adjusted my patch.

**Comment by moollaza** [comment]
@homeworkprod thanks a lot! We had another PR this morning that ended up having some discussion on it, would you like to chime in over there so we can combine and agree on all the changes that we'd like to be made? I had no idea so many people would contribute to this Instant Answer!

https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1368

**Comment by moollaza** [comment]
Actually I guess the others should chime in here. It looks like you changes don't overlap too much with the other PR's.

**Comment by homeworkprod** [comment]
@moollaza: TBH, I'm slightly annoyed by how this is not working well.

After complaining on the initial version of the cheat sheet on Twitter, @yegg asked me to do a PR with improvements – which is what I did here.

(IIRC) After my PR was created, the file was modified, and I kindly updated my patch. Now it has conflicts again.

I was very happy to pause work on my current project for a moment to provide a simple patch based on my knowledge, and I felt warm inside because of doing a good thing by supporting DuckDuckGo. But instead of this being a straight-forward process *that almost takes no time*, this isn't resolved after two weeks and might require even more work on my part.

Admittedly, it's just a few very simple changes, but it's kind of a counter example on how supporting open source projects should work. After this, I absolutely don't feel motivated to provide any more patches to this project because of the disproportionate overhead for me while not having achieved an actual change in the end.

**Comment by zekiel** [comment]
@homeworkprod  thanks for the honest feedback -- we're very receptive to it and appreciate the personal experience you're sharing. I head up community @ duckduckgo and, if you're willing, would like to follow up in more detail about how we're going to improve this process going forward. Do you mind if I reach out to you via email?

**Comment by homeworkprod** [comment]
@zekiel, feel free to, my address is on my profile page.

**Pull request closed without merging**
