### PR TITLE
ritwikraghav14's first Goodie

### PR DESCRIPTION
**Pull request by ritwikraghav14**
Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**
Trains me to create Goodie and announces 'I am awesome' to the world.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
It solved the very first problem of 'How to create a Goodie'

**What is the data source for your Instant Answer? (Provide a link if possible)**
N/A

**Why did you choose this data source?**
N/A

**Are there any other alternative (better) data sources?**
N/A

**What are some example queries that trigger this Instant Answer?**
N/A

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Everyone searching my github handle.. or not even them

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No

**Which existing Instant Answers will this one supercede/overlap with?**
N/A

**Are you having any problems? Do you need our help with anything?**
N/A

**Where did you hear about DuckDuckHack? (For first time contributors)**
I read 'Develop' at the search results page and it led me to DuckDuckHack

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
duckduckhack_ritwikraghav14_at_duckduckgo_-_2014-12-18_19 52 12

## Checklist
Please place an 'X' where appropriate.

```
[] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

    - Kubuntu
        [] Firefox   --- This one.

### CODE REVIEW

**Comment by jagtalon** [comment]
Hey, @ritwikraghav14! Can you separate the two PRs or maybe make a new PR with just the IsAwesome goodie like what @moollaza said? :)

**Comment by zekiel** [comment]
@ritwikraghav14  let us know if you need any help w/ this!

**Comment by jagtalon** [comment]
@ritwikraghav14 any updates?

**Comment by jagtalon** [comment]
@ritwikraghav14 closing this for now. Can always re-open!

**Pull request closed without merging**
