### PR TITLE
goodie tutorial

### PR DESCRIPTION
**Pull request by gokul1794**
**Goodie tutorial pull request**
**What does your Instant Answer do?**
DuckDuckHack goodie tutorial

**What are some example queries that trigger this Instant Answer?**
duckduckhack gokul1794

Looks like this
goodietutorial

## Checklist
Please place an 'X' where appropriate.

```
- [] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [x] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [x
![goodietutorial](https://cloud.githubusercontent.com/assets/6311809/8434370/a017dd74-1f68-11e5-86f3-cfd8956761b1.png)
] Native Browser
        - [x] Google Chrome
        - [] Opera

```

### CODE REVIEW

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
@gokul1794 thanks, and congrats ;)

**Comment by gokul1794** [comment]
@moollaza Looking forward to contribute some more ;)

**Comment by moollaza** [comment]
@gokul1794 congrats! It's live: https://duckduckgo.com/?q=duckduckhack+gokul1794&ia=answer

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
