### PR TITLE
Improve dice triggers and images

### PR DESCRIPTION
**Pull request by marianosimone**
This also addresses:

- #1163 Converting from HTML to Templates goodie
- #1255 Supporting the "dices" spelling, as well as adding images

I've just seen #1831, which addresses a couple of other issues, but it seems abandoned now, so I'd like to bring some of those changes back once this is approved (I think this implementation is cleaner, which would make it easier to make changes to the triggers)

screen shot 2016-01-12 at 12 23 05 pm

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@marianosimone thanks for this! There is actually another PR in-progress that updates this IA to use templates: #1982 

I've pinged you and our designer over there to settle on a design.

**Comment by marianosimone** [comment]
This is being taken care of here: #1982

**Comment by moollaza** [comment]
@marianosimone #1982 has been merged but it did't address the triggering issue -- would you like to update this branch, or make a new PR to fix that?

**Comment by marianosimone** [comment]
@moolaza. Sure thing! I'll update this branch and see what I can do about the triggering

**Pull request closed without merging**
