### PR TITLE
Test Goodie: duckduckhack

### PR DESCRIPTION
**Pull request by alexishancock**
**What does your Instant Answer do?**
Trigger for IsAwesome practice Goodie

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Helps me understand DuckDuckGo's Goodies. 

**What are some example queries that trigger this Instant Answer?**
duckduckhack alexishancock

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
My geeky self

**Which existing Instant Answers will this one supercede/overlap with?**
Other IsAwesome Goodies

**Where did you hear about DuckDuckHack? (For first time contributors)**
An article discussing internet privacy

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screen shot 2015-01-12 at 10 48 40 am

## Checklist
```
[x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[x] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [x] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [x] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by mintsoft** [comment]
Hiya @alexishancock Congratulations on your first goodie! This looks perfect :cake:

**Comment by alexishancock** [comment]
Thanks @mintsoft! I am very new to Perl so I hope to submit a more significant pull request in the near future.

**Comment by mintsoft** [comment]
@alexishancock Glad to hear it; if you're looking for ideas to implement there's a list of suggestions here: https://duck.co/ideas

**Comment by moollaza** [comment]
@alexishancock it's live! https://duckduckgo.com/?q=+duckduckhack+alexishancock&ia=answer

Now that you've completed your first Goodie, we really hope you'll work on another! Feel free to check out our [Ideas Forum](https://duck.co/ideas) or look through our Github issues if you need something to work on!

**Comment by alexishancock** [comment]
How cool! Thanks @moollaza! I will be sure to try and implement new ideas. Just need to learn Perl a little more so that I can contribute more. Are there any Perl resources you recommend?

**Comment by moollaza** [comment]
I personally found the easiest way for me to learn Perl was to try an build an Instant Answer I wanted to use. Then as I needed to know how to do various things I would research them until I had a working IA. Of course, there are also lots of books and resources online. I know that http://learn.perl.org/ exists, which is to help Perl newcomers. 

Also, If you're more comfortable with JavaScript, you could try writing a simple Spice Instant Answer. It will require a relatively simple Perl backend (similar to your Goodie) to handle the triggering, but the display is handled with JavaScript.

**Comment by alexishancock** [comment]
Thank you @moollaza. I am going to check out IAs and see if I can implement one that is "simple" enough to work with. Thanks for the advice.

**Comment by mintsoft** [comment]
@alexishancock If you get stuck with anything (even just Perl in an IA in general) feel free to just open a PR and one of us will be happy to help you out!

**Pull request merged**
