### PR TITLE
Awesome Bar Cheatsheet

### PR DESCRIPTION
**Pull request by domjacko**
IA Page: https://duck.co/ia/view/awesome_bar_cheat_sheet

### CODE REVIEW

**Comment by domjacko** [comment]
@moollaza I'm not entirely sure what you meant by 'symlink'. Is that a git specific thing, or do I create an alias file in my repo and call it 'firefox awesome bar.json'

**Comment by moollaza** [comment]
@domjacko ah it's no problem, I'll make the symlink for you after merging. 

FWIW a symlink is an actual file, which is simply a link to another file: https://en.wikipedia.org/wiki/Symbolic_link

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
@domjacko congrats! It's live: https://duckduckgo.com/?q=awesome%20bar%20cheat%20sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Pull request merged**
