### PR TITLE
AngularJS: Add component in module

### PR DESCRIPTION
**Pull request by rafaelnery**
## Description of new Instant Answer, or changes

Added `component`  in module reference.

## People to notify

Maintainer: @SibuStephen

---

IA Page: https://duck.co/ia/view/angularjs_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
@SibuStephen is this okay to merge?

**Comment by gautamkrishnar** [comment]
👍 Merged... Thanks for your contribution... @rafaelnery

**Comment by SibuStephen** [comment]
Did you review the code?

**Comment by gautamkrishnar** [comment]
@SibuStephen Yes it was a minor change... Its good to merge...

**Comment by SibuStephen** [comment]
GTG then, next time will review the PR first, unless it's a small change :)

**Pull request merged**
