### PR TITLE
Conversions: Switching to custom template

### PR DESCRIPTION
**Pull request by mintsoft**
This is the first step to getting it interactive, I'm deliberately outputting things in the `structured_answer` that aren't used as I plan to use them in the JS.

Some design tidying up around this version would be much welcomed @abeyang 

image

I've not updated the tests yet for the new structure, hence the failure

ToDo:
 - [x] Fix tests
 - [x] Fix scientific notation output
 - [x] Improve design
 - [x] Add maximum input value

-------
IA Page: https://duck.co/ia/view/conversions

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@mintsoft I spoke with our design team and the showed me the previously made design we have for this IA. Should be fairly simple to implement :+1: 

https://github.com/duckduckgo/zeroclickinfo-goodies/pull/781#issuecomment-69231364

**Comment by mintsoft** [comment]
@moollaza I'll look at aiming for that in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2075 

I'll do something similar, but not interactive here in order to get it converted to the structured answer with the separate fields for JS consumptino

**Comment by moollaza** [comment]
> @moollaza I'll look at aiming for that in: #2075 

Perfect :+1:

**Comment by mintsoft** [comment]
@moollaza @abenyang my half-way house until interactive is complete: conversions_partial

**Comment by mintsoft** [comment]
@moollaza any idea what's wrong with the deployment here?

**Comment by GuiltyDolphin** [comment]
@mintsoft Are you up-to-date with master? Wouldn't hurt to be.

**Comment by moollaza** [comment]
@mintsoft running it again, not sure what the problem was...

**Comment by moollaza** [comment]
@mintsoft it seems to be failing tests because it thinks the `structured_answer->name` shouldn't exist

```
    #   Failed test 'Deep: full ZCI object'
    #   at /~~~~/lib/perl5/DDG/Test/Goodie.pm line 76.
    #     Structures begin differing at:
    #          $got->{structured_answer}{name} = 'conversions'
    #     $expected->{structured_answer}{name} = Does not exist
    # Looks like you failed 1 test of 1.
#   Failed test 'Query: 84856 celsius in rankine'
#   at /~~~~/lib/perl5/DDG/Test/Goodie.pm line 80.
    #   Failed test 'Deep: full ZCI object'
    #   at /~~~~/lib/perl5/DDG/Test/Goodie.pm line 76.
    #     Structures begin differing at:
    #          $got->{structured_answer}{name} = 'conversions'
    #     $expected->{structured_answer}{name} = Does not exist
    # Looks like you failed 1 test of 1.
#   Failed test 'Query: 84856 kelvin in rankine'
#   at /~~~~/lib/perl5/DDG/Test/Goodie.pm line 80.
    #   Failed test 'Deep: full ZCI object'
    #   at /~~~~/lib/perl5/DDG/Test/Goodie.pm line 76.
    #     Structures begin differing at:
    #          $got->{structured_answer}{name} = 'conversions'
    #     $expected->{structured_answer}{name} = Does not exist
    # Looks like you failed 1 test of 1.
#   Failed test 'Query: 84856 rankine in rankine'
#   at /~~~~/lib/perl5/DDG/Test/Goodie.pm line 80.
```

**Comment by moollaza** [comment]
@jdorweiler any idea what might be going on here? Tests are passing elsewhere...

**Comment by GuiltyDolphin** [comment]
@moollaza @mintsoft Looks like the tests might not have been updated?

**Comment by mintsoft** [comment]
@moollaza @GuiltyDolphin @jdorweiler I've just repushed them on travis too to test; the tests are passing there and on both my dev environments!

**Comment by GuiltyDolphin** [comment]
@mintsoft I've rebased locally onto master and now the tests are failing (the new ping).

**Comment by mintsoft** [comment]
@GuiltyDolphin how is that different from: https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/builds/110651738 ?

**Comment by GuiltyDolphin** [comment]
@mintsoft Is your master up-to-date? `ping` was only merged today I believe.

**Comment by jdorweiler** [comment]
I had the same error.  Could be a clash with another PR.

**Comment by moollaza** [comment]
@mintsoft going to deploy to Moollaza for testing...

**Comment by mintsoft** [comment]
@GuiltyDolphin it's weird there are no conflicts in the merge here o.0

**Comment by mintsoft** [comment]
@moollaza Right I've tinkered with it and made it look like the original version, although the margins are slightly different and I can't tell why:

conversionssubtlydifferent

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

**Comment by GuiltyDolphin** [comment]
@mintsoft Was this ready to merge? On Beta I'm getting:

screenshot from 2016-03-10 12 21 00

**Pull request merged**
