### PR TITLE
AngularJS cheatsheet

### PR DESCRIPTION
**Pull request by SibuStephen**
**What does your Instant Answer do?**
The goodie provided here helps the developers to make it easy to take the angular directives
for their references easily , so that they can use it in their applications ,i personally felt this
because their are many times when i needed some directives but was not able to find it instantly rather
i had to go to the site and search for angular directives.So this goodie might help some instant actions                                                                                                                                                                              and save time as well.

**What is the data source for your Instant Answer? (Provide a link if possible)**
https://docs.angularjs.org/api/ng/directive

**Why did you choose this data source?**
This data source is the official site, as well there are as many 1000 additional directives that can be found in this data source mentioned

**Are there any other alternative (better) data sources?**
No

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Web Developers (Front end developers).

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes.

**Are you having any problems? Do you need our help with anything?**
For now no, but yes in future i will need help
when contributing to the ideas as such.

**Where did you hear about DuckDuckHack? (For first time contributors)**
Social site, friends.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screenshot from 2015-09-07 11 17 46

-----
IA Page: https://duck.co/ia/view/angularjs_cheat_sheet

### CODE REVIEW

**Comment by moollaza** [comment]
@SibuStephen this LGTM :+1:

Thanks a lot for contributing (we really appreciate it :smiley:). We invite you to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

**Comment by SibuStephen** [comment]
Thank's alot @moollaza , it will be my pleasure to contribute more  and will be looking forward to contribute more for the goodies .Was fun contributing :)

**Comment by moollaza** [comment]
@SibuStephen congrats! It's live: https://duckduckgo.com/?q=angularjs+cheat+sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Comment by SibuStephen** [comment]
@moollaza  Thank you, sure i''m going with some other PR's mentioned by the community members. :+1:

**Pull request merged**
