### PR TITLE
NumberStyler GoodieRole: Improvements

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
Working on the NumberStyler Role!
## TO-DO
- [ ] Incorporate #2766 
- [x] Update existing IAs to new format(s)
- [ ] ~~Move number formats into YAML~~
- [x] Make formats locale aware (per #2797)

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@GuiltyDolphin looks tidier already

**Comment by moollaza** [comment]
Ping! What's the status here?

**Comment by mintsoft** [comment]
I'm going to close this for now until we decide what we want to do with it, feel free to re-open if you disagree

**Pull request closed without merging**
