### PR TITLE
Cheat Sheet Controller: Require remainder to be defined

### PR DESCRIPTION
**Pull request by moollaza**
Ensure we have a remainder and that the trigger is not entire query.

Prevents us from triggering any IA's which may define a null alias (which should be avoided anyways..).
###### People to notify (@mention interested parties)

@zachthompson @GuiltyDolphin 

---

Instant Answer Page: https://duck.co/ia/view/cheat_sheets

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@moollaza Lets add a critical test for null aliases too (anything consisting of empty string + zero or more whitespace).

**Comment by mintsoft** [comment]
@moollaza Is this PR still valid? I think it'd be nice to add a test to clarify the triggering situation this is guarding against if possible

**Comment by mintsoft** [comment]
I'm going to close this for now (doing some house-keeping). Feel free to re-open if I've closed it in error

**Pull request closed without merging**
