### PR TITLE
New Latex CheatSheet

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
Fixes: #3691 

## Type of Change

- [X] New Instant Answer
  - [X] Cheat Sheet
- [ ] Improvement
  - [ ] Bug fix
  - [ ] Enhancement
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.)
## Description of new Instant Answer, or changes

I have made a new cheat sheet for Latex and Tex. I have tried to make it comprehensive and concise. I divided it into sections on the basis of their uses. Most of these stem from those commonly used in papers and online.
## Related Issues and Discussions

This cheat sheet is inspired by #3691 .

The IA page `latex_cheat_sheet` appeared to be taken, however no work etc had been mentioned. It would be nice if I could use the same, otherwise that needs to be deleted. It would be great if mods could address this.
## People to notify

@QVaucher @gautamkrishnar 
---

Forum Topic:

IA Page: https://duck.co/ia/view/latex_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@nalinbhardwaj Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/latex_cheat_sheet_mobile.png?A5Up5OoWhZ)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/latex_cheat_sheet_mobile.png?xadU2TRaMB)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/latex_cheat_sheet_mobile.png?1ROASOsaKR)

**Comment by gautamkrishnar** [comment]
Good job @nalinbhardwaj

**Comment by gautamkrishnar** [comment]
@duckduckgo/duckduckhack-contributors any latex experts here?

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/latex_cheat_sheet_mobile.png?eAknTiRMPF)

**Comment by atilacamurca** [comment]
@gautamkrishnar The screenshot and the example query are not working :(

**Comment by nalinbhardwaj** [comment]
@atilacamurca The example query [seems to work](https://beta.duckduckgo.com/?q=latex+cheat+sheet&t=h_&ia=cheatsheet&iax=1) as expected for me. Also, if it helps, here are the [screenshots](http://imgur.com/a/mZaoR) from my laptop and mobile. :-P

Also @gautamkrishnar as I mentioned, the IA page `latex_cheat_sheet` is taken, so can some mod modify it to contain the right information? How should I do that? Or will that be done automatically after PR is approved? Because currently the beta.duckduckgo.com also shows Developer as @ryoji992 and not me.

**Comment by atilacamurca** [comment]
Those commands are specific to the mathematics environment, don't you think it should be described in the description? (Also LaTeX is so complex that I think there should be separated cheat sheets, but for now LGTM).

**Comment by nalinbhardwaj** [comment]
@atilacamurca Don't know how I forgot to mention that. My apologies. I'll make a commit in a while. Also, regarding separate cheat sheets, I think the math mode cheat sheet is usually what most of us are looking for.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/latex_cheat_sheet_mobile.png?YvItjPYJxe)

**Comment by gautamkrishnar** [comment]
@moollaza can you please fix the IA page?

**Comment by moollaza** [comment]
> @moollaza can you please fix the IA page?

@gautamkrishnar I see nothing wrong with it? The IA is working on Beta: https://beta.duckduckgo.com/?q=Latex+Cheat+Sheet&t=h_&ia=cheatsheet

**Comment by moollaza** [comment]
If you're referring to the broken screenshot, that's because there was no example query -- the developer should be providing at least 1 example query.

**Comment by nalinbhardwaj** [comment]
@moollaza there is no example query because I did not create the IA page. Someone else had made the IA page before, but no work was done on it. That is what you need to fix. Basically give me some way to access the page. :)

**Comment by moollaza** [comment]
> That is what you need to fix. Basically give me some way to access the page. :)

Thanks for clarifying. I've made you the Maintainer of the page. I think that should give you edit permissions, but I've created an internal task to make sure.

If everything else is fine you should be okay to move ahead with this.

**Comment by moollaza** [comment]
@nalinbhardwaj do you have an account on duck.co? If not, please make one, and send me your username. A duck.co account is required for you to have edit permissions on an IA page. You can signup via GitHub so you don't need to create any new passwords, and associate your Duck.co with your GitHub.

**Comment by nalinbhardwaj** [comment]
@moollaza my handle is nibnalin on duck.co the website. I have already got edit rights for the page and did correct the description of the IA page. Is there anything else I need to do?

**Comment by jarmokivekas** [comment]
Would it make sense to add thing like mathjax  (I think that's the name) as aliases for triggering this. I haven't actually used that too much, but if all the listed commands work in that framework too, it may increase relevant hits. Just a thought.

**Comment by nalinbhardwaj** [comment]
@jarmokivekas  I thought about that but it is possible that it may confuse developers who are looking to integrate mathjax into their platform. Hence decided to not add that for the time. If everyone feels it wont be an issue, we should add it.

**Pull request merged**
