### PR TITLE
Military rank india

### PR DESCRIPTION
**Pull request by lowellosaurus**
###### What does your Pull Request do (check all that apply)?

- [x] Improvement
    - [x] Enhancement: **`{MilitaryRank}: {Add Indian Armed Forces data}`**

###### Description of changes

Adds Indian Armed Forces rank insignia to the list of military rank returned by this instant answer.

###### People to notify (@mention interested parties)

@shadabk, @GuiltyDolphin 

---

Instant Answer Page: https://duck.co/ia/view/military_rank

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @lowellosaurus

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Thank you for this @lowellosaurus - looks good to me. As you may have seen, I've asked for a bit of feedback on this before we merge.

**Comment by shadabk** [comment]
@lowellosaurus The improvement works fine army, navy and air force. Good work.

**Comment by tagawa** [comment]
Thanks @shadabk. I've added the "Needs Community Review" label and if there's no further feedback in the next couple of days we can merge this.

**Comment by GuiltyDolphin** [comment]
@shadabk @lowellosaurus Thanks guys! :dolphin:

**Comment by tagawa** [comment]
@shadabk @lowellosaurus Just letting you know that this is now live: https://duckduckgo.com/?q=indian+army+ranks&ia=answer
Thanks again!

**Pull request merged**
