### PR TITLE
Public DNS : update IA

### PR DESCRIPTION
**Pull request by Snapy**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer
  - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
  - [ ] Other: **`New {IA Name} Instant Answer`**
- [x] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [x] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Remove obsolete providers, add new ones and update links to https.
###### Which issues (if any) does this fix?

Fixes no issues.
###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/public_dns

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Hey @Snapy,

I rerun the tests there 😄  It was failing on something unrelated before. Hope this helps you push this forward!

**Comment by Snapy** [comment]
Thanks @pjhampton but I will review (maybe resubmit) this PR taking into account another recent one (#3883) when I have a bit more time. Feel free to close the PR if you want to.

**Comment by pjhampton** [comment]
Thanks @Snapy!! 😄

**Pull request closed without merging**
