### PR TITLE
ConvertLatLon: Switching to text template

### PR DESCRIPTION
**Pull request by mintsoft**
###### Description of changes

Ref: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2767

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/convert_lat_lon

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @wilkox

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@wilkox I've had to kick the tests about quite a bit with this; much obliged if you could give them a once over

**Comment by wilkox** [comment]
@mintsoft 👍  Looks good

**Comment by mintsoft** [comment]
@GuiltyDolphin Conflicts fixed

**Comment by GuiltyDolphin** [comment]
@mintsoft @wilkox Thanks!

**Pull request merged**
