### PR TITLE
Tips: Sets min attribute to 1

### PR DESCRIPTION
**Pull request by adityatandon007**
**Here is the story**:
I was just calculating tip for my bill using tip calculator but then I when I changed the no of person to 2 using arrow button the tip amount divided into two which was fine and then i just casually started playing with the arrow button and then I noticed something that if we set the number of people to 0 using arrow button then the bill shows the same result as when `number` of people = 1`. 

screenshot from 2017-07-22 17-51-55

## Related Issues and Discussions
This PR sets min attribute to 1

**Further Improvements** :
I know somebody can still trick this by typing it manually but at least it will complain them by placing a red border around the input box and asking them politely `select  a value no less than 1` instead. 
Right now every input accepts letters and even negatives numbers, and adds to unnecessary processing which we could have avoided. There are things on the design part which can be improved as well like the font size and weight **its too large and bold**.

## People to notify
@pjhampton @moollaza

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/tips

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by adityatandon007** [comment]
@pjhampton test passed in codio but travis is failing. Can you figure it out?

**Comment by pjhampton** [comment]
@adityatandon007 Thanks, this is a good contribution! 
Yeah, I already have. See https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4373. Travis is moving all their builds to 14.04 but we need to stay on 12.04. I can't merge anything until the staff give me more information.

**Comment by adityatandon007** [comment]
thanks @pjhampton I wasn't aware about this.

**Pull request merged**
