### PR TITLE
CountryCodes: remove trailing space, add newline before ABSTRACT

### PR DESCRIPTION
**Pull request by moollaza**
Needed a PR to get this one onto Beta. Seems to be offline, and I'm not sure why...

-----
IA Page: https://duck.co/ia/view/country_codes

### CODE REVIEW

**Comment by daxtheduck** [comment]
## [Country Codes](https://duck.co/ia/view/country_codes)

**Description**: Matches country names to ISO 3166 codes and vice versa

**Example Query**: [country code Japan](https://beta.duckduckgo.com/?q=country code Japan), [iso code for Spain, Russia two letter country code, 3 letter country code of China](https://beta.duckduckgo.com/?q=iso code for Spain, Russia two letter country code, 3 letter country code of China)

**Tab Name**: Answer

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/country_codes)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/country_codes)*

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=country code Japan)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/country_codes_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=country code Japan)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/country_codes_mobile.png)

**Comment by moollaza** [comment]
This LGTM :+1:

**Pull request merged**
