### PR TITLE
Mbps to kb/s converter goodie

### PR DESCRIPTION
**Pull request by kethinov**
**What does your Instant Answer do?**
Convert mbps bandwidth into kb/s.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Provides instant answer to simple math calculation.

**What is the data source for your Instant Answer? (Provide a link if possible)**
Math.

**Why did you choose this data source?**
Google has this feature already! :wink: 

**Are there any other alternative (better) data sources?**
No! Math FTW!

**What are some example queries that trigger this Instant Answer?**
Example search: "5 mbps in kb/s"

Example answer: "5 Mbps = 625 kilobytes / second"

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
People trying to figure out how fast internet connections are!

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Negative.

**Which existing Instant Answers will this one supercede/overlap with?**
None that I know of!

**Are you having any problems? Do you need our help with anything?**
I'm open to feedback about improving code quality!

**Where did you hear about DuckDuckHack? (For first time contributors)**
Hacker News.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screen shot 2014-12-02 at 10 28 26 am

## Checklist
Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

Regarding browser compatibility... it's plain text! I think we're good! :stuck_out_tongue:

### CODE REVIEW

**Comment by zekiel** [comment]
@kethinov  I noticed you may have missed the @ mention from elohmrow above. Can we help with anything here?

**Comment by kethinov** [comment]
@zekiel yeah sorry about that. I had some unfinished work in this branch, but then this fell off my radar as I've been focusing on spices.

I just pushed the unfinished work of migrating this into Conversions.pm so I can get some feedback on the work in progress. @elohmrow so far is this in line with what you recommended?

**Comment by kethinov** [comment]
This implementation feels kinda like a workaround, but I wasn't sure how to add more types directly to the object provided by `Convert::Pluggable`.

**Comment by mintsoft** [comment]
@kethinov @moollaza Sorry to keep harping on about this, but can we kind-of put this on-hold until we know what we're doing about the Conversions IA etc?

**Comment by elohmrow** [comment]
i kinda thought it was already ... so i have only been observing

**Comment by kethinov** [comment]
Oh of course, no worries. I didn't get very far moving the idea into Conversions anyway so I can revisit this after a rebase if big changes are coming to how Conversions is laid out.

**Comment by jagtalon** [comment]
Closing this for now since it's on hold. We can always re-open it when we figure things out! :)

**Comment by javathunderman** [comment]
@moollaza should we just update conversions then?

**Comment by elohmrow** [comment]
i have no idea what is going on with this - if someone needs me to do something, please let me know

**Comment by moollaza** [comment]
@elohmrow no sweat, you're good. I'll ping you if needed :)

**Comment by moollaza** [comment]
@javathunderman yes if we want support for these units a PR should be made against the Convert::Pluggable repo.

@elohmrow has done an amazing job, but it's clear that conversions are in need of constant updates and I would like to enable our devs to easily add support for new units by only updating our DDG repos. This means that sooner or later we'll need to move away from our dependency on Convert::Pluggable.

I believe @mintsoft had toyed with the idea before.

**Comment by moollaza** [comment]
Ideally I'd love to use an API that supports the majority of our conversions out of the box. I will investigate http://www.convert.net/, which offers an awesome API. Unfortunately it uses XML which makes things difficult...

**Comment by elohmrow** [comment]
@moollaza i can give you control of C::P if it helps

**Comment by mintsoft** [comment]
@moollaza there's a branch banging around somewhere with it inlined a little, also what needs to be done to support XML API's? Is it all internal or can I take a stab at it?

**Comment by moollaza** [comment]
>what needs to be done to support XML API's? Is it all internal or can I take a stab at it?

@mintsoft internal changes :)

**Comment by elohmrow** [comment]
@moollaza ~ how is this going? are you certainly moving to an external service (expected load, prefered format?), or would it be sufficient to use a local datastore (db | cfg | serliazed struct)? depending on load, i could, say, provide a json-y api.  on the other side, i have somewhere a serialized, modern OO version.

**Comment by moollaza** [comment]
@elohmrow apologies for the delayed response, been busy!

We aren't exactly certain of anything right now, but I'd like to use a JSON API if one exists because it just seems like the simplest approach. Similarly, a JS Lib like Math.JS (or https://github.com/gentooboontoo/js-quantities) could be used to allow for an interactive conversion Instant Answer, that could be updated through an interface (similar to what Google/Bing currently provide)

What I don't like is that we have several IA's which have implement their own logic right now, and don't handle things as well as our Conversions.pm does, so the experience is a little degraded and inconsistent.

**Comment by elohmrow** [comment]
@moollaza we're all busy, no need for apologies :)

i'll try to write a barebones json-y service in the next cpl days, then post back here so you can try it if you want.

**Comment by elohmrow** [comment]
@moollaza i have spent a few mins to put up a barebones demo at timewind.us ... you can try lots of things like: <code>curl http://timewind.us:3000/convert/100/feet/inches</code>.  you can see how support could be added to this of course for adding units, etc.

**Comment by javathunderman** [comment]
@elohmrow Cool to see this move forward, I'll check it out as well!

**Comment by elohmrow** [comment]
@javathunderman @moollaza i will try to add an 'add' units route tomorrow and post back here

**Comment by moollaza** [comment]
> i have spent a few mins to put up a barebones demo at timewind.us ... you can try lots of things like: curl http://timewind.us:3000/convert/100/feet/inches. you can see how support could be added to this of course for adding units, etc.

@elohmrow wow thanks! This is pretty awesome.

**Comment by elohmrow** [comment]
i did not have time yest but plan to look at this today ...

**Comment by javathunderman** [comment]
@elohmrow no problem!

**Comment by elohmrow** [comment]
@moollaza @javathunderman 

_n.b.: i limited experience with solr, and have never used redis._

i have been looking at this ... i have tried: 
* an rdbms (too heavy)
* json (winner atm)
* redis (searching on complex structures hard - eventually i ended up with aliases as keys for every unit (_keyN => "alias1|alias2|a..aliasN"_))
* solr

'add/update' functionality is tough to implement in all cases because C::P stores its own data atm and creates an object using that internal data.  i'm going to locally re-factor C::P a bit today so that it works with external data sources, then i think the 'add/update' functionality is easy.

**Comment by elohmrow** [comment]
@moollaza @javathunderman basic re-factor complete here:
https://github.com/elohmrow/Convert-Pluggable/commit/d1f97773c614a2a5b0f6bdc81b3e01704feb4e11

this will not be pushed to CPAN until the service is solid.  will work on the C/U/D parts in a little bit.

**Comment by elohmrow** [comment]
@javathunderman @moollaza i am still working on this.  i am trying to make sure C::P is solid before i push the service.  i now locally have everything i need done; i will post back when all testing is passing.

see https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1731#issuecomment-153286234
see https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1729#issuecomment-152854825

for context.

**Comment by moollaza** [comment]
@elohmrow thanks! Please keep us posted :+1:

**Pull request closed without merging**
