### PR TITLE
New 8085 instructions cheat sheet

### PR DESCRIPTION
**Pull request by jophab**
**What does your Instant Answer do?**
8085 instructions reference
**What is the data source for your Instant Answer? (Provide a link if possible)**
http://home.iitk.ac.in/~ajalan/8085_is_details.pdf
**Why did you choose this data source?**
Its reliable
**Are there any other alternative (better) data sources?**
Yes,may be
**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
students
**Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?**
no
**Are you having any problems? Do you need our help with anything?**
no
**Where did you hear about DuckDuckHack? (For first time contributors)**
From my friend
**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
36a03eaa-913b-11e5-977f-9c54e66990d4
368f4ea6-913b-11e5-9846-70f50d887aaf
36978b66-913b-11e5-969e-d4676b5493ad

-----
IA Page: https://duck.co/ia/view/8085_cheat_sheet

### CODE REVIEW

**Comment by moollaza** [comment]
@jophab FWIW you've made this PR from your master branch -- which you should **really** avoid.

If you make any other changes to you master branch and push them to your GitHub, this PR will reflect those changes.

If you plan to do any other work, I suggest you close this, and re-create it from a new branch.

**Comment by gautamkrishnar** [comment]
@jophab  you can change the current branch by
>   git checkout "branch-name"

**Comment by jophab** [comment]
@moollaza Now i understand its consequences. I will avoid it from next time :+1:

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/8085_cheat_sheet_mobile.png)

**Comment by jophab** [comment]
@moollaza Any more changes??

**Comment by moollaza** [comment]
Merged in #1861

**Pull request merged**
