### PR TITLE
DaysBetween: Add 'Days since' feature

### LINKED ISSUE #3454: DaysBetween: Add "days since" feature
For example, the search query "days since 12/03/1989" would calculate the days between 12/03/1989 and today's date (depending on my location).

------
IA Page:  http://duck.co/ia/view/days_between 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @JetFault

### PR DESCRIPTION
**Pull request by shubh1m**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [X] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [X] Enhancement: **`DaysBetween: Add 'days since' feature`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Add 'Days since' feature. User can search queries like 'days since 31 August 2016'.

###### Which issues (if any) does this fix?

Fixes #3454 

###### People to notify (@mention interested parties)
@tagawa 

---

Instant Answer Page: https://duck.co/ia/view/days_between

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @JetFault

### CODE REVIEW

**Comment by daxtheduck** [comment]
@shubh1m Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Hi @shubh1m. Thanks very much for working on this. I've sent you a pull request with a couple of edits - if you can merge that then the Travis checks here should run again and pass (I hope!).

**Comment by shubh1m** [comment]
Hi @tagawa. I have merged the changes but I didn't got why it was wrong in the previous case.

**Comment by tagawa** [comment]
@shubh1m I've been sitting here trying to write an explanation of why the test case was failing, and now I'm getting confused myself! When I did it this morning I thought it was because of the lack of `^` and `$` in the regex but now I'm not so sure. I'll try to look at this from the beginning again tomorrow. Perhaps there's a better way after all...

**Comment by shubh1m** [comment]
@tagawa Will it be deployed?

**Comment by tagawa** [comment]
@shubh1m I've just deployed it to the beta server for testing, and we can get some community feedback: https://beta.duckduckgo.com/?q=days+since+12+march+1989&ia=answer

**Comment by tagawa** [comment]
We've had no further review comments and this is looking good to me, and keeps it's originally functionality. Let's merge it - thank you very much @shubh1m for the improvement and for fixing the issues 🍰

**Pull request merged**
