### PR TITLE
Cheat Sheets: fix css issue

### PR DESCRIPTION
**Pull request by vikashvverma**
This PR fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2507

https://duck.co/ia/view/cheat_sheets

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@vikashvverma can you explain why you've chose this approach? Have you tested it much?

We'll likely need to run the screenshot tool against all the cheat sheets to inspect how this changes affects the UI. I can deploy this to another dev machine for you to run the screenshots tool if you’d like. I don't want to deploy it to beta though because I don't want to change how all the cheat sheets look.

**Comment by gautamkrishnar** [comment]
@vikashvverma can u post a screenshot here

**Comment by vikashvverma** [comment]
@gautamkrishnar I  am out on tour right now. I will share in one or two weeks

**Comment by vikashvverma** [comment]
@gautamkrishnar @moollaza using `table-layout:fixed;` tries to fix this issue but fails when a word is longer than the width of the table.


screen shot 2016-04-04 at 7 39 50 am



screen shot 2016-04-04 at 7 40 48 am

**Comment by gautamkrishnar** [comment]
@vishivish18 Looks good...

**Comment by vikashvverma** [comment]
@gautamkrishnar If you look at second image in `Images` section then you will find that a longer word spans to adjacent table

**Comment by jdorweiler** [comment]
@moollaza I ran screen shots using the (screen shot tool)[https://github.com/duckduckgo/ddg-screen-diff] and didn't see anything weird.

**Comment by vikashvverma** [comment]
@jdorweiler unless the word is too long it would be fine. I still think we can use `word-break`

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

I took another look at screenshots as well and didn't notice any breakage:

https://moollaza.duckduckgo.com/screenshots/

**Pull request merged**
