### PR TITLE
Temporal Tests breaking Travis/Prove

### PR DESCRIPTION
**Pull request by mintsoft**
Lo,

There's some tests that I missed in last year's MockTime frenzy that are causing trouble with people attempting to test their changes

cc @moollaza @jagtalon

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
Apologies for the self-merging here, however it's causing difficulty with PR's and the only changes are tests so I've made the call that it's OK. If not then let me know and I'll refrain from all self-merging in future.

**Comment by moollaza** [comment]
:+1:

**Comment by moollaza** [comment]
Thanks a lot @mintsoft

**Pull request merged**
