### PR TITLE
Fix translation and romanization mistakes

### PR DESCRIPTION
**Pull request by amulya349**
This PR fixes translation in Hindi cheat sheet.

IA Page : https://duck.co/ia/view/hindi_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@amulya349 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub username:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by amulya349** [comment]
@GuiltyDolphin  , @moollaza : Can you review this PR ?

**Comment by moollaza** [comment]
@amulya349 the JSON looks fine, but I can' speak to it's accuracy.

@duckduckgo/community-leaders, @duckduckgo/instant-answer-maintainers 

Anyone fluent in Hindi? If so please review this. We can also send out a tweet.

**Comment by tagawa** [comment]
I've queued up a tweet asking for feedback.

**Comment by rahulroxx** [comment]
@moollaza reviewed hindi cheat sheet on beta , translation looks fine .

**Comment by pnpninja** [comment]
@moollaza : I have basic proficiency in Hindi. And this seems right. He has updated pronunciation of the words in english which seem more accurate. However , to be truly accurate, the pronunciations must use the symbols

**Comment by GuiltyDolphin** [comment]
@pnpninja Would you mind commenting on the sections that need to be updated? (Or are you referring to the `trn` section?)

**Comment by tagawa** [comment]
Some feedback from Twitter:
> People would usually ask for **medicine store** instead of **pharmacy**.

(I think this is a British/US English difference)
Source: https://twitter.com/NormalAadmi/status/699952914651959297
> The translation for "you're welcome" works, if by that phrase you mean the greeting, but as a response to thanks, nope.

Source: https://twitter.com/darbaga/status/699961192857493504
> Do "आप कैसे हौ", this works for both genders and is more generally used.

Source: https://twitter.com/darbaga/status/699960770835009537
> In **Going out for Dinner** section, "I'm a vegetarian" - मैं शाकाहारी हूँ - main śākāhāri hoon

Source: https://twitter.com/vinayneekhra/status/700005725649690624
> "Can I use your phone?" - क्या मैं आपका फ़ोन इस्तेमाल कर सकता हूँ? - kya main aapka phone istemaal kar sakata hoon?

Source: https://twitter.com/vinayneekhra/status/700006941049884674

**Comment by amulya349** [comment]
@tagawa : updated pharmacy to medicine store because in India, we ask for medicine store. 
Made some other updates for "can I use your phone" and the phonetic phrase for "I'm a vegetarian"...

**Comment by pnpninja** [comment]
@GuiltyDolphin : It does not convey anything about pronunciation.. In hindi, that makes a huge difference

**Comment by tagawa** [comment]
Thanks @amulya349 :+1:

**Comment by Mailkov** [comment]
@amulya349 
The phrase "The check, please", is written twice ! Can you fix it?

**Comment by amulya349** [comment]
@Mailkov : fixed the duplicate entry.. Thanks for pointing out.. :)

**Comment by Mailkov** [comment]
@amulya349 :+1:

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

**Comment by moollaza** [comment]
Hey @amulya349 thanks again for fixing the Hindi Cheat Sheet! You did a great job. We at DuckDuckGo, the DuckDuckHack community, and all the people who will encounter this Instant Answer really appreciate it.

We could really use your help on something else now. There was a nice suggestion about Switching the UUID Generator Goodie to the more random looking, "Version 4” UUIDs in https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2002 and I think you'd similarly do a great job with it. Please comment on this issue if you'd be willing to take it up!

I think it is a good fit for you, but I'm of course not entirely sure, so I'd love to chat if you're around this week or next. Please message me on slack (@moollaza) or send me an email (moollaza@duckduckgo.com) if you'd be interested in talking. 

Thank you again,

-Zaahir

**Comment by preemeijer** [comment]
Thanks @amulya349

**Pull request merged**
