### PR TITLE
calculator: trigger/safe

### PR DESCRIPTION
**Pull request by zachthompson**
* Update trigger
* Run expression with Safe with minimum ops
* Add tests

Have fun @moollaza ;)

---
IA Page: https://duck.co/ia/view/calculator

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@zachthompson this should be live on Beta now. One issue I can see is a string like `********23` -- it still throws errors:

```
Argument "*main::*" isn't numeric in exponentiation (**) at (eval 4040)
```

Similarly, `log23/log3` produces:

```
Warning: Use of "log" without parentheses is ambiguous at (eval 4038)
```

I suppose we can bail early if we have more than 1 consecutive operators without a number between them?

**Comment by zachthompson** [comment]
I believe both of these are present on master.  I don't see the error with `********23` on this branch but do with the other.  

Checking for, say, three or more ops in a row is probably a quick guard.

Made an update to the opsets.

**Comment by moollaza** [comment]
> Checking for, say, three or more ops in a row is probably a quick guard.

I'll make a task for this. 

The rest LGTM :+1:

**Pull request merged**
