### PR TITLE
New Python Escape Sequence Cheat Sheet

### PR DESCRIPTION
**Pull request by marioluigiman**
https://duck.co/ia/view/python_escape_sequences

### CODE REVIEW

**Comment by daxtheduck** [comment]
@marioluigiman Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub ID:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata post coming soon

**Comment by mintsoft** [comment]
@marioluigiman Thanks for the contribution, I think this might be worth renaming to "common escape sequences"? Pretty much every C-based language uses this set of escape sequences (C,C++, C#, Java, PHP, Python, Perl, JS and so on)

**Comment by marioluigiman** [comment]
@mintsoft I will rename the Instant Answer to "common escape sequences".

**Pull request closed without merging**
