### PR TITLE
Conversions: Addition of more mass units

### LINKED ISSUE #4176: Conversions Suggestion: (MASS) - Add Missing Units
## Problem

We recently migrated the conversions API into an interactive UI. However, some units were ditched for various reasons and the legacy code didn't necessarily support all of the units that were desired from users. This is a good opportunity to take the lead in the search engine conversions game.

screen shot 2017-05-08 at 6 37 07 pm

## Solution

1. Add some front-end tests to [spec/conversions_spec.js](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/spec/conversions_spec.js). This will test the custom units

2. Add some back-end tests to [t/Conversions.t](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/Conversions.t). This will test the triggering.

3. Update the triggering in [triggers.yml](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/triggers.yml) 

4. Add the custom unit to [Conversions.js (Line 45)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L45) and add it to the Units Object in [Conversions.js (Line 166)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L166)

### UNITS

- [x] Decigram
- [x] Centigram
- [x] Picogram
- [x] Femtogram
- [x] Dekagram
- [x] Hectogram
- [x] Megagram
- [x] Metric Ton
- [x] Long Ton
- [x] Short Ton
- [x] Imperial Ton
- [x] Metric Quintal
- [ ] US Quintal
- [ ] French Quintal
- [x] Troy OUnce
- [x] Slug
- [ ] Tola
- [x] Carat
- [x] Grain
- [x] Atomic Mass Unit

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/conversions

### PR DESCRIPTION
**Pull request by TheOdd**
## Description of new Instant Answer, or changes

This PR will add missing mass units to the conversion IA.

## Related Issues and Discussions

Fixes #4176 
Clean PR of #4192 

## People to notify

@pjhampton @mintsoft 

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

 
Instant Answer Page: https://duck.co/ia/view/conversions

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
I'm not a big fan of the jasmine tests but it's not overly important right now.
Thanks @TheOdd 💯  Awesome job

**Comment by TheOdd** [comment]
@pjhampton No problem! I had a fun time doing it, too! I'm not too comfortable with how the tests are implemented right now, either, but I'd love to work on them later at some point. If you have any ideas on how it could be improved, let me know!

**Comment by bsstoner** [comment]
This was released to production 🚀

**Pull request merged**
