### PR TITLE
mumbai cheat sheet added

### PR DESCRIPTION
**Pull request by khanshaheen**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer
    - [ ] Cheat Sheets: **`New {Cheat Sheet Name} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

@mention any relevant people/organizations

---

Instant Answer Page: https://duck.co/ia/view/mumbai_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html):
mum

### CODE REVIEW

**Comment by daxtheduck** [comment]
@khanshaheen Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=mumbai cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/mumbai_cheat_sheet_mobile.png?d6UNKyRKPb)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=mumbai cheat sheet)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/mumbai_cheat_sheet_mobile.png?wE53RAGCer)

**Comment by sahildua2305** [comment]
@khanshaheen sorry, we can't accept this type of cheat sheets. The purpose of a cheat sheet is to provide concise information to users. This cheat sheet violates the mentioned purpose.

While, I will be closing this PR, please feel free to create cheat sheets for other topics which you feel is missing. Here's how you can help us with our mission to improve programming results - https://forum.duckduckhack.com/c/programming

**Comment by daxtheduck** [comment]
## [Hydra](https://duck.co/ia/view/hydra)

**Description**: Don't get on the phishing page. Original site address HYDRA http://hydrakxbeouow4af.onion

**Example Query**: [hydra](https://beta.duckduckgo.com/?q=hydra), [гидра](https://beta.duckduckgo.com/?q=гидра), [гидра онион](https://beta.duckduckgo.com/?q=гидра%20онион), [hydra onion](https://beta.duckduckgo.com/?q=hydra%20onion), [hydraru](https://beta.duckduckgo.com/?q=hydraru)

**Tab Name**:  

**Source**: https://godnotaba.ru

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/hydra)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/hydra)*

**Comment by daxtheduck** [comment]
## [Hydra](https://duck.co/ia/view/hydra)

**Description**: Don't get on the phishing page. Original site address HYDRA http://hydrakxbeouow4af.onion

**Example Query**: [hydra](https://beta.duckduckgo.com/?q=hydra), [гидра](https://beta.duckduckgo.com/?q=гидра), [гидра онион](https://beta.duckduckgo.com/?q=гидра%20онион), [hydra onion](https://beta.duckduckgo.com/?q=hydra%20onion), [hydraru](https://beta.duckduckgo.com/?q=hydraru)

**Tab Name**:  

**Source**: https://godnotaba.ru

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/hydra)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/hydra)*

**Comment by daxtheduck** [comment]
## [Hydra](https://duck.co/ia/view/hydra)

**Description**: Don't get on the phishing page. Original site address HYDRA http://hydrakxbeouow4af.onion

**Example Query**: [hydra](https://beta.duckduckgo.com/?q=hydra), [гидра](https://beta.duckduckgo.com/?q=гидра), [гидра онион](https://beta.duckduckgo.com/?q=гидра%20онион), [hydra onion](https://beta.duckduckgo.com/?q=hydra%20onion), [hydraru](https://beta.duckduckgo.com/?q=hydraru)

**Tab Name**:  

**Source**: https://godnotaba.ru

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/hydra)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/hydra)*

**Comment by daxtheduck** [comment]
## [Hydra](https://duck.co/ia/view/hydra)

**Description**: Don't get on the phishing page. Original site address HYDRA http://hydrakxbeouow4af.onion

**Example Query**: [hydra](https://beta.duckduckgo.com/?q=hydra), [гидра](https://beta.duckduckgo.com/?q=гидра), [гидра онион](https://beta.duckduckgo.com/?q=гидра%20онион), [hydra onion](https://beta.duckduckgo.com/?q=hydra%20onion), [hydraru](https://beta.duckduckgo.com/?q=hydraru)

**Tab Name**:  

**Source**: https://godnotaba.ru

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/hydra)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/hydra)*

**Comment by daxtheduck** [comment]
## [Hydra](https://duck.co/ia/view/hydra)

**Description**: Don't get on the phishing page. Original site address HYDRA http://hydrakxbeouow4af.onion

**Example Query**: [hydra](https://beta.duckduckgo.com/?q=hydra), [гидра](https://beta.duckduckgo.com/?q=гидра), [гидра онион](https://beta.duckduckgo.com/?q=гидра%20онион), [hydra onion](https://beta.duckduckgo.com/?q=hydra%20onion), [hydraru](https://beta.duckduckgo.com/?q=hydraru)

**Tab Name**:  

**Source**: https://godnotaba.ru

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/hydra)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/hydra)*

**Comment by daxtheduck** [comment]
## [Hydra](https://duck.co/ia/view/hydra)

**Description**: Don't get on the phishing page. Original site address HYDRA http://hydrakxbeouow4af.onion

**Example Query**: [hydra](https://beta.duckduckgo.com/?q=hydra), [гидра](https://beta.duckduckgo.com/?q=гидра), [гидра онион](https://beta.duckduckgo.com/?q=гидра%20онион), [hydra onion](https://beta.duckduckgo.com/?q=hydra%20onion), [hydraru](https://beta.duckduckgo.com/?q=hydraru)

**Tab Name**:  

**Source**: https://godnotaba.ru

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/hydra)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/hydra)*

**Pull request closed without merging**
