### PR TITLE
New Indian Helpline Cheat Sheet

### PR DESCRIPTION
**Pull request by aiyankovil**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer
    - [x] Cheat Sheets: **`New {Indian helpline} Cheat Sheet`**
    - [ ] Other: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{GoodieRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Added a cheatsheet for Indian helpline

---

Instant Answer Page: https://duck.co/ia/view/indian_helpline_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
hey @aiyankovil we're going to check and see why the checks failed. will review it soon!

**Comment by moollaza** [comment]
@aiyankovil the filename should be `indian-helpline.json` -- Please switch it to that and then we can get this deployed to Beta 👍

**Comment by aiyankovil** [comment]
@moollaza the specified changes has been made. Thks

**Comment by aiyankovil** [comment]
@edgesince84 thks for helping out.

**Comment by aiyankovil** [comment]
@moollaza i would like to be part of the organisation. Can u add me??

**Comment by edgesince84** [comment]
hey @aiyankovil - I got you invited to our contributors team!

**Comment by moollaza** [comment]
@aiyankovil it looks like your IA Page was ghosted? Did you do that?

I've un-ghosted it and fixed the ID as there was no existing IA Page for your cheat sheet. Now that the IA page has been updated the IA will deploy to Beta

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/indian_helpline_cheat_sheet_mobile.png?Pcr0zIgNOG)

**Comment by daxtheduck** [comment]
@aiyankovil this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Comment by moollaza** [comment]
@aiyankovil Thanks! This LGTM :+1:

Can you update the Instant Answer Page with a description of the Cheat Sheet please?

**Comment by aiyankovil** [comment]
@moollaza i will do it . thks for helping me out.

**Comment by aiyankovil** [comment]
@edgesince84 got the invitation. thks...

**Pull request merged**
