### PR TITLE
URLEncode: New design to prevent text overflow and better present answer

### LINKED ISSUE #3864: URLEncode: Long encoded URLs gets stripped off in while displaying
Attempt to encode a long URL such as the one below:

http://steamcommunity.com/market/search/render/?query=&start=10&count=10&search_descriptions=0&sort_column=popular&sort_dir=desc&appid=753&category_753_Game[]=tag_app_753

Part of the encoded URL gets hidden in the UI. See [here](https://i.imgur.com/KEowY2Q.gifv).

------
IA Page:  http://duck.co/ia/view/urlencode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nishanths

### PR DESCRIPTION
**Pull request by tossj**
## Description of new Instant Answer, or changes

This PR introduces a new design for the URLEncode IA, so that encoded results are presented in a `<pre>` tag that will not overflow and cut off the result when it is very long. This PR also adds functionality that allows users to click the `<pre>` box to quickly select all text in it so that they may copy it quickly.

## Related Issues and Discussions

Fixes #3864

## People to notify

@tagawa @nishanths 

---

Instant Answer Page: https://duck.co/ia/view/urlencode

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@tossj thanks for helping out.

Let's simplify this and just add CSS to wrap the existing title:

```css
.zci--urlencode .c-base__title {
    word-break: break-all;
    word-wrap: break-word;
}
```

**Comment by tossj** [comment]
@moollaza As these changes should probably be applied to the URLDecode IA as well, should that be done in another PR or in this one?

**Comment by mintsoft** [comment]
@tossj one change per PR please :)

**Comment by moollaza** [comment]
@tossj Thanks! This LGTM :+1:

**Pull request merged**
