### PR TITLE
Leap Year structured answer and template added

### LINKED ISSUE #415: Release Leap Year
Working on duckpan but not on live site.  https://next.duckduckgo.com/?q=is+it+a+leap+year

### PR DESCRIPTION
**Pull request by Sloff**
Fixes #415 and was pull request #1280

**What does your Instant Answer do?**
Shows whether a certain year is a leap year or not, among other leap year related functions

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Immediately shows if it is a leap year

**What are some example queries that trigger this Instant Answer?**
"is it a leap year"
"was 2010 a leap year"
"next 50 leap years"

**Which existing Instant Answers will this one supercede/overlap with?**
It adds structured answers to the existing leap year module

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

## Checklist
Please place an 'X' where appropriate.

```
- [X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [] Google Chrome
        - [X] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

```

-----
IA Page: https://duck.co/ia/view/leap_year

### CODE REVIEW

**Comment by mintsoft** [comment]
Replacement of: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1280

**Comment by moollaza** [comment]
@chrismorast any thoughts on this one? We're using the text template.

**Comment by moollaza** [comment]
@Sloff spoke to the design team. Let's drop the "CE" from all the years (I think it's pretty clear already) and then this is good to go!

**Comment by Sloff** [comment]
Hi @moollaza, I've changed the output as sugested, here are some examples:

**Comment by moollaza** [comment]
@Sloff excellent. LGTM :+1:

**Pull request merged**
