### PR TITLE
MongoDB cheatsheet

### PR DESCRIPTION
**Pull request by javathunderman**
Continuation of #1636. Please refer to that PR for metadata on this IA.

### CODE REVIEW

**Comment by javathunderman** [comment]
What does your Instant Answer do?

Show all The MongoDB basic queries and keys as cheat sheet.

What is the data source for your Instant Answer? (Provide a link if possible)

https://blog.codecentric.de/files/2012/12/MongoDB-CheatSheet-v1_0.pdf

Why did you choose this data source?

One of the Best and even recommended database for open-source development.

Are there any other alternative (better) data sources?

There are chances.

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)

Coder, Open source, Git users, Geeks, Hackers, etc.

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?

Yes, https://duck.co/ideas/idea/6304/mongodb-cheet-sheet

Are you having any problems? Do you need our help with anything?

No


IA Page: https://duck.co/ia/view/mongodb_cheat_sheet

**Comment by moollaza** [comment]
Hey @javathunderman, it looks like #1636 is still being developed, I'm not sure this PR is necessary.

In any case after reading the content more closely, I don't think this source is appropriate as mentioned in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1636#discussion_r47425680, https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1636#discussion_r47425731

**Comment by javathunderman** [comment]
@moollaza Oops, my mistake. Thought I saw an "Abandoned" label on that PR. Sorry about that.

**Comment by javathunderman** [comment]
Ah, seems like this was already taken up in #1636. I saw a PR with this same title in #1487. I think the "Abandoned" label on that can be removed.

**Pull request closed without merging**
