### PR TITLE
Timezone Coverter: Removed friendly "Noon" and "Midnight" times from TimezoneConverter IA

### LINKED ISSUE #1451: TimezoneConverter: Some results are "too" friendly
I tried to convert "5 AM EDT" to my time zone and I got "Noon EEST". It took me a while to notice the word because I was looking for a HH:MM time stamp. Please always give the exact time as the main text and use smaller text for the more friendly "noon".

image

---

IA Page:  http://duck.co/ia/view/timezone_converter

### PR DESCRIPTION
**Pull request by tossj**
## Description of new Instant Answer, or changes

Timezone Converter would previously show the converted times 12 PM and 0 AM as "Noon" and "Midnight", respectively. This PR changes the instant answer so 12 PM and 0 AM are always shown in the same time format as all other times.

## Related Issues and Discussions

Fixes #1451 

## People to notify

@moollaza @mintsoft 

---

Instant Answer Page: https://duck.co/ia/view/timezone_converter

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mintsoft** [comment]
@tossj We chose to use `noon` and `midnight` here to disambiguate for users. Not all people are aware around the rules for AM/PM vs 0/12; is there a specific reason you think this should be changed?

**Comment by tossj** [comment]
@mintsoft Would it be fine if on a query like [`12pm UTC into GMT`](https://duckduckgo.com/?q=12pm+UTC+into+GMT&ia=answer) it gives output `Noon - 12:00 PM GMT`?

Also, with this current fix a query such as [`0am UTC into GMT`](https://duckduckgo.com/?q=0am+UTC+into+GMT&ia=answer) gives output `Midnight - 0:00 AM GMT`, but if `AM` is present the time should be `12:00`. Would that be a separate issue, or can I fix it in this PR?

**Comment by mintsoft** [comment]
It makes sense to fix it in this PR

**Comment by moollaza** [comment]
Deploying to Beta

**Comment by moollaza** [comment]
@tossj @mintsoft Thanks! This LGTM :+1:

I noticed one oddity though: `3:00 est to pst` shows `0:00 PST` -- is it intended to show `midnight - 0:00 PST`?

**Comment by tossj** [comment]
@moollaza The existing code only added `Midnight` or `Noon` when `am` or `pm` was present in the query. Should they also be added for 24-hour clock times, or is it already implied?

**Pull request merged**
