### PR TITLE
Scratch cheatsheet

### PR DESCRIPTION
**Pull request by preemeijer**
What does your Instant Answer do?
Scratch cheatsheet for the buildingblocks

What is the data source for your Instant Answer? (Provide a link if possible)
http://www.dummies.com/how-to/content/scratch-for-kids-for-dummies-cheat-sheet.html
http://wiki.scratch.mit.edu/wiki/Scratch_Wiki:Table_of_Contents/Program

Why did you choose this data source?
It was the best that I could find for this purpose

Are there any other alternative (better) data sources?
Yes used the original wiki for the value texts

What are some example queries that trigger this Instant Answer?
scratch cheatsheet

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)
For students who get some lessons with this program; starting programmers.

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?
https://duck.co/ideas/idea/6332/scratch-cheatsheet

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
scratch-cheatsheet-screenshot

### CODE REVIEW

**Comment by mintsoft** [comment]
@preemeijer thanks for the new PR; it looks like this is conflicted currently, can you rebase the changes in from upstream/master? It should be similar to: https://help.github.com/articles/fork-a-repo/#keep-your-fork-synced although feel free to gimme a shout if you're struggling!

**Comment by mintsoft** [comment]
@moollaza this PR is really confusing, the diff implies that it's modifying `share/goodie/cheat_sheets/json/scratch.json` however that file doesn't even exist in master. I'm guessing the conflict has confused Github's diffinator?

**Comment by preemeijer** [comment]
@mintsoft @moollaza: it is indeed a little bit confusing. I did some things wrong with fixing a little issue and created this one. 
I can clean up my master. Make a branch and put up a new pull request. Just let me know what you want me to do and I will.
Greetings, Paul

**Comment by mintsoft** [comment]
@preemeijer I think once the conflicts are resolved the diff'll make sense. However if you experience difficulties merging in the changes, it may be easier to: 
* copy your new IA to somewhere safe
* bomb this out completely
* resync your master against origin (https://github.com/duckduckgo/zeroclickinfo-goodies.git) 
* branch in your fork
* re-add your new IA to the fork
* do a PR from there

**Pull request closed without merging**
