### PR TITLE
TheAdamGalloway's first Goodie

### PR DESCRIPTION
**Pull request by TheAdamGalloway**
# Goodie Pull Request Template

Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**
Provides simple feedback to the user when typing 'duckduckhack TheAdamGalloway'.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
This was created to solve the problem of me not knowing how to make a DuckDuckGo goodie.

**What is the data source for your Instant Answer? (Provide a link if possible)**
Simple text.

**Why did you choose this data source?**
The tutorial told me to.

**Are there any other alternative (better) data sources?**
Of course not.

**What are some example queries that trigger this Instant Answer?**
'DuckDuckHack TheAdamGalloway'

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Geeks.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No.

**Which existing Instant Answers will this one supercede/overlap with?**
All of the other DuckDuckHack answers.

**Are you having any problems? Do you need our help with anything?**
Not yet.

**Where did you hear about DuckDuckHack? (For first time contributors)**
On DuckDuckGo.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
Screenshot

## Checklist
Please place an 'X' where appropriate.

```
[x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[x] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [x] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by MrChrisW** [comment]
Congratulations on finishing your first Goodie (cake) 
@mintsoft LGTM :+1:

**Comment by TheAdamGalloway** [comment]
Thanks, it was easier than I expected, it's my first time using Perl though, I'll have to do some learning!

**Comment by TheAdamGalloway** [comment]
Also, I noticed that Travis Cl is giving errors because one of the current goodies references 2014 instead of 2015!

**Comment by TheAdamGalloway** [comment]
Updated pull request to fix testing issue with LeapYears.t

**Comment by mintsoft** [comment]
@TheAdamGalloway Excellent LGTM to me too.

Usually we'd do 2 PR's for this (even though they're minor) just for admin purposes, however this is obvious enough

**Comment by moollaza** [comment]
@TheAdamGalloway it's live! https://duckduckgo.com/?q=DuckDuckHack+TheAdamGalloway&ia=answer

Now that you've completed your first Goodie, we really hope you'll work on another! Feel free to check out our [Ideas Forum](https://duck.co/ideas) or look through our Github issues if you need something to work on!

**Pull request merged**
