### PR TITLE
AwesomeWM cheat sheet: Added new alias

### PR DESCRIPTION
**Pull request by tagawa**
---
https://duck.co/ia/view/awesome_window_manager_cheat_sheet 
Maintainer: @kennyballou

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@tagawa thanks!

Just need an approval from @kennyballou and then this should be good to merge@

**Comment by kennyballou** [comment]
Looks good to me.

**Comment by GuiltyDolphin** [comment]
@tagawa @kennyballou Thanks! :dolphin:

**Pull request merged**
