### PR TITLE
Update svn.json

### PR DESCRIPTION
**Pull request by Justforahorror**
updated sourceName, description and section names

-----
IA Page: https://duck.co/ia/view/svn_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata post coming soon

**Comment by moollaza** [comment]
@Justforahorror Thanks! This LGTM :+1:

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=svn cheat sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/svn_cheat_sheet_mobile.png)

**Comment by zekiel** [comment]
@Justforahorror haven't seen you in a few weeks! Would you like to help with some of the issues in goodies?

**Comment by Justforahorror** [comment]
@zekiel I am sorry.
Was a bit busy and also got no new ideas to make a cheat sheet.
Yes I would like to help with issues in goodies(Only cheat sheets, thats what I only looked)

**Comment by zekiel** [comment]
@Justforahorror  there are a lot of programming IA cheat sheets that could use a cheat sheet! https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage

**Comment by moollaza** [comment]
@Justforahorror thanks again for improving the SVN Cheat Sheet! You did a great job. We at DuckDuckGo, the DuckDuckHack community, and all the people who will encounter this Instant Answer really appreciate it.

We could really use your help on something else now. As Zac mentioned, we want to increase our Instant Answer coverage for as many programming languages and platforms as possible. We want a Arduino Cheat Sheet and I think you'd similarly do a great job with building that. Please update the [Programming IA Coverage table](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage) (mark it with a 'd') if you'd be willing to take it up!

I think it is a good fit for you, but I'm of course not entirely sure, so I'd love to chat if you're around this week or next. Please message me on slack (@moollaza) or send me an email (moollaza@duckduckgo.com) if you'd be interested in talking. 

Thanks again!

**Pull request merged**
