### PR TITLE
Constants goodie

### PR DESCRIPTION
**Pull request by Roysten**
**What does your Instant Answer do?**
Add constants goodie.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Going to wikipedia to obtain the constant.

**What are some example queries that trigger this Instant Answer?**
Speed of light, avogadro's number

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
scientists, students, ...

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
I'm not sure, I guess: https://duck.co/ia/view/constants

**Which existing Instant Answers will this one supercede/overlap with?**
Wikipedia in some cases.

**Are you having any problems? Do you need our help with anything?**
Not yet :)

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
Imgur
and
Imgur

## Checklist
Please place an 'X' where appropriate.

```
- [x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [x] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 10
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 11
        - [] Microsoft edge
        
    - Windows 8
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Linux
        - [] Google Chrome
        - [x] Firefox
        
    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

```

-----
IA Page: https://duck.co/ia/view/constants

### CODE REVIEW

**Comment by daxtheduck** [comment]
@Roysten Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by hemanth** [comment]
:+1:

**Comment by Roysten** [comment]
@moollaza I wanted to do that initially, but I couldn't figure out how. I was under the impression the query was handled underwater and not modifiable.

**Comment by moollaza** [comment]
> I was under the impression the query was handled underwater and not modifiable.

@Roysten Not at all! Firstly, you can choose if you send the whole query, or just the remainder, or a version of the query, to your `handle` function:

```perl
handle query => {}
handle query_lc => {}
handle query_raw => {}
handle query_nowhitepsace => {}
handle query_nowhitespace_nodash => {}
handle query_clean => {}
```

You also have available to you, a `$req` object which you can use to access those versions of  the query as well: `$req->query_raw`

In your case, we pass in the `query` as the first argument to the sub so you can access it via `$_`. You can simply put that into a named variable and edit as you like, or even modify `$_` if you want:

```perl
handle query => sub {
return unless m/.../; #implicitly match against $_
my $var = $_;
$var =~ s/'//; #remove apostrophes
...
```

I hope this makes things more clear?

Seeing as this PR is basically done, I'd be happy to merge this in now, and you're welcome to update the code if you'd like

**Comment by hemanth** [comment]
@Roysten Cool! Happy to see this.

@moollaza When will it be deployed? :smile:

**Comment by Roysten** [comment]
@moollaza Thank you for your explanation. I'm still not able to figure out how to ignore the apostrophes though. 

The handle function _only_ gets called when a trigger matches with the query. So even though I could ignore the apostrophes in the handle function, it would not actually call the handle function because it doesn't match my trigger without apostrophes. Deciding whether a query matches with my trigger seems to be out of my control, because I get the message "_Sorry, no hit for your instant answer_" as the output from duckpan.

**Comment by moollaza** [comment]
@Roysten congrats! It's live: https://duckduckgo.com/?q=speed+of+light&ia=answer

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

**Comment by moollaza** [comment]
Sorry for the delayed notification, it's actually been live for a little while now!

**Comment by hemanth** [comment]
WOW! Nice :+1:  Thank you everyone. 

Specailly @moollaza @Roysten 

screen shot 2015-11-14 at 18 27 50

**Pull request merged**
