### PR TITLE
New mysql cheat sheet

### PR DESCRIPTION
**Pull request by navneetzz**
**What does your Instant Answer do?**
   My Instant Answer provide information about basic commands used in MySQL.

**What is the data source for your Instant Answer? (Provide a link if possible)**
  http://www.cheatography.com/davechild/

**Why did you choose this data source?**
  I chose this this source because it provided some information of how to make cheat sheets.
 
**Are there any other alternative (better) data sources?**
There might be better data source.But according to me this gave me desired information for making cheat sheets.  

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
MySQL user community and database user community will get lot of benefit out of this cheat sheet.

**Where did you hear about DuckDuckHack? (For first time contributors)**
From social-media sites.

---

IA Page: https://duck.co/ia/view/mysql_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=MySQL Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/mysql_cheat_sheet_mobile.png)

**Comment by moollaza** [comment]
@navneetzz Thanks! This LGTM :+1:

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=MySQL Cheat Sheet)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/mysql_cheat_sheet_mobile.png)

**Pull request merged**
