### PR TITLE
Cheat sheet for Colorado's peaks over 14,000 feet.

### PR DESCRIPTION
**Pull request by zachthompson**
**What does your Instant Answer do?**
Cheat sheet for Colorado's peaks over 14,000 feet grouped by mountain range.

**What is the data source for your Instant Answer? (Provide a link if possible)**
http://14ers.com

**Why did you choose this data source?**
Good presentation of data.

**Are there any other alternative (better) data sources?**
There are certainly others but they don't have different info.

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Hikers, climbers, outdoor enthusiasts living in, curious about, or visiting Colorado.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
no

https://duck.co/ia/view/colorado_14ers_cheat_sheet

**Are you having any problems? Do you need our help with anything?**

no

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
14ers

-----
IA Page: https://duck.co/ia/view/colorado_14ers_cheat_sheet

### CODE REVIEW

**Comment by moollaza** [comment]
@zachthompson this LGTM :+1: 

@abeyang my only thought is on the best way to represent the units. I don't love the `'` for "feet". I think we should show "feet" or "ft":

colorado_14ers_reference_at_duckduckgo

**Comment by zachthompson** [comment]
What about changing the description to "Colorado mountains over 14,000 **feet**" and removing it from the individual entries?  We could also explicitly call it out in the description with something like "...(all units in feet)".

**Comment by abeyang** [comment]
@zachthompson is it widely known that `'` means feet? It took me a couple seconds to figure that out, personally.

Also, this would make a great **reference sheet**. :smile:

**Comment by zachthompson** [comment]
@abeyang In the US `'` for feet and `"` for inches is commonly understood.  I'm not wedded to that representation though.  To me, adding `ft` or `feet` to all of them adds a lot of clutter.

The reference template rendering is a bit weird with long sections on the unexpanded view:

14ers-reference-sheet

**Comment by mintsoft** [comment]
Same is true of `'`and `"` in the UK; most people still recognise arcane units from these

**Comment by zachthompson** [comment]
The reference template is fixed in another pr:
15ers-reference-sheet-fixed

**Comment by zachthompson** [comment]
Here's what it looks like with the units just in the description:
14ers-unit-fix

@mintsoft I was just reading about the crazy mix of imperial/metric in the UK. ;)

**Comment by mintsoft** [comment]
@zachthompson Crazy is *definitely* the word!

**Comment by abeyang** [comment]
I see. I'm ok with @zachthompson 's initial proposal, then. Let's use *feet* in the subtitle, and leave the rest with `'`.

**Comment by zachthompson** [comment]
Done @abeyang.

14ers-feet-apos

**Comment by abeyang** [comment]
Sweet! :+1:

**Comment by zachthompson** [comment]
@abeyang Are you merging cheat sheets these days or shall we send it back to @moollaza?

**Comment by abeyang** [comment]
I pushed the button.

**Comment by zachthompson** [comment]
:+1:

**Comment by moollaza** [comment]
:+1:

**Pull request merged**
