### PR TITLE
New Country Codes Cheat Sheet

### PR DESCRIPTION
**Pull request by nemeth**
**What does your Instant Answer do?**
Lists all ISO_3166-1 two letter country codes (alpha-2) with the corresponding country name, numeric and alpha-3 codes.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Display the conplete list of codes instantly.

**What is the data source for your Instant Answer? (Provide a link if possible)**
https://en.wikipedia.org/wiki/ISO_3166-1
The .json file for the cheat sheet can be updated with the following this [ruby gist](https://gist.github.com/nemeth/39415872b502732c4518), which uses the linked data source.

**Why did you choose this data source?**
Reliable and easily parseable.

**Are there any other alternative (better) data sources?**
The original ISO definitions are listed here: https://www.iso.org/obp/ui/

**What are some example queries that trigger this Instant Answer?**
`country code cheat sheet`

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
finance, who interested in country TLDs 

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
No

**Which existing Instant Answers will this one supercede/overlap with?**
It is slightly related with this idea: https://duck.co/ideas/idea/4856

**Are you having any problems? Do you need our help with anything?**
I have to check CheatSheet implementation, because the alias `ISO 3166-1` does not seem to work in codio box environment.

**Where did you hear about DuckDuckHack? (For first time contributors)**
I use DDG almost exclusively, so it was easy to figure out how to contribute.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
Demo Country Codes PNG

-----
IA Page: https://duck.co/ia/view/country_codes_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@nemeth Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by moollaza** [comment]
@nemeth this LGTM :+1:

Thanks a lot for contributing (we really appreciate it :smiley:). We invite you to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

By the way, we think you did a great job with this! Are you interested in helping others who build similar Instant Answers in the future?

If yes, we'll reach out and add you to a private list of mentors as well as send over some DDG merch as an additional thank you. Just email <open@duckduckgo.com> with the subject 'I want to help.' Please include your shipping address, phone-number (required for shipping outside USA) and t-shirt size. We'll reach out from there!

Otherwise, thank you for this amazing contribution. We hope you'll keep exploring and playing around with DuckDuckHack.

**Comment by nemeth** [comment]
@moollaza Thanks for the possibility!
Originally I wanted to solve the local country inference in XE's currency converter Spice. I used the converter many times before, but I missed this feature. As I never really coded in perl, I wanted to be a bit familiar with the DDG open source codebase, so I choose committing a cheat sheet first. 
It was really fun and easy to start with codio environment. I found the DDG developer docs very useful too. 
Since then I found [the on-hold issue](https://github.com/duckduckgo/zeroclickinfo-spice/issues/2069) about the missing feature. I'am interested in the outcome of it.
I hope I can help in the future.

**Comment by moollaza** [comment]
>It was really fun and easy to start with codio environment. I found the DDG developer docs very useful too. 

Thanks for the feedback! I'm glad to hear things went smoothly. If you have any suggestions/thoughts on improvements we'd love to hear them. Feel free to email me if you'd like: moollaza@duckduckgo.com

> Since then I found the on-hold issue about the missing feature. I'am interested in the outcome of it.

Thanks for bringing this back to my attention! I've pinged the team on it to see what we can do.

**Comment by moollaza** [comment]
@nemeth congrats! It's live: https://duckduckgo.com/?q=Country+Codes+Cheat+Sheet&ia=cheatsheet

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's, tackle open issues or even submit more Instant Answers!

Sorry for the late notice, it's actually been live for a little while now!

**Pull request merged**
