### PR TITLE
LeapYear: Adding MockTime to output

### PR DESCRIPTION
**Pull request by mintsoft**
Fixes to address reduced test coverage caused by: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/888

@MrChrisW this is what's normally done for testing temporal things (see https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/CalendarToday.t#L87 for example)

However, I've just noticed that this technique absolutely hasn't worked here as the current date and time isn't actually used when a query is made, only the time when the goodie was loaded : https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/LeapYear.pm#L34

### CODE REVIEW

**Comment by mintsoft** [comment]
@jagtalon @moollaza what are the implications of only loading this once for the live goodie (if it was live). I presume that it would depend on the next reloading/recycle of the applications until the date and time is correct again?

**Comment by mintsoft** [comment]
Well these have passed now. I've just tested moving the updating of `$year` etc into the `handle` so that the datetime is always updated when the goodie is used which appears to work

**Comment by mintsoft** [comment]
Also harmonised the indentation on spaced

**Comment by jagtalon** [comment]
@mintsoft nice! :+1:

**Pull request merged**
