### PR TITLE
New Telugu CheatSheet

### PR DESCRIPTION
**Pull request by roxxup**
a

https://duck.co/ia/view/telugu_language_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
@roxxup Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub username:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by roxxup** [comment]
someone help i don't know what's going on

**Comment by moollaza** [comment]
>  someone help i don't know what's going on

@roxxup I see you have several PR's with several different files being modified. You need to separate all these changes into different branches and submit new Instant Answers individually.

@duckduckgo/duckduckhack-mentors can someone please assist here?

**Comment by moollaza** [comment]
@roxxup I'm going to close these Puil Request because they're likely going to lead to problems

**Comment by mohan08p** [comment]
@rahulroxx :  Before following these steps, do git pull origin master for updating your local repo with the master repo. Then follow these steps, 
1) First create a new branch on your local repository (for each PR create a new branch), 
    git checkout -b telugu
2) Now confirm that you have switch to the branch telugu.
3) Then create a new json file of name, telugu.json
4) Update the index to prepare staged content for next commit,
    git add .
5) Then, commit the changes with respective message.
    git commit -m "Telugu cheat sheet"
6) To push the current branch(newly created) and set the remote as upstream branch,
    git push --set-upstream origin telugu
7) Now check your local github repo, that this branch is added into it.
    Then, finally make a PR to master repo. from your local repo. with the IA page. Done.

**Comment by rahulroxx** [comment]
i have language cheatsheet where should i put the json file  ( language or json folder ) ?

**Comment by mohan08p** [comment]
@roxxup : In the language directory.

**Pull request closed without merging**
