### PR TITLE
HTMLEntitiesEncode: Structured answer

### PR DESCRIPTION
**Pull request by mintsoft**
Notes: This is a weird IA to work on, it has single row output and guessed multi-line output, so I've used a basic structured_answer in the "one line" output case and the record template in the multi-line output.

Edge case queries to test:
* right angle brackets htmlencode
* how to encode an apostrophe in html ?
* htmlencode pound

New output (I really doubt many people actually see this record template):

image
image

Single lookup answer (much more likely for people to see I think!)
image

### CODE REVIEW

**Comment by moollaza** [comment]
@mintsoft thanks for this!

@abeyang any ideas on the design?

**Comment by abeyang** [comment]
Looks decent. But with the list view, can we include a (small) title that says something like this:

> HTML Entity Encode for {search term}

So, an example:

> HTML Entity Encode for right angle brackets

**Comment by mintsoft** [comment]
@moollaza I can't seem to find a way to add a title or something to the record template without creating a custom template. Have I missed something?

**Comment by mintsoft** [comment]
image

@moollaza @abeyang

**Comment by mintsoft** [comment]
related: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1163

**Comment by abeyang** [comment]
@mintsoft looking good! Sorry, after seeing this the way you have it, can we lay it out with both title and subtitle, like this:

> **Pound**
> HTML Entity Encode

I think after that, it should be good to go!

**Comment by mintsoft** [comment]
@abeyang we're here:

image

**Comment by moollaza** [comment]
@mintsoft @abeyang the LGTM :+1: 

One thought though: the new version, for single results doesn't show what the rendered HTML entitty looks like. The previous result would should you the name of the entity and the actual symbol.

@abeyang Shall we render it in the title?

> &#36; | $
> HTML Entity Encode: Dollar

----

This is particularly useful because then I can copy the actual element from the Serp. I use it often for things like `em dash` which lets me grab the symbol: —

**Comment by mintsoft** [comment]
@moollaza how about this: 
image

**Comment by abeyang** [comment]
Looks good!

**Comment by moollaza** [comment]
@mintsoft @abeyang the only thing I don't love about the parens is if the entity is a paren. I suppose we can write some additional logic to change the parens to something else in that case?

html___at_duckduckgo

Either way it's a minor edge case we can solve outside of this PR :+1:

**Pull request merged**
