### PR TITLE
HelpLine: new triggers

### PR DESCRIPTION
**Pull request by mattr555**
## Description of new Instant Answer, or changes

New triggers for the suicide helpline IA as per [discussion on /r/duckduckgo](https://www.reddit.com/r/duckduckgo/comments/78fksf/saw_this_on_rteenagers_as_a_teenager_myself_i/).

## People to notify

@moollaza @duckduckgo/community-leaders Hoping for a quick resolution on this, thanks.

---

Instant Answer Page: https://duck.co/ia/view/help_line

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Yeah, I think this is a good idea. Tests failing for an unrelated reason - restarting would be pointless.

**Comment by mattr555** [comment]
@pjhampton Thanks! Any idea when this will be deployed?

**Comment by pjhampton** [comment]
Sorry - I don't, @mattr555. Since the community went dark I'm unclear of the release schedule. 
@moollaza / @bsstoner have got this ✨

**Comment by bsstoner** [comment]
Should go out tomorrow around 4pm EDT /cc @duendex

**Pull request merged**
