### PR TITLE
templates: use ia_id instead of lia_name

### PR DESCRIPTION
**Pull request by srvsh**
Tested with changes introduced in https://github.com/duckduckgo/p5-app-duckpan/pull/289

### CODE REVIEW

**Comment by daxtheduck** [comment]
@srvsh Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Zip Code:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub ID:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by srvsh** [comment]
Hmm, the test has failed in Travis CI during installation of dependencies. The suspected line in the log is `! Couldn't find module or a distribution Dist::Zilla::Plugin::AnnounceRelease`, but that's not related to the code changes in this PR.

**Comment by moollaza** [comment]
@srvsh that package shouldn't have any trouble installing -- I'm running the test again to verify

**Comment by moollaza** [comment]
@srvsh Thanks! This LGTM :+1:

**Comment by srvsh** [comment]
@moollaza thanks for reviewing the code and verifying the test failure!

**Pull request merged**
