### PR TITLE
ColorCodes: Fixing Bug #1473

### LINKED ISSUE #1473: ColorCodes: Problem with #000000
We have some trouble with color #000000. See https://duckduckgo.com/?q=%23000000&ia=answer

Complementary and Analogous color are strange.

------
IA Page:  http://duck.co/ia/view/color_codes

### PR DESCRIPTION
**Pull request by mintsoft**
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1473

### CODE REVIEW

**Comment by mintsoft** [comment]
ColourCodes really needs switching to a template, however there's quite a lot of markup so I'll swing round and do it another time if that's fine with everyone

**Comment by jagtalon** [comment]
@mintsoft awesome! Checking it

**Comment by jagtalon** [comment]
@mintsoft would the same be applicable for https://duckduckgo.com/?q=%23fff&ia=answer?

**Comment by mintsoft** [comment]
@jagtalon yeah, it's applicable for all pure-grey shades (#000 -> #fff)

**Comment by jagtalon** [comment]
@mintsoft oh my bad must not have been reading the code.

@abeyang what do you think?

screen shot 2015-08-29 at 6 14 07 pm

**Comment by chrismorast** [comment]
:+1:

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
