### PR TITLE
bfmags's First Goodie

### PR DESCRIPTION
**Pull request by bfmags**
# Goodie Pull Request

**What does your Instant Answer do?**
Following goodie_quickstart tutorial.

**What are some example queries that trigger this Instant Answer?**
"duckduckhack bfmags" 

**Where did you hear about DuckDuckHack? (For first time contributors)**
EDX Computer Science course

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screen shot 2015-01-25 at 21 50 59

## Checklist
Please place an 'X' where appropriate.

```
[x] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[x] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[x] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [x] Google Chrome
        [x] Firefox
        [] Opera
        [x] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by MrChrisW** [comment]
@bfmags Congratulations on your first Goodie :cake: This will be merged and live shortly! :+1:

**Comment by bfmags** [comment]
Thank you :) @MrChrisW Seems the build is failing, though

**Comment by MrChrisW** [comment]
@bfmags That's an internal issue :smile: Your Goodie tests fine!

````
t/IsAwesome/bfmags.t .. ok   

All tests successful.

Files=1, Tests=2,  0 wallclock secs ( 0.02 usr  0.03 sys +  0.11 cusr  0.16 csys =  0.32 CPU)

Result: PASS
`````

**Comment by moollaza** [comment]
@bfmags congrats! It's live: https://duckduckgo.com/?q=duckduckhack+bfmags&ia=answer

Thanks a lot for contributing, we really appreciate it :smiley:. 

Now that you've made your first Goodie, we really hope you'll continue to contribute and make more Instant Answers! Please checkout our [Ideas forum](https://duck.co/ideas) if you're unsure about what to build. There's also lots of Github Issues in our repos that need someone to tackle them!

**Pull request merged**
