### PR TITLE
Issue #1595 - Zodiac: Switch to Icon template, use new icons

### PR DESCRIPTION
**Pull request by Mailkov**
This is a WIP... I'll create other commit to complete! 

-----
IA Page: https://duck.co/ia/view/zodiac

### CODE REVIEW

**Comment by Mailkov** [comment]
This is WIP

**Comment by mintsoft** [comment]
@Mailkov Thats fine just ping someone when you're ready for review :+1:

**Comment by Mailkov** [comment]
@mintsoft Ok, thanks!

**Comment by Mailkov** [comment]
@moollaza ping
This is ready for review.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=zodiac 21st June)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/zodiac_mobile.png)

**Comment by moollaza** [comment]
@Mailkov Thanks! This LGTM :+1:

**Pull request merged**
