### PR TITLE
New Airmon Cheat Sheet Goodie 

### PR DESCRIPTION
**Pull request by anukarsh1**
## Description of new Instant Answer, or changes

The purpose of this instant answer is to provide the consumer a cheat sheet of exhaustive aircrack-ng/airmon commands which the user can use to carry out a particular task. 

## Related Issues and Discussions

 Fixes #4364 

## People to notify

@daxtheduck  

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <goodie_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/airmon_cheat_sheet

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by anukarsh1** [comment]
Edit: I have modified the example queries to suit the description of the cheat sheet.

**Comment by anukarsh1** [comment]
@sahildua2305 
Hi Sahil , can you please have a look at this?

**Comment by jophab** [comment]
@anukarsh1 Hello,

There are two files in this PR. Cheat sheet PRs should contain only one file. 
So lets remove the file for aircrack and update the PR.

**Comment by anukarsh1** [comment]
@jophab I deleted the aircrack file :)

**Comment by pjhampton** [comment]
Travis is now fixed. Please rebase and push your work to get the updated build information 👍

**Comment by anukarsh1** [comment]
@pjhampton  I am new to git. Can you please guide me how to do that? :)

**Comment by pjhampton** [comment]
Yo @anukarsh1! Welcome to DuckDuckHack 🤘 

```
git checkout aircrack-ng    # make sure you're in your branch
git fetch origin                    # Updates origin/master
git rebase origin/master    # Rebases current branch onto origin/master
git push -f                          # push with much farce ;-)
```

Hope this helps.

**Comment by anukarsh1** [comment]
Hi @pjhampton  When I run the command git push -f an error pops up which says the following:-

fatal: The current branch aircrack-ng has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin aircrack-ng

Any suggestions on what should I do ?

**Comment by pjhampton** [comment]
@anukarsh1 did you run `git push --set-upstream origin aircrack-ng`

**Comment by anukarsh1** [comment]
@pjhampton Yes I did. It gave the following error:-
error: failed to push some refs to 'https://github.com/anukarsh1/zeroclickinfo-goodies'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
How should I deal with this?

**Comment by anukarsh1** [comment]
@pjhampton  I think I fixed the problem. Thanks a lot for helping! :smile:

**Comment by mintsoft** [comment]
@anukarsh1 can you beautiful the json here?

**Comment by mintsoft** [comment]
I'm closing this for now due to inactivity, feel free to re-open if this in in-error

**Pull request closed without merging**
