### PR TITLE
Create apt-get.json

### PR DESCRIPTION
**Pull request by abadojack**

### CODE REVIEW

**Comment by daxtheduck** [comment]
@abadojack Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by abadojack** [comment]
Someone please show me how to separate these into two pull requests

**Comment by moollaza** [comment]
@abadojack you'll need to use Git branches. A typical flow is like this:

```term
git pull upstream master (fetches changes from upstream branch, duckduckgo/zeroclickinfo-goodies)
git checkout -b my-new-branch
<do work>
git commit
git push origin my-new-branch (push changes to GitHub.com)
<create pr>
git checkout master (switch back to master after making PR)
git pull upstream master (get latest updates)
git checkout -b my-other-new-branch
<do work>
git commit
git push origin my-other-new-branch
```

There's lots of tutorials online that explain this, and of course there's our Slack channel where the community and myself can assist you

**Comment by codenirvana** [comment]
@abadojack Always use different branches for any new change you make, you made this PR on ```master``` which will work but is not recommended.
To solve your current problem you can try this:
- First backup both the cheat sheets locally.
- Run these git commands
```
git reset HEAD~2
```
> This will bring back the master branch to its original state by remove your last two commits.

- Create a new branch for  apt-get cheat sheet first
```
git branch apt-get-cs
git checkout apt-get-cs
```
- Add and commit  ```apt-get.json``` file and finally push but this time its on ```apt-get-cs``` branch
```
git push origin apt-get-cs
```
- Similarly create a new branch for pacman but remember **Always make new branch from the master** so,
```
git checkout master
git branch pacman-cs
git checkout pacman-cs
```
- Commit and push this branch too
- You need to close this PR and create two separate PRs for each cheat sheet.

I hope this will solve your problem, for more help ping anyone at DDG Slack channel.

**Comment by abadojack** [comment]
Let me try that.

**Pull request closed without merging**
